Downloading Libraries and Imports

In [1]:
!rm -rf /usr/local/lib/python3.13/dist-packages/~orch*
!pip install -q --upgrade "pillow<11.0.0" torch torchvision transformers>=4.45.0 accelerate scikit-learn tqdm chess cairosvg python-Levenshtein datasets peft huggingface_hub python-dotenv
!pip uninstall -y torchaudio torchao -q
!pip install -q flash-linear-attention



# Standard library imports
import json
import os
import subprocess
import sys
from pathlib import Path

# Third-party library imports
import numpy as np
from functools import partial
import pandas as pd
import torch
from datasets import load_dataset, Dataset
from huggingface_hub import login
from peft import LoraConfig, PeftModel, TaskType, get_peft_model
from PIL import Image
from tqdm import tqdm
from transformers import (
    AutoModelForImageTextToText,
    AutoProcessor,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 399.6/399.6 kB 24.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.2/819.2 kB 57.4 MB/s eta 0:00:00

Setting up environment

In [2]:
# Project configuration dictionary
CONFIG = {
    "colab": True,
    "branch": "Ivo2",
    "repo_name": "BigDataAndTextMiningProject",
    "repo_owner": "Aivon99",
    "repo_dir": "/content/BigDataAndTextMiningProject",
}

# 1. Setup repository path and handle cloning safely
repo_root = Path(CONFIG["repo_dir"])

if CONFIG["colab"]:
    # If the repository folder already exists, reference it safely
    if repo_root.exists():
        # /content survives "Restart session", so an old clone can linger -- pull so
        # the notebook always runs the latest code (restart the session afterwards if
        # eval.utilities was already imported in this kernel).
        print(f"Repository directory already exists at: {repo_root}; pulling latest changes...")
        pull = subprocess.run(["git", "-C", str(repo_root), "pull", "--ff-only"], capture_output=True, text=True)
        print((pull.stdout or pull.stderr).strip())
    else:
        auth_url = "https://"
        repo_url = f"{auth_url}github.com/{CONFIG['repo_owner']}/{CONFIG['repo_name']}.git"

        print(f"Cloning repository from {repo_url}...")
        result = subprocess.run(
            ["git", "clone", "--single-branch", "--branch", CONFIG["branch"], repo_url, str(repo_root)],
            capture_output=True, text=True
        )
        assert result.returncode == 0, f"Git clone failed: {result.stderr}"
else:
    repo_root = Path(".").resolve().parent.parent


print(f"Setup Complete. REPO_ROOT: {repo_root}")

# Check GPU and device availability
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")
if device == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Configure system paths for absolute module imports
sys.path.insert(0, str(repo_root))
sys.path.insert(0, str(repo_root / "src"))
sys.path.insert(0, str(repo_root / "src" / "data"))
sys.path.insert(0, str(repo_root / "src" / "eval"))

# 4. Import custom project modules cleanly
from data.generation import (
    build_sample,
    generate_dataset,
)

from data.utilities import (
    load_lichess_csv,
    upload_dataset_to_hub,
    authenticate_hf,
)

from eval.utilities import (
   calculate_fen_exact_match,
   calculate_levenshtein_metrics,
   calculate_square_by_square_accuracy,
   evaluate_chessboard_model_task_1,
   preprocess_function,
   get_patch_reordering_indices,
   reorder_chessboard_image,
   apply_patch_permutation,
   finetune_and_push_chessboard_model,
   find_resumable_checkpoint,
   Qwen35OnTheFlyCollator,
   evaluate_with_cache,
   load_or_init_results_table,
   append_or_replace,
   load_results_table,
   push_results_table,
   train_or_load_finished,
   HubBestAdapterCallback,
)

from training.learned_reordering import train_with_learned_reordering

from eval.diagnostics import (
    training_health_report,
    rescore_cached_fen_results,
    save_diagnostics,
)

# Used to key every cached evaluation result on the Hub (evaluation-results-task1
# and the per-strategy LoRA repos) -- defined here, early, instead of only inside
# the "Vanilla + LoRA" section further down, since evaluate_with_cache/
# load_or_init_results_table need it as soon as the very first evaluation runs.
hf_org_prefix = "bdatm-project"

print("All custom modules and eval utilities imported successfully!")

Cloning repository from https://github.com/Aivon99/BigDataAndTextMiningProject.git...
Setup Complete. REPO_ROOT: /content/BigDataAndTextMiningProject
Using device: cuda
GPU: NVIDIA A100-SXM4-80GB
All custom modules and eval utilities imported successfully!

Dowloading dataset for task 1 from HuggingFace repo

In [3]:
# Authenticate with Hugging Face:
# - Colab: reads a token from a Colab secret named HF_TOKEN (key icon, left sidebar)
# - Local: reads HF_TOKEN from a repo-root .env file, or the environment
# - Falls back to an interactive login prompt if neither is found
hf_token = None
if CONFIG["colab"]:
    try:
        from google.colab import userdata
        hf_token = userdata.get("HF_TOKEN")
    except Exception:
        hf_token = None
else:
    from dotenv import load_dotenv
    load_dotenv(repo_root / ".env")
    hf_token = os.environ.get("HF_TOKEN")

if hf_token:
    login(token=hf_token, add_to_git_credential=False)
    print("Logged in to Hugging Face Hub using HF_TOKEN.")
else:
    print("No HF_TOKEN found in secrets/.env/environment — falling back to interactive login.")
    login()

dataset_name = "bdatm-project/dataset_task1"
print(f"Downloading dataset '{dataset_name}'...")

dataset_task1 = load_dataset(dataset_name, num_proc=16)

print("\nDataset loaded successfully!")
print(dataset_task1)
print("\nStructure sample of train split:")
print(dataset_task1["train"][0])

Logged in to Hugging Face Hub using HF_TOKEN.
Downloading dataset 'bdatm-project/dataset_task1'...

Resolving data files:   0%|          | 0/3201 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/401 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/401 [00:00<?, ?it/s]

metadata.jsonl:   0%|          | 0.00/1.88M [00:00<?, ?B/s]

metadata.jsonl:   0%|          | 0.00/235k [00:00<?, ?B/s]

metadata.jsonl:   0%|          | 0.00/235k [00:00<?, ?B/s]

Setting num_proc from 16 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 16 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Generating train split:   0%|          | 0/3200 [00:00<?, ? examples/s]

Setting num_proc from 16 back to 1 for the validation split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 16 back to 1 for the validation split to disable multiprocessing as it only contains one shard.

Generating validation split:   0%|          | 0/400 [00:00<?, ? examples/s]

Setting num_proc from 16 back to 1 for the test split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 16 back to 1 for the test split to disable multiprocessing as it only contains one shard.

Generating test split:   0%|          | 0/400 [00:00<?, ? examples/s]

Dataset loaded successfully!
DatasetDict({
    train: Dataset({
        features: ['sample_id', 'puzzle_id', 'task', 'fen', 'prompt', 'target', 'image', 'file_name_t1'],
        num_rows: 3200
    })
    validation: Dataset({
        features: ['sample_id', 'puzzle_id', 'task', 'fen', 'prompt', 'target', 'image', 'file_name_t1'],
        num_rows: 400
    })
    test: Dataset({
        features: ['sample_id', 'puzzle_id', 'task', 'fen', 'prompt', 'target', 'image', 'file_name_t1'],
        num_rows: 400
    })
})

Structure sample of train split:
{'sample_id': 'sample_000000', 'puzzle_id': 'drw7g', 'task': 'task1', 'fen': 'r3k2r/pppq2pp/2nb1p2/1B1Q3P/8/1P2P2P/PBPP1P2/R3K2R w KQkq - 1 13', 'prompt': 'You are a specialized model for chessboard understanding.\nYour goal is to extract the exact board state from the provided chessboard image.\nInput:\n- Board Image: The visual representation of the chessboard.\nOutput Format:\nReturn only the valid FEN string representing the position of all pieces on the board.', 'target': 'r3k2r/pppq2pp/2nb1p2/1B1Q3P/8/1P2P2P/PBPP1P2/R3K2R w KQkq - 1 13', 'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=512x512 at 0x7D5340B57CB0>, 'file_name_t1': ''}

## Vanilla Model

Loading model

In [4]:
model_id = "Qwen/Qwen3.5-0.8B"
print(f"Loading model {model_id}...")

model_vanilla = AutoModelForImageTextToText.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

processor = AutoProcessor.from_pretrained(model_id)
print("model and Processor loaded correctly!")

Loading model Qwen/Qwen3.5-0.8B...

config.json:   0%|          | 0.00/2.91k [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/50.9k [00:00<?, ?B/s]

model.safetensors-00001-of-00001.safeten(…): reconstructing file:   0%|          |  0.00B / 1.75GB

model.safetensors-00001-of-00001.safeten(…): downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/7.75k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/16.7k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 12.8MB

tokenizer.json: downloading bytes:           |  0.00B

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

model and Processor loaded correctly!

Test with baseline on a single sample

In [5]:
# Grab the first test sample
test_sample = dataset_task1["test"][0]

fen = test_sample["fen"]
task_prompt = test_sample["prompt"]
ground_truth_fen = test_sample["target"]
sample_id = test_sample["sample_id"]
board_image = test_sample["image"]

print(f"Sample ID: {sample_id}")
print(f"FEN: {fen}")
print(f"Prompt provided to the model:\n{task_prompt}\n")
print(f"Real FEN (Ground Truth): {ground_truth_fen}\n")

# Prepare the multimodal input format for the model
chat_messages = [
    {
        "role": "user",
        "content": [
            {"type": "image", "image": board_image},
            {"type": "text", "text": task_prompt},
        ]
    }
]

# Apply the processor's chat template
formatted_text = processor.apply_chat_template(chat_messages, tokenize=False, add_generation_prompt=True)

# Tokenize inputs and move them to the GPU device
model_inputs = processor(
    text=[formatted_text],
    images=board_image,
    padding=True,
    return_tensors="pt"
).to(model_vanilla.device)

# Generate the zero-shot prediction
print("Generating zero-shot prediction...")
with torch.no_grad():
    output_token_ids = model_vanilla.generate(**model_inputs, max_new_tokens=128)

# Trim prompt tokens from the generated output
trimmed_output_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, output_token_ids)
]
predicted_fen_string = processor.batch_decode(
    trimmed_output_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False
)[0]

print(f"Predicted FEN (Zero-Shot): {predicted_fen_string.strip()}")

Sample ID: sample_000000
FEN: 6R1/kbqn1p2/1p5p/1Pp5/4Pb2/7Q/1PPr3P/4K3 b - - 0 33
Prompt provided to the model:
You are a specialized model for chessboard understanding.
Your goal is to extract the exact board state from the provided chessboard image.
Input:
- Board Image: The visual representation of the chessboard.
Output Format:
Return only the valid FEN string representing the position of all pieces on the board.

Real FEN (Ground Truth): 6R1/kbqn1p2/1p5p/1Pp5/4Pb2/7Q/1PPr3P/4K3 b - - 0 33

Generating zero-shot prediction...

[transformers] `causal_conv1d_fn` is falling back to its reference PyTorch implementation because `causal_conv1d` is not installed. This is correct but much slower; install `causal_conv1d` for the optimized kernel.
[transformers] `causal_conv1d_update` is falling back to its reference PyTorch implementation because `causal_conv1d` is not installed. This is correct but much slower; install `causal_conv1d` for the optimized kernel.

Predicted FEN (Zero-Shot): e2r1qpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp

Testing vanilla model on the whole dataset using the function *evaluate_chessboard_model_task_1*

In [6]:
# Call the evaluation function for the vanilla model -- checks the Hub first
# (evaluate_with_cache) and skips straight to the cached numbers if this
# model was already evaluated in an earlier session, instead of re-running
# generation on the full test set.
vanilla_results_df, vanilla_summary_df = evaluate_with_cache(
    task="task1",
    model=model_vanilla,
    processor=processor,
    dataset_split=dataset_task1["test"],
    model_name="Vanilla Qwen2.5-VL (Zero-Shot)",
    hf_org_prefix=hf_org_prefix,
)

# Initialize the global comparison DataFrame from whatever's already been
# evaluated and cached on the Hub for this task, then fold in this result --
# so it's never left undefined just because an earlier cell didn't run this
# session, and running cells out of order never crashes with a NameError.
all_models_results = load_or_init_results_table(task="task1", hf_org_prefix=hf_org_prefix)
all_models_results = append_or_replace(all_models_results, vanilla_summary_df)

print("\nExample of results obtained form the evaluation:")
if vanilla_results_df is not None:
    display(vanilla_results_df.head())
else:
    print("(per-sample results not cached for this entry -- only the summary row was available)")

print("\nComparative Summary DataFrame (all_models_results):")
display(all_models_results)

README.md:   0%|          | 0.00/466 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 3.54kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/816dd122f0ae264ad1ca7dd4ada1b6f0a9b4c803/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/816dd122f0ae264ad1ca7dd4ada1b6f0a9b4c803/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Evaluating Vanilla Qwen2.5-VL (Zero-Shot): 100%|██████████| 400/400 [29:16<00:00,  4.39s/it]

Evaluation completed for Vanilla Qwen2.5-VL (Zero-Shot)! Results saved to task1_vanilla_qwen2.5-vl_(zero-shot)_results.csv.

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/48c4c9e722c41063ab4b6af02d22a7c406cc8159/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/48c4c9e722c41063ab4b6af02d22a7c406cc8159/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmpxk4e6x74.parquet    : 100%|##########| 2.96kB / 2.96kB

Validating                    :           |   0%

[task1] Cached evaluation for 'Vanilla Qwen2.5-VL (Zero-Shot)' -- pushed to 'bdatm-project/evaluation-results-task1'.

README.md:   0%|          | 0.00/464 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 2.96kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Loaded existing comparison table for task1 from 'bdatm-project/evaluation-results-task1' (1 model(s) already evaluated).

Example of results obtained form the evaluation:

,sample_id,ground_truth,predicted,raw_output,fen_exact_match,levenshtein_distance,character_error_rate,square_by_square_accuracy
0,sample_000000,6R1/kbqn1p2/1p5p/1Pp5/4Pb2/7Q/1PPr3P/4K3 b - -...,e2r1qppppppppppppppppppppppppppppppppppppppppp...,e2r1qppppppppppppppppppppppppppppppppppppppppp...,0.0,190,3.725490,0.0
1,sample_000001,r1r5/p6n/4pq2/3P1p1k/7P/5PQ1/P5P1/R3R1K1 w - -...,b1r1p1pppppppppppppppppppppppppppppppppppppppp...,b1r1p1pppppppppppppppppppppppppppppppppppppppp...,0.0,189,3.705882,0.0
2,sample_000002,8/6pk/5np1/1p5p/p1pP3q/P1P1Q3/1P3P2/5RK1 w - -...,b1rnb1q1ppp1pppppppppppppppppppppppppppppppppp...,b1rnb1q1ppp1pppppppppppppppppppppppppppppppppp...,0.0,186,3.647059,0.0
3,sample_000003,r4r1k/6p1/p5P1/1p2ppNP/1q2b2Q/4n3/PPPRB3/1K4R1...,a1b1c1d1e1f1g1h1i1j1k1l1m1n1o1p1q1r1s1t1u1v1w1...,a1b1c1d1e1f1g1h1i1j1k1l1m1n1o1p1q1r1s1t1u1v1w1...,0.0,49,0.859649,0.0
4,sample_000004,4rrk1/6pp/p1p1q3/3p2Q1/2PP2b1/1PR2N2/P5PP/5RK1...,e2r1q1ppp1pppppppppppppppppppppppppppppppppppp...,e2r1q1ppp1pppppppppppppppppppppppppppppppppppp...,0.0,185,3.245614,0.0

Comparative Summary DataFrame (all_models_results):

,model_name,fen_exact_match,character_error_rate,square_by_square_accuracy,levenshtein_distance
0,Vanilla Qwen2.5-VL (Zero-Shot),0.0,3.259093,0.0,169.225

## Vanilla + LoRA

Preprocessing dataset and finetuning

In [7]:
# 1. No dataset.map preprocessing: the collator below tokenizes and runs the
# image processor per batch (in DataLoader workers), so nothing big is cached.

# 2. Configure PEFT and LoRA parameters
peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=16,
    lora_alpha=32,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    lora_dropout=0.05,
    bias="none",
)

# Apply LoRA to model vanilla and saving the new one into lora_model
lora_model = get_peft_model(model_vanilla, peft_config)
lora_model.print_trainable_parameters()

# 3. Resolve the target Hub repo now (needed before training starts) and
# check whether an earlier, interrupted run already left a resumable
# checkpoint there (e.g. after a Colab disconnect wiped the local runtime).
hf_org_prefix = "bdatm-project"
repo_id_standard = f"{hf_org_prefix}/qwen-task1-standard-lora"
resume_checkpoint = find_resumable_checkpoint(repo_id_standard)

# 4. Define Training Arguments. Trains for up to 10 epochs, but relies on
# the validation set (via EarlyStoppingCallback below) to stop once
# eval_loss stops improving, and keeps the best-performing checkpoint
# (by validation loss) rather than just whichever epoch finishes last.
# push_to_hub + hub_strategy="checkpoint" uploads a fully resumable
# checkpoint (optimizer/scheduler/RNG state included) after every epoch,
# so a Colab disconnect at epoch i loses at most that epoch's progress.

training_args = TrainingArguments(
    output_dir="./qwen_task1_lora_output",
    per_device_train_batch_size=8,  # same effective batch (8) as before, but one GPU pass instead of 8
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    logging_steps=10,
    num_train_epochs=10,
    save_strategy="epoch",
    eval_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    save_total_limit=2,
    push_to_hub=True,
    hub_model_id=repo_id_standard,
    hub_strategy="checkpoint",
    bf16=True,  # model is loaded in bfloat16; fp16 autocast on top of it was mismatched
    dataloader_num_workers=4,
    remove_unused_columns=False,
    report_to="none",
)

# 5. Initialize the Trainer using 'lora_model', with early stopping driven
# by the validation set (stops if eval_loss doesn't improve for 2 epochs).
# data_collator preprocesses each batch on the fly (image processor + tokenizer)
# rather than precomputing pixel_values with dataset.map -- that cache would be
# ~20 GB of float tensors and slow to reload -- and it batches Qwen's per-sample
# image_grid_thw/pixel_values correctly (torch.cat along dim 0), which the
# default collator can't (it fails later inside the vision tower as IndexError).
data_collator = Qwen35OnTheFlyCollator(processor=processor)

trainer = Trainer(
    model=lora_model,
    args=training_args,
    train_dataset=dataset_task1["train"],
    eval_dataset=dataset_task1["validation"],
    data_collator=data_collator,
    # HubBestAdapterCallback keeps the best epoch's adapter on the Hub, so
    # load_best_model_at_end still works if this run is resumed in a new session.
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2), HubBestAdapterCallback(repo_id_standard)],
)

# 6. Start (or resume) Fine-Tuning
if resume_checkpoint:
    print(f"Resuming LoRA Supervised Fine-Tuning from {resume_checkpoint}...")
else:
    print("Starting LoRA Supervised Fine-Tuning...")
# Skips training (and loads the final Hub adapter) if this run already finished --
# resuming a finished run would otherwise retrain an epoch and replace the best weights.
train_or_load_finished(trainer, repo_id_standard, resume_checkpoint)

trainable params: 6,389,760 || all params: 859,375,680 || trainable%: 0.7435

training_recipe.json:   0%|          | 0.00/33.0 [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

Found a resumable checkpoint on the Hub for 'bdatm-project/qwen-task1-standard-lora': /root/.cache/huggingface/hub/models--bdatm-project--qwen-task1-standard-lora/snapshots/17b4d814973feec6b44a0088cf63456547faba34/last-checkpoint
Resuming LoRA Supervised Fine-Tuning from /root/.cache/huggingface/hub/models--bdatm-project--qwen-task1-standard-lora/snapshots/17b4d814973feec6b44a0088cf63456547faba34/last-checkpoint...

[transformers] The best checkpoint ./qwen_task1_lora_output/checkpoint-1600 recorded in the resumed state does not exist anymore. Ignoring it for this run.

TrainOutput(global_step=3600, training_loss=0.030957272383901807, metrics={'train_runtime': 538.3362, 'train_samples_per_second': 59.442, 'train_steps_per_second': 7.43, 'total_flos': 4.065660124633498e+16, 'train_loss': 0.030957272383901807, 'epoch': 9.0})

Saving model on hugging face

In [8]:
# 6. Save weights to Hugging Face folder
hf_org_prefix = "bdatm-project"
repo_id_standard = f"{hf_org_prefix}/qwen-task1-standard-lora"

print(f"Pushing standard LoRA model and processor to Hugging Face Hub: {repo_id_standard}...")

trainer.model.push_to_hub(
    repo_id_standard,
    commit_message="Training complete for standard LoRA baseline (raster-scan)"
)
processor.push_to_hub(
    repo_id_standard
)

print("Fine-tuning completed and weights successfully uploaded to Hugging Face Hub!")

Pushing standard LoRA model and processor to Hugging Face Hub: bdatm-project/qwen-task1-standard-lora...

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:  62%|######2   | 16.0MB / 25.6MB

Validating                    :           |   0%

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpzq_czx83/tokenizer.json: 100%|##########| 20.0MB / 20.0MB

Validating                    :           |   0%

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Fine-tuning completed and weights successfully uploaded to Hugging Face Hub!

Loading model and evaluation

In [9]:
# 7. Loading Model from hugging face and evaluate model using predefined functions
print("\nLoading standard LoRA model from Hugging Face for evaluation...")

# Load fresh base model instance
base_eval_model = AutoModelForImageTextToText.from_pretrained(
    "Qwen/Qwen3.5-0.8B",
    torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

# Load the LoRA weights directly from the Hub repository
standard_lora_eval_model = PeftModel.from_pretrained(base_eval_model, repo_id_standard)

print("Evaluating the Hugging Face LoRA model on the test set...")
lora_results_df, lora_summary_df = evaluate_with_cache(
    task="task1",
    model=standard_lora_eval_model,
    processor=processor,
    dataset_split=dataset_task1["test"],
    model_name="Qwen + LoRA Fine-Tuning (from HF)",
    hf_org_prefix=hf_org_prefix,
    adapter_repo_id=repo_id_standard,  # cache is tied to this adapter's Hub commit
)

# Append the new metrics to the global comparison DataFrame
all_models_results = append_or_replace(all_models_results, lora_summary_df)

print("\nUpdated Comparative Summary Table (all_models_results):")
display(all_models_results)

Loading standard LoRA model from Hugging Face for evaluation...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating the Hugging Face LoRA model on the test set...

Evaluating Qwen + LoRA Fine-Tuning (from HF): 100%|██████████| 400/400 [21:11<00:00,  3.18s/it]

Evaluation completed for Qwen + LoRA Fine-Tuning (from HF)! Results saved to task1_qwen_+_lora_fine-tuning_(from_hf)_results.csv.

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmp5j12hvlw.parquet    : 100%|##########| 3.63kB / 3.63kB

Validating                    :           |   0%

[task1] Cached evaluation for 'Qwen + LoRA Fine-Tuning (from HF)' -- pushed to 'bdatm-project/evaluation-results-task1'.

Updated Comparative Summary Table (all_models_results):

,model_name,fen_exact_match,character_error_rate,square_by_square_accuracy,levenshtein_distance,adapter_sha
0,Vanilla Qwen2.5-VL (Zero-Shot),0.0000,3.259093,0.000000,169.2250,NaN
1,Qwen + LoRA Fine-Tuning (from HF),0.0075,0.043934,0.994844,2.2775,df1de1e657acce1785c7604a3206a4ec22b1a28f

## Reordering patches - Advanced models

Checking function *get_patch_reordering_indices()*

In [10]:
for strat in ["raster", "zigzag", "spiral", "file_wise"]:
    order_map = get_patch_reordering_indices(strategy=strat)
    print(f"Strategy '{strat}' first 10 patch indices: {order_map[:10]}")

Strategy 'raster' first 10 patch indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Strategy 'zigzag' first 10 patch indices: [0, 1, 2, 3, 4, 5, 6, 7, 15, 14]
Strategy 'spiral' first 10 patch indices: [0, 1, 2, 3, 4, 5, 6, 7, 15, 23]
Strategy 'file_wise' first 10 patch indices: [0, 8, 16, 24, 32, 40, 48, 56, 1, 9]

Let's evalaute the model we created before using three different patch ordering: zigzag, spiral and file-wise. We'll use the function ***reorder_chessboard_image*** defined in *src/eval/utilities.py*

In [11]:
# ==========================================
# Training-Free Benchmark Loop for REOrder
# ==========================================

# Define the strategies you want to benchmark (as outlined in the project specs)
strategies_to_test = ["zigzag", "spiral", "file_wise"]

# Choose the model to test (we use the fine-tuned LoRA model)
model_to_evaluate = lora_model  # You can switch to 'model' if you want to test the vanilla version

for strat in strategies_to_test:
    print(f"\nEvaluating strategy (Training-Free): {strat.upper()}...")

    # 1. Apply the reordering function to the images in the test set
    reordered_test_split = dataset_task1["test"].map(
        lambda sample: {
            "image": reorder_chessboard_image(sample["image"], strategy=strat, grid_size=8)
        }
    )

    # 2. Run the evaluation function on the reordered test split
    strat_results_df, strat_summary_df = evaluate_with_cache(
        task="task1",
        model=model_to_evaluate,
        processor=processor,
        dataset_split=reordered_test_split,
        model_name=f"Qwen + LoRA ({strat.capitalize()} - TF)",
        hf_org_prefix=hf_org_prefix,
        adapter_repo_id=repo_id_standard,  # cache is tied to this adapter's Hub commit
    )

    # 3. Append the results to your global comparison table
    all_models_results = append_or_replace(all_models_results, strat_summary_df)

print("\n--- Final Comparative Summary Table (Including Training-Free Strategies) ---")
display(all_models_results)

Evaluating strategy (Training-Free): ZIGZAG...

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/466 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 3.63kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/2 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/beaaec9bfe5c8fadc9c497dc9d07b26cfe7c7cf0/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/beaaec9bfe5c8fadc9c497dc9d07b26cfe7c7cf0/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Evaluating Qwen + LoRA (Zigzag - TF): 100%|██████████| 400/400 [21:37<00:00,  3.24s/it]

Evaluation completed for Qwen + LoRA (Zigzag - TF)! Results saved to task1_qwen_+_lora_(zigzag_-_tf)_results.csv.

Generating train split:   0%|          | 0/2 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/f47ddb9553efec047501333361153fa2f1497adf/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/f47ddb9553efec047501333361153fa2f1497adf/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmp1wbx7cle.parquet    : 100%|##########| 3.52kB / 3.52kB

Validating                    :           |   0%

[task1] Cached evaluation for 'Qwen + LoRA (Zigzag - TF)' -- pushed to 'bdatm-project/evaluation-results-task1'.

Evaluating strategy (Training-Free): SPIRAL...

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/466 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 3.52kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/590ca8bd3f9f981e03357acabdc4f06578c9df6f/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/590ca8bd3f9f981e03357acabdc4f06578c9df6f/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Evaluating Qwen + LoRA (Spiral - TF): 100%|██████████| 400/400 [21:59<00:00,  3.30s/it]

Evaluation completed for Qwen + LoRA (Spiral - TF)! Results saved to task1_qwen_+_lora_(spiral_-_tf)_results.csv.

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/a2d508486519168be109ec90f3b45afabdec7bbe/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/a2d508486519168be109ec90f3b45afabdec7bbe/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmpkfkuh4ub.parquet    : 100%|##########| 3.52kB / 3.52kB

Validating                    :           |   0%

[task1] Cached evaluation for 'Qwen + LoRA (Spiral - TF)' -- pushed to 'bdatm-project/evaluation-results-task1'.

Evaluating strategy (Training-Free): FILE_WISE...

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 3.52kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/6d387a026d8aef7e8440aadc2164ed7797031a21/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/6d387a026d8aef7e8440aadc2164ed7797031a21/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Evaluating Qwen + LoRA (File_wise - TF): 100%|██████████| 400/400 [21:50<00:00,  3.28s/it]

Evaluation completed for Qwen + LoRA (File_wise - TF)! Results saved to task1_qwen_+_lora_(file_wise_-_tf)_results.csv.

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/54c8b31e5d7d5e7949f098218014f128e00bbfe5/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/54c8b31e5d7d5e7949f098218014f128e00bbfe5/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmpjgnk3x_u.parquet    : 100%|##########| 3.54kB / 3.54kB

Validating                    :           |   0%

[task1] Cached evaluation for 'Qwen + LoRA (File_wise - TF)' -- pushed to 'bdatm-project/evaluation-results-task1'.

--- Final Comparative Summary Table (Including Training-Free Strategies) ---

,model_name,fen_exact_match,character_error_rate,square_by_square_accuracy,levenshtein_distance,adapter_sha
0,Vanilla Qwen2.5-VL (Zero-Shot),0.0000,3.259093,0.000000,169.2250,NaN
1,Qwen + LoRA Fine-Tuning (from HF),0.0075,0.043934,0.994844,2.2775,df1de1e657acce1785c7604a3206a4ec22b1a28f
2,Qwen + LoRA (Zigzag - TF),0.0000,0.314656,0.500781,16.4500,df1de1e657acce1785c7604a3206a4ec22b1a28f
3,Qwen + LoRA (Spiral - TF),0.0000,0.621696,0.379414,33.0075,df1de1e657acce1785c7604a3206a4ec22b1a28f
4,Qwen + LoRA (File_wise - TF),0.0000,0.653481,0.570391,34.9800,df1de1e657acce1785c7604a3206a4ec22b1a28f

As highlighted in the summary table, applying unconventional patch reordering strategies (such as Zigzag, Spiral, or File-wise) in a "Training-Free" (TF) manner leads to a performance drop, resulting in an increased Character Error Rate (CER) and Levenshtein distance compared to the standard raster-scan baseline.

To truly reap the benefits of the REOrder methodology, we must proceed with Supervised Fine-Tuning (SFT) directly on the pre-reordered dataset. This will allow the model to adapt its weights and attention layers to the new spatial serialization strategy.

Finetuning the new models on the dataset using function **finetune_and_push_chessboard_model()** defined in *src/eval/utilities.py*. This function directly upload the models on hugging face

In [12]:
import gc

strategies_to_train = ["zigzag", "spiral", "file_wise"]

# Repo IDs, NOT the model objects: the eval cells below always reload each
# strategy's weights fresh from the Hub (PeftModel.from_pretrained), so
# nothing here needs the trained model kept in memory after it's pushed.
# Keeping it (dict of model objects, one per strategy) held every strategy's
# full base+LoRA model on the GPU at once -- memory grew with each strategy
# instead of staying flat, which is what caused an OutOfMemoryError on the
# 3rd strategy. Explicitly deleting the model and clearing the CUDA cache
# after each strategy keeps peak GPU memory to roughly one strategy's worth
# at a time, and lets this run on a smaller/cheaper GPU.
trained_reordered_repo_ids = {}

print("=== Starting Fine-Tuning Pipeline for Task 1 (Reordering Strategies) ===")
2
for strat in strategies_to_train:
    print(f"\nLoading fresh base model for Task 1 | Strategy: {strat}...")

    # Load a clean instance of the base model for each strategy
    base_model = AutoModelForImageTextToText.from_pretrained(
        model_id,
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
        device_map="auto"
    )

    trained_model = finetune_and_push_chessboard_model(
        strategy_name=strat,
        dataset=dataset_task1,
        processor=processor,
        model=base_model,
        peft_config=peft_config,
        task="task1",
        hf_org_prefix=hf_org_prefix,
    )
    trained_reordered_repo_ids[strat] = f"{hf_org_prefix}/qwen-task1-{strat}-lora"

    # Free this strategy's GPU memory before the next strategy loads its own
    # fresh base model -- see the note above.
    del trained_model, base_model
    gc.collect()
    torch.cuda.empty_cache()

print("\nAll reordered models have been successfully trained and pushed to Hugging Face!")

=== Starting Fine-Tuning Pipeline for Task 1 (Reordering Strategies) ===

Loading fresh base model for Task 1 | Strategy: zigzag...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

==============================================
Starting pipeline for TASK: TASK1 | STRATEGY: ZIGZAG
==============================================
Applying LoRA to the provided model...

training_recipe.json:   0%|          | 0.00/33.0 [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 0 files: 0it [00:00, ?it/s]

Training model for task1 with zigzag reordering...

Pushing model and processor to Hugging Face Hub: bdatm-project/qwen-task1-zigzag-lora...

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:  62%|######2   | 16.0MB / 25.6MB

Validating                    :           |   0%

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpbiufql5l/tokenizer.json:  80%|#######9  | 16.0MB / 20.0MB

Validating                    :           |   0%

Finished! Successfully uploaded to Hub: bdatm-project/qwen-task1-zigzag-lora

Loading fresh base model for Task 1 | Strategy: spiral...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

==============================================
Starting pipeline for TASK: TASK1 | STRATEGY: SPIRAL
==============================================
Applying LoRA to the provided model...
Ignoring the checkpoint in 'bdatm-project/qwen-task1-spiral-lora': it was trained with recipe None, the current code uses 'answer-only-loss-v1'. Starting fresh.
Training model for task1 with spiral reordering...

Pushing model and processor to Hugging Face Hub: bdatm-project/qwen-task1-spiral-lora...

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:  62%|######2   | 16.0MB / 25.6MB

Validating                    :           |   0%

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpqmx2r6gc/tokenizer.json:  80%|#######9  | 16.0MB / 20.0MB

Validating                    :           |   0%

Finished! Successfully uploaded to Hub: bdatm-project/qwen-task1-spiral-lora

Loading fresh base model for Task 1 | Strategy: file_wise...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

==============================================
Starting pipeline for TASK: TASK1 | STRATEGY: FILE_WISE
==============================================
Applying LoRA to the provided model...
Ignoring the checkpoint in 'bdatm-project/qwen-task1-file_wise-lora': it was trained with recipe None, the current code uses 'answer-only-loss-v1'. Starting fresh.
Training model for task1 with file_wise reordering...

Pushing model and processor to Hugging Face Hub: bdatm-project/qwen-task1-file_wise-lora...

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:  62%|######2   | 16.0MB / 25.6MB

Validating                    :           |   0%

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mphjdae668/tokenizer.json:  80%|#######9  | 16.0MB / 20.0MB

Validating                    :           |   0%

Finished! Successfully uploaded to Hub: bdatm-project/qwen-task1-file_wise-lora

All reordered models have been successfully trained and pushed to Hugging Face!

Evaluating models using function **evaluate_chessboard_model_task_1()** defined in *src/eval/utilities.py*.

Models are downloaded from the hugging face repo.

In [13]:
strategies_to_evaluate = ["zigzag", "spiral", "file_wise"]

# Robust to running this cell on its own, in any session: pulls in whatever's
# already cached on the Hub instead of relying on all_models_results already
# being defined from an earlier cell in this same kernel.
if "all_models_results" not in dir():
    all_models_results = load_or_init_results_table(task="task1", hf_org_prefix=hf_org_prefix)

for strat in strategies_to_evaluate:
    print(f"\nLoading and evaluating SFT model for strategy: {strat.upper()} from Hugging Face...")

    # 1. Load fresh base model instance
    base_eval_model = AutoModelForImageTextToText.from_pretrained(
        "Qwen/Qwen3.5-0.8B",
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
        device_map="auto"
    )

    # 2. Load the specific LoRA weights from Hugging Face Hub
    repo_id_source = f"{hf_org_prefix}/qwen-task1-{strat}-lora"
    model_to_eval = PeftModel.from_pretrained(base_eval_model, repo_id_source)

    # 3. Apply the specific patch reordering to the test split images
    reordered_test_split = dataset_task1["test"].map(
        lambda sample: {
            "image": reorder_chessboard_image(sample["image"], strategy=strat, grid_size=8)
        }
    )

    # 4. Run the evaluation utility function -- cached, so a strategy already
    # evaluated in a previous run/session is skipped instantly instead of
    # re-running generation on all 400 test samples.
    strat_results_df, strat_summary_df = evaluate_with_cache(
        task="task1",
        model=model_to_eval,
        processor=processor,
        dataset_split=reordered_test_split,
        model_name=f"Qwen + LoRA ({strat.capitalize()} - SFT)",
        hf_org_prefix=hf_org_prefix,
        adapter_repo_id=repo_id_source,  # cache is tied to this adapter's Hub commit
    )

    # 5. Append results to the global comparison DataFrame
    all_models_results = append_or_replace(all_models_results, strat_summary_df)

print("\n--- Final Comparative Summary Table (Loaded from Hub & Evaluated) ---")
display(all_models_results)

Loading and evaluating SFT model for strategy: ZIGZAG from Hugging Face...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 3.54kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/ef0b816ef0e8a20908a3b46581e7461293904b70/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/ef0b816ef0e8a20908a3b46581e7461293904b70/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Evaluating Qwen + LoRA (Zigzag - SFT): 100%|██████████| 400/400 [21:29<00:00,  3.22s/it]

Evaluation completed for Qwen + LoRA (Zigzag - SFT)! Results saved to task1_qwen_+_lora_(zigzag_-_sft)_results.csv.

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/48451ea701173ef8259308c91f9c025d3713bd47/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/48451ea701173ef8259308c91f9c025d3713bd47/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmpu3nv6gmn.parquet    : 100%|##########| 3.53kB / 3.53kB

Validating                    :           |   0%

[task1] Cached evaluation for 'Qwen + LoRA (Zigzag - SFT)' -- pushed to 'bdatm-project/evaluation-results-task1'.

Loading and evaluating SFT model for strategy: SPIRAL from Hugging Face...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

README.md:   0%|          | 0.00/466 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 3.53kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/ce3e93c2dfa4493fa7528c02ba6fcb687571a893/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/ce3e93c2dfa4493fa7528c02ba6fcb687571a893/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Evaluating Qwen + LoRA (Spiral - SFT): 100%|██████████| 400/400 [21:34<00:00,  3.24s/it]

Evaluation completed for Qwen + LoRA (Spiral - SFT)! Results saved to task1_qwen_+_lora_(spiral_-_sft)_results.csv.

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/b5db3b8ad759b8462236a1fa9e6781489d98d428/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/b5db3b8ad759b8462236a1fa9e6781489d98d428/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmpttd2yekx.parquet    : 100%|##########| 3.53kB / 3.53kB

Validating                    :           |   0%

[task1] Cached evaluation for 'Qwen + LoRA (Spiral - SFT)' -- pushed to 'bdatm-project/evaluation-results-task1'.

Loading and evaluating SFT model for strategy: FILE_WISE from Hugging Face...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 3.53kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/f13495fa1f8ed164f0826e034bab85edcd963150/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/f13495fa1f8ed164f0826e034bab85edcd963150/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Evaluating Qwen + LoRA (File_wise - SFT): 100%|██████████| 400/400 [21:16<00:00,  3.19s/it]

Evaluation completed for Qwen + LoRA (File_wise - SFT)! Results saved to task1_qwen_+_lora_(file_wise_-_sft)_results.csv.

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/4f6869a460a8d5648ef1aabc3305e590eb62aeed/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/4f6869a460a8d5648ef1aabc3305e590eb62aeed/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmpaeezx_6n.parquet    : 100%|##########| 3.54kB / 3.54kB

Validating                    :           |   0%

[task1] Cached evaluation for 'Qwen + LoRA (File_wise - SFT)' -- pushed to 'bdatm-project/evaluation-results-task1'.

--- Final Comparative Summary Table (Loaded from Hub & Evaluated) ---

,model_name,fen_exact_match,character_error_rate,square_by_square_accuracy,levenshtein_distance,adapter_sha
0,Vanilla Qwen2.5-VL (Zero-Shot),0.0000,3.259093,0.000000,169.2250,NaN
1,Qwen + LoRA Fine-Tuning (from HF),0.0075,0.043934,0.994844,2.2775,df1de1e657acce1785c7604a3206a4ec22b1a28f
2,Qwen + LoRA (Zigzag - TF),0.0000,0.314656,0.500781,16.4500,df1de1e657acce1785c7604a3206a4ec22b1a28f
3,Qwen + LoRA (Spiral - TF),0.0000,0.621696,0.379414,33.0075,df1de1e657acce1785c7604a3206a4ec22b1a28f
4,Qwen + LoRA (File_wise - TF),0.0000,0.653481,0.570391,34.9800,df1de1e657acce1785c7604a3206a4ec22b1a28f
5,Qwen + LoRA (Zigzag - SFT),0.0125,0.044541,0.974492,2.2975,2e7358f780fb18aca54b0b96e626811ef9b34335
6,Qwen + LoRA (Spiral - SFT),0.0125,0.046081,0.996680,2.3850,cb9ddf3ac519846bd91e962711ff4667bc7a1573
7,Qwen + LoRA (File_wise - SFT),0.0225,0.044630,0.999648,2.3050,27bf9ae48a8332ef6fe9d1ad70e6a5954fa38359

## Learned Reordering (Project Work)

Instead of a fixed strategy, trains a lightweight `PlackettLucePatchPolicy` (`src/training/learned_reordering.py`) jointly with LoRA to learn which 8x8 patch order helps the model most, via REINFORCE using the per-sample LM loss as the reward — see the module's docstring for how this differs from REOrder's own from-scratch-model approach.

**Known limitations of this first version, worth knowing before running:** unlike the `Trainer`-based cells above, this custom training loop has **no checkpointing or resume support** — a Colab disconnect mid-run loses all progress, not just the current epoch. It's also unbatched (one sample at a time, no gradient accumulation) and does two backward passes per sample (model + policy), so it's slower per-epoch than the standard fine-tuning above. `num_train_epochs` is kept low below (3, not the default 10) to keep a first run's wall-clock time and disconnect risk bounded — raise it once you've confirmed this runs end-to-end.

In [14]:
print("=== Starting Learned Reordering Training Pipeline for Task 1 ===")

# Fresh base model instance, same pattern as the training-free strategies above
base_model_learned = AutoModelForImageTextToText.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

learned_lora_model, learned_policy, repo_id_learned = train_with_learned_reordering(
    dataset=dataset_task1,
    processor=processor,
    model=base_model_learned,
    peft_config=peft_config,
    task="task1",
    hf_org_prefix=hf_org_prefix,
    num_train_epochs=3,  # kept low for a first run -- see the note above
)

print(f"\nLearned Reordering training complete. Model pushed to: {repo_id_learned}")

=== Starting Learned Reordering Training Pipeline for Task 1 ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 0 files: 0it [00:00, ?it/s]

No resumable learned-reordering checkpoint found for task1; starting fresh.
[task1] epoch 0 step 10: lm_loss=2.0732 policy_loss=-11.5994 baseline=-1.3776
[task1] epoch 0 step 20: lm_loss=1.6824 policy_loss=-0.1923 baseline=-1.6751
[task1] epoch 0 step 30: lm_loss=1.5615 policy_loss=6.1645 baseline=-1.7793
[task1] epoch 0 step 40: lm_loss=1.7412 policy_loss=0.8455 baseline=-1.7925
[task1] epoch 0 step 50: lm_loss=1.3818 policy_loss=5.8852 baseline=-1.6683
[task1] epoch 0 step 60: lm_loss=1.8056 policy_loss=-2.2154 baseline=-1.7138
[task1] epoch 0 step 70: lm_loss=1.6287 policy_loss=0.5237 baseline=-1.6521
[task1] epoch 0 step 80: lm_loss=1.7131 policy_loss=-1.2995 baseline=-1.6549
[task1] epoch 0 step 90: lm_loss=1.4510 policy_loss=4.9871 baseline=-1.5831
[task1] epoch 0 step 100: lm_loss=1.3655 policy_loss=4.6139 baseline=-1.5686
[task1] epoch 0 step 110: lm_loss=1.6040 policy_loss=0.0972 baseline=-1.6092
[task1] epoch 0 step 120: lm_loss=1.5298 policy_loss=1.8119 baseline=-1.6096
[task1] epoch 0 step 130: lm_loss=1.3977 policy_loss=2.1158 baseline=-1.5136
[task1] epoch 0 step 140: lm_loss=1.6701 policy_loss=-2.8614 baseline=-1.5312
[task1] epoch 0 step 150: lm_loss=1.7272 policy_loss=-5.9604 baseline=-1.4828
[task1] epoch 0 step 160: lm_loss=1.7011 policy_loss=-5.7391 baseline=-1.5200
[task1] epoch 0 step 170: lm_loss=1.3333 policy_loss=2.8558 baseline=-1.4717
[task1] epoch 0 step 180: lm_loss=1.4648 policy_loss=-1.0126 baseline=-1.4333
[task1] epoch 0 step 190: lm_loss=1.4944 policy_loss=0.0739 baseline=-1.4974
[task1] epoch 0 step 200: lm_loss=1.6889 policy_loss=-4.4309 baseline=-1.5109
[task1] checkpoint saved at epoch 0, step 200 (global step 200).
[task1] epoch 0 step 210: lm_loss=1.5558 policy_loss=-1.5631 baseline=-1.5065
[task1] epoch 0 step 220: lm_loss=1.4342 policy_loss=0.3820 baseline=-1.4463
[task1] epoch 0 step 230: lm_loss=1.1568 policy_loss=9.6219 baseline=-1.4721
[task1] epoch 0 step 240: lm_loss=1.2569 policy_loss=4.6115 baseline=-1.4299
[task1] epoch 0 step 250: lm_loss=1.5303 policy_loss=-2.3824 baseline=-1.4445
[task1] epoch 0 step 260: lm_loss=1.4448 policy_loss=0.4811 baseline=-1.4640
[task1] epoch 0 step 270: lm_loss=1.4474 policy_loss=0.7482 baseline=-1.4814
[task1] epoch 0 step 280: lm_loss=1.5664 policy_loss=-3.0067 baseline=-1.4609
[task1] epoch 0 step 290: lm_loss=1.5893 policy_loss=-5.1341 baseline=-1.4568
[task1] epoch 0 step 300: lm_loss=1.4715 policy_loss=-0.6646 baseline=-1.4422
[task1] epoch 0 step 310: lm_loss=1.2066 policy_loss=4.4248 baseline=-1.3527
[task1] epoch 0 step 320: lm_loss=1.4405 policy_loss=-0.7477 baseline=-1.3948
[task1] epoch 0 step 330: lm_loss=0.9057 policy_loss=14.0482 baseline=-1.3108
[task1] epoch 0 step 340: lm_loss=1.5279 policy_loss=-2.7740 baseline=-1.4197
[task1] epoch 0 step 350: lm_loss=1.7984 policy_loss=-9.6008 baseline=-1.4107
[task1] epoch 0 step 360: lm_loss=1.7199 policy_loss=-8.5274 baseline=-1.4725
[task1] epoch 0 step 370: lm_loss=1.4602 policy_loss=0.1460 baseline=-1.4673
[task1] epoch 0 step 380: lm_loss=1.3161 policy_loss=1.8166 baseline=-1.3900
[task1] epoch 0 step 390: lm_loss=1.4180 policy_loss=-1.0283 baseline=-1.3684
[task1] epoch 0 step 400: lm_loss=1.2658 policy_loss=1.8446 baseline=-1.3325
[task1] checkpoint saved at epoch 0, step 400 (global step 400).
[task1] epoch 0 step 410: lm_loss=1.4449 policy_loss=0.0149 baseline=-1.4454
[task1] epoch 0 step 420: lm_loss=1.4252 policy_loss=-0.0469 baseline=-1.4233
[task1] epoch 0 step 430: lm_loss=1.3679 policy_loss=-0.0291 baseline=-1.3665
[task1] epoch 0 step 440: lm_loss=1.7922 policy_loss=-10.3919 baseline=-1.3907
[task1] epoch 0 step 450: lm_loss=1.1919 policy_loss=2.1024 baseline=-1.2794
[task1] epoch 0 step 460: lm_loss=1.3195 policy_loss=-1.1722 baseline=-1.2627
[task1] epoch 0 step 470: lm_loss=1.2060 policy_loss=1.2100 baseline=-1.2474
[task1] epoch 0 step 480: lm_loss=1.0457 policy_loss=4.0441 baseline=-1.2220
[task1] epoch 0 step 490: lm_loss=1.5428 policy_loss=-8.1527 baseline=-1.2217
[task1] epoch 0 step 500: lm_loss=1.1438 policy_loss=1.0240 baseline=-1.1884
[task1] epoch 0 step 510: lm_loss=1.2046 policy_loss=-0.0191 baseline=-1.2038
[task1] epoch 0 step 520: lm_loss=1.4058 policy_loss=-2.8261 baseline=-1.2548
[task1] epoch 0 step 530: lm_loss=1.3731 policy_loss=-0.6921 baseline=-1.3426
[task1] epoch 0 step 540: lm_loss=1.1456 policy_loss=1.5102 baseline=-1.2034
[task1] epoch 0 step 550: lm_loss=1.2141 policy_loss=-0.9091 baseline=-1.1761
[task1] epoch 0 step 560: lm_loss=1.0287 policy_loss=0.0842 baseline=-1.0314
[task1] epoch 0 step 570: lm_loss=0.8423 policy_loss=4.0101 baseline=-1.0191
[task1] epoch 0 step 580: lm_loss=1.5334 policy_loss=-11.6614 baseline=-1.1046
[task1] epoch 0 step 590: lm_loss=0.8597 policy_loss=4.6026 baseline=-0.9980
[task1] epoch 0 step 600: lm_loss=1.0119 policy_loss=-1.5435 baseline=-0.9732
[task1] checkpoint saved at epoch 0, step 600 (global step 600).
[task1] epoch 0 step 610: lm_loss=0.9534 policy_loss=2.1504 baseline=-1.0205
[task1] epoch 0 step 620: lm_loss=1.0202 policy_loss=-0.5999 baseline=-0.9947
[task1] epoch 0 step 630: lm_loss=1.0047 policy_loss=-0.3998 baseline=-0.9925
[task1] epoch 0 step 640: lm_loss=0.7885 policy_loss=3.2255 baseline=-0.9675
[task1] epoch 0 step 650: lm_loss=0.6415 policy_loss=7.0762 baseline=-0.8757
[task1] epoch 0 step 660: lm_loss=0.8161 policy_loss=2.4167 baseline=-0.9213
[task1] epoch 0 step 670: lm_loss=0.8064 policy_loss=2.3675 baseline=-0.8874
[task1] epoch 0 step 680: lm_loss=0.6002 policy_loss=7.1492 baseline=-0.8939
[task1] epoch 0 step 690: lm_loss=0.8513 policy_loss=-0.6498 baseline=-0.8252
[task1] epoch 0 step 700: lm_loss=0.6070 policy_loss=3.0398 baseline=-0.7888
[task1] epoch 0 step 710: lm_loss=0.6845 policy_loss=1.6526 baseline=-0.7799
[task1] epoch 0 step 720: lm_loss=0.6792 policy_loss=1.2001 baseline=-0.7288
[task1] epoch 0 step 730: lm_loss=0.9142 policy_loss=-3.3631 baseline=-0.7850
[task1] epoch 0 step 740: lm_loss=0.8347 policy_loss=0.2839 baseline=-0.8447
[task1] epoch 0 step 750: lm_loss=0.7093 policy_loss=3.6723 baseline=-0.8346
[task1] epoch 0 step 760: lm_loss=0.9123 policy_loss=-1.4563 baseline=-0.8235
[task1] epoch 0 step 770: lm_loss=0.8159 policy_loss=0.6839 baseline=-0.8403
[task1] epoch 0 step 780: lm_loss=0.6859 policy_loss=1.8050 baseline=-0.7598
[task1] epoch 0 step 790: lm_loss=0.4263 policy_loss=7.4791 baseline=-0.7395
[task1] epoch 0 step 800: lm_loss=0.7716 policy_loss=2.5568 baseline=-0.9029
[task1] checkpoint saved at epoch 0, step 800 (global step 800).
[task1] epoch 0 step 810: lm_loss=0.6304 policy_loss=7.4104 baseline=-0.8815
[task1] epoch 0 step 820: lm_loss=0.6580 policy_loss=3.3867 baseline=-0.8255
[task1] epoch 0 step 830: lm_loss=0.8046 policy_loss=-0.3020 baseline=-0.7948
[task1] epoch 0 step 840: lm_loss=0.8300 policy_loss=-1.2320 baseline=-0.7976
[task1] epoch 0 step 850: lm_loss=0.6881 policy_loss=4.7232 baseline=-0.8307
[task1] epoch 0 step 860: lm_loss=0.7380 policy_loss=3.0621 baseline=-0.8340
[task1] epoch 0 step 870: lm_loss=0.8409 policy_loss=1.5083 baseline=-0.9016
[task1] epoch 0 step 880: lm_loss=0.9154 policy_loss=-1.9027 baseline=-0.8201
[task1] epoch 0 step 890: lm_loss=0.5565 policy_loss=4.2900 baseline=-0.7821
[task1] epoch 0 step 900: lm_loss=0.5940 policy_loss=2.5185 baseline=-0.6912
[task1] epoch 0 step 910: lm_loss=0.7498 policy_loss=-1.2733 baseline=-0.6953
[task1] epoch 0 step 920: lm_loss=0.4894 policy_loss=6.4450 baseline=-0.6721
[task1] epoch 0 step 930: lm_loss=0.4911 policy_loss=6.2903 baseline=-0.6849
[task1] epoch 0 step 940: lm_loss=0.6726 policy_loss=-0.3362 baseline=-0.6539
[task1] epoch 0 step 950: lm_loss=0.5789 policy_loss=2.2942 baseline=-0.6673
[task1] epoch 0 step 960: lm_loss=0.4741 policy_loss=2.4819 baseline=-0.5968
[task1] epoch 0 step 970: lm_loss=0.8220 policy_loss=-4.4273 baseline=-0.6335
[task1] epoch 0 step 980: lm_loss=0.6285 policy_loss=2.0699 baseline=-0.7107
[task1] epoch 0 step 990: lm_loss=0.6743 policy_loss=0.7318 baseline=-0.7035
[task1] epoch 0 step 1000: lm_loss=0.5593 policy_loss=2.2826 baseline=-0.6737
[task1] checkpoint saved at epoch 0, step 1000 (global step 1000).
[task1] epoch 0 step 1010: lm_loss=0.5647 policy_loss=2.5776 baseline=-0.6716
[task1] epoch 0 step 1020: lm_loss=0.7037 policy_loss=-1.3818 baseline=-0.6575
[task1] epoch 0 step 1030: lm_loss=0.3891 policy_loss=4.8366 baseline=-0.6213
[task1] epoch 0 step 1040: lm_loss=0.5980 policy_loss=-0.1351 baseline=-0.5930
[task1] epoch 0 step 1050: lm_loss=0.6820 policy_loss=-1.6449 baseline=-0.6367
[task1] epoch 0 step 1060: lm_loss=0.5311 policy_loss=2.4364 baseline=-0.6228
[task1] epoch 0 step 1070: lm_loss=0.8922 policy_loss=-9.4480 baseline=-0.6327
[task1] epoch 0 step 1080: lm_loss=0.5694 policy_loss=2.2270 baseline=-0.6422
[task1] epoch 0 step 1090: lm_loss=0.5790 policy_loss=0.8966 baseline=-0.6014
[task1] epoch 0 step 1100: lm_loss=0.6028 policy_loss=-0.5954 baseline=-0.5673
[task1] epoch 0 step 1110: lm_loss=0.5109 policy_loss=1.5122 baseline=-0.5679
[task1] epoch 0 step 1120: lm_loss=0.6677 policy_loss=-1.8430 baseline=-0.5749
[task1] epoch 0 step 1130: lm_loss=0.7838 policy_loss=-5.5282 baseline=-0.6468
[task1] epoch 0 step 1140: lm_loss=0.6009 policy_loss=1.1425 baseline=-0.6404
[task1] epoch 0 step 1150: lm_loss=0.4615 policy_loss=3.8043 baseline=-0.6017
[task1] epoch 0 step 1160: lm_loss=0.6163 policy_loss=0.2447 baseline=-0.6255
[task1] epoch 0 step 1170: lm_loss=0.4207 policy_loss=4.8591 baseline=-0.5964
[task1] epoch 0 step 1180: lm_loss=0.7989 policy_loss=-5.4962 baseline=-0.6068
[task1] epoch 0 step 1190: lm_loss=0.5872 policy_loss=0.8267 baseline=-0.6196
[task1] epoch 0 step 1200: lm_loss=0.4769 policy_loss=3.3488 baseline=-0.5943
[task1] checkpoint saved at epoch 0, step 1200 (global step 1200).
[task1] epoch 0 step 1210: lm_loss=0.5550 policy_loss=-0.7114 baseline=-0.5243
[task1] epoch 0 step 1220: lm_loss=0.5717 policy_loss=0.3812 baseline=-0.5882
[task1] epoch 0 step 1230: lm_loss=0.6865 policy_loss=-2.6055 baseline=-0.6129
[task1] epoch 0 step 1240: lm_loss=0.4631 policy_loss=2.6236 baseline=-0.5731
[task1] epoch 0 step 1250: lm_loss=0.5401 policy_loss=0.6900 baseline=-0.5725
[task1] epoch 0 step 1260: lm_loss=0.4840 policy_loss=0.1341 baseline=-0.4916
[task1] epoch 0 step 1270: lm_loss=0.4104 policy_loss=2.3983 baseline=-0.5141
[task1] epoch 0 step 1280: lm_loss=0.3433 policy_loss=5.1684 baseline=-0.5506
[task1] epoch 0 step 1290: lm_loss=0.5311 policy_loss=0.0283 baseline=-0.5325
[task1] epoch 0 step 1300: lm_loss=0.5632 policy_loss=0.4287 baseline=-0.5782
[task1] epoch 0 step 1310: lm_loss=0.7070 policy_loss=-5.5890 baseline=-0.5633
[task1] epoch 0 step 1320: lm_loss=0.6443 policy_loss=-1.7430 baseline=-0.5800
[task1] epoch 0 step 1330: lm_loss=0.5035 policy_loss=2.3809 baseline=-0.5862
[task1] epoch 0 step 1340: lm_loss=0.2928 policy_loss=5.5673 baseline=-0.5478
[task1] epoch 0 step 1350: lm_loss=0.6881 policy_loss=-4.1289 baseline=-0.5331
[task1] epoch 0 step 1360: lm_loss=0.4018 policy_loss=3.1390 baseline=-0.4949
[task1] epoch 0 step 1370: lm_loss=0.3358 policy_loss=5.4534 baseline=-0.5143
[task1] epoch 0 step 1380: lm_loss=0.2819 policy_loss=3.6098 baseline=-0.4935
[task1] epoch 0 step 1390: lm_loss=0.4529 policy_loss=1.1858 baseline=-0.4994
[task1] epoch 0 step 1400: lm_loss=0.4104 policy_loss=1.6178 baseline=-0.4995
[task1] checkpoint saved at epoch 0, step 1400 (global step 1400).
[task1] epoch 0 step 1410: lm_loss=0.4363 policy_loss=2.0988 baseline=-0.5222
[task1] epoch 0 step 1420: lm_loss=0.7574 policy_loss=-6.8240 baseline=-0.5602
[task1] epoch 0 step 1430: lm_loss=0.5302 policy_loss=0.3420 baseline=-0.5432
[task1] epoch 0 step 1440: lm_loss=0.4102 policy_loss=1.5868 baseline=-0.4791
[task1] epoch 0 step 1450: lm_loss=0.5803 policy_loss=-1.6302 baseline=-0.5170
[task1] epoch 0 step 1460: lm_loss=0.4169 policy_loss=1.4498 baseline=-0.4634
[task1] epoch 0 step 1470: lm_loss=0.5357 policy_loss=-1.7962 baseline=-0.4788
[task1] epoch 0 step 1480: lm_loss=0.3550 policy_loss=3.2320 baseline=-0.5212
[task1] epoch 0 step 1490: lm_loss=0.5442 policy_loss=0.1997 baseline=-0.5521
[task1] epoch 0 step 1500: lm_loss=0.3432 policy_loss=4.0888 baseline=-0.5516
[task1] epoch 0 step 1510: lm_loss=0.4885 policy_loss=1.1542 baseline=-0.5237
[task1] epoch 0 step 1520: lm_loss=0.5477 policy_loss=-0.4376 baseline=-0.5305
[task1] epoch 0 step 1530: lm_loss=0.6345 policy_loss=-2.8732 baseline=-0.4946
[task1] epoch 0 step 1540: lm_loss=0.4864 policy_loss=-0.6919 baseline=-0.4576
[task1] epoch 0 step 1550: lm_loss=0.8938 policy_loss=-7.4854 baseline=-0.5223
[task1] epoch 0 step 1560: lm_loss=0.4856 policy_loss=-0.1255 baseline=-0.4801
[task1] epoch 0 step 1570: lm_loss=0.4507 policy_loss=1.1729 baseline=-0.4887
[task1] epoch 0 step 1580: lm_loss=0.6294 policy_loss=-2.7623 baseline=-0.5497
[task1] epoch 0 step 1590: lm_loss=0.6308 policy_loss=-1.8873 baseline=-0.5707
[task1] epoch 0 step 1600: lm_loss=0.3879 policy_loss=2.2458 baseline=-0.4888
[task1] checkpoint saved at epoch 0, step 1600 (global step 1600).
[task1] epoch 0 step 1610: lm_loss=0.5464 policy_loss=-1.0537 baseline=-0.5064
[task1] epoch 0 step 1620: lm_loss=0.6634 policy_loss=-2.8281 baseline=-0.5415
[task1] epoch 0 step 1630: lm_loss=0.4626 policy_loss=1.5750 baseline=-0.5191
[task1] epoch 0 step 1640: lm_loss=0.9273 policy_loss=-9.9746 baseline=-0.5617
[task1] epoch 0 step 1650: lm_loss=0.6505 policy_loss=-0.5388 baseline=-0.6306
[task1] epoch 0 step 1660: lm_loss=0.4308 policy_loss=4.0755 baseline=-0.6213
[task1] epoch 0 step 1670: lm_loss=0.3380 policy_loss=4.3866 baseline=-0.5341
[task1] epoch 0 step 1680: lm_loss=0.4787 policy_loss=1.0584 baseline=-0.5240
[task1] epoch 0 step 1690: lm_loss=0.4485 policy_loss=1.4429 baseline=-0.5196
[task1] epoch 0 step 1700: lm_loss=0.4945 policy_loss=1.5786 baseline=-0.5580
[task1] epoch 0 step 1710: lm_loss=0.6740 policy_loss=-2.1506 baseline=-0.5799
[task1] epoch 0 step 1720: lm_loss=0.4308 policy_loss=3.3765 baseline=-0.5846
[task1] epoch 0 step 1730: lm_loss=0.9091 policy_loss=-11.4047 baseline=-0.6004
[task1] epoch 0 step 1740: lm_loss=0.4289 policy_loss=2.9826 baseline=-0.5544
[task1] epoch 0 step 1750: lm_loss=0.5890 policy_loss=-2.5888 baseline=-0.5155
[task1] epoch 0 step 1760: lm_loss=0.2959 policy_loss=4.5567 baseline=-0.5046
[task1] epoch 0 step 1770: lm_loss=0.6527 policy_loss=-1.4902 baseline=-0.6051
[task1] epoch 0 step 1780: lm_loss=0.3043 policy_loss=4.6887 baseline=-0.4853
[task1] epoch 0 step 1790: lm_loss=0.3235 policy_loss=3.1990 baseline=-0.4756
[task1] epoch 0 step 1800: lm_loss=0.5717 policy_loss=-1.7338 baseline=-0.5148
[task1] checkpoint saved at epoch 0, step 1800 (global step 1800).
[task1] epoch 0 step 1810: lm_loss=0.6563 policy_loss=-3.9084 baseline=-0.5185
[task1] epoch 0 step 1820: lm_loss=0.6615 policy_loss=-5.8515 baseline=-0.4854
[task1] epoch 0 step 1830: lm_loss=0.3226 policy_loss=5.3976 baseline=-0.5291
[task1] epoch 0 step 1840: lm_loss=0.3103 policy_loss=6.0766 baseline=-0.5235
[task1] epoch 0 step 1850: lm_loss=0.3029 policy_loss=3.4139 baseline=-0.4723
[task1] epoch 0 step 1860: lm_loss=0.4182 policy_loss=1.8288 baseline=-0.4949
[task1] epoch 0 step 1870: lm_loss=0.5136 policy_loss=0.3967 baseline=-0.5256
[task1] epoch 0 step 1880: lm_loss=0.7125 policy_loss=-6.4033 baseline=-0.4993
[task1] epoch 0 step 1890: lm_loss=0.3663 policy_loss=2.4185 baseline=-0.4651
[task1] epoch 0 step 1900: lm_loss=0.5707 policy_loss=-3.0387 baseline=-0.4783
[task1] epoch 0 step 1910: lm_loss=0.4977 policy_loss=0.1118 baseline=-0.5027
[task1] epoch 0 step 1920: lm_loss=0.7993 policy_loss=-6.9805 baseline=-0.5211
[task1] epoch 0 step 1930: lm_loss=0.4251 policy_loss=1.0043 baseline=-0.4849
[task1] epoch 0 step 1940: lm_loss=0.3664 policy_loss=2.8078 baseline=-0.4606
[task1] epoch 0 step 1950: lm_loss=0.4842 policy_loss=-0.1105 baseline=-0.4802
[task1] epoch 0 step 1960: lm_loss=0.5220 policy_loss=-2.2320 baseline=-0.4507
[task1] epoch 0 step 1970: lm_loss=0.5691 policy_loss=-2.1279 baseline=-0.4839
[task1] epoch 0 step 1980: lm_loss=0.4674 policy_loss=1.0026 baseline=-0.4991
[task1] epoch 0 step 1990: lm_loss=0.5186 policy_loss=-0.9087 baseline=-0.4804
[task1] epoch 0 step 2000: lm_loss=0.4477 policy_loss=0.5603 baseline=-0.4685
[task1] checkpoint saved at epoch 0, step 2000 (global step 2000).
[task1] epoch 0 step 2010: lm_loss=0.3669 policy_loss=2.2519 baseline=-0.4580
[task1] epoch 0 step 2020: lm_loss=0.4835 policy_loss=-1.6210 baseline=-0.4359
[task1] epoch 0 step 2030: lm_loss=0.2983 policy_loss=1.3757 baseline=-0.3834
[task1] epoch 0 step 2040: lm_loss=0.6362 policy_loss=-3.6397 baseline=-0.4700
[task1] epoch 0 step 2050: lm_loss=0.3971 policy_loss=1.0657 baseline=-0.4407
[task1] epoch 0 step 2060: lm_loss=0.4812 policy_loss=0.1655 baseline=-0.4880
[task1] epoch 0 step 2070: lm_loss=0.4774 policy_loss=-0.8673 baseline=-0.4466
[task1] epoch 0 step 2080: lm_loss=0.5596 policy_loss=-3.6044 baseline=-0.4441
[task1] epoch 0 step 2090: lm_loss=0.3344 policy_loss=3.4060 baseline=-0.4885
[task1] epoch 0 step 2100: lm_loss=0.2832 policy_loss=5.1276 baseline=-0.4507
[task1] epoch 0 step 2110: lm_loss=0.4935 policy_loss=-1.1468 baseline=-0.4555
[task1] epoch 0 step 2120: lm_loss=0.3796 policy_loss=3.0548 baseline=-0.4865
[task1] epoch 0 step 2130: lm_loss=0.4831 policy_loss=-0.0007 baseline=-0.4831
[task1] epoch 0 step 2140: lm_loss=0.3950 policy_loss=1.7860 baseline=-0.4684
[task1] epoch 0 step 2150: lm_loss=0.5143 policy_loss=-1.1864 baseline=-0.4706
[task1] epoch 0 step 2160: lm_loss=0.5411 policy_loss=-1.8521 baseline=-0.4586
[task1] epoch 0 step 2170: lm_loss=0.3481 policy_loss=3.6323 baseline=-0.4565
[task1] epoch 0 step 2180: lm_loss=0.3091 policy_loss=2.9112 baseline=-0.4358
[task1] epoch 0 step 2190: lm_loss=0.3705 policy_loss=1.4561 baseline=-0.4299
[task1] epoch 0 step 2200: lm_loss=0.5485 policy_loss=-2.3943 baseline=-0.4749
[task1] checkpoint saved at epoch 0, step 2200 (global step 2200).
[task1] epoch 0 step 2210: lm_loss=0.4929 policy_loss=-1.2618 baseline=-0.4401
[task1] epoch 0 step 2220: lm_loss=0.6859 policy_loss=-5.2548 baseline=-0.4788
[task1] epoch 0 step 2230: lm_loss=0.5967 policy_loss=-4.2741 baseline=-0.4774
[task1] epoch 0 step 2240: lm_loss=0.3094 policy_loss=2.5550 baseline=-0.4493
[task1] epoch 0 step 2250: lm_loss=0.4689 policy_loss=-1.7890 baseline=-0.4161
[task1] epoch 0 step 2260: lm_loss=0.2562 policy_loss=3.0059 baseline=-0.4171
[task1] epoch 0 step 2270: lm_loss=0.4195 policy_loss=1.8572 baseline=-0.4738
[task1] epoch 0 step 2280: lm_loss=0.5125 policy_loss=-1.8243 baseline=-0.4456
[task1] epoch 0 step 2290: lm_loss=0.5362 policy_loss=-1.8999 baseline=-0.4678
[task1] epoch 0 step 2300: lm_loss=0.3035 policy_loss=2.4720 baseline=-0.4511
[task1] epoch 0 step 2310: lm_loss=0.3080 policy_loss=2.7626 baseline=-0.3931
[task1] epoch 0 step 2320: lm_loss=0.4818 policy_loss=-0.2677 baseline=-0.4701
[task1] epoch 0 step 2330: lm_loss=0.2503 policy_loss=8.8276 baseline=-0.4895
[task1] epoch 0 step 2340: lm_loss=0.4538 policy_loss=-1.3924 baseline=-0.4185
[task1] epoch 0 step 2350: lm_loss=0.3573 policy_loss=1.4631 baseline=-0.4405
[task1] epoch 0 step 2360: lm_loss=0.6361 policy_loss=-4.4493 baseline=-0.4172
[task1] epoch 0 step 2370: lm_loss=0.3336 policy_loss=1.5547 baseline=-0.4165
[task1] epoch 0 step 2380: lm_loss=0.2867 policy_loss=2.9173 baseline=-0.4165
[task1] epoch 0 step 2390: lm_loss=0.2608 policy_loss=2.1839 baseline=-0.3797
[task1] epoch 0 step 2400: lm_loss=0.2614 policy_loss=1.9334 baseline=-0.3632
[task1] checkpoint saved at epoch 0, step 2400 (global step 2400).
[task1] epoch 0 step 2410: lm_loss=0.8763 policy_loss=-12.4806 baseline=-0.4707
[task1] epoch 0 step 2420: lm_loss=0.3760 policy_loss=2.7689 baseline=-0.4718
[task1] epoch 0 step 2430: lm_loss=0.4052 policy_loss=1.8523 baseline=-0.4698
[task1] epoch 0 step 2440: lm_loss=0.4278 policy_loss=-0.5778 baseline=-0.4114
[task1] epoch 0 step 2450: lm_loss=0.4018 policy_loss=0.5695 baseline=-0.4271

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:  62%|######2   | 16.0MB / 25.6MB

Validating                    :           |   0%

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mp80b317it/tokenizer.json: 100%|##########| 20.0MB / 20.0MB

Validating                    :           |   0%

Saved learned reordering policy weights to learned_reordering_output/policy.pt

Learned Reordering training complete. Model pushed to: bdatm-project/qwen-task1-learned-reordering-lora

Evaluating the learned-reordering model: training samples permutations stochastically (that's how REINFORCE explores), but evaluation needs one fixed ordering — `policy.greedy_permutation()` gives the policy's single best guess (argsort of its learned logits, no sampling noise), which is what actually gets applied to the test set here.

In [15]:
print("=== Evaluating the Learned Reordering model on Task 1 ===")

learned_permutation = learned_policy.greedy_permutation()
print(f"Learned (greedy) patch order: {learned_permutation}")

reordered_test_split = dataset_task1["test"].map(
    lambda sample: {
        "image": apply_patch_permutation(sample["image"], learned_permutation, grid_size=8)
    }
)

if "all_models_results" not in dir():
    all_models_results = load_or_init_results_table(task="task1", hf_org_prefix=hf_org_prefix)

learned_results_df, learned_summary_df = evaluate_with_cache(
    task="task1",
    model=learned_lora_model,
    processor=processor,
    dataset_split=reordered_test_split,
    model_name="Qwen + LoRA (Learned Reordering)",
    hf_org_prefix=hf_org_prefix,
    adapter_repo_id=repo_id_learned,  # cache is tied to this adapter's Hub commit
)

all_models_results = append_or_replace(all_models_results, learned_summary_df)

print("\n--- Comparative Summary Table (Including Learned Reordering) ---")
display(all_models_results)

=== Evaluating the Learned Reordering model on Task 1 ===
Learned (greedy) patch order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/466 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 3.54kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/8da6f320ebd5410b3f4ac0c638fb0584f26149f9/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/8da6f320ebd5410b3f4ac0c638fb0584f26149f9/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Evaluating Qwen + LoRA (Learned Reordering): 100%|██████████| 400/400 [21:41<00:00,  3.25s/it]

Evaluation completed for Qwen + LoRA (Learned Reordering)! Results saved to task1_qwen_+_lora_(learned_reordering)_results.csv.

Generating train split:   0%|          | 0/1 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/7ac0e9aa9080dfa005069d57ddc421ef74c493aa/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/7ac0e9aa9080dfa005069d57ddc421ef74c493aa/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmpy2h_xmuk.parquet    : 100%|##########| 3.56kB / 3.56kB

Validating                    :           |   0%

[task1] Cached evaluation for 'Qwen + LoRA (Learned Reordering)' -- pushed to 'bdatm-project/evaluation-results-task1'.

--- Comparative Summary Table (Including Learned Reordering) ---

,model_name,fen_exact_match,character_error_rate,square_by_square_accuracy,levenshtein_distance,adapter_sha
0,Vanilla Qwen2.5-VL (Zero-Shot),0.0000,3.259093,0.000000,169.2250,NaN
1,Qwen + LoRA Fine-Tuning (from HF),0.0075,0.043934,0.994844,2.2775,df1de1e657acce1785c7604a3206a4ec22b1a28f
2,Qwen + LoRA (Zigzag - TF),0.0000,0.314656,0.500781,16.4500,df1de1e657acce1785c7604a3206a4ec22b1a28f
3,Qwen + LoRA (Spiral - TF),0.0000,0.621696,0.379414,33.0075,df1de1e657acce1785c7604a3206a4ec22b1a28f
4,Qwen + LoRA (File_wise - TF),0.0000,0.653481,0.570391,34.9800,df1de1e657acce1785c7604a3206a4ec22b1a28f
5,Qwen + LoRA (Zigzag - SFT),0.0125,0.044541,0.974492,2.2975,2e7358f780fb18aca54b0b96e626811ef9b34335
6,Qwen + LoRA (Spiral - SFT),0.0125,0.046081,0.996680,2.3850,cb9ddf3ac519846bd91e962711ff4667bc7a1573
7,Qwen + LoRA (File_wise - SFT),0.0225,0.044630,0.999648,2.3050,27bf9ae48a8332ef6fe9d1ad70e6a5954fa38359
8,Qwen + LoRA (Learned Reordering),0.0200,0.055516,0.981055,2.9025,04e3799b675534ad419bb77505afeb670301fbe2

Pushing Task 1 evaluation results to Hugging Face, so they can be reloaded later without re-running any inference (same approach used in *main.ipynb*)

In [16]:
print("=== Pushing Task 1 Evaluation Results to Hugging Face ===")

repo_id_eval_task1 = f"{hf_org_prefix}/evaluation-results-task1"

# push_results_table (not Dataset.push_to_hub): writes the parquet plus a dataset
# card without a pinned schema, so adding a column (e.g. adapter_sha) can't make
# later reads fail with a CastError.
print(f"Pushing Task 1 evaluation results to Hugging Face Hub: {repo_id_eval_task1}...")
push_results_table(repo_id_eval_task1, all_models_results, commit_message="Task 1: full comparison table")
print("Task 1 evaluation results successfully pushed to Hugging Face Hub!")

Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

=== Pushing Task 1 Evaluation Results to Hugging Face ===
Pushing Task 1 evaluation results to Hugging Face Hub: bdatm-project/evaluation-results-task1...

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmpfjvn_fpv.parquet    : 100%|##########| 4.14kB / 4.14kB

Validating                    :           |   0%

Task 1 evaluation results successfully pushed to Hugging Face Hub!

Displaying oredered results

In [17]:
print("=== Downloading Task 1 Evaluation Results from Hugging Face ===")
repo_id_eval_task1 = f"{hf_org_prefix}/evaluation-results-task1"
downloaded_eval_results_task1 = load_results_table(repo_id_eval_task1)

print("\n--- TASK 1 Comparative Summary Table (Ordered from Best to Worst by CER, loaded from Hugging Face) ---")
sorted_results_task1_from_hub = downloaded_eval_results_task1.sort_values(
    by="character_error_rate", ascending=True
).reset_index(drop=True)
display(sorted_results_task1_from_hub)

=== Downloading Task 1 Evaluation Results from Hugging Face ===

README.md:   0%|          | 0.00/466 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 4.14kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/9 [00:00<?, ? examples/s]

Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/2067dddf9c183168ab814aacdac469e5d5af951e/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match
ERROR:datasets.packaged_modules.parquet.parquet:Failed to read file '/root/.cache/huggingface/hub/datasets--bdatm-project--evaluation-results-task1/snapshots/2067dddf9c183168ab814aacdac469e5d5af951e/data/train-00000-of-00001.parquet' with error CastError: Couldn't cast
model_name: string
fen_exact_match: double
character_error_rate: double
square_by_square_accuracy: double
levenshtein_distance: double
adapter_sha: string
-- schema metadata --
huggingface: '{"info": {"features": {"model_name": {"dtype": "string", "_' + 328
to
{'model_name': Value('string'), 'fen_exact_match': Value('float64'), 'character_error_rate': Value('float64'), 'square_by_square_accuracy': Value('float64'), 'levenshtein_distance': Value('float64')}
because column names don't match

DatasetGenerationError: An error occurred while generating the dataset

## Results and Final Considerations

Reloading the Task 1 evaluation results directly from Hugging Face (instead of from the in-memory `all_models_results`), to confirm they persist independently of this notebook session — same idea as the "Results and Final Considerations" section in *main.ipynb*.

In [ ]:
sorted_results_df = all_models_results.sort_values(by="character_error_rate", ascending=True).reset_index(drop=True)

print("\n--- Comparative Summary Table (Ordered from Best to Worst by CER) ---")
display(sorted_results_df)

## Diagnostics

Tools from `src/eval/diagnostics.py`. Background: Task 3 scored ~0% for every model because every Task 3 training run was **started before the prompt-masking fix** (commit `9df1c7d`, loss over the whole sequence) **and resumed after it** (loss over the answer only). `eval_loss` jumped from ~2.76 to ~0.75 at the resume point, and only the last few epochs trained on the actual objective. Task 1 was trained entirely before the fix.

`find_resumable_checkpoint` now refuses to resume a checkpoint whose `training_recipe.json` does not match `TRAINING_RECIPE` (all pre-existing repos have none), so re-running the training cells retrains from scratch; `evaluate_with_cache(..., adapter_repo_id=...)` then re-evaluates automatically because the adapter's Hub commit changed.

1. `training_health_report(repo)` -- eval-loss history per epoch, flags discontinuities and missing/mismatched recipe markers. Run it after every training run: a healthy run has no flagged problems.

In [ ]:
# Optional: mount Google Drive so save_diagnostics() writes there (survives a
# Colab runtime reset) instead of the ephemeral local ./diagnostics folder.
if CONFIG["colab"]:
    from google.colab import drive
    drive.mount("/content/drive")

health = {repo: training_health_report(repo) for repo in [f"{hf_org_prefix}/qwen-task1-{s}-lora" for s in ["standard", "zigzag", "spiral", "file_wise", "learned-reordering"]]}
health_df = pd.DataFrame([
    {"repo_id": r, "n_problems": len(h["problems"]), "problems": " | ".join(h["problems"]),
     "last_eval_loss": h["eval_loss"][-1][1] if h.get("eval_loss") else None}
    for r, h in health.items()
])
display(health_df)
save_diagnostics(health_df, "training_health", "task1")

Task 1 per-field FEN metrics (`rescore_cached_fen_results`, no GPU). Only the board (field 1) is visible in the image: side to move isn't drawn, and the halfmove/fullmove counters can't be seen at all, so full-FEN `fen_exact_match` (and CER/Levenshtein on the full string) mostly measure guessing. `board_exact_match` and `board_character_error_rate` are the perception metrics.

In [ ]:
fen_fields = rescore_cached_fen_results(hf_org_prefix)
display(fen_fields)
save_diagnostics(fen_fields, "fen_field_metrics", "task1")