Downloading Libraries and Imports

In [5]:
!pip install -q --upgrade "pillow<11.0.0" transformers>=4.45.0 accelerate torchao scikit-learn tqdm chess cairosvg python-Levenshtein datasets peft huggingface_hub python-dotenv
!pip install -q flash-linear-attention  # speeds up Qwen3.5 linear attention

# Standard library imports
import json
import os
import subprocess
import sys
from pathlib import Path

# Third-party library imports
import numpy as np
from functools import partial
import pandas as pd
import torch
from datasets import load_dataset, Dataset
from huggingface_hub import login
from peft import LoraConfig, PeftModel, TaskType, get_peft_model
from PIL import Image
from tqdm import tqdm
from transformers import (
    AutoModelForImageTextToText,
    AutoProcessor,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
)

WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so
WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so

Setting up environment

In [6]:
# Project configuration dictionary
CONFIG = {
    "colab": True,
    "branch": "Ivo",
    "repo_name": "BigDataAndTextMiningProject",
    "repo_owner": "Aivon99",
    "repo_dir": "/content/BigDataAndTextMiningProject",
}

# 1. Setup repository path and handle cloning safely
repo_root = Path(CONFIG["repo_dir"])

if CONFIG["colab"]:
    # If the repository folder already exists, reference it safely
    if repo_root.exists():
        # /content survives "Restart session", so an old clone can linger -- pull so
        # the notebook always runs the latest code (restart the session afterwards if
        # eval.utilities was already imported in this kernel).
        print(f"Repository directory already exists at: {repo_root}; pulling latest changes...")
        pull = subprocess.run(["git", "-C", str(repo_root), "pull", "--ff-only"], capture_output=True, text=True)
        print((pull.stdout or pull.stderr).strip())
    else:
        auth_url = "https://"
        repo_url = f"{auth_url}github.com/{CONFIG['repo_owner']}/{CONFIG['repo_name']}.git"

        print(f"Cloning repository from {repo_url}...")
        result = subprocess.run(
            ["git", "clone", "--single-branch", "--branch", CONFIG["branch"], repo_url, str(repo_root)],
            capture_output=True, text=True
        )
        assert result.returncode == 0, f"Git clone failed: {result.stderr}"
else:
    repo_root = Path(".").resolve().parent.parent


print(f"Setup Complete. REPO_ROOT: {repo_root}")

# Check GPU and device availability
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")
if device == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Configure system paths for absolute module imports
sys.path.insert(0, str(repo_root))
sys.path.insert(0, str(repo_root / "src"))
sys.path.insert(0, str(repo_root / "src" / "data"))
sys.path.insert(0, str(repo_root / "src" / "eval"))

# 4. Import custom project modules cleanly
from data.generation import (
    build_sample,
    generate_dataset,
)

from data.utilities import (
    load_lichess_csv,
    upload_dataset_to_hub,
    authenticate_hf,
)

from eval.utilities import (
   calculate_fen_exact_match,
   calculate_levenshtein_metrics,
   calculate_square_by_square_accuracy,
   evaluate_chessboard_model_task_3,
   preprocess_function,
   get_patch_reordering_indices,
   reorder_chessboard_image,
   apply_patch_permutation,
   finetune_and_push_chessboard_model,
   find_resumable_checkpoint,
   Qwen35OnTheFlyCollator,
)

from training.learned_reordering import train_with_learned_reordering

print("All custom modules and eval utilities imported successfully!")

Cloning repository from https://github.com/Aivon99/BigDataAndTextMiningProject.git...
Setup Complete. REPO_ROOT: /content/BigDataAndTextMiningProject
Using device: cuda
GPU: NVIDIA A100-SXM4-40GB
All custom modules and eval utilities imported successfully!

Dowloading dataset for task 1 from HuggingFace repo

In [7]:
# Authenticate with Hugging Face:
# - Colab: reads a token from a Colab secret named HF_TOKEN (key icon, left sidebar)
# - Local: reads HF_TOKEN from a repo-root .env file, or the environment
# - Falls back to an interactive login prompt if neither is found
hf_token = None
if CONFIG["colab"]:
    try:
        from google.colab import userdata
        hf_token = userdata.get("HF_TOKEN")
    except Exception:
        hf_token = None
else:
    from dotenv import load_dotenv
    load_dotenv(repo_root / ".env")
    hf_token = os.environ.get("HF_TOKEN")

if hf_token:
    login(token=hf_token, add_to_git_credential=False)
    print("Logged in to Hugging Face Hub using HF_TOKEN.")
else:
    print("No HF_TOKEN found in secrets/.env/environment — falling back to interactive login.")
    login()

from huggingface_hub import snapshot_download

dataset_name = "bdatm-project/dataset_task3"

# 1. Download the entire dataset repository locally into 'my_dataset_files'
print("Downloading dataset snapshot locally...")
local_data_dir = snapshot_download(
    repo_id=dataset_name,
    repo_type="dataset",
    local_dir="./my_dataset_files"
)

# 2. Build the dataset structure from the files already on disk. Using
# load_dataset(dataset_name) here would re-download every image a second
# time straight from the Hub (the exact same ~8000 files snapshot_download
# just fetched) -- redundant on its own, and enough individual HEAD/GET
# requests in a row to trip Hugging Face's rate limiting (HTTP 429),
# stalling the notebook for minutes per file. Pointing the "imagefolder"
# loader at the local snapshot directory instead builds the same DatasetDict
# (it uses the same metadata.jsonl-driven logic load_dataset(repo_id) would
# run internally after its own download step) purely from disk -- no
# network calls at all.
print(f"Loading dataset '{dataset_name}' from the local snapshot...")
dataset_task3 = load_dataset("imagefolder", data_dir=local_data_dir, num_proc=16)

# 3. Loop through each split (train, validation, test) and map the second frame correctly
print("Mapping the dataset across splits to include image_t1...")
for split_name in dataset_task3.keys():

    def add_second_frame(example):
        # Build the path incorporating the split folder (train/val/test)
        file_path = os.path.join(local_data_dir, split_name, example["file_name_t1"])
        example["image_t1"] = Image.open(file_path).convert("RGB")
        return example

    dataset_task3[split_name] = dataset_task3[split_name].map(add_second_frame, num_proc=4)

print("\nDone! Every split has been successfully mapped with image_t1.")
print(dataset_task3)

No HF_TOKEN found in secrets/.env/environment — falling back to interactive login.

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")

Downloading dataset snapshot locally...

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 8004 files:   0%|          | 0/8004 [00:00<?, ?it/s]

Loading dataset 'bdatm-project/dataset_task3' from the local snapshot...

Resolving data files:   0%|          | 0/6401 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/801 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/801 [00:00<?, ?it/s]

Setting num_proc from 16 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 16 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Generating train split: 0 examples [00:00, ? examples/s]

Setting num_proc from 16 back to 1 for the validation split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 16 back to 1 for the validation split to disable multiprocessing as it only contains one shard.

Generating validation split: 0 examples [00:00, ? examples/s]

Setting num_proc from 16 back to 1 for the test split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 16 back to 1 for the test split to disable multiprocessing as it only contains one shard.

Generating test split: 0 examples [00:00, ? examples/s]

Mapping the dataset across splits to include image_t1...

Map (num_proc=4):   0%|          | 0/3200 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/400 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/400 [00:00<?, ? examples/s]

Done! Every split has been successfully mapped with image_t1.
DatasetDict({
    train: Dataset({
        features: ['sample_id', 'puzzle_id', 'task', 'fen', 'prompt', 'target', 'image', 'file_name_t1', 'image_t1'],
        num_rows: 3200
    })
    validation: Dataset({
        features: ['sample_id', 'puzzle_id', 'task', 'fen', 'prompt', 'target', 'image', 'file_name_t1', 'image_t1'],
        num_rows: 400
    })
    test: Dataset({
        features: ['sample_id', 'puzzle_id', 'task', 'fen', 'prompt', 'target', 'image', 'file_name_t1', 'image_t1'],
        num_rows: 400
    })
})

In [8]:
# ==========================================
# Verification Script for Task 3 Dataset
# ==========================================

print("Verifying dataset_task3 structure...")

# 1. Check if it's a DatasetDict and list available splits
print(f"Dataset splits available: {list(dataset_task3.keys())}")

# 2. Pick the train split (or any other split) to inspect
sample_split = dataset_task3["train"]
print(f"Number of samples in train split: {len(sample_split)}")

# 3. Grab the first sample
sample = sample_split[0]

# 4. Print core metadata fields
print("\n--- Sample Metadata ---")
print(f"Sample ID: {sample.get('sample_id', 'N/A')}")
print(f"Task type: {sample.get('task', 'N/A')}")
print(f"Ground Truth Move (Target): {sample.get('target', 'N/A')}")
print(f"Prompt preview:\n{sample.get('prompt', 'N/A')[:150]}...")

# 5. Verify images (State t and State t+1)
print("\n--- Image Verification ---")
img_t = sample.get("image")
img_t1 = sample.get("image_t1")

print(f"Frame 1 ('image'): {type(img_t)}")
if img_t is not None:
    print(f"  -> Size: {img_t.size}, Mode: {img_t.mode}")

print(f"Frame 2 ('image_t1'): {type(img_t1)}")
if img_t1 is not None:
    print(f"  -> Size: {img_t1.size}, Mode: {img_t1.mode}")

# 6. Assertion check to ensure everything is ready for training
assert img_t is not None, "Error: Frame 1 ('image') is missing or None!"
assert img_t1 is not None, "Error: Frame 2 ('image_t1') is missing or None!"
assert "target" in sample, "Error: Target field is missing!"

print("\nVerification Successful! dataset_task3 is correctly formatted and ready for training/evaluation.")

Verifying dataset_task3 structure...
Dataset splits available: ['train', 'validation', 'test']
Number of samples in train split: 3200

--- Sample Metadata ---
Sample ID: sample_000000
Task type: task3
Ground Truth Move (Target): O-O
Prompt preview:
You are a specialized model for chessboard temporal reasoning.
Your goal is to identify the move that transitioned the chessboard from State t to Stat...

--- Image Verification ---
Frame 1 ('image'): <class 'PIL.PngImagePlugin.PngImageFile'>
  -> Size: (512, 512), Mode: RGB
Frame 2 ('image_t1'): <class 'PIL.PngImagePlugin.PngImageFile'>
  -> Size: (512, 512), Mode: RGB

Verification Successful! dataset_task3 is correctly formatted and ready for training/evaluation.

## Vanilla Model

Loading model

In [9]:
model_id = "Qwen/Qwen3.5-0.8B"
print(f"Loading model {model_id}...")

model_vanilla = AutoModelForImageTextToText.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

processor = AutoProcessor.from_pretrained(model_id)
print("model and Processor loaded correctly!")

Loading model Qwen/Qwen3.5-0.8B...

config.json:   0%|          | 0.00/2.91k [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/50.9k [00:00<?, ?B/s]

model.safetensors-00001-of-00001.safeten(…): reconstructing file:   0%|          |  0.00B / 1.75GB

model.safetensors-00001-of-00001.safeten(…): downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/7.75k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/16.7k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/6.72M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/3.35M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 12.8MB

tokenizer.json: downloading bytes:           |  0.00B

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

model and Processor loaded correctly!

Test with baseline on a single sample

In [10]:
from PIL import Image
from huggingface_hub import hf_hub_download

# Grab the first test sample from the Task 3 dataset
test_sample = dataset_task3["test"][0]

fen = test_sample["fen"]
task_prompt = test_sample["prompt"]
ground_truth_move = test_sample["target"]  # Task 3 target is the SAN move
sample_id = test_sample["sample_id"]

# Frame 1: State t
frame_t_image = test_sample["image"]

# Frame 2: State t+1

frame_t_plus_1_image = test_sample["image_t1"]

print(f"Sample ID: {sample_id}")
print(f"FEN State: {fen}")
print(f"\n Prompt provided to the model:\n{task_prompt}\n")
print(f"Real Move (Ground Truth): {ground_truth_move}\n")

# Prepare the multimodal input format for the model with two ordered images (State t and State t+1)
chat_messages = [
    {
        "role": "user",
        "content": [
            {"type": "image", "image": frame_t_image},
            {"type": "image", "image": frame_t_plus_1_image},
            {"type": "text", "text": task_prompt},
        ]
    }
]

# Apply the processor's chat template
formatted_text = processor.apply_chat_template(chat_messages, tokenize=False, add_generation_prompt=True)

# Tokenize inputs and pass both images as a list to the processor, then move to the GPU device
model_inputs = processor(
    text=[formatted_text],
    images=[frame_t_image, frame_t_plus_1_image],
    padding=True,
    return_tensors="pt"
).to(device)

# Generate the zero-shot prediction for the delta move
print("Waiting for the model to respond....")
with torch.no_grad():
    output_token_ids = model_vanilla.generate(**model_inputs, max_new_tokens=128)

# Trim prompt tokens from the generated output
trimmed_output_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, output_token_ids)
]
predicted_move_string = processor.batch_decode(
    trimmed_output_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False
)[0]

print(f"\n MODEL OUTPUT: \n{predicted_move_string.strip()}")

Sample ID: sample_000000
FEN State: 6R1/kbqn1p2/1p5p/1Pp5/4Pb2/7Q/1PPr3P/4K3 b - - 0 33

 Prompt provided to the model:
You are a specialized model for chessboard temporal reasoning.
Your goal is to identify the move that transitioned the chessboard from State t to State t+1.
Input:
- Frame 1: Chessboard state at time t.
- Frame 2: Chessboard state at time t+1.
Output Format:
Return only the move in Standard Algebraic Notation (SAN).

Real Move (Ground Truth): Bxe4

Waiting for the model to respond....

[transformers] `causal_conv1d_fn` is falling back to its reference PyTorch implementation because `causal_conv1d` is not installed. This is correct but much slower; install `causal_conv1d` for the optimized kernel.
[transformers] `causal_conv1d_update` is falling back to its reference PyTorch implementation because `causal_conv1d` is not installed. This is correct but much slower; install `causal_conv1d` for the optimized kernel.

 MODEL OUTPUT:
Let's analyze the board from Frame 1 to Frame 2 to identify the move.

In Frame 1:
- White pieces: King on e1, Queen on d1, Rook on c1, Bishop on f1, Pawn on e2, Pawn on f2, Pawn on g2, Pawn on h2, Pawn on h3, Pawn on h4, Pawn on h5, Pawn on h6, Pawn on h7, Pawn on h8, Pawn on h9, Pawn on h10, Pawn on h11, Pawn on h12, Pawn on h13

Testing vanilla model on the whole dataset using the function *evaluate_chessboard_model_task_1*

In [11]:
# Call the evaluation function for the vanilla model
vanilla_results_df, vanilla_summary_df = evaluate_chessboard_model_task_3(
    model=model_vanilla,
    processor=processor,
    dataset_split=dataset_task3["test"],
    model_name="Vanilla Qwen3.5-0.8B (Zero-Shot)"
)

# Initialize the global comparison DataFrame with the vanilla results
all_models_results = vanilla_summary_df

print("\nExample of results obtained form the evaluation:")
display(vanilla_results_df.head())

print("\nComparative Summary DataFrame (all_models_results):")
display(all_models_results)

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) on Task 3: 100%|██████████| 400/400 [32:54<00:00,  4.94s/it]

Evaluation completed for Vanilla Qwen3.5-0.8B (Zero-Shot) on Task 3! Results saved to task3_vanilla_qwen3.5-0.8b_(zero-shot)_results.csv.

Example of results obtained form the evaluation:

,sample_id,ground_truth,predicted,exact_match
0,sample_000000,Bxe4,Let's analyze the board from Frame 1 to Frame ...,0
1,sample_000001,Rxe6,Let's analyze the board from Frame 1 to Frame ...,0
2,sample_000002,Rd1,The move is: c4,0
3,sample_000003,h6,Let's analyze the board from Frame 1 to Frame ...,0
4,sample_000004,Re1,Let's carefully compare the two images to iden...,0

Comparative Summary DataFrame (all_models_results):

                         model_name  exact_match
0  Vanilla Qwen3.5-0.8B (Zero-Shot)          0.0

## Vanilla + LoRA

Preprocessing dataset and finetuning

In [12]:
# 1. No dataset.map preprocessing: the collator below tokenizes and runs the
# image processor per batch (in DataLoader workers), so nothing big is cached.

# 2. Configure PEFT and LoRA parameters
peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=16,
    lora_alpha=32,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    lora_dropout=0.05,
    bias="none",
)

# Apply LoRA to model vanilla and saving the new one into lora_model
lora_model = get_peft_model(model_vanilla, peft_config)
lora_model.print_trainable_parameters()

# data_collator preprocesses each batch on the fly (image processor + tokenizer)
# rather than precomputing pixel_values with dataset.map -- that cache would be
# ~20 GB of float tensors and slow to reload -- and it batches Qwen's per-sample
# image_grid_thw/pixel_values correctly (torch.cat along dim 0), which the
# default collator can't (it fails later inside the vision tower as IndexError).
data_collator = Qwen35OnTheFlyCollator(processor=processor)

# 3. Resolve the target Hub repo now (needed before training starts) and
# check whether an earlier, interrupted run already left a resumable
# checkpoint there (e.g. after a Colab disconnect wiped the local runtime).
hf_org_prefix = "bdatm-project"
repo_id_standard = f"{hf_org_prefix}/qwen-task3-standard-lora"
resume_checkpoint = find_resumable_checkpoint(repo_id_standard)

# 4. Define Training Arguments. Trains for up to 10 epochs, but relies on
# the validation set (via EarlyStoppingCallback below) to stop once
# eval_loss stops improving, and keeps the best-performing checkpoint
# (by validation loss) rather than just whichever epoch finishes last.
# push_to_hub + hub_strategy="checkpoint" uploads a fully resumable
# checkpoint (optimizer/scheduler/RNG state included) after every epoch,
# so a Colab disconnect at epoch i loses at most that epoch's progress.
training_args = TrainingArguments(
    output_dir="./qwen_task3_lora_output",
    per_device_train_batch_size=8,  # same effective batch (8) as before, but one GPU pass instead of 8
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    logging_steps=10,
    num_train_epochs=10,
    save_strategy="epoch",
    eval_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    save_total_limit=2,
    push_to_hub=True,
    hub_model_id=repo_id_standard,
    hub_strategy="checkpoint",
    bf16=True,  # model is loaded in bfloat16; fp16 autocast on top of it was mismatched
    dataloader_num_workers=4,
    remove_unused_columns=False, # Essenziale per i modelli multimodali
    report_to="none",
)

# 5. Initialize the Trainer using 'lora_model', with early stopping driven
# by the validation set (stops if eval_loss doesn't improve for 2 epochs)
trainer = Trainer(
    model=lora_model,
    args=training_args,
    train_dataset=dataset_task3["train"],
    eval_dataset=dataset_task3["validation"],
    data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

# 6. Start (or resume) Fine-Tuning
if resume_checkpoint:
    print(f"Resuming LoRA Supervised Fine-Tuning for Task 3 from {resume_checkpoint}...")
else:
    print("Starting LoRA Supervised Fine-Tuning for Task 3...")
trainer.train(resume_from_checkpoint=resume_checkpoint)

trainable params: 6,389,760 || all params: 859,375,680 || trainable%: 0.7435

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

Found a resumable checkpoint on the Hub for 'bdatm-project/qwen-task3-standard-lora': /root/.cache/huggingface/hub/models--bdatm-project--qwen-task3-standard-lora/snapshots/a7c3a2f5284243e5bdc4ee4bcd4ae7d185199ce2/last-checkpoint
Resuming LoRA Supervised Fine-Tuning for Task 3 from /root/.cache/huggingface/hub/models--bdatm-project--qwen-task3-standard-lora/snapshots/a7c3a2f5284243e5bdc4ee4bcd4ae7d185199ce2/last-checkpoint...

[transformers] The best checkpoint ./qwen_task3_lora_output/checkpoint-3600 recorded in the resumed state does not exist anymore. Ignoring it for this run.

TrainOutput(global_step=4000, training_loss=0.0, metrics={'train_runtime': 0.0035, 'train_samples_per_second': 9229026.198, 'train_steps_per_second': 1153628.275, 'total_flos': 7.14138304744704e+16, 'train_loss': 0.0, 'epoch': 10.0})

Saving model on hugging face

In [13]:
# 6. Save weights to Hugging Face folder for Task 3
hf_org_prefix = "bdatm-project"
repo_id_standard = f"{hf_org_prefix}/qwen-task3-standard-lora"

print(f"Pushing standard LoRA model and processor to Hugging Face Hub for Task 3: {repo_id_standard}...")

trainer.model.push_to_hub(
    repo_id_standard,
    commit_message="Training complete for standard LoRA baseline on Task 3 (Dual-Image Delta Move)"
)
processor.push_to_hub(
    repo_id_standard
)

print("Fine-tuning completed and weights successfully uploaded to Hugging Face Hub for Task 3!")

Pushing standard LoRA model and processor to Hugging Face Hub for Task 3: bdatm-project/qwen-task3-standard-lora...

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors: 100%|##########| 25.6MB / 25.6MB

Validating                    :           |   0%

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpvdyy_qa5/tokenizer.json: 100%|##########| 20.0MB / 20.0MB

Validating                    :           |   0%

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Fine-tuning completed and weights successfully uploaded to Hugging Face Hub for Task 3!

Loading model and evaluation

In [14]:
# 7. Loading Model from Hugging Face and evaluate model using predefined functions for Task 3
print("\nLoading standard LoRA model from Hugging Face for Task 3 evaluation...")

# Load fresh base model instance
base_eval_model = AutoModelForImageTextToText.from_pretrained(
    "Qwen/Qwen3.5-0.8B",
    torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

# Load the LoRA weights directly from the Hub repository
standard_lora_eval_model = PeftModel.from_pretrained(base_eval_model, repo_id_standard)

print("Evaluating the Hugging Face LoRA model on the Task 3 test set...")
lora_results_df, lora_summary_df = evaluate_chessboard_model_task_3(
    model=standard_lora_eval_model,
    processor=processor,
    dataset_split=dataset_task3["test"],
    model_name="Qwen + LoRA Fine-Tuning (from HF)"
)

# Append the new metrics to the global comparison DataFrame
all_models_results = pd.concat([all_models_results, lora_summary_df], ignore_index=True)

print("\nUpdated Comparative Summary Table (all_models_results):")
display(all_models_results)

Loading standard LoRA model from Hugging Face for Task 3 evaluation...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

Evaluating the Hugging Face LoRA model on the Task 3 test set...

Evaluating Qwen + LoRA Fine-Tuning (from HF) on Task 3: 100%|██████████| 400/400 [03:10<00:00,  2.10it/s]

Evaluation completed for Qwen + LoRA Fine-Tuning (from HF) on Task 3! Results saved to task3_qwen_+_lora_fine-tuning_(from_hf)_results.csv.

Updated Comparative Summary Table (all_models_results):

                          model_name  exact_match
0   Vanilla Qwen3.5-0.8B (Zero-Shot)       0.0000
1  Qwen + LoRA Fine-Tuning (from HF)       0.0075

## Reordering patches - Advanced models

Checking function *get_patch_reordering_indices()*

In [15]:
for strat in ["raster", "zigzag", "spiral", "file_wise"]:
    order_map = get_patch_reordering_indices(strategy=strat)
    print(f"Strategy '{strat}' first 10 patch indices: {order_map[:10]}")

Strategy 'raster' first 10 patch indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Strategy 'zigzag' first 10 patch indices: [0, 1, 2, 3, 4, 5, 6, 7, 15, 14]
Strategy 'spiral' first 10 patch indices: [0, 1, 2, 3, 4, 5, 6, 7, 15, 23]
Strategy 'file_wise' first 10 patch indices: [0, 8, 16, 24, 32, 40, 48, 56, 1, 9]

Let's evalaute the model we created before using three different patch ordering: zigzag, spiral and file-wise. We'll use the function ***reorder_chessboard_image*** defined in *src/eval/utilities.py*

In [16]:
# ==========================================
# Training-Free Benchmark Loop for REOrder (Task 3)
# ==========================================

# Define the strategies you want to benchmark (as outlined in the project specs)
strategies_to_test = ["zigzag", "spiral", "file_wise"]

# Choose the model to test (we use the fine-tuned LoRA model)
model_to_evaluate = lora_model  # You can switch to 'model_vanilla' if you want to test the vanilla version

for strat in strategies_to_test:
    print(f"\nEvaluating strategy (Training-Free) on Task 3: {strat.upper()}...")

    # 1. Apply the reordering function to BOTH images in the test set (State t and State t+1)
    reordered_test_split = dataset_task3["test"].map(
        lambda sample: {
            "image": reorder_chessboard_image(sample["image"], strategy=strat, grid_size=8),
            "image_t1": reorder_chessboard_image(sample["image_t1"], strategy=strat, grid_size=8)
        }
    )

    # 2. Run the Task 3 evaluation function on the reordered test split
    strat_results_df, strat_summary_df = evaluate_chessboard_model_task_3(
        model=model_to_evaluate,
        processor=processor,
        dataset_split=reordered_test_split,
        model_name=f"Qwen + LoRA ({strat.capitalize()} - TF)"
    )

    # 3. Append the results to your global comparison table
    all_models_results = pd.concat([all_models_results, strat_summary_df], ignore_index=True)

print("\n--- Final Comparative Summary Table for Task 3 (Including Training-Free Strategies) ---")
display(all_models_results)

Evaluating strategy (Training-Free) on Task 3: ZIGZAG...

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Evaluating Qwen + LoRA (Zigzag - TF) on Task 3: 100%|██████████| 400/400 [03:02<00:00,  2.20it/s]

Evaluation completed for Qwen + LoRA (Zigzag - TF) on Task 3! Results saved to task3_qwen_+_lora_(zigzag_-_tf)_results.csv.

Evaluating strategy (Training-Free) on Task 3: SPIRAL...

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Evaluating Qwen + LoRA (Spiral - TF) on Task 3: 100%|██████████| 400/400 [03:01<00:00,  2.21it/s]

Evaluation completed for Qwen + LoRA (Spiral - TF) on Task 3! Results saved to task3_qwen_+_lora_(spiral_-_tf)_results.csv.

Evaluating strategy (Training-Free) on Task 3: FILE_WISE...

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Evaluating Qwen + LoRA (File_wise - TF) on Task 3: 100%|██████████| 400/400 [03:24<00:00,  1.95it/s]

Evaluation completed for Qwen + LoRA (File_wise - TF) on Task 3! Results saved to task3_qwen_+_lora_(file_wise_-_tf)_results.csv.

--- Final Comparative Summary Table for Task 3 (Including Training-Free Strategies) ---

                          model_name  exact_match
0   Vanilla Qwen3.5-0.8B (Zero-Shot)       0.0000
1  Qwen + LoRA Fine-Tuning (from HF)       0.0075
2          Qwen + LoRA (Zigzag - TF)       0.0000
3          Qwen + LoRA (Spiral - TF)       0.0000
4       Qwen + LoRA (File_wise - TF)       0.0025

As highlighted in the summary table, applying unconventional patch reordering strategies (such as Zigzag, Spiral, or File-wise) in a "Training-Free" (TF) manner leads to a performance drop, resulting in an increased Character Error Rate (CER) and Levenshtein distance compared to the standard raster-scan baseline.

To truly reap the benefits of the REOrder methodology, we must proceed with Supervised Fine-Tuning (SFT) directly on the pre-reordered dataset. This will allow the model to adapt its weights and attention layers to the new spatial serialization strategy.

Finetuning the new models on the dataset using function **finetune_and_push_chessboard_model()** defined in *src/eval/utilities.py*. This function directly upload the models on hugging face

In [17]:
import gc

strategies_to_train = ["zigzag", "spiral", "file_wise"]

# Repo IDs, NOT the model objects: the eval cells below always reload each
# strategy's weights fresh from the Hub (PeftModel.from_pretrained), so
# nothing here needs the trained model kept in memory after it's pushed.
# Keeping it (dict of model objects, one per strategy) held every strategy's
# full base+LoRA model on the GPU at once -- memory grew with each strategy
# instead of staying flat, which is what caused an OutOfMemoryError on the
# 3rd strategy. Explicitly deleting the model and clearing the CUDA cache
# after each strategy keeps peak GPU memory to roughly one strategy's worth
# at a time, and lets this run on a smaller/cheaper GPU.
trained_reordered_repo_ids = {}

print("=== Starting Fine-Tuning Pipeline for Task 3 (Reordering Strategies) ===")

for strat in strategies_to_train:
    print(f"\nLoading fresh base model for Task 3 | Strategy: {strat}...")

    # Load a clean instance of the base model for each strategy
    base_model = AutoModelForImageTextToText.from_pretrained(
        model_id,
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
        device_map="auto"
    )

    trained_model = finetune_and_push_chessboard_model(
        strategy_name=strat,
        dataset=dataset_task3,
        processor=processor,
        model=base_model,
        peft_config=peft_config,
        task="task3",
        hf_org_prefix=hf_org_prefix,
    )
    trained_reordered_repo_ids[strat] = f"{hf_org_prefix}/qwen-task3-{strat}-lora"

    # Free this strategy's GPU memory before the next strategy loads its own
    # fresh base model -- see the note above.
    del trained_model, base_model
    gc.collect()
    torch.cuda.empty_cache()

print("\nAll reordered models have been successfully trained and pushed to Hugging Face!")

=== Starting Fine-Tuning Pipeline for Task 3 (Reordering Strategies) ===

Loading fresh base model for Task 3 | Strategy: zigzag...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

==============================================
Starting pipeline for TASK: TASK3 | STRATEGY: ZIGZAG
==============================================
Applying LoRA to the provided model...

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

Found a resumable checkpoint on the Hub for 'bdatm-project/qwen-task3-zigzag-lora': /root/.cache/huggingface/hub/models--bdatm-project--qwen-task3-zigzag-lora/snapshots/cb49623a22a59533671fc2690ad3cd0f0649d167/last-checkpoint
Resuming training for task3 (zigzag reordering) from /root/.cache/huggingface/hub/models--bdatm-project--qwen-task3-zigzag-lora/snapshots/cb49623a22a59533671fc2690ad3cd0f0649d167/last-checkpoint...

[transformers] The best checkpoint ./temp_task3_zigzag_output/checkpoint-3200 recorded in the resumed state does not exist anymore. Ignoring it for this run.

Pushing model and processor to Hugging Face Hub: bdatm-project/qwen-task3-zigzag-lora...

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors: 100%|##########| 25.6MB / 25.6MB

Validating                    :           |   0%

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpshc3sp99/tokenizer.json:  80%|#######9  | 16.0MB / 20.0MB

Validating                    :           |   0%

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Finished! Successfully uploaded to Hub: bdatm-project/qwen-task3-zigzag-lora

Loading fresh base model for Task 3 | Strategy: spiral...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

==============================================
Starting pipeline for TASK: TASK3 | STRATEGY: SPIRAL
==============================================
Applying LoRA to the provided model...

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

Found a resumable checkpoint on the Hub for 'bdatm-project/qwen-task3-spiral-lora': /root/.cache/huggingface/hub/models--bdatm-project--qwen-task3-spiral-lora/snapshots/47a1d10f5d610cc4c9ccbdfbf89ecac4de521e0b/last-checkpoint
Resuming training for task3 (spiral reordering) from /root/.cache/huggingface/hub/models--bdatm-project--qwen-task3-spiral-lora/snapshots/47a1d10f5d610cc4c9ccbdfbf89ecac4de521e0b/last-checkpoint...

[transformers] The best checkpoint ./temp_task3_spiral_output/checkpoint-4000 recorded in the resumed state does not exist anymore. Ignoring it for this run.

Pushing model and processor to Hugging Face Hub: bdatm-project/qwen-task3-spiral-lora...

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          | 18.0kB / 25.6MB

Validating                    :           |   0%

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpvvo9tosr/tokenizer.json:  80%|#######9  | 16.0MB / 20.0MB

Validating                    :           |   0%

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Finished! Successfully uploaded to Hub: bdatm-project/qwen-task3-spiral-lora

Loading fresh base model for Task 3 | Strategy: file_wise...

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

==============================================
Starting pipeline for TASK: TASK3 | STRATEGY: FILE_WISE
==============================================
Applying LoRA to the provided model...

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

Found a resumable checkpoint on the Hub for 'bdatm-project/qwen-task3-file_wise-lora': /root/.cache/huggingface/hub/models--bdatm-project--qwen-task3-file_wise-lora/snapshots/f7047462019ae1a0e13f1f0dae0717039db1ce42/last-checkpoint
Resuming training for task3 (file_wise reordering) from /root/.cache/huggingface/hub/models--bdatm-project--qwen-task3-file_wise-lora/snapshots/f7047462019ae1a0e13f1f0dae0717039db1ce42/last-checkpoint...

[transformers] The best checkpoint ./temp_task3_file_wise_output/checkpoint-400 recorded in the resumed state does not exist anymore. Ignoring it for this run.

OutOfMemoryError: CUDA out of memory. Tried to allocate 4.56 GiB. GPU 0 has a total capacity of 39.49 GiB of which 2.43 GiB is free. Including non-PyTorch memory, this process has 37.05 GiB memory in use. Of the allocated memory 29.27 GiB is allocated by PyTorch, and 5.20 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://docs.pytorch.org/docs/stable/notes/cuda.html#optimizing-memory-usage-with-pytorch-cuda-alloc-conf)

Evaluating models using function **evaluate_chessboard_model_task_1()** defined in *src/eval/utilities.py*.

Models are downloaded from the hugging face repo.

In [ ]:
# ==========================================
# Evaluator Loop for REOrder SFT Models (Task 3)
# ==========================================

strategies_to_evaluate = ["zigzag", "spiral", "file_wise"]
hf_org_prefix = "bdatm-project"  # Ensure this matches the prefix used for the push

for strat in strategies_to_evaluate:
    print(f"\nLoading and evaluating SFT model for strategy on Task 3: {strat.upper()} from Hugging Face...")

    # 1. Load fresh base model instance
    base_eval_model = AutoModelForImageTextToText.from_pretrained(
        "Qwen/Qwen3.5-0.8B",
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
        device_map="auto"
    )

    # 2. Load the specific LoRA weights from Hugging Face Hub for Task 3
    repo_id_source = f"{hf_org_prefix}/qwen-task3-{strat}-lora"
    model_to_eval = PeftModel.from_pretrained(base_eval_model, repo_id_source)

    # 3. Apply the specific patch reordering to BOTH images in the test split (State t and State t+1)
    reordered_test_split = dataset_task3["test"].map(
        lambda sample: {
            "image": reorder_chessboard_image(sample["image"], strategy=strat, grid_size=8),
            "image_t1": reorder_chessboard_image(sample["image_t1"], strategy=strat, grid_size=8)
        }
    )

    # 4. Run the Task 3 evaluation utility function
    strat_results_df, strat_summary_df = evaluate_chessboard_model_task_3(
        model=model_to_eval,
        processor=processor,
        dataset_split=reordered_test_split,
        model_name=f"Qwen + LoRA ({strat.capitalize()} - SFT)"
    )

    # 5. Append results to the global comparison DataFrame
    all_models_results = pd.concat([all_models_results, strat_summary_df], ignore_index=True)

print("\n--- Final Comparative Summary Table for Task 3 (Loaded from Hub & Evaluated) ---")
display(all_models_results)

## Learned Reordering (Project Work)

Instead of a fixed strategy, trains a lightweight `PlackettLucePatchPolicy` (`src/training/learned_reordering.py`) jointly with LoRA to learn which 8x8 patch order helps the model most, via REINFORCE using the per-sample LM loss as the reward — see the module's docstring for how this differs from REOrder's own from-scratch-model approach. For Task 3 (dual-image), the same sampled permutation is applied independently to both frames, mirroring how the training-free strategies above reorder both `image` and `image_t1`.

**Known limitations of this first version, worth knowing before running:** unlike the `Trainer`-based cells above, this custom training loop has **no checkpointing or resume support** — a Colab disconnect mid-run loses all progress, not just the current epoch. It's also unbatched (one sample at a time, no gradient accumulation) and does two backward passes per sample (model + policy), so it's slower per-epoch than the standard fine-tuning above. `num_train_epochs` is kept low below (3, not the default 10) to keep a first run's wall-clock time and disconnect risk bounded — raise it once you've confirmed this runs end-to-end.

In [ ]:
print("=== Starting Learned Reordering Training Pipeline for Task 3 ===")

# Fresh base model instance, same pattern as the training-free strategies above
base_model_learned = AutoModelForImageTextToText.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

learned_lora_model, learned_policy, repo_id_learned = train_with_learned_reordering(
    dataset=dataset_task3,
    processor=processor,
    model=base_model_learned,
    peft_config=peft_config,
    task="task3",
    hf_org_prefix=hf_org_prefix,
    num_train_epochs=3,  # kept low for a first run -- see the note above
)

print(f"\nLearned Reordering training complete. Model pushed to: {repo_id_learned}")

Evaluating the learned-reordering model: training samples permutations stochastically (that's how REINFORCE explores), but evaluation needs one fixed ordering — `policy.greedy_permutation()` gives the policy's single best guess (argsort of its learned logits, no sampling noise), which is what actually gets applied to both frames of the test set here.

In [ ]:
print("=== Evaluating the Learned Reordering model on Task 3 ===")

learned_permutation = learned_policy.greedy_permutation()
print(f"Learned (greedy) patch order: {learned_permutation}")

# Task 3 is dual-image: apply the same learned permutation to both frames
# (State t and State t+1), same idea as the training-free strategies above.
reordered_test_split = dataset_task3["test"].map(
    lambda sample: {
        "image": apply_patch_permutation(sample["image"], learned_permutation, grid_size=8),
        "image_t1": apply_patch_permutation(sample["image_t1"], learned_permutation, grid_size=8),
    }
)

learned_results_df, learned_summary_df = evaluate_chessboard_model_task_3(
    model=learned_lora_model,
    processor=processor,
    dataset_split=reordered_test_split,
    model_name="Qwen + LoRA (Learned Reordering)"
)

all_models_results = pd.concat([all_models_results, learned_summary_df], ignore_index=True)

print("\n--- Comparative Summary Table for Task 3 (Including Learned Reordering) ---")
display(all_models_results)

Pushing Task 3 evaluation results to Hugging Face, so they can be reloaded later without re-running any inference (same approach used in *main.ipynb*)

In [ ]:
print("=== Pushing Task 3 Evaluation Results to Hugging Face ===")

hf_dataset_results_task3 = Dataset.from_pandas(all_models_results)
repo_id_eval_task3 = f"{hf_org_prefix}/evaluation-results-task3"

print(f"Pushing Task 3 evaluation results to Hugging Face Hub: {repo_id_eval_task3}...")
hf_dataset_results_task3.push_to_hub(
    repo_id_eval_task3,
    private=False
)
print("Task 3 evaluation results successfully pushed to Hugging Face Hub!")

Displaying oredered results

In [ ]:
print("=== Downloading Task 3 Evaluation Results from Hugging Face ===")
downloaded_eval_results_task3 = load_dataset(repo_id_eval_task3, split="train").to_pandas()

print("\n--- TASK 3 Comparative Summary Table (Ordered from Best to Worst by Exact Match, loaded from Hugging Face) ---")
sorted_results_task3_from_hub = downloaded_eval_results_task3.sort_values(
    by="exact_match", ascending=False
).reset_index(drop=True)
display(sorted_results_task3_from_hub)

## Results and Final Considerations

Reloading the Task 3 evaluation results directly from Hugging Face (instead of from the in-memory `all_models_results`), to confirm they persist independently of this notebook session — same idea as the "Results and Final Considerations" section in *main.ipynb*.

In [ ]:
sorted_results_df = all_models_results.sort_values(by="exact_match", ascending=False).reset_index(drop=True)

print("\n--- Comparative Summary Table for Task 3 (Ordered from Best to Worst by Exact Match) ---")
display(sorted_results_df)