# Reproducing the main results

This notebook checks that the code of this repository produces the numbers in the README. It does
**not** retrain anything: it downloads the LoRA adapters we published on Hugging Face, evaluates
them again on the test set from scratch (no cached results are used), and compares the new
predictions with the ones we saved during our runs.

- **Hugging Face token: optional, but recommended.** All datasets, adapters and result tables of
  the [bdatm-project](https://huggingface.co/bdatm-project) organization are public, and this
  notebook never writes to the Hub, so no access to our repositories is needed. But each dataset is
  stored as thousands of image files, and Hugging Face allows far fewer downloads without a token:
  without one, the downloads can stop with a rate-limit error. Any read-only token of a free
  Hugging Face account works (create one at
  [huggingface.co/settings/tokens](https://huggingface.co/settings/tokens)). On Colab, add it as a
  secret called `HF_TOKEN` (key icon in the left sidebar) and allow this notebook to access it:
  `huggingface_hub` reads it by itself, and the token never appears in the notebook. Locally, set
  the `HF_TOKEN` environment variable or run `hf auth login`.
- **GPU:** an NVIDIA L4 or A100 (on Colab: *Runtime > Change runtime type*). The model runs in
  bfloat16, which the free T4 GPU does not support well.
- **The predictions are not exactly the same as ours.** Decoding is greedy (no sampling), but GPU
  computations in bfloat16 have some numerical noise, and when two tokens are almost equally likely
  it is enough to pick the other one. This happens where the model is unsure: in Task 1 mostly in
  the parts of the FEN that cannot be seen in the image (side to move, move counters), and in the
  vanilla models almost everywhere. The scores should match ours or differ by one or two samples.
  A different GPU type can change a few more predictions. The README explains this in more detail.
- **torch version.** The predictions also depend on the torch version. All our results were
  produced with torch 2.11.0 (the CUDA 13.0 build preinstalled on Colab), and this notebook installs
  that version if Colab has a different one.

The `LEVEL` setting in Section 2 chooses how much to run. The outputs saved in this notebook come
from `LEVEL = "tables"`; to check the code quickly, choose `"main"` before running:

| `LEVEL` | What runs | Time on an L4 |
|---|---|---|
| `"main"` (quick check) | The raster LoRA model of each task, on all 400 test samples | about 35 min |
| `"tables"` (the saved outputs) | Every row of the README tables, including the 512px resolution ablation. Task 2 and Task 3 on all 400 samples; Task 1 on all 400 samples for the raster LoRA model and on the first 100 for the other rows | about 2.5 h |
| `"full"` | Every row of the README tables, including the 512px resolution ablation, on all 400 test samples | about 6.5 h |

These times are for the evaluation. Downloading the three datasets without a token takes about
40 minutes more in total (about 10 minutes each for Task 1 and Task 2, 20 for Task 3, measured on
our connection).

Task 1 is the slow one: a FEN answer is about 40 tokens long and is generated one token at a time.
Using 100 samples is still a fair check, because the comparison is done sample by sample against
our saved predictions for those same samples.

## 1. Setup

On Colab this cell clones the repository and installs the pinned packages of `requirements.txt`
except `torch` and `torchvision`. It keeps Colab's preinstalled torch if it is 2.11.0, the version
of our runs, and installs 2.11.0 otherwise. It also removes Colab's `torchao`, which is too old for
`peft`, and `torchaudio`, which is not used and would not match torch 2.11.0 if it has to be
installed. To run locally, set `CONFIG["colab"] = False`, install the packages with
`pip install -r requirements.txt` (it pins torch 2.11.0) and start Jupyter from the `notebooks/`
folder.

The next cell imports the libraries, checks the GPU and says whether a Hugging Face token was found
(see the top of the notebook).

In [1]:
import importlib.metadata
import subprocess
import sys
from pathlib import Path

CONFIG = {
    "colab": True,
    "branch": "main",
    "repo_name": "BigDataAndTextMiningProject",
    "repo_owner": "Aivon99",
    "repo_dir": "/content/BigDataAndTextMiningProject",
}
# torch version of our runs (see TORCH_VERSIONS in src/eval/reproduce.py)
TORCH, TORCHVISION = "2.11.0", "0.26.0"

if CONFIG["colab"]:
    repo_root = Path(CONFIG["repo_dir"])
    if not repo_root.exists():
        repo_url = f"https://github.com/{CONFIG['repo_owner']}/{CONFIG['repo_name']}.git"
        print(f"Cloning {repo_url}...")
        result = subprocess.run(
            ["git", "clone", "--single-branch", "--branch", CONFIG["branch"], repo_url, str(repo_root)],
            capture_output=True, text=True,
        )
        assert result.returncode == 0, f"Git clone failed: {result.stderr}"
    # torch and torchvision are handled below: install everything else at the pinned versions
    requirements = [line for line in (repo_root / "requirements.txt").read_text().splitlines()
                    if line.strip() and not line.startswith(("#", "torch"))]
    Path("/tmp/requirements_colab.txt").write_text("\n".join(requirements))
    !pip install -q -r /tmp/requirements_colab.txt
    # Colab's preinstalled torchao is too old for peft, which then fails to load the adapters;
    # the task notebooks remove it too. torchaudio is not used and would not match torch 2.11.0.
    !pip uninstall -y -q torchao torchaudio
    # Our runs used Colab's torch 2.11.0 (CUDA 13.0 build)
    if importlib.metadata.version("torch").split("+")[0] != TORCH:
        !pip install -q torch=={TORCH} torchvision=={TORCHVISION} --index-url https://download.pytorch.org/whl/cu130
else:
    repo_root = Path(".").resolve().parent

print(f"Repository: {repo_root}")

Cloning https://github.com/Aivon99/BigDataAndTextMiningProject.git...
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 94.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 139.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 399.6/399.6 kB 39.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 604.4/604.4 kB 49.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 839.9/839.9 kB 59.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.2/819.2 kB 64.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 125.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.4/157.4 kB 14.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.9/53.9 MB 45.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 117.7 MB/s eta 0:00:00
  Building wheel for chess (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu13 26.6.0 requires pyarrow<24,>=19.0.0, but you have pyarrow 26.0.0 which is incompatible.
diffusers 0.41.0 requires huggingface-hub<2.0,>=1.32.0, but you have huggingface-hub 2.2.0 which is incompatible.
Repository: /content/BigDataAndTextMiningProject

In [2]:
import pandas as pd
import torch
import transformers
import peft

sys.path.insert(0, str(repo_root / "src"))

from eval.reproduce import IMAGE_SIZE, check_token_reordering, make_processors, reproduce_task

print(f"torch {torch.__version__}, transformers {transformers.__version__}, peft {peft.__version__}")
assert torch.cuda.is_available(), "This notebook needs a GPU (an L4 or A100)."
print(f"GPU: {torch.cuda.get_device_name(0)}")
if not torch.cuda.is_bf16_supported():
    print("WARNING: this GPU does not support bfloat16 well; results may differ from ours.")

# Optional token: huggingface_hub reads it from the Colab secret HF_TOKEN (or the HF_TOKEN
# environment variable) by itself; without it the Hub allows far fewer downloads
from huggingface_hub import get_token
if get_token():
    print("Hugging Face token found: downloads use the higher rate limit.")
else:
    print("No Hugging Face token: downloading without one (the Hub may rate-limit the downloads).")

torch 2.11.0+cu130, transformers 5.20.2, peft 0.21.2
GPU: NVIDIA L4

## 2. Settings

`LEVEL` chooses which rows to reproduce (see the table at the top). On Colab it is a drop-down menu
next to the code; elsewhere, edit the value. The outputs saved in this notebook come from
`LEVEL = "tables"`; for a quick check choose `"main"`.

`NUM_WORKERS` sets how many processes download and load the datasets in parallel. It only changes
the loading time, not the results; a split stored as a single file is loaded by one process
whatever its value. The other settings (model, image sizes, scan orders, number of shots) are the
ones used in the task notebooks and are defined in `src/eval/reproduce.py`.

In [3]:
LEVEL = "tables"  # @param ["main", "tables", "full"]
TASK1_SUBSET = 100      # with LEVEL = "tables": test samples for the Task 1 rows other than raster LoRA
NUM_WORKERS = 8  # @param {type:"integer"}

assert LEVEL in ("main", "tables", "full"), f"Unknown LEVEL: {LEVEL}"

## 3. The evaluation code

The code that evaluates the models is in `src/eval/reproduce.py`, and the cells below call it.
Importing it turns off the progress bars of the downloads, which would print one bar for each of
the thousands of image files of a dataset; the evaluation keeps its own progress bar.

- `load_task_dataset` loads a task's dataset from the Hub the same way the task notebooks do.
  Task 3 has two images per sample, so its files are downloaded first and the second frame
  (`image_t1`) is added to each row.
- `experiment_rows` lists the rows of the README tables for a task: the model name used in the
  results table, the adapter on the Hub (`None` for the vanilla model), the scan order used at
  test time and the image size. For the learned orders, the order is read from
  `learned_order.json` in the adapter's repository. The last row is the 512px raster LoRA model of
  the resolution ablation (repository `qwen-taskN-standard-lora`, named
  `Qwen + LoRA Fine-Tuning (from HF)` in the results table).
- `evaluate_row` loads the base model and the adapter, sets the scan order and runs the task's
  evaluation function of `src/eval/evaluation.py`, with the processor of the row's image size.
- `compare_with_published` downloads our saved per-sample predictions for the same model and
  compares them with the new ones, sample by sample.
- `reproduce_task` runs the rows selected by `LEVEL` for one task and returns the comparison. It
  first prints a warning if the installed torch is not the one of our runs of that task.

## 4. Processors and token reordering check

Two processors are prepared: one resizes the boards to 256px (all the main experiments) and one to
512px (the resolution ablation). Each prints the token grid it gives: 8x8 tokens at 256px (one per
square) and 16x16 at 512px (2x2 per square).

The scan orders are applied by patching the model's code at run time
(`src/training/token_reordering.py`). `verify_token_reordering` checks that the patch works with
the installed `transformers` version: with no order set the output equals the unpatched model,
the token embeddings and their positions move together, and setting an order changes the output.

In [4]:
processors = make_processors()
check_token_reordering(processors[IMAGE_SIZE])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/7.75k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/2.91k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/16.7k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 12.8MB

tokenizer.json: downloading bytes:           |  0.00B

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

[resolution] processor set to 256px: {'image_size': 256, 'patch_grid': (16, 16), 'llm_token_grid': (8, 8), 'tokens_per_square': 1}
[resolution] processor set to 512px: {'image_size': 512, 'patch_grid': (32, 32), 'llm_token_grid': (16, 16), 'tokens_per_square': 4}

Resolving data files:   0%|          | 0/3201 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/401 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/401 [00:00<?, ?it/s]

train/sample_000003/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

Downloading data:   0%|          | 0/3200 [00:00<?, ?files/s]

train/sample_000000/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_000013/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_000002/board.png: reconstructing file:   0%|          |  0.00B / 13.8kB

train/sample_000001/board.png: reconstructing file:   0%|          |  0.00B / 10.4kB

train/sample_000011/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_000009/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_000005/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_000004/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_000007/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_000010/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_000006/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_000014/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_000003/board.png: downloading bytes:           |  0.00B

train/sample_000000/board.png: downloading bytes:           |  0.00B

train/sample_000013/board.png: downloading bytes:           |  0.00B

train/sample_000009/board.png: downloading bytes:           |  0.00B

train/sample_000011/board.png: downloading bytes:           |  0.00B

train/sample_000002/board.png: downloading bytes:           |  0.00B

train/sample_000004/board.png: downloading bytes:           |  0.00B

train/sample_000001/board.png: downloading bytes:           |  0.00B

train/sample_000005/board.png: downloading bytes:           |  0.00B

train/sample_000008/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_000007/board.png: downloading bytes:           |  0.00B

train/sample_000015/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_000006/board.png: downloading bytes:           |  0.00B

train/sample_000014/board.png: downloading bytes:           |  0.00B

train/sample_000010/board.png: downloading bytes:           |  0.00B

train/sample_000012/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_000015/board.png: downloading bytes:           |  0.00B

train/sample_000012/board.png: downloading bytes:           |  0.00B

train/sample_000008/board.png: downloading bytes:           |  0.00B

train/sample_000016/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_000016/board.png: downloading bytes:           |  0.00B

train/sample_000017/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_000017/board.png: downloading bytes:           |  0.00B

train/sample_000018/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

train/sample_000019/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_000018/board.png: downloading bytes:           |  0.00B

train/sample_000019/board.png: downloading bytes:           |  0.00B

train/sample_000020/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_000021/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_000020/board.png: downloading bytes:           |  0.00B

train/sample_000023/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_000022/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_000021/board.png: downloading bytes:           |  0.00B

train/sample_000023/board.png: downloading bytes:           |  0.00B

train/sample_000024/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_000022/board.png: downloading bytes:           |  0.00B

train/sample_000025/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_000026/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_000024/board.png: downloading bytes:           |  0.00B

train/sample_000026/board.png: downloading bytes:           |  0.00B

train/sample_000025/board.png: downloading bytes:           |  0.00B

train/sample_000027/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

train/sample_000027/board.png: downloading bytes:           |  0.00B

train/sample_000028/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

train/sample_000028/board.png: downloading bytes:           |  0.00B

train/sample_000029/board.png: reconstructing file:   0%|          |  0.00B / 19.3kB

train/sample_000029/board.png: downloading bytes:           |  0.00B

train/sample_000030/board.png: reconstructing file:   0%|          |  0.00B / 19.5kB

train/sample_000030/board.png: downloading bytes:           |  0.00B

train/sample_000031/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_000032/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_000031/board.png: downloading bytes:           |  0.00B

train/sample_000032/board.png: downloading bytes:           |  0.00B

train/sample_000033/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_000033/board.png: downloading bytes:           |  0.00B

train/sample_000034/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_000034/board.png: downloading bytes:           |  0.00B

train/sample_000035/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_000036/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_000035/board.png: downloading bytes:           |  0.00B

train/sample_000036/board.png: downloading bytes:           |  0.00B

train/sample_000037/board.png: reconstructing file:   0%|          |  0.00B / 42.6kB

train/sample_000037/board.png: downloading bytes:           |  0.00B

train/sample_000038/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_000038/board.png: downloading bytes:           |  0.00B

train/sample_000039/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_000039/board.png: downloading bytes:           |  0.00B

train/sample_000040/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_000040/board.png: downloading bytes:           |  0.00B

train/sample_000042/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_000041/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_000042/board.png: downloading bytes:           |  0.00B

train/sample_000041/board.png: downloading bytes:           |  0.00B

train/sample_000043/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_000043/board.png: downloading bytes:           |  0.00B

train/sample_000044/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_000044/board.png: downloading bytes:           |  0.00B

train/sample_000045/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_000045/board.png: downloading bytes:           |  0.00B

train/sample_000046/board.png: reconstructing file:   0%|          |  0.00B / 22.8kB

train/sample_000046/board.png: downloading bytes:           |  0.00B

train/sample_000047/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_000047/board.png: downloading bytes:           |  0.00B

train/sample_000048/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

train/sample_000049/board.png: reconstructing file:   0%|          |  0.00B / 12.6kB

train/sample_000048/board.png: downloading bytes:           |  0.00B

train/sample_000050/board.png: reconstructing file:   0%|          |  0.00B / 16.8kB

train/sample_000049/board.png: downloading bytes:           |  0.00B

train/sample_000050/board.png: downloading bytes:           |  0.00B

train/sample_000051/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_000051/board.png: downloading bytes:           |  0.00B

train/sample_000052/board.png: reconstructing file:   0%|          |  0.00B / 20.8kB

train/sample_000053/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_000052/board.png: downloading bytes:           |  0.00B

train/sample_000053/board.png: downloading bytes:           |  0.00B

train/sample_000054/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_000055/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_000054/board.png: downloading bytes:           |  0.00B

train/sample_000055/board.png: downloading bytes:           |  0.00B

train/sample_000056/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_000056/board.png: downloading bytes:           |  0.00B

train/sample_000057/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_000058/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_000057/board.png: downloading bytes:           |  0.00B

train/sample_000058/board.png: downloading bytes:           |  0.00B

train/sample_000059/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_000059/board.png: downloading bytes:           |  0.00B

train/sample_000060/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_000061/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_000060/board.png: downloading bytes:           |  0.00B

train/sample_000061/board.png: downloading bytes:           |  0.00B

train/sample_000062/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_000062/board.png: downloading bytes:           |  0.00B

train/sample_000063/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_000064/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_000063/board.png: downloading bytes:           |  0.00B

train/sample_000064/board.png: downloading bytes:           |  0.00B

train/sample_000065/board.png: reconstructing file:   0%|          |  0.00B / 16.5kB

train/sample_000065/board.png: downloading bytes:           |  0.00B

train/sample_000066/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_000066/board.png: downloading bytes:           |  0.00B

train/sample_000067/board.png: reconstructing file:   0%|          |  0.00B / 37.0kB

train/sample_000067/board.png: downloading bytes:           |  0.00B

train/sample_000069/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

train/sample_000068/board.png: reconstructing file:   0%|          |  0.00B / 39.4kB

train/sample_000068/board.png: downloading bytes:           |  0.00B

train/sample_000069/board.png: downloading bytes:           |  0.00B

train/sample_000071/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_000071/board.png: downloading bytes:           |  0.00B

train/sample_000070/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_000070/board.png: downloading bytes:           |  0.00B

train/sample_000073/board.png: reconstructing file:   0%|          |  0.00B / 12.4kB

train/sample_000072/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_000074/board.png: reconstructing file:   0%|          |  0.00B / 13.4kB

train/sample_000073/board.png: downloading bytes:           |  0.00B

train/sample_000072/board.png: downloading bytes:           |  0.00B

train/sample_000074/board.png: downloading bytes:           |  0.00B

train/sample_000075/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_000077/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_000076/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_000075/board.png: downloading bytes:           |  0.00B

train/sample_000077/board.png: downloading bytes:           |  0.00B

train/sample_000076/board.png: downloading bytes:           |  0.00B

train/sample_000078/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

train/sample_000079/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_000078/board.png: downloading bytes:           |  0.00B

train/sample_000080/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_000081/board.png: reconstructing file:   0%|          |  0.00B / 20.8kB

train/sample_000080/board.png: downloading bytes:           |  0.00B

train/sample_000079/board.png: downloading bytes:           |  0.00B

train/sample_000082/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_000081/board.png: downloading bytes:           |  0.00B

train/sample_000082/board.png: downloading bytes:           |  0.00B

train/sample_000083/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_000083/board.png: downloading bytes:           |  0.00B

train/sample_000084/board.png: reconstructing file:   0%|          |  0.00B / 16.8kB

train/sample_000084/board.png: downloading bytes:           |  0.00B

train/sample_000085/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_000085/board.png: downloading bytes:           |  0.00B

train/sample_000086/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_000086/board.png: downloading bytes:           |  0.00B

train/sample_000087/board.png: reconstructing file:   0%|          |  0.00B / 42.3kB

train/sample_000089/board.png: reconstructing file:   0%|          |  0.00B / 17.3kB

train/sample_000087/board.png: downloading bytes:           |  0.00B

train/sample_000088/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_000089/board.png: downloading bytes:           |  0.00B

train/sample_000088/board.png: downloading bytes:           |  0.00B

train/sample_000090/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_000090/board.png: downloading bytes:           |  0.00B

train/sample_000091/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_000091/board.png: downloading bytes:           |  0.00B

train/sample_000092/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_000093/board.png: reconstructing file:   0%|          |  0.00B / 18.6kB

train/sample_000093/board.png: downloading bytes:           |  0.00B

train/sample_000092/board.png: downloading bytes:           |  0.00B

train/sample_000094/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_000095/board.png: reconstructing file:   0%|          |  0.00B / 22.8kB

train/sample_000094/board.png: downloading bytes:           |  0.00B

train/sample_000095/board.png: downloading bytes:           |  0.00B

train/sample_000096/board.png: reconstructing file:   0%|          |  0.00B / 43.8kB

train/sample_000096/board.png: downloading bytes:           |  0.00B

train/sample_000097/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_000097/board.png: downloading bytes:           |  0.00B

train/sample_000098/board.png: reconstructing file:   0%|          |  0.00B / 44.4kB

train/sample_000098/board.png: downloading bytes:           |  0.00B

train/sample_000099/board.png: reconstructing file:   0%|          |  0.00B / 14.6kB

train/sample_000100/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_000099/board.png: downloading bytes:           |  0.00B

train/sample_000100/board.png: downloading bytes:           |  0.00B

train/sample_000101/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_000101/board.png: downloading bytes:           |  0.00B

train/sample_000102/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_000102/board.png: downloading bytes:           |  0.00B

train/sample_000103/board.png: reconstructing file:   0%|          |  0.00B / 41.0kB

train/sample_000103/board.png: downloading bytes:           |  0.00B

train/sample_000104/board.png: reconstructing file:   0%|          |  0.00B / 13.6kB

train/sample_000105/board.png: reconstructing file:   0%|          |  0.00B / 45.2kB

train/sample_000104/board.png: downloading bytes:           |  0.00B

train/sample_000105/board.png: downloading bytes:           |  0.00B

train/sample_000106/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_000106/board.png: downloading bytes:           |  0.00B

train/sample_000107/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_000107/board.png: downloading bytes:           |  0.00B

train/sample_000108/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

train/sample_000108/board.png: downloading bytes:           |  0.00B

train/sample_000109/board.png: reconstructing file:   0%|          |  0.00B / 44.3kB

train/sample_000109/board.png: downloading bytes:           |  0.00B

train/sample_000110/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

train/sample_000110/board.png: downloading bytes:           |  0.00B

train/sample_000111/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_000111/board.png: downloading bytes:           |  0.00B

train/sample_000112/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_000112/board.png: downloading bytes:           |  0.00B

train/sample_000113/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_000113/board.png: downloading bytes:           |  0.00B

train/sample_000114/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

train/sample_000114/board.png: downloading bytes:           |  0.00B

train/sample_000115/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

train/sample_000115/board.png: downloading bytes:           |  0.00B

train/sample_000116/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_000117/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_000116/board.png: downloading bytes:           |  0.00B

train/sample_000118/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_000119/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_000117/board.png: downloading bytes:           |  0.00B

train/sample_000118/board.png: downloading bytes:           |  0.00B

train/sample_000119/board.png: downloading bytes:           |  0.00B

train/sample_000120/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_000120/board.png: downloading bytes:           |  0.00B

train/sample_000121/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_000121/board.png: downloading bytes:           |  0.00B

train/sample_000122/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_000122/board.png: downloading bytes:           |  0.00B

train/sample_000123/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_000123/board.png: downloading bytes:           |  0.00B

train/sample_000124/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_000126/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_000127/board.png: reconstructing file:   0%|          |  0.00B / 12.8kB

train/sample_000125/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_000128/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

train/sample_000124/board.png: downloading bytes:           |  0.00B

train/sample_000126/board.png: downloading bytes:           |  0.00B

train/sample_000127/board.png: downloading bytes:           |  0.00B

train/sample_000125/board.png: downloading bytes:           |  0.00B

train/sample_000128/board.png: downloading bytes:           |  0.00B

train/sample_000129/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_000129/board.png: downloading bytes:           |  0.00B

train/sample_000130/board.png: reconstructing file:   0%|          |  0.00B / 20.7kB

train/sample_000130/board.png: downloading bytes:           |  0.00B

train/sample_000131/board.png: reconstructing file:   0%|          |  0.00B / 41.8kB

train/sample_000131/board.png: downloading bytes:           |  0.00B

train/sample_000132/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_000133/board.png: reconstructing file:   0%|          |  0.00B / 18.1kB

train/sample_000135/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_000132/board.png: downloading bytes:           |  0.00B

train/sample_000134/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_000133/board.png: downloading bytes:           |  0.00B

train/sample_000136/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_000135/board.png: downloading bytes:           |  0.00B

train/sample_000134/board.png: downloading bytes:           |  0.00B

train/sample_000136/board.png: downloading bytes:           |  0.00B

train/sample_000137/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_000137/board.png: downloading bytes:           |  0.00B

train/sample_000138/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_000138/board.png: downloading bytes:           |  0.00B

train/sample_000139/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_000139/board.png: downloading bytes:           |  0.00B

train/sample_000141/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_000142/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_000141/board.png: downloading bytes:           |  0.00B

train/sample_000142/board.png: downloading bytes:           |  0.00B

train/sample_000140/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_000140/board.png: downloading bytes:           |  0.00B

train/sample_000143/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

train/sample_000143/board.png: downloading bytes:           |  0.00B

train/sample_000144/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_000144/board.png: downloading bytes:           |  0.00B

train/sample_000145/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_000145/board.png: downloading bytes:           |  0.00B

train/sample_000146/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_000146/board.png: downloading bytes:           |  0.00B

train/sample_000147/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_000147/board.png: downloading bytes:           |  0.00B

train/sample_000148/board.png: reconstructing file:   0%|          |  0.00B / 43.6kB

train/sample_000148/board.png: downloading bytes:           |  0.00B

train/sample_000149/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_000149/board.png: downloading bytes:           |  0.00B

train/sample_000150/board.png: reconstructing file:   0%|          |  0.00B / 43.1kB

train/sample_000150/board.png: downloading bytes:           |  0.00B

train/sample_000151/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_000151/board.png: downloading bytes:           |  0.00B

train/sample_000152/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

train/sample_000152/board.png: downloading bytes:           |  0.00B

train/sample_000153/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_000153/board.png: downloading bytes:           |  0.00B

train/sample_000154/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_000154/board.png: downloading bytes:           |  0.00B

train/sample_000155/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

train/sample_000155/board.png: downloading bytes:           |  0.00B

train/sample_000156/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_000156/board.png: downloading bytes:           |  0.00B

train/sample_000157/board.png: reconstructing file:   0%|          |  0.00B / 18.1kB

train/sample_000157/board.png: downloading bytes:           |  0.00B

train/sample_000158/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_000158/board.png: downloading bytes:           |  0.00B

train/sample_000159/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_000159/board.png: downloading bytes:           |  0.00B

train/sample_000160/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000160/board.png: downloading bytes:           |  0.00B

train/sample_000161/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_000161/board.png: downloading bytes:           |  0.00B

train/sample_000162/board.png: reconstructing file:   0%|          |  0.00B / 38.2kB

train/sample_000162/board.png: downloading bytes:           |  0.00B

train/sample_000164/board.png: reconstructing file:   0%|          |  0.00B / 42.2kB

train/sample_000163/board.png: reconstructing file:   0%|          |  0.00B / 16.4kB

train/sample_000164/board.png: downloading bytes:           |  0.00B

train/sample_000163/board.png: downloading bytes:           |  0.00B

train/sample_000165/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_000165/board.png: downloading bytes:           |  0.00B

train/sample_000166/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_000166/board.png: downloading bytes:           |  0.00B

train/sample_000167/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_000167/board.png: downloading bytes:           |  0.00B

train/sample_000168/board.png: reconstructing file:   0%|          |  0.00B / 22.8kB

train/sample_000168/board.png: downloading bytes:           |  0.00B

train/sample_000169/board.png: reconstructing file:   0%|          |  0.00B / 39.4kB

train/sample_000169/board.png: downloading bytes:           |  0.00B

train/sample_000171/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_000170/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_000171/board.png: downloading bytes:           |  0.00B

train/sample_000170/board.png: downloading bytes:           |  0.00B

train/sample_000172/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

train/sample_000172/board.png: downloading bytes:           |  0.00B

train/sample_000173/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

train/sample_000173/board.png: downloading bytes:           |  0.00B

train/sample_000174/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_000174/board.png: downloading bytes:           |  0.00B

train/sample_000176/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_000175/board.png: reconstructing file:   0%|          |  0.00B / 40.4kB

train/sample_000176/board.png: downloading bytes:           |  0.00B

train/sample_000175/board.png: downloading bytes:           |  0.00B

train/sample_000177/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_000177/board.png: downloading bytes:           |  0.00B

train/sample_000178/board.png: reconstructing file:   0%|          |  0.00B / 12.9kB

train/sample_000178/board.png: downloading bytes:           |  0.00B

train/sample_000179/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_000179/board.png: downloading bytes:           |  0.00B

train/sample_000180/board.png: reconstructing file:   0%|          |  0.00B / 25.6kB

train/sample_000180/board.png: downloading bytes:           |  0.00B

train/sample_000181/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_000181/board.png: downloading bytes:           |  0.00B

train/sample_000182/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_000184/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_000183/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_000183/board.png: downloading bytes:           |  0.00B

train/sample_000182/board.png: downloading bytes:           |  0.00B

train/sample_000184/board.png: downloading bytes:           |  0.00B

train/sample_000185/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_000185/board.png: downloading bytes:           |  0.00B

train/sample_000186/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

train/sample_000186/board.png: downloading bytes:           |  0.00B

train/sample_000187/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

train/sample_000187/board.png: downloading bytes:           |  0.00B

train/sample_000188/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_000189/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_000188/board.png: downloading bytes:           |  0.00B

train/sample_000189/board.png: downloading bytes:           |  0.00B

train/sample_000190/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_000191/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_000192/board.png: reconstructing file:   0%|          |  0.00B / 22.3kB

train/sample_000190/board.png: downloading bytes:           |  0.00B

train/sample_000191/board.png: downloading bytes:           |  0.00B

train/sample_000192/board.png: downloading bytes:           |  0.00B

train/sample_000193/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_000193/board.png: downloading bytes:           |  0.00B

train/sample_000194/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_000194/board.png: downloading bytes:           |  0.00B

train/sample_000195/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_000195/board.png: downloading bytes:           |  0.00B

train/sample_000196/board.png: reconstructing file:   0%|          |  0.00B / 40.5kB

train/sample_000196/board.png: downloading bytes:           |  0.00B

train/sample_000197/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_000197/board.png: downloading bytes:           |  0.00B

train/sample_000199/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_000198/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_000199/board.png: downloading bytes:           |  0.00B

train/sample_000198/board.png: downloading bytes:           |  0.00B

train/sample_000200/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_000200/board.png: downloading bytes:           |  0.00B

train/sample_000201/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_000201/board.png: downloading bytes:           |  0.00B

train/sample_000202/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_000202/board.png: downloading bytes:           |  0.00B

train/sample_000203/board.png: reconstructing file:   0%|          |  0.00B / 41.1kB

train/sample_000203/board.png: downloading bytes:           |  0.00B

train/sample_000204/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

train/sample_000204/board.png: downloading bytes:           |  0.00B

train/sample_000205/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_000206/board.png: reconstructing file:   0%|          |  0.00B / 38.7kB

train/sample_000207/board.png: reconstructing file:   0%|          |  0.00B / 35.9kB

train/sample_000208/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_000205/board.png: downloading bytes:           |  0.00B

train/sample_000206/board.png: downloading bytes:           |  0.00B

train/sample_000207/board.png: downloading bytes:           |  0.00B

train/sample_000208/board.png: downloading bytes:           |  0.00B

train/sample_000209/board.png: reconstructing file:   0%|          |  0.00B / 39.2kB

train/sample_000209/board.png: downloading bytes:           |  0.00B

train/sample_000210/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_000210/board.png: downloading bytes:           |  0.00B

train/sample_000211/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_000211/board.png: downloading bytes:           |  0.00B

train/sample_000212/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_000212/board.png: downloading bytes:           |  0.00B

train/sample_000213/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_000213/board.png: downloading bytes:           |  0.00B

train/sample_000214/board.png: reconstructing file:   0%|          |  0.00B / 22.9kB

train/sample_000214/board.png: downloading bytes:           |  0.00B

train/sample_000215/board.png: reconstructing file:   0%|          |  0.00B / 18.1kB

train/sample_000215/board.png: downloading bytes:           |  0.00B

train/sample_000216/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_000216/board.png: downloading bytes:           |  0.00B

train/sample_000217/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

train/sample_000218/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_000219/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

train/sample_000217/board.png: downloading bytes:           |  0.00B

train/sample_000220/board.png: reconstructing file:   0%|          |  0.00B / 40.9kB

train/sample_000219/board.png: downloading bytes:           |  0.00B

train/sample_000218/board.png: downloading bytes:           |  0.00B

train/sample_000220/board.png: downloading bytes:           |  0.00B

train/sample_000221/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_000221/board.png: downloading bytes:           |  0.00B

train/sample_000222/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_000222/board.png: downloading bytes:           |  0.00B

train/sample_000223/board.png: reconstructing file:   0%|          |  0.00B / 35.9kB

train/sample_000223/board.png: downloading bytes:           |  0.00B

train/sample_000224/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_000224/board.png: downloading bytes:           |  0.00B

train/sample_000226/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_000225/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_000227/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_000228/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_000226/board.png: downloading bytes:           |  0.00B

train/sample_000225/board.png: downloading bytes:           |  0.00B

train/sample_000229/board.png: reconstructing file:   0%|          |  0.00B / 16.5kB

train/sample_000228/board.png: downloading bytes:           |  0.00B

train/sample_000230/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_000227/board.png: downloading bytes:           |  0.00B

train/sample_000229/board.png: downloading bytes:           |  0.00B

train/sample_000230/board.png: downloading bytes:           |  0.00B

train/sample_000231/board.png: reconstructing file:   0%|          |  0.00B / 14.8kB

train/sample_000231/board.png: downloading bytes:           |  0.00B

train/sample_000232/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

train/sample_000232/board.png: downloading bytes:           |  0.00B

train/sample_000235/board.png: reconstructing file:   0%|          |  0.00B / 38.9kB

train/sample_000233/board.png: reconstructing file:   0%|          |  0.00B / 15.3kB

train/sample_000234/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_000236/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_000237/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_000235/board.png: downloading bytes:           |  0.00B

train/sample_000233/board.png: downloading bytes:           |  0.00B

train/sample_000234/board.png: downloading bytes:           |  0.00B

train/sample_000238/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_000236/board.png: downloading bytes:           |  0.00B

train/sample_000237/board.png: downloading bytes:           |  0.00B

train/sample_000238/board.png: downloading bytes:           |  0.00B

train/sample_000239/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_000239/board.png: downloading bytes:           |  0.00B

train/sample_000240/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_000240/board.png: downloading bytes:           |  0.00B

train/sample_000241/board.png: reconstructing file:   0%|          |  0.00B / 18.1kB

train/sample_000241/board.png: downloading bytes:           |  0.00B

train/sample_000242/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_000243/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

train/sample_000242/board.png: downloading bytes:           |  0.00B

train/sample_000244/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

train/sample_000243/board.png: downloading bytes:           |  0.00B

train/sample_000245/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_000244/board.png: downloading bytes:           |  0.00B

train/sample_000245/board.png: downloading bytes:           |  0.00B

train/sample_000246/board.png: reconstructing file:   0%|          |  0.00B / 44.3kB

train/sample_000246/board.png: downloading bytes:           |  0.00B

train/sample_000247/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_000247/board.png: downloading bytes:           |  0.00B

train/sample_000248/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_000248/board.png: downloading bytes:           |  0.00B

train/sample_000249/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_000249/board.png: downloading bytes:           |  0.00B

train/sample_000250/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_000250/board.png: downloading bytes:           |  0.00B

train/sample_000251/board.png: reconstructing file:   0%|          |  0.00B / 19.5kB

train/sample_000251/board.png: downloading bytes:           |  0.00B

train/sample_000252/board.png: reconstructing file:   0%|          |  0.00B / 39.3kB

train/sample_000252/board.png: downloading bytes:           |  0.00B

train/sample_000253/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_000253/board.png: downloading bytes:           |  0.00B

train/sample_000254/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_000254/board.png: downloading bytes:           |  0.00B

train/sample_000255/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_000255/board.png: downloading bytes:           |  0.00B

train/sample_000256/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_000256/board.png: downloading bytes:           |  0.00B

train/sample_000257/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_000257/board.png: downloading bytes:           |  0.00B

train/sample_000258/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_000258/board.png: downloading bytes:           |  0.00B

train/sample_000259/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_000259/board.png: downloading bytes:           |  0.00B

train/sample_000260/board.png: reconstructing file:   0%|          |  0.00B / 22.8kB

train/sample_000260/board.png: downloading bytes:           |  0.00B

train/sample_000262/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_000262/board.png: downloading bytes:           |  0.00B

train/sample_000261/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

train/sample_000261/board.png: downloading bytes:           |  0.00B

train/sample_000263/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_000263/board.png: downloading bytes:           |  0.00B

train/sample_000264/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_000264/board.png: downloading bytes:           |  0.00B

train/sample_000265/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

train/sample_000265/board.png: downloading bytes:           |  0.00B

train/sample_000266/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

train/sample_000266/board.png: downloading bytes:           |  0.00B

train/sample_000267/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_000268/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_000267/board.png: downloading bytes:           |  0.00B

train/sample_000268/board.png: downloading bytes:           |  0.00B

train/sample_000269/board.png: reconstructing file:   0%|          |  0.00B / 20.5kB

train/sample_000269/board.png: downloading bytes:           |  0.00B

train/sample_000271/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_000270/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_000270/board.png: downloading bytes:           |  0.00B

train/sample_000271/board.png: downloading bytes:           |  0.00B

train/sample_000272/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000272/board.png: downloading bytes:           |  0.00B

train/sample_000273/board.png: reconstructing file:   0%|          |  0.00B / 39.8kB

train/sample_000273/board.png: downloading bytes:           |  0.00B

train/sample_000274/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_000274/board.png: downloading bytes:           |  0.00B

train/sample_000275/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_000275/board.png: downloading bytes:           |  0.00B

train/sample_000276/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_000276/board.png: downloading bytes:           |  0.00B

train/sample_000277/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_000277/board.png: downloading bytes:           |  0.00B

train/sample_000278/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

train/sample_000278/board.png: downloading bytes:           |  0.00B

train/sample_000279/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

train/sample_000279/board.png: downloading bytes:           |  0.00B

train/sample_000280/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

train/sample_000280/board.png: downloading bytes:           |  0.00B

train/sample_000281/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_000282/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_000281/board.png: downloading bytes:           |  0.00B

train/sample_000282/board.png: downloading bytes:           |  0.00B

train/sample_000283/board.png: reconstructing file:   0%|          |  0.00B / 25.6kB

train/sample_000283/board.png: downloading bytes:           |  0.00B

train/sample_000285/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_000284/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_000285/board.png: downloading bytes:           |  0.00B

train/sample_000284/board.png: downloading bytes:           |  0.00B

train/sample_000286/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_000286/board.png: downloading bytes:           |  0.00B

train/sample_000287/board.png: reconstructing file:   0%|          |  0.00B / 37.4kB

train/sample_000287/board.png: downloading bytes:           |  0.00B

train/sample_000288/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

train/sample_000288/board.png: downloading bytes:           |  0.00B

train/sample_000289/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_000289/board.png: downloading bytes:           |  0.00B

train/sample_000290/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_000290/board.png: downloading bytes:           |  0.00B

train/sample_000291/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

train/sample_000291/board.png: downloading bytes:           |  0.00B

train/sample_000292/board.png: reconstructing file:   0%|          |  0.00B / 14.4kB

train/sample_000292/board.png: downloading bytes:           |  0.00B

train/sample_000293/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_000293/board.png: downloading bytes:           |  0.00B

train/sample_000294/board.png: reconstructing file:   0%|          |  0.00B / 25.6kB

train/sample_000294/board.png: downloading bytes:           |  0.00B

train/sample_000295/board.png: reconstructing file:   0%|          |  0.00B / 41.2kB

train/sample_000295/board.png: downloading bytes:           |  0.00B

train/sample_000296/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_000296/board.png: downloading bytes:           |  0.00B

train/sample_000297/board.png: reconstructing file:   0%|          |  0.00B / 18.5kB

train/sample_000297/board.png: downloading bytes:           |  0.00B

train/sample_000298/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

train/sample_000298/board.png: downloading bytes:           |  0.00B

train/sample_000299/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_000299/board.png: downloading bytes:           |  0.00B

train/sample_000300/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_000301/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_000300/board.png: downloading bytes:           |  0.00B

train/sample_000301/board.png: downloading bytes:           |  0.00B

train/sample_000302/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_000302/board.png: downloading bytes:           |  0.00B

train/sample_000303/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_000303/board.png: downloading bytes:           |  0.00B

train/sample_000304/board.png: reconstructing file:   0%|          |  0.00B / 14.0kB

train/sample_000304/board.png: downloading bytes:           |  0.00B

train/sample_000305/board.png: reconstructing file:   0%|          |  0.00B / 13.0kB

train/sample_000305/board.png: downloading bytes:           |  0.00B

train/sample_000306/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_000306/board.png: downloading bytes:           |  0.00B

train/sample_000307/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_000307/board.png: downloading bytes:           |  0.00B

train/sample_000308/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_000308/board.png: downloading bytes:           |  0.00B

train/sample_000309/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_000309/board.png: downloading bytes:           |  0.00B

train/sample_000310/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

train/sample_000310/board.png: downloading bytes:           |  0.00B

train/sample_000311/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_000311/board.png: downloading bytes:           |  0.00B

train/sample_000312/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_000312/board.png: downloading bytes:           |  0.00B

train/sample_000313/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

train/sample_000314/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_000313/board.png: downloading bytes:           |  0.00B

train/sample_000314/board.png: downloading bytes:           |  0.00B

train/sample_000315/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_000315/board.png: downloading bytes:           |  0.00B

train/sample_000316/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_000316/board.png: downloading bytes:           |  0.00B

train/sample_000317/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_000317/board.png: downloading bytes:           |  0.00B

train/sample_000318/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

train/sample_000318/board.png: downloading bytes:           |  0.00B

train/sample_000319/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

train/sample_000319/board.png: downloading bytes:           |  0.00B

train/sample_000320/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_000320/board.png: downloading bytes:           |  0.00B

train/sample_000321/board.png: reconstructing file:   0%|          |  0.00B / 17.9kB

train/sample_000321/board.png: downloading bytes:           |  0.00B

train/sample_000322/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

train/sample_000322/board.png: downloading bytes:           |  0.00B

train/sample_000323/board.png: reconstructing file:   0%|          |  0.00B / 17.4kB

train/sample_000323/board.png: downloading bytes:           |  0.00B

train/sample_000325/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_000324/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_000325/board.png: downloading bytes:           |  0.00B

train/sample_000324/board.png: downloading bytes:           |  0.00B

train/sample_000326/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_000326/board.png: downloading bytes:           |  0.00B

train/sample_000327/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_000327/board.png: downloading bytes:           |  0.00B

train/sample_000328/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_000328/board.png: downloading bytes:           |  0.00B

train/sample_000329/board.png: reconstructing file:   0%|          |  0.00B / 15.7kB

train/sample_000329/board.png: downloading bytes:           |  0.00B

train/sample_000330/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_000331/board.png: reconstructing file:   0%|          |  0.00B / 19.2kB

train/sample_000330/board.png: downloading bytes:           |  0.00B

train/sample_000331/board.png: downloading bytes:           |  0.00B

train/sample_000332/board.png: reconstructing file:   0%|          |  0.00B / 24.6kB

train/sample_000332/board.png: downloading bytes:           |  0.00B

train/sample_000333/board.png: reconstructing file:   0%|          |  0.00B / 17.3kB

train/sample_000333/board.png: downloading bytes:           |  0.00B

train/sample_000334/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_000335/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_000334/board.png: downloading bytes:           |  0.00B

train/sample_000335/board.png: downloading bytes:           |  0.00B

train/sample_000336/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

train/sample_000336/board.png: downloading bytes:           |  0.00B

train/sample_000337/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_000337/board.png: downloading bytes:           |  0.00B

train/sample_000338/board.png: reconstructing file:   0%|          |  0.00B / 42.4kB

train/sample_000338/board.png: downloading bytes:           |  0.00B

train/sample_000340/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_000339/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_000340/board.png: downloading bytes:           |  0.00B

train/sample_000339/board.png: downloading bytes:           |  0.00B

train/sample_000341/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_000343/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_000342/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

train/sample_000341/board.png: downloading bytes:           |  0.00B

train/sample_000343/board.png: downloading bytes:           |  0.00B

train/sample_000342/board.png: downloading bytes:           |  0.00B

train/sample_000344/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_000345/board.png: reconstructing file:   0%|          |  0.00B / 17.3kB

train/sample_000344/board.png: downloading bytes:           |  0.00B

train/sample_000345/board.png: downloading bytes:           |  0.00B

train/sample_000346/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

train/sample_000346/board.png: downloading bytes:           |  0.00B

train/sample_000347/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_000347/board.png: downloading bytes:           |  0.00B

train/sample_000348/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_000348/board.png: downloading bytes:           |  0.00B

train/sample_000349/board.png: reconstructing file:   0%|          |  0.00B / 40.5kB

train/sample_000349/board.png: downloading bytes:           |  0.00B

train/sample_000350/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

train/sample_000350/board.png: downloading bytes:           |  0.00B

train/sample_000351/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_000351/board.png: downloading bytes:           |  0.00B

train/sample_000353/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

train/sample_000352/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_000354/board.png: reconstructing file:   0%|          |  0.00B / 18.2kB

train/sample_000353/board.png: downloading bytes:           |  0.00B

train/sample_000352/board.png: downloading bytes:           |  0.00B

train/sample_000354/board.png: downloading bytes:           |  0.00B

train/sample_000355/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_000356/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_000357/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_000357/board.png: downloading bytes:           |  0.00B

train/sample_000356/board.png: downloading bytes:           |  0.00B

train/sample_000355/board.png: downloading bytes:           |  0.00B

train/sample_000358/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000358/board.png: downloading bytes:           |  0.00B

train/sample_000359/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_000359/board.png: downloading bytes:           |  0.00B

train/sample_000360/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_000360/board.png: downloading bytes:           |  0.00B

train/sample_000361/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_000361/board.png: downloading bytes:           |  0.00B

train/sample_000362/board.png: reconstructing file:   0%|          |  0.00B / 40.7kB

train/sample_000362/board.png: downloading bytes:           |  0.00B

train/sample_000363/board.png: reconstructing file:   0%|          |  0.00B / 15.0kB

train/sample_000363/board.png: downloading bytes:           |  0.00B

train/sample_000364/board.png: reconstructing file:   0%|          |  0.00B / 15.9kB

train/sample_000366/board.png: reconstructing file:   0%|          |  0.00B / 41.3kB

train/sample_000364/board.png: downloading bytes:           |  0.00B

train/sample_000365/board.png: reconstructing file:   0%|          |  0.00B / 41.5kB

train/sample_000367/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_000365/board.png: downloading bytes:           |  0.00B

train/sample_000366/board.png: downloading bytes:           |  0.00B

train/sample_000367/board.png: downloading bytes:           |  0.00B

train/sample_000368/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_000368/board.png: downloading bytes:           |  0.00B

train/sample_000369/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_000370/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_000369/board.png: downloading bytes:           |  0.00B

train/sample_000370/board.png: downloading bytes:           |  0.00B

train/sample_000371/board.png: reconstructing file:   0%|          |  0.00B / 20.8kB

train/sample_000373/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_000372/board.png: reconstructing file:   0%|          |  0.00B / 40.2kB

train/sample_000371/board.png: downloading bytes:           |  0.00B

train/sample_000373/board.png: downloading bytes:           |  0.00B

train/sample_000374/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_000372/board.png: downloading bytes:           |  0.00B

train/sample_000375/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_000374/board.png: downloading bytes:           |  0.00B

train/sample_000375/board.png: downloading bytes:           |  0.00B

train/sample_000376/board.png: reconstructing file:   0%|          |  0.00B / 18.2kB

train/sample_000376/board.png: downloading bytes:           |  0.00B

train/sample_000377/board.png: reconstructing file:   0%|          |  0.00B / 35.9kB

train/sample_000377/board.png: downloading bytes:           |  0.00B

train/sample_000378/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_000378/board.png: downloading bytes:           |  0.00B

train/sample_000379/board.png: reconstructing file:   0%|          |  0.00B / 15.5kB

train/sample_000381/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_000380/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_000379/board.png: downloading bytes:           |  0.00B

train/sample_000381/board.png: downloading bytes:           |  0.00B

train/sample_000383/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_000382/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_000380/board.png: downloading bytes:           |  0.00B

train/sample_000383/board.png: downloading bytes:           |  0.00B

train/sample_000382/board.png: downloading bytes:           |  0.00B

train/sample_000384/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_000384/board.png: downloading bytes:           |  0.00B

train/sample_000385/board.png: reconstructing file:   0%|          |  0.00B / 38.5kB

train/sample_000385/board.png: downloading bytes:           |  0.00B

train/sample_000386/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000386/board.png: downloading bytes:           |  0.00B

train/sample_000387/board.png: reconstructing file:   0%|          |  0.00B / 39.2kB

train/sample_000389/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_000388/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_000387/board.png: downloading bytes:           |  0.00B

train/sample_000389/board.png: downloading bytes:           |  0.00B

train/sample_000388/board.png: downloading bytes:           |  0.00B

train/sample_000390/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_000391/board.png: reconstructing file:   0%|          |  0.00B / 16.7kB

train/sample_000390/board.png: downloading bytes:           |  0.00B

train/sample_000391/board.png: downloading bytes:           |  0.00B

train/sample_000392/board.png: reconstructing file:   0%|          |  0.00B / 15.8kB

train/sample_000393/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

train/sample_000392/board.png: downloading bytes:           |  0.00B

train/sample_000393/board.png: downloading bytes:           |  0.00B

train/sample_000394/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_000394/board.png: downloading bytes:           |  0.00B

train/sample_000395/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_000395/board.png: downloading bytes:           |  0.00B

train/sample_000396/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_000396/board.png: downloading bytes:           |  0.00B

train/sample_000397/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_000398/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_000397/board.png: downloading bytes:           |  0.00B

train/sample_000399/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

train/sample_000400/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_000398/board.png: downloading bytes:           |  0.00B

train/sample_000399/board.png: downloading bytes:           |  0.00B

train/sample_000400/board.png: downloading bytes:           |  0.00B

train/sample_000401/board.png: reconstructing file:   0%|          |  0.00B / 41.1kB

train/sample_000401/board.png: downloading bytes:           |  0.00B

train/sample_000402/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

train/sample_000402/board.png: downloading bytes:           |  0.00B

train/sample_000403/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_000403/board.png: downloading bytes:           |  0.00B

train/sample_000404/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_000404/board.png: downloading bytes:           |  0.00B

train/sample_000405/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_000405/board.png: downloading bytes:           |  0.00B

train/sample_000406/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_000407/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_000406/board.png: downloading bytes:           |  0.00B

train/sample_000407/board.png: downloading bytes:           |  0.00B

train/sample_000408/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000408/board.png: downloading bytes:           |  0.00B

train/sample_000409/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_000409/board.png: downloading bytes:           |  0.00B

train/sample_000410/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_000410/board.png: downloading bytes:           |  0.00B

train/sample_000411/board.png: reconstructing file:   0%|          |  0.00B / 39.2kB

train/sample_000411/board.png: downloading bytes:           |  0.00B

train/sample_000412/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000412/board.png: downloading bytes:           |  0.00B

train/sample_000413/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_000413/board.png: downloading bytes:           |  0.00B

train/sample_000414/board.png: reconstructing file:   0%|          |  0.00B / 22.9kB

train/sample_000414/board.png: downloading bytes:           |  0.00B

train/sample_000415/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_000416/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_000415/board.png: downloading bytes:           |  0.00B

train/sample_000416/board.png: downloading bytes:           |  0.00B

train/sample_000417/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_000417/board.png: downloading bytes:           |  0.00B

train/sample_000418/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_000418/board.png: downloading bytes:           |  0.00B

train/sample_000419/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_000419/board.png: downloading bytes:           |  0.00B

train/sample_000420/board.png: reconstructing file:   0%|          |  0.00B / 43.0kB

train/sample_000421/board.png: reconstructing file:   0%|          |  0.00B / 19.5kB

train/sample_000420/board.png: downloading bytes:           |  0.00B

train/sample_000422/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_000421/board.png: downloading bytes:           |  0.00B

train/sample_000422/board.png: downloading bytes:           |  0.00B

train/sample_000424/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_000424/board.png: downloading bytes:           |  0.00B

train/sample_000423/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_000425/board.png: reconstructing file:   0%|          |  0.00B / 21.4kB

train/sample_000423/board.png: downloading bytes:           |  0.00B

train/sample_000425/board.png: downloading bytes:           |  0.00B

train/sample_000426/board.png: reconstructing file:   0%|          |  0.00B / 12.9kB

train/sample_000426/board.png: downloading bytes:           |  0.00B

train/sample_000427/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_000427/board.png: downloading bytes:           |  0.00B

train/sample_000428/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_000429/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_000429/board.png: downloading bytes:           |  0.00B

train/sample_000428/board.png: downloading bytes:           |  0.00B

train/sample_000431/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_000430/board.png: reconstructing file:   0%|          |  0.00B / 20.8kB

train/sample_000431/board.png: downloading bytes:           |  0.00B

train/sample_000432/board.png: reconstructing file:   0%|          |  0.00B / 20.5kB

train/sample_000430/board.png: downloading bytes:           |  0.00B

train/sample_000432/board.png: downloading bytes:           |  0.00B

train/sample_000433/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_000433/board.png: downloading bytes:           |  0.00B

train/sample_000434/board.png: reconstructing file:   0%|          |  0.00B / 17.9kB

train/sample_000434/board.png: downloading bytes:           |  0.00B

train/sample_000435/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_000435/board.png: downloading bytes:           |  0.00B

train/sample_000436/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_000437/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_000436/board.png: downloading bytes:           |  0.00B

train/sample_000437/board.png: downloading bytes:           |  0.00B

train/sample_000438/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

train/sample_000438/board.png: downloading bytes:           |  0.00B

train/sample_000440/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_000440/board.png: downloading bytes:           |  0.00B

train/sample_000439/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

train/sample_000441/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_000441/board.png: downloading bytes:           |  0.00B

train/sample_000439/board.png: downloading bytes:           |  0.00B

train/sample_000442/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_000442/board.png: downloading bytes:           |  0.00B

train/sample_000443/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_000443/board.png: downloading bytes:           |  0.00B

train/sample_000445/board.png: reconstructing file:   0%|          |  0.00B / 35.9kB

train/sample_000444/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_000447/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_000446/board.png: reconstructing file:   0%|          |  0.00B / 24.6kB

train/sample_000445/board.png: downloading bytes:           |  0.00B

train/sample_000444/board.png: downloading bytes:           |  0.00B

train/sample_000447/board.png: downloading bytes:           |  0.00B

train/sample_000448/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_000446/board.png: downloading bytes:           |  0.00B

train/sample_000448/board.png: downloading bytes:           |  0.00B

train/sample_000449/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_000449/board.png: downloading bytes:           |  0.00B

train/sample_000450/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_000450/board.png: downloading bytes:           |  0.00B

train/sample_000451/board.png: reconstructing file:   0%|          |  0.00B / 36.3kB

train/sample_000451/board.png: downloading bytes:           |  0.00B

train/sample_000452/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_000452/board.png: downloading bytes:           |  0.00B

train/sample_000458/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_000455/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_000454/board.png: reconstructing file:   0%|          |  0.00B / 15.0kB

train/sample_000456/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

train/sample_000457/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

train/sample_000455/board.png: downloading bytes:           |  0.00B

train/sample_000458/board.png: downloading bytes:           |  0.00B

train/sample_000456/board.png: downloading bytes:           |  0.00B

train/sample_000454/board.png: downloading bytes:           |  0.00B

train/sample_000457/board.png: downloading bytes:           |  0.00B

train/sample_000462/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_000462/board.png: downloading bytes:           |  0.00B

train/sample_000453/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_000453/board.png: downloading bytes:           |  0.00B

train/sample_000461/board.png: reconstructing file:   0%|          |  0.00B / 14.3kB

train/sample_000461/board.png: downloading bytes:           |  0.00B

train/sample_000459/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_000459/board.png: downloading bytes:           |  0.00B

train/sample_000460/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_000460/board.png: downloading bytes:           |  0.00B

train/sample_000465/board.png: reconstructing file:   0%|          |  0.00B / 44.5kB

train/sample_000465/board.png: downloading bytes:           |  0.00B

train/sample_000463/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_000463/board.png: downloading bytes:           |  0.00B

train/sample_000464/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_000464/board.png: downloading bytes:           |  0.00B

train/sample_000466/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_000466/board.png: downloading bytes:           |  0.00B

train/sample_000467/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_000467/board.png: downloading bytes:           |  0.00B

train/sample_000469/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

train/sample_000468/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_000469/board.png: downloading bytes:           |  0.00B

train/sample_000468/board.png: downloading bytes:           |  0.00B

train/sample_000470/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_000472/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_000471/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_000470/board.png: downloading bytes:           |  0.00B

train/sample_000472/board.png: downloading bytes:           |  0.00B

train/sample_000471/board.png: downloading bytes:           |  0.00B

train/sample_000473/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_000473/board.png: downloading bytes:           |  0.00B

train/sample_000474/board.png: reconstructing file:   0%|          |  0.00B / 38.6kB

train/sample_000474/board.png: downloading bytes:           |  0.00B

train/sample_000475/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_000475/board.png: downloading bytes:           |  0.00B

train/sample_000476/board.png: reconstructing file:   0%|          |  0.00B / 38.7kB

train/sample_000477/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_000478/board.png: reconstructing file:   0%|          |  0.00B / 39.8kB

train/sample_000476/board.png: downloading bytes:           |  0.00B

train/sample_000479/board.png: reconstructing file:   0%|          |  0.00B / 24.5kB

train/sample_000478/board.png: downloading bytes:           |  0.00B

train/sample_000477/board.png: downloading bytes:           |  0.00B

train/sample_000479/board.png: downloading bytes:           |  0.00B

train/sample_000480/board.png: reconstructing file:   0%|          |  0.00B / 21.4kB

train/sample_000480/board.png: downloading bytes:           |  0.00B

train/sample_000481/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_000481/board.png: downloading bytes:           |  0.00B

train/sample_000482/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

train/sample_000482/board.png: downloading bytes:           |  0.00B

train/sample_000483/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_000483/board.png: downloading bytes:           |  0.00B

train/sample_000484/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000484/board.png: downloading bytes:           |  0.00B

train/sample_000485/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_000485/board.png: downloading bytes:           |  0.00B

train/sample_000486/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

train/sample_000488/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_000487/board.png: reconstructing file:   0%|          |  0.00B / 38.6kB

train/sample_000489/board.png: reconstructing file:   0%|          |  0.00B / 25.6kB

train/sample_000487/board.png: downloading bytes:           |  0.00B

train/sample_000486/board.png: downloading bytes:           |  0.00B

train/sample_000488/board.png: downloading bytes:           |  0.00B

train/sample_000489/board.png: downloading bytes:           |  0.00B

train/sample_000490/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_000490/board.png: downloading bytes:           |  0.00B

train/sample_000491/board.png: reconstructing file:   0%|          |  0.00B / 14.2kB

train/sample_000491/board.png: downloading bytes:           |  0.00B

train/sample_000492/board.png: reconstructing file:   0%|          |  0.00B / 43.7kB

train/sample_000492/board.png: downloading bytes:           |  0.00B

train/sample_000494/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_000493/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_000496/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_000495/board.png: reconstructing file:   0%|          |  0.00B / 12.7kB

train/sample_000493/board.png: downloading bytes:           |  0.00B

train/sample_000494/board.png: downloading bytes:           |  0.00B

train/sample_000496/board.png: downloading bytes:           |  0.00B

train/sample_000495/board.png: downloading bytes:           |  0.00B

train/sample_000497/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_000497/board.png: downloading bytes:           |  0.00B

train/sample_000498/board.png: reconstructing file:   0%|          |  0.00B / 14.4kB

train/sample_000498/board.png: downloading bytes:           |  0.00B

train/sample_000499/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_000499/board.png: downloading bytes:           |  0.00B

train/sample_000500/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_000500/board.png: downloading bytes:           |  0.00B

train/sample_000501/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

train/sample_000501/board.png: downloading bytes:           |  0.00B

train/sample_000502/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_000502/board.png: downloading bytes:           |  0.00B

train/sample_000503/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_000504/board.png: reconstructing file:   0%|          |  0.00B / 15.0kB

train/sample_000505/board.png: reconstructing file:   0%|          |  0.00B / 39.4kB

train/sample_000504/board.png: downloading bytes:           |  0.00B

train/sample_000503/board.png: downloading bytes:           |  0.00B

train/sample_000505/board.png: downloading bytes:           |  0.00B

train/sample_000506/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_000506/board.png: downloading bytes:           |  0.00B

train/sample_000507/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_000507/board.png: downloading bytes:           |  0.00B

train/sample_000508/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_000508/board.png: downloading bytes:           |  0.00B

train/sample_000509/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_000509/board.png: downloading bytes:           |  0.00B

train/sample_000510/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_000510/board.png: downloading bytes:           |  0.00B

train/sample_000511/board.png: reconstructing file:   0%|          |  0.00B / 18.5kB

train/sample_000511/board.png: downloading bytes:           |  0.00B

train/sample_000512/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_000512/board.png: downloading bytes:           |  0.00B

train/sample_000513/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_000513/board.png: downloading bytes:           |  0.00B

train/sample_000514/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_000514/board.png: downloading bytes:           |  0.00B

train/sample_000515/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_000515/board.png: downloading bytes:           |  0.00B

train/sample_000516/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

train/sample_000516/board.png: downloading bytes:           |  0.00B

train/sample_000518/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_000518/board.png: downloading bytes:           |  0.00B

train/sample_000517/board.png: reconstructing file:   0%|          |  0.00B / 39.3kB

train/sample_000519/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_000517/board.png: downloading bytes:           |  0.00B

train/sample_000519/board.png: downloading bytes:           |  0.00B

train/sample_000520/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_000520/board.png: downloading bytes:           |  0.00B

train/sample_000521/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_000522/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_000521/board.png: downloading bytes:           |  0.00B

train/sample_000522/board.png: downloading bytes:           |  0.00B

train/sample_000523/board.png: reconstructing file:   0%|          |  0.00B / 40.3kB

train/sample_000523/board.png: downloading bytes:           |  0.00B

train/sample_000524/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_000524/board.png: downloading bytes:           |  0.00B

train/sample_000525/board.png: reconstructing file:   0%|          |  0.00B / 41.0kB

train/sample_000525/board.png: downloading bytes:           |  0.00B

train/sample_000526/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_000526/board.png: downloading bytes:           |  0.00B

train/sample_000527/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

train/sample_000528/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_000527/board.png: downloading bytes:           |  0.00B

train/sample_000528/board.png: downloading bytes:           |  0.00B

train/sample_000529/board.png: reconstructing file:   0%|          |  0.00B / 43.0kB

train/sample_000529/board.png: downloading bytes:           |  0.00B

train/sample_000530/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_000530/board.png: downloading bytes:           |  0.00B

train/sample_000531/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_000531/board.png: downloading bytes:           |  0.00B

train/sample_000532/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_000532/board.png: downloading bytes:           |  0.00B

train/sample_000533/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_000533/board.png: downloading bytes:           |  0.00B

train/sample_000534/board.png: reconstructing file:   0%|          |  0.00B / 21.1kB

train/sample_000535/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_000534/board.png: downloading bytes:           |  0.00B

train/sample_000536/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

train/sample_000537/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_000535/board.png: downloading bytes:           |  0.00B

train/sample_000536/board.png: downloading bytes:           |  0.00B

train/sample_000537/board.png: downloading bytes:           |  0.00B

train/sample_000538/board.png: reconstructing file:   0%|          |  0.00B / 13.3kB

train/sample_000538/board.png: downloading bytes:           |  0.00B

train/sample_000539/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

train/sample_000539/board.png: downloading bytes:           |  0.00B

train/sample_000540/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_000540/board.png: downloading bytes:           |  0.00B

train/sample_000541/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_000541/board.png: downloading bytes:           |  0.00B

train/sample_000542/board.png: reconstructing file:   0%|          |  0.00B / 25.6kB

train/sample_000543/board.png: reconstructing file:   0%|          |  0.00B / 24.5kB

train/sample_000544/board.png: reconstructing file:   0%|          |  0.00B / 41.2kB

train/sample_000542/board.png: downloading bytes:           |  0.00B

train/sample_000545/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_000543/board.png: downloading bytes:           |  0.00B

train/sample_000544/board.png: downloading bytes:           |  0.00B

train/sample_000545/board.png: downloading bytes:           |  0.00B

train/sample_000546/board.png: reconstructing file:   0%|          |  0.00B / 15.5kB

train/sample_000546/board.png: downloading bytes:           |  0.00B

train/sample_000547/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_000547/board.png: downloading bytes:           |  0.00B

train/sample_000548/board.png: reconstructing file:   0%|          |  0.00B / 40.5kB

train/sample_000548/board.png: downloading bytes:           |  0.00B

train/sample_000549/board.png: reconstructing file:   0%|          |  0.00B / 13.6kB

train/sample_000549/board.png: downloading bytes:           |  0.00B

train/sample_000551/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_000550/board.png: reconstructing file:   0%|          |  0.00B / 15.3kB

train/sample_000553/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_000551/board.png: downloading bytes:           |  0.00B

train/sample_000552/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_000553/board.png: downloading bytes:           |  0.00B

train/sample_000550/board.png: downloading bytes:           |  0.00B

train/sample_000552/board.png: downloading bytes:           |  0.00B

train/sample_000554/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_000554/board.png: downloading bytes:           |  0.00B

train/sample_000555/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_000555/board.png: downloading bytes:           |  0.00B

train/sample_000556/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_000556/board.png: downloading bytes:           |  0.00B

train/sample_000557/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_000557/board.png: downloading bytes:           |  0.00B

train/sample_000558/board.png: reconstructing file:   0%|          |  0.00B / 20.5kB

train/sample_000558/board.png: downloading bytes:           |  0.00B

train/sample_000559/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_000560/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_000559/board.png: downloading bytes:           |  0.00B

train/sample_000560/board.png: downloading bytes:           |  0.00B

train/sample_000561/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_000561/board.png: downloading bytes:           |  0.00B

train/sample_000562/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000562/board.png: downloading bytes:           |  0.00B

train/sample_000563/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_000564/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_000563/board.png: downloading bytes:           |  0.00B

train/sample_000565/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

train/sample_000564/board.png: downloading bytes:           |  0.00B

train/sample_000565/board.png: downloading bytes:           |  0.00B

train/sample_000566/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_000566/board.png: downloading bytes:           |  0.00B

train/sample_000567/board.png: reconstructing file:   0%|          |  0.00B / 19.5kB

train/sample_000567/board.png: downloading bytes:           |  0.00B

train/sample_000568/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_000568/board.png: downloading bytes:           |  0.00B

train/sample_000569/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_000570/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_000569/board.png: downloading bytes:           |  0.00B

train/sample_000570/board.png: downloading bytes:           |  0.00B

train/sample_000571/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_000571/board.png: downloading bytes:           |  0.00B

train/sample_000572/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_000573/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_000572/board.png: downloading bytes:           |  0.00B

train/sample_000573/board.png: downloading bytes:           |  0.00B

train/sample_000574/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_000575/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_000574/board.png: downloading bytes:           |  0.00B

train/sample_000576/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_000575/board.png: downloading bytes:           |  0.00B

train/sample_000576/board.png: downloading bytes:           |  0.00B

train/sample_000577/board.png: reconstructing file:   0%|          |  0.00B / 35.9kB

train/sample_000577/board.png: downloading bytes:           |  0.00B

train/sample_000578/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_000578/board.png: downloading bytes:           |  0.00B

train/sample_000579/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_000579/board.png: downloading bytes:           |  0.00B

train/sample_000580/board.png: reconstructing file:   0%|          |  0.00B / 21.8kB

train/sample_000580/board.png: downloading bytes:           |  0.00B

train/sample_000581/board.png: reconstructing file:   0%|          |  0.00B / 18.2kB

train/sample_000581/board.png: downloading bytes:           |  0.00B

train/sample_000582/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_000582/board.png: downloading bytes:           |  0.00B

train/sample_000583/board.png: reconstructing file:   0%|          |  0.00B / 22.6kB

train/sample_000583/board.png: downloading bytes:           |  0.00B

train/sample_000584/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

train/sample_000584/board.png: downloading bytes:           |  0.00B

train/sample_000585/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_000586/board.png: reconstructing file:   0%|          |  0.00B / 21.3kB

train/sample_000585/board.png: downloading bytes:           |  0.00B

train/sample_000586/board.png: downloading bytes:           |  0.00B

train/sample_000587/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_000588/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_000587/board.png: downloading bytes:           |  0.00B

train/sample_000588/board.png: downloading bytes:           |  0.00B

train/sample_000589/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_000589/board.png: downloading bytes:           |  0.00B

train/sample_000590/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

train/sample_000590/board.png: downloading bytes:           |  0.00B

train/sample_000591/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_000591/board.png: downloading bytes:           |  0.00B

train/sample_000592/board.png: reconstructing file:   0%|          |  0.00B / 18.0kB

train/sample_000592/board.png: downloading bytes:           |  0.00B

train/sample_000593/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_000594/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_000594/board.png: downloading bytes:           |  0.00B

train/sample_000593/board.png: downloading bytes:           |  0.00B

train/sample_000595/board.png: reconstructing file:   0%|          |  0.00B / 16.3kB

train/sample_000595/board.png: downloading bytes:           |  0.00B

train/sample_000596/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_000596/board.png: downloading bytes:           |  0.00B

train/sample_000597/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

train/sample_000597/board.png: downloading bytes:           |  0.00B

train/sample_000598/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

train/sample_000599/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_000598/board.png: downloading bytes:           |  0.00B

train/sample_000599/board.png: downloading bytes:           |  0.00B

train/sample_000600/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

train/sample_000600/board.png: downloading bytes:           |  0.00B

train/sample_000601/board.png: reconstructing file:   0%|          |  0.00B / 37.0kB

train/sample_000601/board.png: downloading bytes:           |  0.00B

train/sample_000602/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

train/sample_000603/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_000602/board.png: downloading bytes:           |  0.00B

train/sample_000603/board.png: downloading bytes:           |  0.00B

train/sample_000604/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_000604/board.png: downloading bytes:           |  0.00B

train/sample_000605/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_000605/board.png: downloading bytes:           |  0.00B

train/sample_000606/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_000606/board.png: downloading bytes:           |  0.00B

train/sample_000607/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

train/sample_000607/board.png: downloading bytes:           |  0.00B

train/sample_000608/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_000608/board.png: downloading bytes:           |  0.00B

train/sample_000609/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_000609/board.png: downloading bytes:           |  0.00B

train/sample_000610/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_000611/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_000610/board.png: downloading bytes:           |  0.00B

train/sample_000612/board.png: reconstructing file:   0%|          |  0.00B / 38.9kB

train/sample_000611/board.png: downloading bytes:           |  0.00B

train/sample_000612/board.png: downloading bytes:           |  0.00B

train/sample_000613/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_000613/board.png: downloading bytes:           |  0.00B

train/sample_000614/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_000614/board.png: downloading bytes:           |  0.00B

train/sample_000615/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

train/sample_000615/board.png: downloading bytes:           |  0.00B

train/sample_000616/board.png: reconstructing file:   0%|          |  0.00B / 17.7kB

train/sample_000616/board.png: downloading bytes:           |  0.00B

train/sample_000617/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_000617/board.png: downloading bytes:           |  0.00B

train/sample_000618/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_000618/board.png: downloading bytes:           |  0.00B

train/sample_000619/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

train/sample_000619/board.png: downloading bytes:           |  0.00B

train/sample_000620/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_000621/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_000620/board.png: downloading bytes:           |  0.00B

train/sample_000621/board.png: downloading bytes:           |  0.00B

train/sample_000622/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_000623/board.png: reconstructing file:   0%|          |  0.00B / 24.7kB

train/sample_000622/board.png: downloading bytes:           |  0.00B

train/sample_000623/board.png: downloading bytes:           |  0.00B

train/sample_000624/board.png: reconstructing file:   0%|          |  0.00B / 18.2kB

train/sample_000625/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_000624/board.png: downloading bytes:           |  0.00B

train/sample_000625/board.png: downloading bytes:           |  0.00B

train/sample_000626/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_000626/board.png: downloading bytes:           |  0.00B

train/sample_000627/board.png: reconstructing file:   0%|          |  0.00B / 23.3kB

train/sample_000628/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_000628/board.png: downloading bytes:           |  0.00B

train/sample_000627/board.png: downloading bytes:           |  0.00B

train/sample_000629/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_000629/board.png: downloading bytes:           |  0.00B

train/sample_000630/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_000630/board.png: downloading bytes:           |  0.00B

train/sample_000632/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_000631/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

train/sample_000632/board.png: downloading bytes:           |  0.00B

train/sample_000634/board.png: reconstructing file:   0%|          |  0.00B / 44.3kB

train/sample_000631/board.png: downloading bytes:           |  0.00B

train/sample_000633/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_000634/board.png: downloading bytes:           |  0.00B

train/sample_000635/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_000633/board.png: downloading bytes:           |  0.00B

train/sample_000637/board.png: reconstructing file:   0%|          |  0.00B / 37.2kB

train/sample_000635/board.png: downloading bytes:           |  0.00B

train/sample_000637/board.png: downloading bytes:           |  0.00B

train/sample_000636/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

train/sample_000636/board.png: downloading bytes:           |  0.00B

train/sample_000638/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_000639/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_000640/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_000641/board.png: reconstructing file:   0%|          |  0.00B / 15.6kB

train/sample_000638/board.png: downloading bytes:           |  0.00B

train/sample_000639/board.png: downloading bytes:           |  0.00B

train/sample_000641/board.png: downloading bytes:           |  0.00B

train/sample_000640/board.png: downloading bytes:           |  0.00B

train/sample_000642/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

train/sample_000642/board.png: downloading bytes:           |  0.00B

train/sample_000643/board.png: reconstructing file:   0%|          |  0.00B / 42.4kB

train/sample_000643/board.png: downloading bytes:           |  0.00B

train/sample_000644/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_000644/board.png: downloading bytes:           |  0.00B

train/sample_000645/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_000645/board.png: downloading bytes:           |  0.00B

train/sample_000646/board.png: reconstructing file:   0%|          |  0.00B / 13.8kB

train/sample_000646/board.png: downloading bytes:           |  0.00B

train/sample_000647/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_000648/board.png: reconstructing file:   0%|          |  0.00B / 14.6kB

train/sample_000647/board.png: downloading bytes:           |  0.00B

train/sample_000649/board.png: reconstructing file:   0%|          |  0.00B / 41.7kB

train/sample_000648/board.png: downloading bytes:           |  0.00B

train/sample_000649/board.png: downloading bytes:           |  0.00B

train/sample_000650/board.png: reconstructing file:   0%|          |  0.00B / 43.5kB

train/sample_000650/board.png: downloading bytes:           |  0.00B

train/sample_000651/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_000651/board.png: downloading bytes:           |  0.00B

train/sample_000652/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_000653/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_000652/board.png: downloading bytes:           |  0.00B

train/sample_000653/board.png: downloading bytes:           |  0.00B

train/sample_000654/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_000654/board.png: downloading bytes:           |  0.00B

train/sample_000655/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_000655/board.png: downloading bytes:           |  0.00B

train/sample_000656/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_000656/board.png: downloading bytes:           |  0.00B

train/sample_000657/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_000658/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_000659/board.png: reconstructing file:   0%|          |  0.00B / 15.0kB

train/sample_000657/board.png: downloading bytes:           |  0.00B

train/sample_000659/board.png: downloading bytes:           |  0.00B

train/sample_000658/board.png: downloading bytes:           |  0.00B

train/sample_000660/board.png: reconstructing file:   0%|          |  0.00B / 42.6kB

train/sample_000660/board.png: downloading bytes:           |  0.00B

train/sample_000661/board.png: reconstructing file:   0%|          |  0.00B / 40.9kB

train/sample_000661/board.png: downloading bytes:           |  0.00B

train/sample_000662/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_000662/board.png: downloading bytes:           |  0.00B

train/sample_000663/board.png: reconstructing file:   0%|          |  0.00B / 21.3kB

train/sample_000663/board.png: downloading bytes:           |  0.00B

train/sample_000664/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_000664/board.png: downloading bytes:           |  0.00B

train/sample_000665/board.png: reconstructing file:   0%|          |  0.00B / 38.2kB

train/sample_000665/board.png: downloading bytes:           |  0.00B

train/sample_000666/board.png: reconstructing file:   0%|          |  0.00B / 17.9kB

train/sample_000666/board.png: downloading bytes:           |  0.00B

train/sample_000668/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_000669/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

train/sample_000667/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_000668/board.png: downloading bytes:           |  0.00B

train/sample_000667/board.png: downloading bytes:           |  0.00B

train/sample_000669/board.png: downloading bytes:           |  0.00B

train/sample_000670/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_000670/board.png: downloading bytes:           |  0.00B

train/sample_000671/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_000671/board.png: downloading bytes:           |  0.00B

train/sample_000672/board.png: reconstructing file:   0%|          |  0.00B / 24.5kB

train/sample_000672/board.png: downloading bytes:           |  0.00B

train/sample_000673/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_000673/board.png: downloading bytes:           |  0.00B

train/sample_000674/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

train/sample_000675/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_000676/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_000674/board.png: downloading bytes:           |  0.00B

train/sample_000675/board.png: downloading bytes:           |  0.00B

train/sample_000676/board.png: downloading bytes:           |  0.00B

train/sample_000677/board.png: reconstructing file:   0%|          |  0.00B / 37.0kB

train/sample_000677/board.png: downloading bytes:           |  0.00B

train/sample_000678/board.png: reconstructing file:   0%|          |  0.00B / 22.0kB

train/sample_000678/board.png: downloading bytes:           |  0.00B

train/sample_000680/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_000679/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_000679/board.png: downloading bytes:           |  0.00B

train/sample_000681/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_000680/board.png: downloading bytes:           |  0.00B

train/sample_000682/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_000681/board.png: downloading bytes:           |  0.00B

train/sample_000682/board.png: downloading bytes:           |  0.00B

train/sample_000684/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_000684/board.png: downloading bytes:           |  0.00B

train/sample_000685/board.png: reconstructing file:   0%|          |  0.00B / 12.7kB

train/sample_000685/board.png: downloading bytes:           |  0.00B

train/sample_000683/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

train/sample_000683/board.png: downloading bytes:           |  0.00B

train/sample_000686/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_000686/board.png: downloading bytes:           |  0.00B

train/sample_000687/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_000688/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_000687/board.png: downloading bytes:           |  0.00B

train/sample_000689/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_000688/board.png: downloading bytes:           |  0.00B

train/sample_000689/board.png: downloading bytes:           |  0.00B

train/sample_000690/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_000690/board.png: downloading bytes:           |  0.00B

train/sample_000691/board.png: reconstructing file:   0%|          |  0.00B / 23.3kB

train/sample_000692/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_000691/board.png: downloading bytes:           |  0.00B

train/sample_000693/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_000692/board.png: downloading bytes:           |  0.00B

train/sample_000693/board.png: downloading bytes:           |  0.00B

train/sample_000694/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

train/sample_000694/board.png: downloading bytes:           |  0.00B

train/sample_000695/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_000695/board.png: downloading bytes:           |  0.00B

train/sample_000696/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_000696/board.png: downloading bytes:           |  0.00B

train/sample_000698/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_000697/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_000698/board.png: downloading bytes:           |  0.00B

train/sample_000700/board.png: reconstructing file:   0%|          |  0.00B / 43.8kB

train/sample_000699/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_000701/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_000697/board.png: downloading bytes:           |  0.00B

train/sample_000700/board.png: downloading bytes:           |  0.00B

train/sample_000699/board.png: downloading bytes:           |  0.00B

train/sample_000701/board.png: downloading bytes:           |  0.00B

train/sample_000702/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_000702/board.png: downloading bytes:           |  0.00B

train/sample_000703/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

train/sample_000703/board.png: downloading bytes:           |  0.00B

train/sample_000705/board.png: reconstructing file:   0%|          |  0.00B / 24.3kB

train/sample_000704/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

train/sample_000705/board.png: downloading bytes:           |  0.00B

train/sample_000704/board.png: downloading bytes:           |  0.00B

train/sample_000706/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000707/board.png: reconstructing file:   0%|          |  0.00B / 14.4kB

train/sample_000708/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_000707/board.png: downloading bytes:           |  0.00B

train/sample_000706/board.png: downloading bytes:           |  0.00B

train/sample_000709/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_000708/board.png: downloading bytes:           |  0.00B

train/sample_000709/board.png: downloading bytes:           |  0.00B

train/sample_000710/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_000710/board.png: downloading bytes:           |  0.00B

train/sample_000711/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

train/sample_000711/board.png: downloading bytes:           |  0.00B

train/sample_000712/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_000712/board.png: downloading bytes:           |  0.00B

train/sample_000713/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_000713/board.png: downloading bytes:           |  0.00B

train/sample_000714/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000716/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_000715/board.png: reconstructing file:   0%|          |  0.00B / 18.0kB

train/sample_000717/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_000714/board.png: downloading bytes:           |  0.00B

train/sample_000716/board.png: downloading bytes:           |  0.00B

train/sample_000715/board.png: downloading bytes:           |  0.00B

train/sample_000717/board.png: downloading bytes:           |  0.00B

train/sample_000718/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_000718/board.png: downloading bytes:           |  0.00B

train/sample_000719/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_000719/board.png: downloading bytes:           |  0.00B

train/sample_000720/board.png: reconstructing file:   0%|          |  0.00B / 43.3kB

train/sample_000720/board.png: downloading bytes:           |  0.00B

train/sample_000721/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_000721/board.png: downloading bytes:           |  0.00B

train/sample_000724/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_000723/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_000722/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_000725/board.png: reconstructing file:   0%|          |  0.00B / 18.5kB

train/sample_000724/board.png: downloading bytes:           |  0.00B

train/sample_000723/board.png: downloading bytes:           |  0.00B

train/sample_000722/board.png: downloading bytes:           |  0.00B

train/sample_000725/board.png: downloading bytes:           |  0.00B

train/sample_000726/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_000726/board.png: downloading bytes:           |  0.00B

train/sample_000727/board.png: reconstructing file:   0%|          |  0.00B / 16.9kB

train/sample_000727/board.png: downloading bytes:           |  0.00B

train/sample_000728/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_000728/board.png: downloading bytes:           |  0.00B

train/sample_000729/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_000729/board.png: downloading bytes:           |  0.00B

train/sample_000730/board.png: reconstructing file:   0%|          |  0.00B / 16.2kB

train/sample_000730/board.png: downloading bytes:           |  0.00B

train/sample_000731/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_000731/board.png: downloading bytes:           |  0.00B

train/sample_000732/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_000732/board.png: downloading bytes:           |  0.00B

train/sample_000733/board.png: reconstructing file:   0%|          |  0.00B / 16.3kB

train/sample_000733/board.png: downloading bytes:           |  0.00B

train/sample_000734/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_000734/board.png: downloading bytes:           |  0.00B

train/sample_000735/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_000735/board.png: downloading bytes:           |  0.00B

train/sample_000736/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_000736/board.png: downloading bytes:           |  0.00B

train/sample_000737/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_000737/board.png: downloading bytes:           |  0.00B

train/sample_000738/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_000740/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_000739/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_000738/board.png: downloading bytes:           |  0.00B

train/sample_000739/board.png: downloading bytes:           |  0.00B

train/sample_000740/board.png: downloading bytes:           |  0.00B

train/sample_000741/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_000741/board.png: downloading bytes:           |  0.00B

train/sample_000742/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_000742/board.png: downloading bytes:           |  0.00B

train/sample_000743/board.png: reconstructing file:   0%|          |  0.00B / 18.9kB

train/sample_000743/board.png: downloading bytes:           |  0.00B

train/sample_000744/board.png: reconstructing file:   0%|          |  0.00B / 36.3kB

train/sample_000744/board.png: downloading bytes:           |  0.00B

train/sample_000745/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_000745/board.png: downloading bytes:           |  0.00B

train/sample_000746/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_000746/board.png: downloading bytes:           |  0.00B

train/sample_000747/board.png: reconstructing file:   0%|          |  0.00B / 40.3kB

train/sample_000747/board.png: downloading bytes:           |  0.00B

train/sample_000748/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_000749/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_000748/board.png: downloading bytes:           |  0.00B

train/sample_000749/board.png: downloading bytes:           |  0.00B

train/sample_000750/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_000750/board.png: downloading bytes:           |  0.00B

train/sample_000751/board.png: reconstructing file:   0%|          |  0.00B / 20.7kB

train/sample_000752/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_000753/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_000751/board.png: downloading bytes:           |  0.00B

train/sample_000752/board.png: downloading bytes:           |  0.00B

train/sample_000753/board.png: downloading bytes:           |  0.00B

train/sample_000755/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_000754/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_000756/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_000755/board.png: downloading bytes:           |  0.00B

train/sample_000756/board.png: downloading bytes:           |  0.00B

train/sample_000754/board.png: downloading bytes:           |  0.00B

train/sample_000757/board.png: reconstructing file:   0%|          |  0.00B / 18.0kB

train/sample_000757/board.png: downloading bytes:           |  0.00B

train/sample_000758/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_000758/board.png: downloading bytes:           |  0.00B

train/sample_000759/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_000759/board.png: downloading bytes:           |  0.00B

train/sample_000760/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_000761/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_000760/board.png: downloading bytes:           |  0.00B

train/sample_000761/board.png: downloading bytes:           |  0.00B

train/sample_000762/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_000764/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

train/sample_000763/board.png: reconstructing file:   0%|          |  0.00B / 39.8kB

train/sample_000762/board.png: downloading bytes:           |  0.00B

train/sample_000764/board.png: downloading bytes:           |  0.00B

train/sample_000763/board.png: downloading bytes:           |  0.00B

train/sample_000765/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

train/sample_000765/board.png: downloading bytes:           |  0.00B

train/sample_000766/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_000766/board.png: downloading bytes:           |  0.00B

train/sample_000767/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_000768/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_000767/board.png: downloading bytes:           |  0.00B

train/sample_000768/board.png: downloading bytes:           |  0.00B

train/sample_000769/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_000772/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_000771/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_000770/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

train/sample_000773/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_000769/board.png: downloading bytes:           |  0.00B

train/sample_000772/board.png: downloading bytes:           |  0.00B

train/sample_000771/board.png: downloading bytes:           |  0.00B

train/sample_000770/board.png: downloading bytes:           |  0.00B

train/sample_000773/board.png: downloading bytes:           |  0.00B

train/sample_000774/board.png: reconstructing file:   0%|          |  0.00B / 15.3kB

train/sample_000774/board.png: downloading bytes:           |  0.00B

train/sample_000775/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_000775/board.png: downloading bytes:           |  0.00B

train/sample_000776/board.png: reconstructing file:   0%|          |  0.00B / 25.6kB

train/sample_000776/board.png: downloading bytes:           |  0.00B

train/sample_000777/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_000778/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_000777/board.png: downloading bytes:           |  0.00B

train/sample_000779/board.png: reconstructing file:   0%|          |  0.00B / 21.7kB

train/sample_000780/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_000778/board.png: downloading bytes:           |  0.00B

train/sample_000780/board.png: downloading bytes:           |  0.00B

train/sample_000779/board.png: downloading bytes:           |  0.00B

train/sample_000781/board.png: reconstructing file:   0%|          |  0.00B / 41.9kB

train/sample_000781/board.png: downloading bytes:           |  0.00B

train/sample_000782/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_000782/board.png: downloading bytes:           |  0.00B

train/sample_000783/board.png: reconstructing file:   0%|          |  0.00B / 42.5kB

train/sample_000784/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_000783/board.png: downloading bytes:           |  0.00B

train/sample_000784/board.png: downloading bytes:           |  0.00B

train/sample_000785/board.png: reconstructing file:   0%|          |  0.00B / 42.0kB

train/sample_000786/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_000789/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_000787/board.png: reconstructing file:   0%|          |  0.00B / 44.4kB

train/sample_000788/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_000785/board.png: downloading bytes:           |  0.00B

train/sample_000789/board.png: downloading bytes:           |  0.00B

train/sample_000786/board.png: downloading bytes:           |  0.00B

train/sample_000787/board.png: downloading bytes:           |  0.00B

train/sample_000788/board.png: downloading bytes:           |  0.00B

train/sample_000790/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_000790/board.png: downloading bytes:           |  0.00B

train/sample_000791/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_000791/board.png: downloading bytes:           |  0.00B

train/sample_000792/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_000792/board.png: downloading bytes:           |  0.00B

train/sample_000793/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

train/sample_000794/board.png: reconstructing file:   0%|          |  0.00B / 35.5kB

train/sample_000793/board.png: downloading bytes:           |  0.00B

train/sample_000794/board.png: downloading bytes:           |  0.00B

train/sample_000795/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

train/sample_000796/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_000797/board.png: reconstructing file:   0%|          |  0.00B / 17.1kB

train/sample_000798/board.png: reconstructing file:   0%|          |  0.00B / 41.1kB

train/sample_000795/board.png: downloading bytes:           |  0.00B

train/sample_000797/board.png: downloading bytes:           |  0.00B

train/sample_000798/board.png: downloading bytes:           |  0.00B

train/sample_000796/board.png: downloading bytes:           |  0.00B

train/sample_000799/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_000800/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_000801/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

train/sample_000799/board.png: downloading bytes:           |  0.00B

train/sample_000802/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_000800/board.png: downloading bytes:           |  0.00B

train/sample_000803/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_000801/board.png: downloading bytes:           |  0.00B

train/sample_000804/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_000805/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_000802/board.png: downloading bytes:           |  0.00B

train/sample_000803/board.png: downloading bytes:           |  0.00B

train/sample_000805/board.png: downloading bytes:           |  0.00B

train/sample_000804/board.png: downloading bytes:           |  0.00B

train/sample_000806/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_000806/board.png: downloading bytes:           |  0.00B

train/sample_000807/board.png: reconstructing file:   0%|          |  0.00B / 41.7kB

train/sample_000807/board.png: downloading bytes:           |  0.00B

train/sample_000808/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_000809/board.png: reconstructing file:   0%|          |  0.00B / 16.2kB

train/sample_000810/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_000808/board.png: downloading bytes:           |  0.00B

train/sample_000811/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_000809/board.png: downloading bytes:           |  0.00B

train/sample_000812/board.png: reconstructing file:   0%|          |  0.00B / 43.2kB

train/sample_000810/board.png: downloading bytes:           |  0.00B

train/sample_000811/board.png: downloading bytes:           |  0.00B

train/sample_000813/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_000812/board.png: downloading bytes:           |  0.00B

train/sample_000813/board.png: downloading bytes:           |  0.00B

train/sample_000814/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_000814/board.png: downloading bytes:           |  0.00B

train/sample_000815/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

train/sample_000815/board.png: downloading bytes:           |  0.00B

train/sample_000816/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_000817/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_000819/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_000818/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_000816/board.png: downloading bytes:           |  0.00B

train/sample_000817/board.png: downloading bytes:           |  0.00B

train/sample_000819/board.png: downloading bytes:           |  0.00B

train/sample_000818/board.png: downloading bytes:           |  0.00B

train/sample_000820/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_000822/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_000821/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_000820/board.png: downloading bytes:           |  0.00B

train/sample_000822/board.png: downloading bytes:           |  0.00B

train/sample_000821/board.png: downloading bytes:           |  0.00B

train/sample_000823/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

train/sample_000823/board.png: downloading bytes:           |  0.00B

train/sample_000824/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_000824/board.png: downloading bytes:           |  0.00B

train/sample_000826/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_000825/board.png: reconstructing file:   0%|          |  0.00B / 15.0kB

train/sample_000827/board.png: reconstructing file:   0%|          |  0.00B / 43.4kB

train/sample_000828/board.png: reconstructing file:   0%|          |  0.00B / 41.5kB

train/sample_000826/board.png: downloading bytes:           |  0.00B

train/sample_000825/board.png: downloading bytes:           |  0.00B

train/sample_000827/board.png: downloading bytes:           |  0.00B

train/sample_000828/board.png: downloading bytes:           |  0.00B

train/sample_000829/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_000830/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

train/sample_000829/board.png: downloading bytes:           |  0.00B

train/sample_000830/board.png: downloading bytes:           |  0.00B

train/sample_000831/board.png: reconstructing file:   0%|          |  0.00B / 41.0kB

train/sample_000831/board.png: downloading bytes:           |  0.00B

train/sample_000832/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

train/sample_000833/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_000832/board.png: downloading bytes:           |  0.00B

train/sample_000835/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_000834/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_000836/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

train/sample_000833/board.png: downloading bytes:           |  0.00B

train/sample_000835/board.png: downloading bytes:           |  0.00B

train/sample_000834/board.png: downloading bytes:           |  0.00B

train/sample_000836/board.png: downloading bytes:           |  0.00B

train/sample_000837/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

train/sample_000837/board.png: downloading bytes:           |  0.00B

train/sample_000838/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_000838/board.png: downloading bytes:           |  0.00B

train/sample_000839/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_000839/board.png: downloading bytes:           |  0.00B

train/sample_000840/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_000841/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_000840/board.png: downloading bytes:           |  0.00B

train/sample_000843/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_000841/board.png: downloading bytes:           |  0.00B

train/sample_000842/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_000843/board.png: downloading bytes:           |  0.00B

train/sample_000842/board.png: downloading bytes:           |  0.00B

train/sample_000844/board.png: reconstructing file:   0%|          |  0.00B / 17.7kB

train/sample_000844/board.png: downloading bytes:           |  0.00B

train/sample_000845/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_000845/board.png: downloading bytes:           |  0.00B

train/sample_000846/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

train/sample_000846/board.png: downloading bytes:           |  0.00B

train/sample_000847/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_000847/board.png: downloading bytes:           |  0.00B

train/sample_000848/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

train/sample_000849/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

train/sample_000848/board.png: downloading bytes:           |  0.00B

train/sample_000850/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_000849/board.png: downloading bytes:           |  0.00B

train/sample_000851/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_000850/board.png: downloading bytes:           |  0.00B

train/sample_000851/board.png: downloading bytes:           |  0.00B

train/sample_000852/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_000852/board.png: downloading bytes:           |  0.00B

train/sample_000853/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_000853/board.png: downloading bytes:           |  0.00B

train/sample_000854/board.png: reconstructing file:   0%|          |  0.00B / 38.2kB

train/sample_000854/board.png: downloading bytes:           |  0.00B

train/sample_000855/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_000855/board.png: downloading bytes:           |  0.00B

train/sample_000856/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_000857/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_000859/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

train/sample_000856/board.png: downloading bytes:           |  0.00B

train/sample_000857/board.png: downloading bytes:           |  0.00B

train/sample_000858/board.png: reconstructing file:   0%|          |  0.00B / 18.5kB

train/sample_000859/board.png: downloading bytes:           |  0.00B

train/sample_000858/board.png: downloading bytes:           |  0.00B

train/sample_000860/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_000860/board.png: downloading bytes:           |  0.00B

train/sample_000861/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_000862/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_000861/board.png: downloading bytes:           |  0.00B

train/sample_000862/board.png: downloading bytes:           |  0.00B

train/sample_000863/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_000863/board.png: downloading bytes:           |  0.00B

train/sample_000864/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_000864/board.png: downloading bytes:           |  0.00B

train/sample_000866/board.png: reconstructing file:   0%|          |  0.00B / 42.2kB

train/sample_000867/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_000865/board.png: reconstructing file:   0%|          |  0.00B / 13.0kB

train/sample_000868/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_000866/board.png: downloading bytes:           |  0.00B

train/sample_000867/board.png: downloading bytes:           |  0.00B

train/sample_000865/board.png: downloading bytes:           |  0.00B

train/sample_000868/board.png: downloading bytes:           |  0.00B

train/sample_000869/board.png: reconstructing file:   0%|          |  0.00B / 16.3kB

train/sample_000870/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_000870/board.png: downloading bytes:           |  0.00B

train/sample_000869/board.png: downloading bytes:           |  0.00B

train/sample_000871/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

train/sample_000871/board.png: downloading bytes:           |  0.00B

train/sample_000872/board.png: reconstructing file:   0%|          |  0.00B / 18.6kB

train/sample_000872/board.png: downloading bytes:           |  0.00B

train/sample_000874/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_000873/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_000873/board.png: downloading bytes:           |  0.00B

train/sample_000875/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_000874/board.png: downloading bytes:           |  0.00B

train/sample_000876/board.png: reconstructing file:   0%|          |  0.00B / 18.5kB

train/sample_000875/board.png: downloading bytes:           |  0.00B

train/sample_000876/board.png: downloading bytes:           |  0.00B

train/sample_000878/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_000877/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_000878/board.png: downloading bytes:           |  0.00B

train/sample_000877/board.png: downloading bytes:           |  0.00B

train/sample_000879/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_000879/board.png: downloading bytes:           |  0.00B

train/sample_000880/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_000880/board.png: downloading bytes:           |  0.00B

train/sample_000882/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_000883/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_000882/board.png: downloading bytes:           |  0.00B

train/sample_000881/board.png: reconstructing file:   0%|          |  0.00B / 21.1kB

train/sample_000885/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_000884/board.png: reconstructing file:   0%|          |  0.00B / 24.3kB

train/sample_000886/board.png: reconstructing file:   0%|          |  0.00B / 21.7kB

train/sample_000883/board.png: downloading bytes:           |  0.00B

train/sample_000884/board.png: downloading bytes:           |  0.00B

train/sample_000881/board.png: downloading bytes:           |  0.00B

train/sample_000886/board.png: downloading bytes:           |  0.00B

train/sample_000885/board.png: downloading bytes:           |  0.00B

train/sample_000887/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_000887/board.png: downloading bytes:           |  0.00B

train/sample_000888/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_000888/board.png: downloading bytes:           |  0.00B

train/sample_000889/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

train/sample_000890/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_000889/board.png: downloading bytes:           |  0.00B

train/sample_000891/board.png: reconstructing file:   0%|          |  0.00B / 16.7kB

train/sample_000890/board.png: downloading bytes:           |  0.00B

train/sample_000891/board.png: downloading bytes:           |  0.00B

train/sample_000892/board.png: reconstructing file:   0%|          |  0.00B / 18.6kB

train/sample_000893/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_000893/board.png: downloading bytes:           |  0.00B

train/sample_000892/board.png: downloading bytes:           |  0.00B

train/sample_000894/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_000894/board.png: downloading bytes:           |  0.00B

train/sample_000895/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_000895/board.png: downloading bytes:           |  0.00B

train/sample_000896/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_000896/board.png: downloading bytes:           |  0.00B

train/sample_000897/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_000897/board.png: downloading bytes:           |  0.00B

train/sample_000898/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_000898/board.png: downloading bytes:           |  0.00B

train/sample_000899/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_000899/board.png: downloading bytes:           |  0.00B

train/sample_000900/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_000901/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

train/sample_000902/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

train/sample_000901/board.png: downloading bytes:           |  0.00B

train/sample_000900/board.png: downloading bytes:           |  0.00B

train/sample_000902/board.png: downloading bytes:           |  0.00B

train/sample_000903/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_000903/board.png: downloading bytes:           |  0.00B

train/sample_000904/board.png: reconstructing file:   0%|          |  0.00B / 16.7kB

train/sample_000904/board.png: downloading bytes:           |  0.00B

train/sample_000905/board.png: reconstructing file:   0%|          |  0.00B / 12.8kB

train/sample_000905/board.png: downloading bytes:           |  0.00B

train/sample_000906/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

train/sample_000906/board.png: downloading bytes:           |  0.00B

train/sample_000908/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_000907/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_000909/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_000908/board.png: downloading bytes:           |  0.00B

train/sample_000910/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

train/sample_000907/board.png: downloading bytes:           |  0.00B

train/sample_000909/board.png: downloading bytes:           |  0.00B

train/sample_000910/board.png: downloading bytes:           |  0.00B

train/sample_000911/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_000911/board.png: downloading bytes:           |  0.00B

train/sample_000912/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_000912/board.png: downloading bytes:           |  0.00B

train/sample_000913/board.png: reconstructing file:   0%|          |  0.00B / 14.2kB

train/sample_000913/board.png: downloading bytes:           |  0.00B

train/sample_000914/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_000914/board.png: downloading bytes:           |  0.00B

train/sample_000915/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_000915/board.png: downloading bytes:           |  0.00B

train/sample_000916/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_000917/board.png: reconstructing file:   0%|          |  0.00B / 13.5kB

train/sample_000918/board.png: reconstructing file:   0%|          |  0.00B / 18.5kB

train/sample_000916/board.png: downloading bytes:           |  0.00B

train/sample_000917/board.png: downloading bytes:           |  0.00B

train/sample_000918/board.png: downloading bytes:           |  0.00B

train/sample_000919/board.png: reconstructing file:   0%|          |  0.00B / 18.9kB

train/sample_000919/board.png: downloading bytes:           |  0.00B

train/sample_000920/board.png: reconstructing file:   0%|          |  0.00B / 16.5kB

train/sample_000920/board.png: downloading bytes:           |  0.00B

train/sample_000921/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_000921/board.png: downloading bytes:           |  0.00B

train/sample_000922/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

train/sample_000922/board.png: downloading bytes:           |  0.00B

train/sample_000923/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_000923/board.png: downloading bytes:           |  0.00B

train/sample_000924/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_000925/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

train/sample_000924/board.png: downloading bytes:           |  0.00B

train/sample_000925/board.png: downloading bytes:           |  0.00B

train/sample_000926/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_000926/board.png: downloading bytes:           |  0.00B

train/sample_000927/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_000927/board.png: downloading bytes:           |  0.00B

train/sample_000928/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

train/sample_000928/board.png: downloading bytes:           |  0.00B

train/sample_000930/board.png: reconstructing file:   0%|          |  0.00B / 36.3kB

train/sample_000931/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_000929/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_000930/board.png: downloading bytes:           |  0.00B

train/sample_000931/board.png: downloading bytes:           |  0.00B

train/sample_000929/board.png: downloading bytes:           |  0.00B

train/sample_000932/board.png: reconstructing file:   0%|          |  0.00B / 15.3kB

train/sample_000932/board.png: downloading bytes:           |  0.00B

train/sample_000933/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_000934/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_000933/board.png: downloading bytes:           |  0.00B

train/sample_000934/board.png: downloading bytes:           |  0.00B

train/sample_000935/board.png: reconstructing file:   0%|          |  0.00B / 42.6kB

train/sample_000935/board.png: downloading bytes:           |  0.00B

train/sample_000936/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_000936/board.png: downloading bytes:           |  0.00B

train/sample_000937/board.png: reconstructing file:   0%|          |  0.00B / 17.0kB

train/sample_000937/board.png: downloading bytes:           |  0.00B

train/sample_000939/board.png: reconstructing file:   0%|          |  0.00B / 38.9kB

train/sample_000938/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_000938/board.png: downloading bytes:           |  0.00B

train/sample_000939/board.png: downloading bytes:           |  0.00B

train/sample_000940/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_000940/board.png: downloading bytes:           |  0.00B

train/sample_000941/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_000942/board.png: reconstructing file:   0%|          |  0.00B / 14.4kB

train/sample_000941/board.png: downloading bytes:           |  0.00B

train/sample_000942/board.png: downloading bytes:           |  0.00B

train/sample_000943/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_000943/board.png: downloading bytes:           |  0.00B

train/sample_000944/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_000945/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_000944/board.png: downloading bytes:           |  0.00B

train/sample_000945/board.png: downloading bytes:           |  0.00B

train/sample_000946/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_000947/board.png: reconstructing file:   0%|          |  0.00B / 15.9kB

train/sample_000946/board.png: downloading bytes:           |  0.00B

train/sample_000948/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_000947/board.png: downloading bytes:           |  0.00B

train/sample_000948/board.png: downloading bytes:           |  0.00B

train/sample_000949/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

train/sample_000949/board.png: downloading bytes:           |  0.00B

train/sample_000950/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

train/sample_000950/board.png: downloading bytes:           |  0.00B

train/sample_000951/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_000951/board.png: downloading bytes:           |  0.00B

train/sample_000952/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

train/sample_000952/board.png: downloading bytes:           |  0.00B

train/sample_000953/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_000954/board.png: reconstructing file:   0%|          |  0.00B / 20.2kB

train/sample_000953/board.png: downloading bytes:           |  0.00B

train/sample_000954/board.png: downloading bytes:           |  0.00B

train/sample_000955/board.png: reconstructing file:   0%|          |  0.00B / 14.2kB

train/sample_000955/board.png: downloading bytes:           |  0.00B

train/sample_000956/board.png: reconstructing file:   0%|          |  0.00B / 12.9kB

train/sample_000956/board.png: downloading bytes:           |  0.00B

train/sample_000957/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_000957/board.png: downloading bytes:           |  0.00B

train/sample_000958/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_000958/board.png: downloading bytes:           |  0.00B

train/sample_000959/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_000959/board.png: downloading bytes:           |  0.00B

train/sample_000960/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_000961/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_000960/board.png: downloading bytes:           |  0.00B

train/sample_000961/board.png: downloading bytes:           |  0.00B

train/sample_000962/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_000962/board.png: downloading bytes:           |  0.00B

train/sample_000963/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_000963/board.png: downloading bytes:           |  0.00B

train/sample_000965/board.png: reconstructing file:   0%|          |  0.00B / 14.3kB

train/sample_000964/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_000964/board.png: downloading bytes:           |  0.00B

train/sample_000965/board.png: downloading bytes:           |  0.00B

train/sample_000966/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_000966/board.png: downloading bytes:           |  0.00B

train/sample_000967/board.png: reconstructing file:   0%|          |  0.00B / 38.5kB

train/sample_000967/board.png: downloading bytes:           |  0.00B

train/sample_000968/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_000968/board.png: downloading bytes:           |  0.00B

train/sample_000969/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_000970/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

train/sample_000973/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_000972/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_000971/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

train/sample_000969/board.png: downloading bytes:           |  0.00B

train/sample_000974/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

train/sample_000970/board.png: downloading bytes:           |  0.00B

train/sample_000973/board.png: downloading bytes:           |  0.00B

train/sample_000971/board.png: downloading bytes:           |  0.00B

train/sample_000972/board.png: downloading bytes:           |  0.00B

train/sample_000974/board.png: downloading bytes:           |  0.00B

train/sample_000975/board.png: reconstructing file:   0%|          |  0.00B / 14.9kB

train/sample_000975/board.png: downloading bytes:           |  0.00B

train/sample_000976/board.png: reconstructing file:   0%|          |  0.00B / 42.6kB

train/sample_000976/board.png: downloading bytes:           |  0.00B

train/sample_000977/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_000977/board.png: downloading bytes:           |  0.00B

train/sample_000978/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_000978/board.png: downloading bytes:           |  0.00B

train/sample_000980/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

train/sample_000979/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_000980/board.png: downloading bytes:           |  0.00B

train/sample_000979/board.png: downloading bytes:           |  0.00B

train/sample_000981/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_000981/board.png: downloading bytes:           |  0.00B

train/sample_000982/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_000982/board.png: downloading bytes:           |  0.00B

train/sample_000983/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

train/sample_000983/board.png: downloading bytes:           |  0.00B

train/sample_000984/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

train/sample_000984/board.png: downloading bytes:           |  0.00B

train/sample_000985/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_000985/board.png: downloading bytes:           |  0.00B

train/sample_000986/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_000987/board.png: reconstructing file:   0%|          |  0.00B / 42.8kB

train/sample_000986/board.png: downloading bytes:           |  0.00B

train/sample_000988/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

train/sample_000987/board.png: downloading bytes:           |  0.00B

train/sample_000988/board.png: downloading bytes:           |  0.00B

train/sample_000989/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_000989/board.png: downloading bytes:           |  0.00B

train/sample_000990/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_000990/board.png: downloading bytes:           |  0.00B

train/sample_000991/board.png: reconstructing file:   0%|          |  0.00B / 43.8kB

train/sample_000991/board.png: downloading bytes:           |  0.00B

train/sample_000992/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_000992/board.png: downloading bytes:           |  0.00B

train/sample_000993/board.png: reconstructing file:   0%|          |  0.00B / 16.9kB

train/sample_000994/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_000993/board.png: downloading bytes:           |  0.00B

train/sample_000994/board.png: downloading bytes:           |  0.00B

train/sample_000995/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_000996/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_000995/board.png: downloading bytes:           |  0.00B

train/sample_000996/board.png: downloading bytes:           |  0.00B

train/sample_000997/board.png: reconstructing file:   0%|          |  0.00B / 19.8kB

train/sample_000997/board.png: downloading bytes:           |  0.00B

train/sample_000998/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

train/sample_000998/board.png: downloading bytes:           |  0.00B

train/sample_000999/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_000999/board.png: downloading bytes:           |  0.00B

train/sample_001000/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_001000/board.png: downloading bytes:           |  0.00B

train/sample_001001/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_001001/board.png: downloading bytes:           |  0.00B

train/sample_001002/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_001003/board.png: reconstructing file:   0%|          |  0.00B / 36.3kB

train/sample_001004/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_001005/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

train/sample_001002/board.png: downloading bytes:           |  0.00B

train/sample_001006/board.png: reconstructing file:   0%|          |  0.00B / 41.5kB

train/sample_001003/board.png: downloading bytes:           |  0.00B

train/sample_001005/board.png: downloading bytes:           |  0.00B

train/sample_001004/board.png: downloading bytes:           |  0.00B

train/sample_001006/board.png: downloading bytes:           |  0.00B

train/sample_001007/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_001007/board.png: downloading bytes:           |  0.00B

train/sample_001008/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_001008/board.png: downloading bytes:           |  0.00B

train/sample_001009/board.png: reconstructing file:   0%|          |  0.00B / 42.2kB

train/sample_001009/board.png: downloading bytes:           |  0.00B

train/sample_001010/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_001010/board.png: downloading bytes:           |  0.00B

train/sample_001012/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_001011/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_001013/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_001014/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_001011/board.png: downloading bytes:           |  0.00B

train/sample_001012/board.png: downloading bytes:           |  0.00B

train/sample_001013/board.png: downloading bytes:           |  0.00B

train/sample_001014/board.png: downloading bytes:           |  0.00B

train/sample_001015/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

train/sample_001015/board.png: downloading bytes:           |  0.00B

train/sample_001016/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

train/sample_001016/board.png: downloading bytes:           |  0.00B

train/sample_001017/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_001017/board.png: downloading bytes:           |  0.00B

train/sample_001018/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_001018/board.png: downloading bytes:           |  0.00B

train/sample_001019/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_001019/board.png: downloading bytes:           |  0.00B

train/sample_001020/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_001020/board.png: downloading bytes:           |  0.00B

train/sample_001021/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

train/sample_001021/board.png: downloading bytes:           |  0.00B

train/sample_001022/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_001022/board.png: downloading bytes:           |  0.00B

train/sample_001023/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

train/sample_001023/board.png: downloading bytes:           |  0.00B

train/sample_001024/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_001024/board.png: downloading bytes:           |  0.00B

train/sample_001025/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_001025/board.png: downloading bytes:           |  0.00B

train/sample_001026/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_001026/board.png: downloading bytes:           |  0.00B

train/sample_001027/board.png: reconstructing file:   0%|          |  0.00B / 18.9kB

train/sample_001028/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_001027/board.png: downloading bytes:           |  0.00B

train/sample_001028/board.png: downloading bytes:           |  0.00B

train/sample_001029/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_001029/board.png: downloading bytes:           |  0.00B

train/sample_001030/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_001030/board.png: downloading bytes:           |  0.00B

train/sample_001032/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_001031/board.png: reconstructing file:   0%|          |  0.00B / 16.4kB

train/sample_001031/board.png: downloading bytes:           |  0.00B

train/sample_001032/board.png: downloading bytes:           |  0.00B

train/sample_001033/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_001033/board.png: downloading bytes:           |  0.00B

train/sample_001036/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_001037/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_001034/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_001035/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_001039/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_001037/board.png: downloading bytes:           |  0.00B

train/sample_001036/board.png: downloading bytes:           |  0.00B

train/sample_001034/board.png: downloading bytes:           |  0.00B

train/sample_001035/board.png: downloading bytes:           |  0.00B

train/sample_001039/board.png: downloading bytes:           |  0.00B

train/sample_001042/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

train/sample_001042/board.png: downloading bytes:           |  0.00B

train/sample_001041/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_001041/board.png: downloading bytes:           |  0.00B

train/sample_001043/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_001043/board.png: downloading bytes:           |  0.00B

train/sample_001038/board.png: reconstructing file:   0%|          |  0.00B / 17.7kB

train/sample_001038/board.png: downloading bytes:           |  0.00B

train/sample_001045/board.png: reconstructing file:   0%|          |  0.00B / 42.5kB

train/sample_001045/board.png: downloading bytes:           |  0.00B

train/sample_001044/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_001044/board.png: downloading bytes:           |  0.00B

train/sample_001040/board.png: reconstructing file:   0%|          |  0.00B / 22.9kB

train/sample_001040/board.png: downloading bytes:           |  0.00B

train/sample_001046/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_001046/board.png: downloading bytes:           |  0.00B

train/sample_001047/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_001047/board.png: downloading bytes:           |  0.00B

train/sample_001048/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

train/sample_001048/board.png: downloading bytes:           |  0.00B

train/sample_001049/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_001049/board.png: downloading bytes:           |  0.00B

train/sample_001050/board.png: reconstructing file:   0%|          |  0.00B / 23.2kB

train/sample_001050/board.png: downloading bytes:           |  0.00B

train/sample_001051/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_001051/board.png: downloading bytes:           |  0.00B

train/sample_001052/board.png: reconstructing file:   0%|          |  0.00B / 43.2kB

train/sample_001052/board.png: downloading bytes:           |  0.00B

train/sample_001053/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_001053/board.png: downloading bytes:           |  0.00B

train/sample_001054/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_001054/board.png: downloading bytes:           |  0.00B

train/sample_001055/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_001055/board.png: downloading bytes:           |  0.00B

train/sample_001056/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

train/sample_001057/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_001056/board.png: downloading bytes:           |  0.00B

train/sample_001057/board.png: downloading bytes:           |  0.00B

train/sample_001058/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_001058/board.png: downloading bytes:           |  0.00B

train/sample_001059/board.png: reconstructing file:   0%|          |  0.00B / 17.7kB

train/sample_001059/board.png: downloading bytes:           |  0.00B

train/sample_001060/board.png: reconstructing file:   0%|          |  0.00B / 12.8kB

train/sample_001061/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_001060/board.png: downloading bytes:           |  0.00B

train/sample_001061/board.png: downloading bytes:           |  0.00B

train/sample_001062/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_001062/board.png: downloading bytes:           |  0.00B

train/sample_001063/board.png: reconstructing file:   0%|          |  0.00B / 15.3kB

train/sample_001063/board.png: downloading bytes:           |  0.00B

train/sample_001064/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_001065/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_001064/board.png: downloading bytes:           |  0.00B

train/sample_001066/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_001065/board.png: downloading bytes:           |  0.00B

train/sample_001066/board.png: downloading bytes:           |  0.00B

train/sample_001067/board.png: reconstructing file:   0%|          |  0.00B / 18.6kB

train/sample_001067/board.png: downloading bytes:           |  0.00B

train/sample_001068/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_001068/board.png: downloading bytes:           |  0.00B

train/sample_001069/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_001069/board.png: downloading bytes:           |  0.00B

train/sample_001070/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_001070/board.png: downloading bytes:           |  0.00B

train/sample_001071/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_001071/board.png: downloading bytes:           |  0.00B

train/sample_001072/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_001073/board.png: reconstructing file:   0%|          |  0.00B / 22.0kB

train/sample_001072/board.png: downloading bytes:           |  0.00B

train/sample_001073/board.png: downloading bytes:           |  0.00B

train/sample_001074/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_001074/board.png: downloading bytes:           |  0.00B

train/sample_001075/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_001077/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_001076/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_001078/board.png: reconstructing file:   0%|          |  0.00B / 37.2kB

train/sample_001075/board.png: downloading bytes:           |  0.00B

train/sample_001077/board.png: downloading bytes:           |  0.00B

train/sample_001076/board.png: downloading bytes:           |  0.00B

train/sample_001078/board.png: downloading bytes:           |  0.00B

train/sample_001079/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_001079/board.png: downloading bytes:           |  0.00B

train/sample_001080/board.png: reconstructing file:   0%|          |  0.00B / 20.2kB

train/sample_001081/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

train/sample_001080/board.png: downloading bytes:           |  0.00B

train/sample_001081/board.png: downloading bytes:           |  0.00B

train/sample_001082/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_001083/board.png: reconstructing file:   0%|          |  0.00B / 21.3kB

train/sample_001082/board.png: downloading bytes:           |  0.00B

train/sample_001085/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_001083/board.png: downloading bytes:           |  0.00B

train/sample_001084/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_001085/board.png: downloading bytes:           |  0.00B

train/sample_001084/board.png: downloading bytes:           |  0.00B

train/sample_001086/board.png: reconstructing file:   0%|          |  0.00B / 18.8kB

train/sample_001086/board.png: downloading bytes:           |  0.00B

train/sample_001088/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_001088/board.png: downloading bytes:           |  0.00B

train/sample_001089/board.png: reconstructing file:   0%|          |  0.00B / 17.7kB

train/sample_001087/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_001090/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_001091/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_001092/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_001089/board.png: downloading bytes:           |  0.00B

train/sample_001090/board.png: downloading bytes:           |  0.00B

train/sample_001093/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_001087/board.png: downloading bytes:           |  0.00B

train/sample_001091/board.png: downloading bytes:           |  0.00B

train/sample_001092/board.png: downloading bytes:           |  0.00B

train/sample_001093/board.png: downloading bytes:           |  0.00B

train/sample_001094/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_001094/board.png: downloading bytes:           |  0.00B

train/sample_001095/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_001095/board.png: downloading bytes:           |  0.00B

train/sample_001096/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_001096/board.png: downloading bytes:           |  0.00B

train/sample_001097/board.png: reconstructing file:   0%|          |  0.00B / 21.8kB

train/sample_001097/board.png: downloading bytes:           |  0.00B

train/sample_001098/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001098/board.png: downloading bytes:           |  0.00B

train/sample_001099/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_001099/board.png: downloading bytes:           |  0.00B

train/sample_001100/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_001100/board.png: downloading bytes:           |  0.00B

train/sample_001101/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_001101/board.png: downloading bytes:           |  0.00B

train/sample_001102/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_001102/board.png: downloading bytes:           |  0.00B

train/sample_001103/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_001104/board.png: reconstructing file:   0%|          |  0.00B / 42.6kB

train/sample_001103/board.png: downloading bytes:           |  0.00B

train/sample_001106/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

train/sample_001105/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_001104/board.png: downloading bytes:           |  0.00B

train/sample_001106/board.png: downloading bytes:           |  0.00B

train/sample_001107/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_001105/board.png: downloading bytes:           |  0.00B

train/sample_001108/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

train/sample_001109/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_001107/board.png: downloading bytes:           |  0.00B

train/sample_001109/board.png: downloading bytes:           |  0.00B

train/sample_001108/board.png: downloading bytes:           |  0.00B

train/sample_001110/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_001110/board.png: downloading bytes:           |  0.00B

train/sample_001111/board.png: reconstructing file:   0%|          |  0.00B / 18.2kB

train/sample_001112/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_001111/board.png: downloading bytes:           |  0.00B

train/sample_001112/board.png: downloading bytes:           |  0.00B

train/sample_001113/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_001114/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

train/sample_001113/board.png: downloading bytes:           |  0.00B

train/sample_001114/board.png: downloading bytes:           |  0.00B

train/sample_001115/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_001115/board.png: downloading bytes:           |  0.00B

train/sample_001116/board.png: reconstructing file:   0%|          |  0.00B / 41.4kB

train/sample_001116/board.png: downloading bytes:           |  0.00B

train/sample_001117/board.png: reconstructing file:   0%|          |  0.00B / 43.8kB

train/sample_001117/board.png: downloading bytes:           |  0.00B

train/sample_001118/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

train/sample_001118/board.png: downloading bytes:           |  0.00B

train/sample_001119/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

train/sample_001119/board.png: downloading bytes:           |  0.00B

train/sample_001120/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_001121/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_001120/board.png: downloading bytes:           |  0.00B

train/sample_001121/board.png: downloading bytes:           |  0.00B

train/sample_001122/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_001122/board.png: downloading bytes:           |  0.00B

train/sample_001123/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

train/sample_001123/board.png: downloading bytes:           |  0.00B

train/sample_001124/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_001125/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_001124/board.png: downloading bytes:           |  0.00B

train/sample_001125/board.png: downloading bytes:           |  0.00B

train/sample_001126/board.png: reconstructing file:   0%|          |  0.00B / 22.9kB

train/sample_001126/board.png: downloading bytes:           |  0.00B

train/sample_001127/board.png: reconstructing file:   0%|          |  0.00B / 40.8kB

train/sample_001127/board.png: downloading bytes:           |  0.00B

train/sample_001128/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_001128/board.png: downloading bytes:           |  0.00B

train/sample_001129/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_001129/board.png: downloading bytes:           |  0.00B

train/sample_001130/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_001130/board.png: downloading bytes:           |  0.00B

train/sample_001131/board.png: reconstructing file:   0%|          |  0.00B / 21.8kB

train/sample_001131/board.png: downloading bytes:           |  0.00B

train/sample_001132/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_001132/board.png: downloading bytes:           |  0.00B

train/sample_001133/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001133/board.png: downloading bytes:           |  0.00B

train/sample_001134/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_001134/board.png: downloading bytes:           |  0.00B

train/sample_001135/board.png: reconstructing file:   0%|          |  0.00B / 41.7kB

train/sample_001135/board.png: downloading bytes:           |  0.00B

train/sample_001136/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_001136/board.png: downloading bytes:           |  0.00B

train/sample_001137/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_001137/board.png: downloading bytes:           |  0.00B

train/sample_001138/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_001139/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_001139/board.png: downloading bytes:           |  0.00B

train/sample_001138/board.png: downloading bytes:           |  0.00B

train/sample_001141/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_001140/board.png: reconstructing file:   0%|          |  0.00B / 37.0kB

train/sample_001142/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_001141/board.png: downloading bytes:           |  0.00B

train/sample_001140/board.png: downloading bytes:           |  0.00B

train/sample_001142/board.png: downloading bytes:           |  0.00B

train/sample_001143/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_001143/board.png: downloading bytes:           |  0.00B

train/sample_001144/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_001145/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_001144/board.png: downloading bytes:           |  0.00B

train/sample_001145/board.png: downloading bytes:           |  0.00B

train/sample_001146/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_001147/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_001146/board.png: downloading bytes:           |  0.00B

train/sample_001149/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_001148/board.png: reconstructing file:   0%|          |  0.00B / 39.4kB

train/sample_001150/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_001147/board.png: downloading bytes:           |  0.00B

train/sample_001149/board.png: downloading bytes:           |  0.00B

train/sample_001150/board.png: downloading bytes:           |  0.00B

train/sample_001148/board.png: downloading bytes:           |  0.00B

train/sample_001151/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_001151/board.png: downloading bytes:           |  0.00B

train/sample_001152/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_001153/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_001152/board.png: downloading bytes:           |  0.00B

train/sample_001153/board.png: downloading bytes:           |  0.00B

train/sample_001154/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_001154/board.png: downloading bytes:           |  0.00B

train/sample_001156/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_001156/board.png: downloading bytes:           |  0.00B

train/sample_001155/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_001157/board.png: reconstructing file:   0%|          |  0.00B / 17.3kB

train/sample_001158/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_001155/board.png: downloading bytes:           |  0.00B

train/sample_001157/board.png: downloading bytes:           |  0.00B

train/sample_001158/board.png: downloading bytes:           |  0.00B

train/sample_001159/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_001159/board.png: downloading bytes:           |  0.00B

train/sample_001160/board.png: reconstructing file:   0%|          |  0.00B / 13.8kB

train/sample_001161/board.png: reconstructing file:   0%|          |  0.00B / 39.3kB

train/sample_001160/board.png: downloading bytes:           |  0.00B

train/sample_001161/board.png: downloading bytes:           |  0.00B

train/sample_001162/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_001162/board.png: downloading bytes:           |  0.00B

train/sample_001163/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_001164/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

train/sample_001165/board.png: reconstructing file:   0%|          |  0.00B / 19.5kB

train/sample_001163/board.png: downloading bytes:           |  0.00B

train/sample_001164/board.png: downloading bytes:           |  0.00B

train/sample_001166/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_001165/board.png: downloading bytes:           |  0.00B

train/sample_001166/board.png: downloading bytes:           |  0.00B

train/sample_001167/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_001167/board.png: downloading bytes:           |  0.00B

train/sample_001168/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_001168/board.png: downloading bytes:           |  0.00B

train/sample_001169/board.png: reconstructing file:   0%|          |  0.00B / 24.7kB

train/sample_001169/board.png: downloading bytes:           |  0.00B

train/sample_001170/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_001170/board.png: downloading bytes:           |  0.00B

train/sample_001171/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_001173/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_001172/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_001174/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_001171/board.png: downloading bytes:           |  0.00B

train/sample_001173/board.png: downloading bytes:           |  0.00B

train/sample_001174/board.png: downloading bytes:           |  0.00B

train/sample_001172/board.png: downloading bytes:           |  0.00B

train/sample_001176/board.png: reconstructing file:   0%|          |  0.00B / 37.2kB

train/sample_001177/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_001176/board.png: downloading bytes:           |  0.00B

train/sample_001175/board.png: reconstructing file:   0%|          |  0.00B / 15.8kB

train/sample_001175/board.png: downloading bytes:           |  0.00B

train/sample_001177/board.png: downloading bytes:           |  0.00B

train/sample_001178/board.png: reconstructing file:   0%|          |  0.00B / 22.6kB

train/sample_001178/board.png: downloading bytes:           |  0.00B

train/sample_001180/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_001179/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

train/sample_001181/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_001180/board.png: downloading bytes:           |  0.00B

train/sample_001179/board.png: downloading bytes:           |  0.00B

train/sample_001181/board.png: downloading bytes:           |  0.00B

train/sample_001182/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_001182/board.png: downloading bytes:           |  0.00B

train/sample_001183/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_001184/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_001183/board.png: downloading bytes:           |  0.00B

train/sample_001184/board.png: downloading bytes:           |  0.00B

train/sample_001185/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_001187/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_001186/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_001187/board.png: downloading bytes:           |  0.00B

train/sample_001185/board.png: downloading bytes:           |  0.00B

train/sample_001186/board.png: downloading bytes:           |  0.00B

train/sample_001188/board.png: reconstructing file:   0%|          |  0.00B / 17.3kB

train/sample_001188/board.png: downloading bytes:           |  0.00B

train/sample_001189/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

train/sample_001189/board.png: downloading bytes:           |  0.00B

train/sample_001190/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_001190/board.png: downloading bytes:           |  0.00B

train/sample_001191/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

train/sample_001191/board.png: downloading bytes:           |  0.00B

train/sample_001192/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_001193/board.png: reconstructing file:   0%|          |  0.00B / 23.3kB

train/sample_001194/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_001192/board.png: downloading bytes:           |  0.00B

train/sample_001193/board.png: downloading bytes:           |  0.00B

train/sample_001194/board.png: downloading bytes:           |  0.00B

train/sample_001195/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

train/sample_001195/board.png: downloading bytes:           |  0.00B

train/sample_001196/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_001196/board.png: downloading bytes:           |  0.00B

train/sample_001197/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_001197/board.png: downloading bytes:           |  0.00B

train/sample_001198/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_001198/board.png: downloading bytes:           |  0.00B

train/sample_001199/board.png: reconstructing file:   0%|          |  0.00B / 20.7kB

train/sample_001199/board.png: downloading bytes:           |  0.00B

train/sample_001200/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_001202/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_001201/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_001200/board.png: downloading bytes:           |  0.00B

train/sample_001201/board.png: downloading bytes:           |  0.00B

train/sample_001205/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_001204/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_001202/board.png: downloading bytes:           |  0.00B

train/sample_001203/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

train/sample_001204/board.png: downloading bytes:           |  0.00B

train/sample_001205/board.png: downloading bytes:           |  0.00B

train/sample_001203/board.png: downloading bytes:           |  0.00B

train/sample_001206/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_001206/board.png: downloading bytes:           |  0.00B

train/sample_001207/board.png: reconstructing file:   0%|          |  0.00B / 44.1kB

train/sample_001207/board.png: downloading bytes:           |  0.00B

train/sample_001208/board.png: reconstructing file:   0%|          |  0.00B / 15.7kB

train/sample_001208/board.png: downloading bytes:           |  0.00B

train/sample_001209/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_001209/board.png: downloading bytes:           |  0.00B

train/sample_001210/board.png: reconstructing file:   0%|          |  0.00B / 20.7kB

train/sample_001210/board.png: downloading bytes:           |  0.00B

train/sample_001211/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_001211/board.png: downloading bytes:           |  0.00B

train/sample_001212/board.png: reconstructing file:   0%|          |  0.00B / 12.8kB

train/sample_001212/board.png: downloading bytes:           |  0.00B

train/sample_001213/board.png: reconstructing file:   0%|          |  0.00B / 19.3kB

train/sample_001213/board.png: downloading bytes:           |  0.00B

train/sample_001214/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_001214/board.png: downloading bytes:           |  0.00B

train/sample_001215/board.png: reconstructing file:   0%|          |  0.00B / 21.3kB

train/sample_001215/board.png: downloading bytes:           |  0.00B

train/sample_001216/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

train/sample_001216/board.png: downloading bytes:           |  0.00B

train/sample_001217/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_001217/board.png: downloading bytes:           |  0.00B

train/sample_001218/board.png: reconstructing file:   0%|          |  0.00B / 39.3kB

train/sample_001218/board.png: downloading bytes:           |  0.00B

train/sample_001219/board.png: reconstructing file:   0%|          |  0.00B / 37.4kB

train/sample_001219/board.png: downloading bytes:           |  0.00B

train/sample_001220/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_001220/board.png: downloading bytes:           |  0.00B

train/sample_001221/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_001222/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_001222/board.png: downloading bytes:           |  0.00B

train/sample_001221/board.png: downloading bytes:           |  0.00B

train/sample_001223/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

train/sample_001224/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_001223/board.png: downloading bytes:           |  0.00B

train/sample_001225/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

train/sample_001224/board.png: downloading bytes:           |  0.00B

train/sample_001225/board.png: downloading bytes:           |  0.00B

train/sample_001226/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_001226/board.png: downloading bytes:           |  0.00B

train/sample_001227/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_001227/board.png: downloading bytes:           |  0.00B

train/sample_001228/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_001228/board.png: downloading bytes:           |  0.00B

train/sample_001229/board.png: reconstructing file:   0%|          |  0.00B / 41.5kB

train/sample_001229/board.png: downloading bytes:           |  0.00B

train/sample_001230/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

train/sample_001230/board.png: downloading bytes:           |  0.00B

train/sample_001231/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

train/sample_001231/board.png: downloading bytes:           |  0.00B

train/sample_001232/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_001232/board.png: downloading bytes:           |  0.00B

train/sample_001233/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_001233/board.png: downloading bytes:           |  0.00B

train/sample_001234/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

train/sample_001234/board.png: downloading bytes:           |  0.00B

train/sample_001235/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_001236/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_001235/board.png: downloading bytes:           |  0.00B

train/sample_001236/board.png: downloading bytes:           |  0.00B

train/sample_001237/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_001237/board.png: downloading bytes:           |  0.00B

train/sample_001238/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_001238/board.png: downloading bytes:           |  0.00B

train/sample_001239/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001239/board.png: downloading bytes:           |  0.00B

train/sample_001240/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

train/sample_001240/board.png: downloading bytes:           |  0.00B

train/sample_001241/board.png: reconstructing file:   0%|          |  0.00B / 21.0kB

train/sample_001241/board.png: downloading bytes:           |  0.00B

train/sample_001242/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_001242/board.png: downloading bytes:           |  0.00B

train/sample_001243/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

train/sample_001243/board.png: downloading bytes:           |  0.00B

train/sample_001244/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_001244/board.png: downloading bytes:           |  0.00B

train/sample_001245/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

train/sample_001245/board.png: downloading bytes:           |  0.00B

train/sample_001246/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_001246/board.png: downloading bytes:           |  0.00B

train/sample_001247/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

train/sample_001248/board.png: reconstructing file:   0%|          |  0.00B / 43.9kB

train/sample_001247/board.png: downloading bytes:           |  0.00B

train/sample_001248/board.png: downloading bytes:           |  0.00B

train/sample_001250/board.png: reconstructing file:   0%|          |  0.00B / 41.3kB

train/sample_001249/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_001251/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_001251/board.png: downloading bytes:           |  0.00B

train/sample_001250/board.png: downloading bytes:           |  0.00B

train/sample_001249/board.png: downloading bytes:           |  0.00B

train/sample_001252/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

train/sample_001252/board.png: downloading bytes:           |  0.00B

train/sample_001253/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_001253/board.png: downloading bytes:           |  0.00B

train/sample_001254/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_001254/board.png: downloading bytes:           |  0.00B

train/sample_001256/board.png: reconstructing file:   0%|          |  0.00B / 22.8kB

train/sample_001255/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

train/sample_001256/board.png: downloading bytes:           |  0.00B

train/sample_001255/board.png: downloading bytes:           |  0.00B

train/sample_001257/board.png: reconstructing file:   0%|          |  0.00B / 46.2kB

train/sample_001258/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_001257/board.png: downloading bytes:           |  0.00B

train/sample_001259/board.png: reconstructing file:   0%|          |  0.00B / 21.3kB

train/sample_001258/board.png: downloading bytes:           |  0.00B

train/sample_001259/board.png: downloading bytes:           |  0.00B

train/sample_001260/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_001260/board.png: downloading bytes:           |  0.00B

train/sample_001261/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_001261/board.png: downloading bytes:           |  0.00B

train/sample_001262/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_001262/board.png: downloading bytes:           |  0.00B

train/sample_001263/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_001263/board.png: downloading bytes:           |  0.00B

train/sample_001264/board.png: reconstructing file:   0%|          |  0.00B / 18.0kB

train/sample_001264/board.png: downloading bytes:           |  0.00B

train/sample_001265/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

train/sample_001265/board.png: downloading bytes:           |  0.00B

train/sample_001266/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_001267/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_001266/board.png: downloading bytes:           |  0.00B

train/sample_001269/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_001267/board.png: downloading bytes:           |  0.00B

train/sample_001268/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_001269/board.png: downloading bytes:           |  0.00B

train/sample_001268/board.png: downloading bytes:           |  0.00B

train/sample_001270/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_001270/board.png: downloading bytes:           |  0.00B

train/sample_001271/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_001271/board.png: downloading bytes:           |  0.00B

train/sample_001272/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_001272/board.png: downloading bytes:           |  0.00B

train/sample_001273/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_001274/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_001275/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_001273/board.png: downloading bytes:           |  0.00B

train/sample_001274/board.png: downloading bytes:           |  0.00B

train/sample_001276/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_001277/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

train/sample_001275/board.png: downloading bytes:           |  0.00B

train/sample_001278/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_001276/board.png: downloading bytes:           |  0.00B

train/sample_001277/board.png: downloading bytes:           |  0.00B

train/sample_001278/board.png: downloading bytes:           |  0.00B

train/sample_001279/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_001279/board.png: downloading bytes:           |  0.00B

train/sample_001280/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_001280/board.png: downloading bytes:           |  0.00B

train/sample_001283/board.png: reconstructing file:   0%|          |  0.00B / 12.8kB

train/sample_001281/board.png: reconstructing file:   0%|          |  0.00B / 16.3kB

train/sample_001282/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_001283/board.png: downloading bytes:           |  0.00B

train/sample_001284/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_001281/board.png: downloading bytes:           |  0.00B

train/sample_001282/board.png: downloading bytes:           |  0.00B

train/sample_001285/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_001284/board.png: downloading bytes:           |  0.00B

train/sample_001285/board.png: downloading bytes:           |  0.00B

train/sample_001286/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_001286/board.png: downloading bytes:           |  0.00B

train/sample_001287/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_001287/board.png: downloading bytes:           |  0.00B

train/sample_001288/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_001288/board.png: downloading bytes:           |  0.00B

train/sample_001289/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_001289/board.png: downloading bytes:           |  0.00B

train/sample_001290/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_001290/board.png: downloading bytes:           |  0.00B

train/sample_001291/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_001291/board.png: downloading bytes:           |  0.00B

train/sample_001292/board.png: reconstructing file:   0%|          |  0.00B / 43.3kB

train/sample_001292/board.png: downloading bytes:           |  0.00B

train/sample_001293/board.png: reconstructing file:   0%|          |  0.00B / 17.9kB

train/sample_001294/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_001293/board.png: downloading bytes:           |  0.00B

train/sample_001294/board.png: downloading bytes:           |  0.00B

train/sample_001295/board.png: reconstructing file:   0%|          |  0.00B / 15.0kB

train/sample_001295/board.png: downloading bytes:           |  0.00B

train/sample_001296/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

train/sample_001296/board.png: downloading bytes:           |  0.00B

train/sample_001297/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_001297/board.png: downloading bytes:           |  0.00B

train/sample_001298/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

train/sample_001298/board.png: downloading bytes:           |  0.00B

train/sample_001300/board.png: reconstructing file:   0%|          |  0.00B / 40.7kB

train/sample_001300/board.png: downloading bytes:           |  0.00B

train/sample_001301/board.png: reconstructing file:   0%|          |  0.00B / 23.2kB

train/sample_001299/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_001301/board.png: downloading bytes:           |  0.00B

train/sample_001299/board.png: downloading bytes:           |  0.00B

train/sample_001302/board.png: reconstructing file:   0%|          |  0.00B / 37.2kB

train/sample_001302/board.png: downloading bytes:           |  0.00B

train/sample_001303/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_001303/board.png: downloading bytes:           |  0.00B

train/sample_001304/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_001304/board.png: downloading bytes:           |  0.00B

train/sample_001305/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_001305/board.png: downloading bytes:           |  0.00B

train/sample_001306/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_001307/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_001306/board.png: downloading bytes:           |  0.00B

train/sample_001307/board.png: downloading bytes:           |  0.00B

train/sample_001309/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_001308/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_001309/board.png: downloading bytes:           |  0.00B

train/sample_001308/board.png: downloading bytes:           |  0.00B

train/sample_001310/board.png: reconstructing file:   0%|          |  0.00B / 17.9kB

train/sample_001310/board.png: downloading bytes:           |  0.00B

train/sample_001311/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_001311/board.png: downloading bytes:           |  0.00B

train/sample_001312/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_001312/board.png: downloading bytes:           |  0.00B

train/sample_001313/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_001313/board.png: downloading bytes:           |  0.00B

train/sample_001315/board.png: reconstructing file:   0%|          |  0.00B / 15.7kB

train/sample_001314/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_001315/board.png: downloading bytes:           |  0.00B

train/sample_001314/board.png: downloading bytes:           |  0.00B

train/sample_001317/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_001317/board.png: downloading bytes:           |  0.00B

train/sample_001316/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_001316/board.png: downloading bytes:           |  0.00B

train/sample_001318/board.png: reconstructing file:   0%|          |  0.00B / 19.8kB

train/sample_001318/board.png: downloading bytes:           |  0.00B

train/sample_001319/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_001319/board.png: downloading bytes:           |  0.00B

train/sample_001320/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_001320/board.png: downloading bytes:           |  0.00B

train/sample_001321/board.png: reconstructing file:   0%|          |  0.00B / 35.5kB

train/sample_001321/board.png: downloading bytes:           |  0.00B

train/sample_001322/board.png: reconstructing file:   0%|          |  0.00B / 41.2kB

train/sample_001322/board.png: downloading bytes:           |  0.00B

train/sample_001323/board.png: reconstructing file:   0%|          |  0.00B / 44.0kB

train/sample_001323/board.png: downloading bytes:           |  0.00B

train/sample_001324/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

train/sample_001324/board.png: downloading bytes:           |  0.00B

train/sample_001325/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_001325/board.png: downloading bytes:           |  0.00B

train/sample_001326/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_001326/board.png: downloading bytes:           |  0.00B

train/sample_001327/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_001327/board.png: downloading bytes:           |  0.00B

train/sample_001328/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

train/sample_001328/board.png: downloading bytes:           |  0.00B

train/sample_001329/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

train/sample_001329/board.png: downloading bytes:           |  0.00B

train/sample_001331/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_001331/board.png: downloading bytes:           |  0.00B

train/sample_001330/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_001330/board.png: downloading bytes:           |  0.00B

train/sample_001332/board.png: reconstructing file:   0%|          |  0.00B / 18.8kB

train/sample_001332/board.png: downloading bytes:           |  0.00B

train/sample_001333/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_001333/board.png: downloading bytes:           |  0.00B

train/sample_001334/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_001335/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

train/sample_001336/board.png: reconstructing file:   0%|          |  0.00B / 18.0kB

train/sample_001334/board.png: downloading bytes:           |  0.00B

train/sample_001335/board.png: downloading bytes:           |  0.00B

train/sample_001336/board.png: downloading bytes:           |  0.00B

train/sample_001338/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

train/sample_001337/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_001339/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

train/sample_001337/board.png: downloading bytes:           |  0.00B

train/sample_001338/board.png: downloading bytes:           |  0.00B

train/sample_001339/board.png: downloading bytes:           |  0.00B

train/sample_001340/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_001340/board.png: downloading bytes:           |  0.00B

train/sample_001341/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_001341/board.png: downloading bytes:           |  0.00B

train/sample_001342/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_001342/board.png: downloading bytes:           |  0.00B

train/sample_001343/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

train/sample_001344/board.png: reconstructing file:   0%|          |  0.00B / 22.6kB

train/sample_001343/board.png: downloading bytes:           |  0.00B

train/sample_001344/board.png: downloading bytes:           |  0.00B

train/sample_001345/board.png: reconstructing file:   0%|          |  0.00B / 19.9kB

train/sample_001345/board.png: downloading bytes:           |  0.00B

train/sample_001346/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_001346/board.png: downloading bytes:           |  0.00B

train/sample_001347/board.png: reconstructing file:   0%|          |  0.00B / 41.2kB

train/sample_001347/board.png: downloading bytes:           |  0.00B

train/sample_001348/board.png: reconstructing file:   0%|          |  0.00B / 21.8kB

train/sample_001348/board.png: downloading bytes:           |  0.00B

train/sample_001349/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

train/sample_001349/board.png: downloading bytes:           |  0.00B

train/sample_001350/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_001350/board.png: downloading bytes:           |  0.00B

train/sample_001351/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_001351/board.png: downloading bytes:           |  0.00B

train/sample_001352/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

train/sample_001352/board.png: downloading bytes:           |  0.00B

train/sample_001354/board.png: reconstructing file:   0%|          |  0.00B / 41.7kB

train/sample_001353/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_001354/board.png: downloading bytes:           |  0.00B

train/sample_001353/board.png: downloading bytes:           |  0.00B

train/sample_001355/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_001355/board.png: downloading bytes:           |  0.00B

train/sample_001356/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_001356/board.png: downloading bytes:           |  0.00B

train/sample_001357/board.png: reconstructing file:   0%|          |  0.00B / 16.7kB

train/sample_001357/board.png: downloading bytes:           |  0.00B

train/sample_001358/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_001358/board.png: downloading bytes:           |  0.00B

train/sample_001360/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

train/sample_001360/board.png: downloading bytes:           |  0.00B

train/sample_001359/board.png: reconstructing file:   0%|          |  0.00B / 11.0kB

train/sample_001361/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_001359/board.png: downloading bytes:           |  0.00B

train/sample_001362/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_001361/board.png: downloading bytes:           |  0.00B

train/sample_001362/board.png: downloading bytes:           |  0.00B

train/sample_001363/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_001363/board.png: downloading bytes:           |  0.00B

train/sample_001364/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_001364/board.png: downloading bytes:           |  0.00B

train/sample_001365/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_001365/board.png: downloading bytes:           |  0.00B

train/sample_001366/board.png: reconstructing file:   0%|          |  0.00B / 23.2kB

train/sample_001366/board.png: downloading bytes:           |  0.00B

train/sample_001367/board.png: reconstructing file:   0%|          |  0.00B / 13.1kB

train/sample_001367/board.png: downloading bytes:           |  0.00B

train/sample_001368/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_001368/board.png: downloading bytes:           |  0.00B

train/sample_001369/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_001370/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_001369/board.png: downloading bytes:           |  0.00B

train/sample_001370/board.png: downloading bytes:           |  0.00B

train/sample_001371/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_001371/board.png: downloading bytes:           |  0.00B

train/sample_001372/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

train/sample_001372/board.png: downloading bytes:           |  0.00B

train/sample_001373/board.png: reconstructing file:   0%|          |  0.00B / 37.2kB

train/sample_001373/board.png: downloading bytes:           |  0.00B

train/sample_001374/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_001374/board.png: downloading bytes:           |  0.00B

train/sample_001375/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_001377/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_001375/board.png: downloading bytes:           |  0.00B

train/sample_001377/board.png: downloading bytes:           |  0.00B

train/sample_001376/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_001378/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_001378/board.png: downloading bytes:           |  0.00B

train/sample_001376/board.png: downloading bytes:           |  0.00B

train/sample_001380/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_001379/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_001380/board.png: downloading bytes:           |  0.00B

train/sample_001379/board.png: downloading bytes:           |  0.00B

train/sample_001381/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_001381/board.png: downloading bytes:           |  0.00B

train/sample_001382/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

train/sample_001382/board.png: downloading bytes:           |  0.00B

train/sample_001383/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_001383/board.png: downloading bytes:           |  0.00B

train/sample_001384/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_001385/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_001384/board.png: downloading bytes:           |  0.00B

train/sample_001385/board.png: downloading bytes:           |  0.00B

train/sample_001386/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

train/sample_001386/board.png: downloading bytes:           |  0.00B

train/sample_001387/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

train/sample_001387/board.png: downloading bytes:           |  0.00B

train/sample_001388/board.png: reconstructing file:   0%|          |  0.00B / 22.9kB

train/sample_001388/board.png: downloading bytes:           |  0.00B

train/sample_001389/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_001389/board.png: downloading bytes:           |  0.00B

train/sample_001390/board.png: reconstructing file:   0%|          |  0.00B / 20.2kB

train/sample_001390/board.png: downloading bytes:           |  0.00B

train/sample_001391/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_001391/board.png: downloading bytes:           |  0.00B

train/sample_001392/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

train/sample_001392/board.png: downloading bytes:           |  0.00B

train/sample_001393/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_001393/board.png: downloading bytes:           |  0.00B

train/sample_001394/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_001394/board.png: downloading bytes:           |  0.00B

train/sample_001395/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

train/sample_001395/board.png: downloading bytes:           |  0.00B

train/sample_001396/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_001396/board.png: downloading bytes:           |  0.00B

train/sample_001397/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_001397/board.png: downloading bytes:           |  0.00B

train/sample_001398/board.png: reconstructing file:   0%|          |  0.00B / 37.4kB

train/sample_001398/board.png: downloading bytes:           |  0.00B

train/sample_001399/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_001399/board.png: downloading bytes:           |  0.00B

train/sample_001400/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_001400/board.png: downloading bytes:           |  0.00B

train/sample_001401/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_001401/board.png: downloading bytes:           |  0.00B

train/sample_001402/board.png: reconstructing file:   0%|          |  0.00B / 13.6kB

train/sample_001402/board.png: downloading bytes:           |  0.00B

train/sample_001403/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_001403/board.png: downloading bytes:           |  0.00B

train/sample_001405/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_001404/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_001405/board.png: downloading bytes:           |  0.00B

train/sample_001404/board.png: downloading bytes:           |  0.00B

train/sample_001406/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

train/sample_001407/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

train/sample_001406/board.png: downloading bytes:           |  0.00B

train/sample_001407/board.png: downloading bytes:           |  0.00B

train/sample_001408/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_001408/board.png: downloading bytes:           |  0.00B

train/sample_001409/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_001409/board.png: downloading bytes:           |  0.00B

train/sample_001410/board.png: reconstructing file:   0%|          |  0.00B / 16.0kB

train/sample_001410/board.png: downloading bytes:           |  0.00B

train/sample_001411/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_001411/board.png: downloading bytes:           |  0.00B

train/sample_001412/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_001412/board.png: downloading bytes:           |  0.00B

train/sample_001413/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_001413/board.png: downloading bytes:           |  0.00B

train/sample_001415/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_001415/board.png: downloading bytes:           |  0.00B

train/sample_001414/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

train/sample_001414/board.png: downloading bytes:           |  0.00B

train/sample_001416/board.png: reconstructing file:   0%|          |  0.00B / 12.8kB

train/sample_001416/board.png: downloading bytes:           |  0.00B

train/sample_001417/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

train/sample_001417/board.png: downloading bytes:           |  0.00B

train/sample_001418/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_001418/board.png: downloading bytes:           |  0.00B

train/sample_001419/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_001420/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_001421/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_001419/board.png: downloading bytes:           |  0.00B

train/sample_001420/board.png: downloading bytes:           |  0.00B

train/sample_001421/board.png: downloading bytes:           |  0.00B

train/sample_001422/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_001422/board.png: downloading bytes:           |  0.00B

train/sample_001423/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_001423/board.png: downloading bytes:           |  0.00B

train/sample_001424/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_001424/board.png: downloading bytes:           |  0.00B

train/sample_001425/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_001425/board.png: downloading bytes:           |  0.00B

train/sample_001426/board.png: reconstructing file:   0%|          |  0.00B / 41.2kB

train/sample_001427/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_001427/board.png: downloading bytes:           |  0.00B

train/sample_001426/board.png: downloading bytes:           |  0.00B

train/sample_001428/board.png: reconstructing file:   0%|          |  0.00B / 14.9kB

train/sample_001428/board.png: downloading bytes:           |  0.00B

train/sample_001429/board.png: reconstructing file:   0%|          |  0.00B / 41.6kB

train/sample_001430/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_001429/board.png: downloading bytes:           |  0.00B

train/sample_001430/board.png: downloading bytes:           |  0.00B

train/sample_001431/board.png: reconstructing file:   0%|          |  0.00B / 40.5kB

train/sample_001431/board.png: downloading bytes:           |  0.00B

train/sample_001432/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_001432/board.png: downloading bytes:           |  0.00B

train/sample_001433/board.png: reconstructing file:   0%|          |  0.00B / 45.3kB

train/sample_001433/board.png: downloading bytes:           |  0.00B

train/sample_001434/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_001435/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

train/sample_001436/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_001434/board.png: downloading bytes:           |  0.00B

train/sample_001435/board.png: downloading bytes:           |  0.00B

train/sample_001436/board.png: downloading bytes:           |  0.00B

train/sample_001437/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_001437/board.png: downloading bytes:           |  0.00B

train/sample_001438/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_001438/board.png: downloading bytes:           |  0.00B

train/sample_001439/board.png: reconstructing file:   0%|          |  0.00B / 15.7kB

train/sample_001439/board.png: downloading bytes:           |  0.00B

train/sample_001440/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_001440/board.png: downloading bytes:           |  0.00B

train/sample_001441/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_001441/board.png: downloading bytes:           |  0.00B

train/sample_001442/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_001442/board.png: downloading bytes:           |  0.00B

train/sample_001443/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_001443/board.png: downloading bytes:           |  0.00B

train/sample_001445/board.png: reconstructing file:   0%|          |  0.00B / 18.5kB

train/sample_001444/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_001445/board.png: downloading bytes:           |  0.00B

train/sample_001444/board.png: downloading bytes:           |  0.00B

train/sample_001446/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_001447/board.png: reconstructing file:   0%|          |  0.00B / 14.7kB

train/sample_001446/board.png: downloading bytes:           |  0.00B

train/sample_001447/board.png: downloading bytes:           |  0.00B

train/sample_001448/board.png: reconstructing file:   0%|          |  0.00B / 16.7kB

train/sample_001448/board.png: downloading bytes:           |  0.00B

train/sample_001449/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_001449/board.png: downloading bytes:           |  0.00B

train/sample_001450/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

train/sample_001450/board.png: downloading bytes:           |  0.00B

train/sample_001452/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_001454/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_001453/board.png: reconstructing file:   0%|          |  0.00B / 20.8kB

train/sample_001451/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_001452/board.png: downloading bytes:           |  0.00B

train/sample_001455/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

train/sample_001454/board.png: downloading bytes:           |  0.00B

train/sample_001451/board.png: downloading bytes:           |  0.00B

train/sample_001453/board.png: downloading bytes:           |  0.00B

train/sample_001455/board.png: downloading bytes:           |  0.00B

train/sample_001456/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

train/sample_001456/board.png: downloading bytes:           |  0.00B

train/sample_001457/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_001457/board.png: downloading bytes:           |  0.00B

train/sample_001458/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_001458/board.png: downloading bytes:           |  0.00B

train/sample_001459/board.png: reconstructing file:   0%|          |  0.00B / 22.6kB

train/sample_001459/board.png: downloading bytes:           |  0.00B

train/sample_001460/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

train/sample_001460/board.png: downloading bytes:           |  0.00B

train/sample_001461/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_001461/board.png: downloading bytes:           |  0.00B

train/sample_001462/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_001462/board.png: downloading bytes:           |  0.00B

train/sample_001463/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_001464/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_001463/board.png: downloading bytes:           |  0.00B

train/sample_001464/board.png: downloading bytes:           |  0.00B

train/sample_001465/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_001465/board.png: downloading bytes:           |  0.00B

train/sample_001467/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_001466/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_001467/board.png: downloading bytes:           |  0.00B

train/sample_001466/board.png: downloading bytes:           |  0.00B

train/sample_001468/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

train/sample_001468/board.png: downloading bytes:           |  0.00B

train/sample_001469/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_001470/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_001471/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_001469/board.png: downloading bytes:           |  0.00B

train/sample_001471/board.png: downloading bytes:           |  0.00B

train/sample_001470/board.png: downloading bytes:           |  0.00B

train/sample_001472/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_001472/board.png: downloading bytes:           |  0.00B

train/sample_001473/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_001474/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_001475/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

train/sample_001473/board.png: downloading bytes:           |  0.00B

train/sample_001474/board.png: downloading bytes:           |  0.00B

train/sample_001475/board.png: downloading bytes:           |  0.00B

train/sample_001476/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_001476/board.png: downloading bytes:           |  0.00B

train/sample_001477/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_001478/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_001477/board.png: downloading bytes:           |  0.00B

train/sample_001478/board.png: downloading bytes:           |  0.00B

train/sample_001479/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_001479/board.png: downloading bytes:           |  0.00B

train/sample_001480/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_001480/board.png: downloading bytes:           |  0.00B

train/sample_001481/board.png: reconstructing file:   0%|          |  0.00B / 38.6kB

train/sample_001481/board.png: downloading bytes:           |  0.00B

train/sample_001482/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_001483/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_001483/board.png: downloading bytes:           |  0.00B

train/sample_001482/board.png: downloading bytes:           |  0.00B

train/sample_001484/board.png: reconstructing file:   0%|          |  0.00B / 14.0kB

train/sample_001484/board.png: downloading bytes:           |  0.00B

train/sample_001486/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_001485/board.png: reconstructing file:   0%|          |  0.00B / 13.4kB

train/sample_001485/board.png: downloading bytes:           |  0.00B

train/sample_001486/board.png: downloading bytes:           |  0.00B

train/sample_001487/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_001487/board.png: downloading bytes:           |  0.00B

train/sample_001488/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_001488/board.png: downloading bytes:           |  0.00B

train/sample_001489/board.png: reconstructing file:   0%|          |  0.00B / 39.8kB

train/sample_001489/board.png: downloading bytes:           |  0.00B

train/sample_001490/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

train/sample_001490/board.png: downloading bytes:           |  0.00B

train/sample_001491/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_001491/board.png: downloading bytes:           |  0.00B

train/sample_001492/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_001492/board.png: downloading bytes:           |  0.00B

train/sample_001493/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_001494/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_001493/board.png: downloading bytes:           |  0.00B

train/sample_001495/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_001494/board.png: downloading bytes:           |  0.00B

train/sample_001495/board.png: downloading bytes:           |  0.00B

train/sample_001496/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_001496/board.png: downloading bytes:           |  0.00B

train/sample_001497/board.png: reconstructing file:   0%|          |  0.00B / 13.7kB

train/sample_001497/board.png: downloading bytes:           |  0.00B

train/sample_001498/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_001498/board.png: downloading bytes:           |  0.00B

train/sample_001499/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_001499/board.png: downloading bytes:           |  0.00B

train/sample_001500/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_001500/board.png: downloading bytes:           |  0.00B

train/sample_001501/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_001501/board.png: downloading bytes:           |  0.00B

train/sample_001502/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_001502/board.png: downloading bytes:           |  0.00B

train/sample_001503/board.png: reconstructing file:   0%|          |  0.00B / 19.3kB

train/sample_001503/board.png: downloading bytes:           |  0.00B

train/sample_001504/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_001504/board.png: downloading bytes:           |  0.00B

train/sample_001505/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_001505/board.png: downloading bytes:           |  0.00B

train/sample_001506/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_001506/board.png: downloading bytes:           |  0.00B

train/sample_001507/board.png: reconstructing file:   0%|          |  0.00B / 24.7kB

train/sample_001508/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_001507/board.png: downloading bytes:           |  0.00B

train/sample_001509/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

train/sample_001510/board.png: reconstructing file:   0%|          |  0.00B / 22.3kB

train/sample_001508/board.png: downloading bytes:           |  0.00B

train/sample_001510/board.png: downloading bytes:           |  0.00B

train/sample_001509/board.png: downloading bytes:           |  0.00B

train/sample_001511/board.png: reconstructing file:   0%|          |  0.00B / 16.8kB

train/sample_001511/board.png: downloading bytes:           |  0.00B

train/sample_001512/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_001512/board.png: downloading bytes:           |  0.00B

train/sample_001513/board.png: reconstructing file:   0%|          |  0.00B / 13.8kB

train/sample_001513/board.png: downloading bytes:           |  0.00B

train/sample_001514/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

train/sample_001514/board.png: downloading bytes:           |  0.00B

train/sample_001515/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_001515/board.png: downloading bytes:           |  0.00B

train/sample_001516/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_001517/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_001518/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_001516/board.png: downloading bytes:           |  0.00B

train/sample_001518/board.png: downloading bytes:           |  0.00B

train/sample_001517/board.png: downloading bytes:           |  0.00B

train/sample_001520/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

train/sample_001519/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_001520/board.png: downloading bytes:           |  0.00B

train/sample_001519/board.png: downloading bytes:           |  0.00B

train/sample_001521/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_001521/board.png: downloading bytes:           |  0.00B

train/sample_001522/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_001522/board.png: downloading bytes:           |  0.00B

train/sample_001523/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_001523/board.png: downloading bytes:           |  0.00B

train/sample_001524/board.png: reconstructing file:   0%|          |  0.00B / 20.8kB

train/sample_001524/board.png: downloading bytes:           |  0.00B

train/sample_001525/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_001525/board.png: downloading bytes:           |  0.00B

train/sample_001526/board.png: reconstructing file:   0%|          |  0.00B / 14.2kB

train/sample_001526/board.png: downloading bytes:           |  0.00B

train/sample_001527/board.png: reconstructing file:   0%|          |  0.00B / 15.0kB

train/sample_001528/board.png: reconstructing file:   0%|          |  0.00B / 19.5kB

train/sample_001527/board.png: downloading bytes:           |  0.00B

train/sample_001528/board.png: downloading bytes:           |  0.00B

train/sample_001529/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_001529/board.png: downloading bytes:           |  0.00B

train/sample_001530/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

train/sample_001530/board.png: downloading bytes:           |  0.00B

train/sample_001531/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_001531/board.png: downloading bytes:           |  0.00B

train/sample_001532/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_001532/board.png: downloading bytes:           |  0.00B

train/sample_001533/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_001533/board.png: downloading bytes:           |  0.00B

train/sample_001534/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_001534/board.png: downloading bytes:           |  0.00B

train/sample_001535/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_001535/board.png: downloading bytes:           |  0.00B

train/sample_001536/board.png: reconstructing file:   0%|          |  0.00B / 19.8kB

train/sample_001536/board.png: downloading bytes:           |  0.00B

train/sample_001537/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_001537/board.png: downloading bytes:           |  0.00B

train/sample_001538/board.png: reconstructing file:   0%|          |  0.00B / 24.7kB

train/sample_001538/board.png: downloading bytes:           |  0.00B

train/sample_001539/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_001539/board.png: downloading bytes:           |  0.00B

train/sample_001540/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_001540/board.png: downloading bytes:           |  0.00B

train/sample_001541/board.png: reconstructing file:   0%|          |  0.00B / 16.2kB

train/sample_001543/board.png: reconstructing file:   0%|          |  0.00B / 40.3kB

train/sample_001542/board.png: reconstructing file:   0%|          |  0.00B / 38.6kB

train/sample_001544/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_001541/board.png: downloading bytes:           |  0.00B

train/sample_001543/board.png: downloading bytes:           |  0.00B

train/sample_001542/board.png: downloading bytes:           |  0.00B

train/sample_001544/board.png: downloading bytes:           |  0.00B

train/sample_001545/board.png: reconstructing file:   0%|          |  0.00B / 40.5kB

train/sample_001546/board.png: reconstructing file:   0%|          |  0.00B / 35.5kB

train/sample_001545/board.png: downloading bytes:           |  0.00B

train/sample_001546/board.png: downloading bytes:           |  0.00B

train/sample_001547/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_001548/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_001547/board.png: downloading bytes:           |  0.00B

train/sample_001548/board.png: downloading bytes:           |  0.00B

train/sample_001549/board.png: reconstructing file:   0%|          |  0.00B / 38.0kB

train/sample_001549/board.png: downloading bytes:           |  0.00B

train/sample_001551/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_001550/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_001551/board.png: downloading bytes:           |  0.00B

train/sample_001550/board.png: downloading bytes:           |  0.00B

train/sample_001552/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_001552/board.png: downloading bytes:           |  0.00B

train/sample_001553/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_001553/board.png: downloading bytes:           |  0.00B

train/sample_001554/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_001554/board.png: downloading bytes:           |  0.00B

train/sample_001555/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_001555/board.png: downloading bytes:           |  0.00B

train/sample_001556/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_001556/board.png: downloading bytes:           |  0.00B

train/sample_001558/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_001557/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_001557/board.png: downloading bytes:           |  0.00B

train/sample_001558/board.png: downloading bytes:           |  0.00B

train/sample_001560/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_001559/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_001560/board.png: downloading bytes:           |  0.00B

train/sample_001559/board.png: downloading bytes:           |  0.00B

train/sample_001561/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_001562/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_001561/board.png: downloading bytes:           |  0.00B

train/sample_001562/board.png: downloading bytes:           |  0.00B

train/sample_001564/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_001564/board.png: downloading bytes:           |  0.00B

train/sample_001565/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_001563/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_001565/board.png: downloading bytes:           |  0.00B

train/sample_001568/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

train/sample_001566/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_001567/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_001563/board.png: downloading bytes:           |  0.00B

train/sample_001568/board.png: downloading bytes:           |  0.00B

train/sample_001566/board.png: downloading bytes:           |  0.00B

train/sample_001567/board.png: downloading bytes:           |  0.00B

train/sample_001569/board.png: reconstructing file:   0%|          |  0.00B / 14.3kB

train/sample_001569/board.png: downloading bytes:           |  0.00B

train/sample_001570/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_001570/board.png: downloading bytes:           |  0.00B

train/sample_001571/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_001571/board.png: downloading bytes:           |  0.00B

train/sample_001572/board.png: reconstructing file:   0%|          |  0.00B / 38.0kB

train/sample_001573/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_001572/board.png: downloading bytes:           |  0.00B

train/sample_001574/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_001573/board.png: downloading bytes:           |  0.00B

train/sample_001574/board.png: downloading bytes:           |  0.00B

train/sample_001575/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_001575/board.png: downloading bytes:           |  0.00B

train/sample_001576/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

train/sample_001576/board.png: downloading bytes:           |  0.00B

train/sample_001577/board.png: reconstructing file:   0%|          |  0.00B / 38.2kB

train/sample_001577/board.png: downloading bytes:           |  0.00B

train/sample_001578/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_001578/board.png: downloading bytes:           |  0.00B

train/sample_001579/board.png: reconstructing file:   0%|          |  0.00B / 24.5kB

train/sample_001580/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_001579/board.png: downloading bytes:           |  0.00B

train/sample_001580/board.png: downloading bytes:           |  0.00B

train/sample_001581/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

train/sample_001581/board.png: downloading bytes:           |  0.00B

train/sample_001582/board.png: reconstructing file:   0%|          |  0.00B / 21.1kB

train/sample_001582/board.png: downloading bytes:           |  0.00B

train/sample_001583/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_001583/board.png: downloading bytes:           |  0.00B

train/sample_001584/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_001584/board.png: downloading bytes:           |  0.00B

train/sample_001585/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001585/board.png: downloading bytes:           |  0.00B

train/sample_001586/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

train/sample_001587/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

train/sample_001586/board.png: downloading bytes:           |  0.00B

train/sample_001587/board.png: downloading bytes:           |  0.00B

train/sample_001589/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_001588/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

train/sample_001589/board.png: downloading bytes:           |  0.00B

train/sample_001590/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_001591/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_001588/board.png: downloading bytes:           |  0.00B

train/sample_001591/board.png: downloading bytes:           |  0.00B

train/sample_001590/board.png: downloading bytes:           |  0.00B

train/sample_001592/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_001592/board.png: downloading bytes:           |  0.00B

train/sample_001593/board.png: reconstructing file:   0%|          |  0.00B / 43.1kB

train/sample_001593/board.png: downloading bytes:           |  0.00B

train/sample_001594/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_001594/board.png: downloading bytes:           |  0.00B

train/sample_001595/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_001595/board.png: downloading bytes:           |  0.00B

train/sample_001596/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_001596/board.png: downloading bytes:           |  0.00B

train/sample_001597/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_001597/board.png: downloading bytes:           |  0.00B

train/sample_001598/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_001598/board.png: downloading bytes:           |  0.00B

train/sample_001599/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

train/sample_001599/board.png: downloading bytes:           |  0.00B

train/sample_001600/board.png: reconstructing file:   0%|          |  0.00B / 15.8kB

train/sample_001600/board.png: downloading bytes:           |  0.00B

train/sample_001601/board.png: reconstructing file:   0%|          |  0.00B / 22.6kB

train/sample_001601/board.png: downloading bytes:           |  0.00B

train/sample_001602/board.png: reconstructing file:   0%|          |  0.00B / 40.9kB

train/sample_001602/board.png: downloading bytes:           |  0.00B

train/sample_001604/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_001603/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_001604/board.png: downloading bytes:           |  0.00B

train/sample_001603/board.png: downloading bytes:           |  0.00B

train/sample_001605/board.png: reconstructing file:   0%|          |  0.00B / 35.5kB

train/sample_001605/board.png: downloading bytes:           |  0.00B

train/sample_001606/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_001606/board.png: downloading bytes:           |  0.00B

train/sample_001607/board.png: reconstructing file:   0%|          |  0.00B / 19.3kB

train/sample_001607/board.png: downloading bytes:           |  0.00B

train/sample_001608/board.png: reconstructing file:   0%|          |  0.00B / 19.8kB

train/sample_001608/board.png: downloading bytes:           |  0.00B

train/sample_001609/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_001609/board.png: downloading bytes:           |  0.00B

train/sample_001610/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_001610/board.png: downloading bytes:           |  0.00B

train/sample_001611/board.png: reconstructing file:   0%|          |  0.00B / 43.3kB

train/sample_001611/board.png: downloading bytes:           |  0.00B

train/sample_001612/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_001613/board.png: reconstructing file:   0%|          |  0.00B / 24.7kB

train/sample_001612/board.png: downloading bytes:           |  0.00B

train/sample_001613/board.png: downloading bytes:           |  0.00B

train/sample_001614/board.png: reconstructing file:   0%|          |  0.00B / 13.8kB

train/sample_001614/board.png: downloading bytes:           |  0.00B

train/sample_001615/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_001615/board.png: downloading bytes:           |  0.00B

train/sample_001616/board.png: reconstructing file:   0%|          |  0.00B / 16.2kB

train/sample_001616/board.png: downloading bytes:           |  0.00B

train/sample_001617/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_001617/board.png: downloading bytes:           |  0.00B

train/sample_001618/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_001618/board.png: downloading bytes:           |  0.00B

train/sample_001619/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_001619/board.png: downloading bytes:           |  0.00B

train/sample_001620/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

train/sample_001620/board.png: downloading bytes:           |  0.00B

train/sample_001621/board.png: reconstructing file:   0%|          |  0.00B / 41.5kB

train/sample_001622/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

train/sample_001623/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

train/sample_001621/board.png: downloading bytes:           |  0.00B

train/sample_001622/board.png: downloading bytes:           |  0.00B

train/sample_001623/board.png: downloading bytes:           |  0.00B

train/sample_001624/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_001624/board.png: downloading bytes:           |  0.00B

train/sample_001625/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

train/sample_001625/board.png: downloading bytes:           |  0.00B

train/sample_001626/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_001627/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_001626/board.png: downloading bytes:           |  0.00B

train/sample_001627/board.png: downloading bytes:           |  0.00B

train/sample_001628/board.png: reconstructing file:   0%|          |  0.00B / 21.4kB

train/sample_001629/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

train/sample_001630/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_001628/board.png: downloading bytes:           |  0.00B

train/sample_001629/board.png: downloading bytes:           |  0.00B

train/sample_001630/board.png: downloading bytes:           |  0.00B

train/sample_001631/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_001631/board.png: downloading bytes:           |  0.00B

train/sample_001632/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_001632/board.png: downloading bytes:           |  0.00B

train/sample_001633/board.png: reconstructing file:   0%|          |  0.00B / 42.5kB

train/sample_001633/board.png: downloading bytes:           |  0.00B

train/sample_001635/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_001634/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_001635/board.png: downloading bytes:           |  0.00B

train/sample_001637/board.png: reconstructing file:   0%|          |  0.00B / 13.8kB

train/sample_001636/board.png: reconstructing file:   0%|          |  0.00B / 16.5kB

train/sample_001634/board.png: downloading bytes:           |  0.00B

train/sample_001637/board.png: downloading bytes:           |  0.00B

train/sample_001636/board.png: downloading bytes:           |  0.00B

train/sample_001638/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_001638/board.png: downloading bytes:           |  0.00B

train/sample_001639/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_001640/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_001639/board.png: downloading bytes:           |  0.00B

train/sample_001640/board.png: downloading bytes:           |  0.00B

train/sample_001641/board.png: reconstructing file:   0%|          |  0.00B / 38.6kB

train/sample_001641/board.png: downloading bytes:           |  0.00B

train/sample_001642/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_001642/board.png: downloading bytes:           |  0.00B

train/sample_001643/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_001643/board.png: downloading bytes:           |  0.00B

train/sample_001644/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_001645/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_001645/board.png: downloading bytes:           |  0.00B

train/sample_001644/board.png: downloading bytes:           |  0.00B

train/sample_001646/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

train/sample_001646/board.png: downloading bytes:           |  0.00B

train/sample_001647/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001647/board.png: downloading bytes:           |  0.00B

train/sample_001648/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_001648/board.png: downloading bytes:           |  0.00B

train/sample_001650/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_001653/board.png: reconstructing file:   0%|          |  0.00B / 37.4kB

train/sample_001651/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_001650/board.png: downloading bytes:           |  0.00B

train/sample_001652/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

train/sample_001649/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_001653/board.png: downloading bytes:           |  0.00B

train/sample_001651/board.png: downloading bytes:           |  0.00B

train/sample_001649/board.png: downloading bytes:           |  0.00B

train/sample_001652/board.png: downloading bytes:           |  0.00B

train/sample_001654/board.png: reconstructing file:   0%|          |  0.00B / 16.9kB

train/sample_001654/board.png: downloading bytes:           |  0.00B

train/sample_001655/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_001655/board.png: downloading bytes:           |  0.00B

train/sample_001656/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001656/board.png: downloading bytes:           |  0.00B

train/sample_001657/board.png: reconstructing file:   0%|          |  0.00B / 38.9kB

train/sample_001657/board.png: downloading bytes:           |  0.00B

train/sample_001658/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_001658/board.png: downloading bytes:           |  0.00B

train/sample_001659/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_001659/board.png: downloading bytes:           |  0.00B

train/sample_001660/board.png: reconstructing file:   0%|          |  0.00B / 20.5kB

train/sample_001660/board.png: downloading bytes:           |  0.00B

train/sample_001661/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_001661/board.png: downloading bytes:           |  0.00B

train/sample_001662/board.png: reconstructing file:   0%|          |  0.00B / 35.9kB

train/sample_001662/board.png: downloading bytes:           |  0.00B

train/sample_001663/board.png: reconstructing file:   0%|          |  0.00B / 14.4kB

train/sample_001663/board.png: downloading bytes:           |  0.00B

train/sample_001664/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_001664/board.png: downloading bytes:           |  0.00B

train/sample_001666/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_001665/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_001665/board.png: downloading bytes:           |  0.00B

train/sample_001666/board.png: downloading bytes:           |  0.00B

train/sample_001667/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_001669/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_001668/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_001667/board.png: downloading bytes:           |  0.00B

train/sample_001669/board.png: downloading bytes:           |  0.00B

train/sample_001670/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_001668/board.png: downloading bytes:           |  0.00B

train/sample_001671/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_001670/board.png: downloading bytes:           |  0.00B

train/sample_001671/board.png: downloading bytes:           |  0.00B

train/sample_001672/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_001673/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

train/sample_001672/board.png: downloading bytes:           |  0.00B

train/sample_001673/board.png: downloading bytes:           |  0.00B

train/sample_001674/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_001674/board.png: downloading bytes:           |  0.00B

train/sample_001675/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001675/board.png: downloading bytes:           |  0.00B

train/sample_001676/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_001676/board.png: downloading bytes:           |  0.00B

train/sample_001679/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_001678/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_001677/board.png: reconstructing file:   0%|          |  0.00B / 17.0kB

train/sample_001679/board.png: downloading bytes:           |  0.00B

train/sample_001678/board.png: downloading bytes:           |  0.00B

train/sample_001677/board.png: downloading bytes:           |  0.00B

train/sample_001680/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_001680/board.png: downloading bytes:           |  0.00B

train/sample_001681/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

train/sample_001682/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_001683/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_001681/board.png: downloading bytes:           |  0.00B

train/sample_001684/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

train/sample_001682/board.png: downloading bytes:           |  0.00B

train/sample_001685/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

train/sample_001683/board.png: downloading bytes:           |  0.00B

train/sample_001684/board.png: downloading bytes:           |  0.00B

train/sample_001685/board.png: downloading bytes:           |  0.00B

train/sample_001686/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_001686/board.png: downloading bytes:           |  0.00B

train/sample_001687/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_001687/board.png: downloading bytes:           |  0.00B

train/sample_001689/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_001688/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_001691/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_001690/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_001688/board.png: downloading bytes:           |  0.00B

train/sample_001692/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

train/sample_001690/board.png: downloading bytes:           |  0.00B

train/sample_001691/board.png: downloading bytes:           |  0.00B

train/sample_001689/board.png: downloading bytes:           |  0.00B

train/sample_001693/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_001692/board.png: downloading bytes:           |  0.00B

train/sample_001693/board.png: downloading bytes:           |  0.00B

train/sample_001695/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_001695/board.png: downloading bytes:           |  0.00B

train/sample_001694/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_001694/board.png: downloading bytes:           |  0.00B

train/sample_001696/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_001696/board.png: downloading bytes:           |  0.00B

train/sample_001698/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_001697/board.png: reconstructing file:   0%|          |  0.00B / 24.3kB

train/sample_001697/board.png: downloading bytes:           |  0.00B

train/sample_001698/board.png: downloading bytes:           |  0.00B

train/sample_001699/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_001699/board.png: downloading bytes:           |  0.00B

train/sample_001700/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_001700/board.png: downloading bytes:           |  0.00B

train/sample_001701/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_001701/board.png: downloading bytes:           |  0.00B

train/sample_001702/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

train/sample_001703/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_001702/board.png: downloading bytes:           |  0.00B

train/sample_001703/board.png: downloading bytes:           |  0.00B

train/sample_001704/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_001704/board.png: downloading bytes:           |  0.00B

train/sample_001705/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_001706/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_001705/board.png: downloading bytes:           |  0.00B

train/sample_001706/board.png: downloading bytes:           |  0.00B

train/sample_001708/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_001710/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_001709/board.png: reconstructing file:   0%|          |  0.00B / 12.8kB

train/sample_001711/board.png: reconstructing file:   0%|          |  0.00B / 12.9kB

train/sample_001707/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_001710/board.png: downloading bytes:           |  0.00B

train/sample_001708/board.png: downloading bytes:           |  0.00B

train/sample_001709/board.png: downloading bytes:           |  0.00B

train/sample_001711/board.png: downloading bytes:           |  0.00B

train/sample_001707/board.png: downloading bytes:           |  0.00B

train/sample_001713/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

train/sample_001718/board.png: reconstructing file:   0%|          |  0.00B / 43.6kB

train/sample_001712/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_001714/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_001715/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_001720/board.png: reconstructing file:   0%|          |  0.00B / 14.8kB

train/sample_001716/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_001713/board.png: downloading bytes:           |  0.00B

train/sample_001714/board.png: downloading bytes:           |  0.00B

train/sample_001718/board.png: downloading bytes:           |  0.00B

train/sample_001712/board.png: downloading bytes:           |  0.00B

train/sample_001720/board.png: downloading bytes:           |  0.00B

train/sample_001715/board.png: downloading bytes:           |  0.00B

train/sample_001716/board.png: downloading bytes:           |  0.00B

train/sample_001719/board.png: reconstructing file:   0%|          |  0.00B / 41.2kB

train/sample_001719/board.png: downloading bytes:           |  0.00B

train/sample_001717/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_001717/board.png: downloading bytes:           |  0.00B

train/sample_001721/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_001721/board.png: downloading bytes:           |  0.00B

train/sample_001722/board.png: reconstructing file:   0%|          |  0.00B / 19.2kB

train/sample_001722/board.png: downloading bytes:           |  0.00B

train/sample_001723/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_001723/board.png: downloading bytes:           |  0.00B

train/sample_001724/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_001724/board.png: downloading bytes:           |  0.00B

train/sample_001726/board.png: reconstructing file:   0%|          |  0.00B / 11.1kB

train/sample_001725/board.png: reconstructing file:   0%|          |  0.00B / 38.7kB

train/sample_001727/board.png: reconstructing file:   0%|          |  0.00B / 38.2kB

train/sample_001726/board.png: downloading bytes:           |  0.00B

train/sample_001727/board.png: downloading bytes:           |  0.00B

train/sample_001725/board.png: downloading bytes:           |  0.00B

train/sample_001728/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_001728/board.png: downloading bytes:           |  0.00B

train/sample_001729/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

train/sample_001729/board.png: downloading bytes:           |  0.00B

train/sample_001730/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_001730/board.png: downloading bytes:           |  0.00B

train/sample_001731/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_001732/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_001731/board.png: downloading bytes:           |  0.00B

train/sample_001732/board.png: downloading bytes:           |  0.00B

train/sample_001733/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_001734/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_001734/board.png: downloading bytes:           |  0.00B

train/sample_001733/board.png: downloading bytes:           |  0.00B

train/sample_001735/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_001735/board.png: downloading bytes:           |  0.00B

train/sample_001736/board.png: reconstructing file:   0%|          |  0.00B / 42.8kB

train/sample_001736/board.png: downloading bytes:           |  0.00B

train/sample_001737/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_001737/board.png: downloading bytes:           |  0.00B

train/sample_001738/board.png: reconstructing file:   0%|          |  0.00B / 18.9kB

train/sample_001738/board.png: downloading bytes:           |  0.00B

train/sample_001739/board.png: reconstructing file:   0%|          |  0.00B / 14.7kB

train/sample_001739/board.png: downloading bytes:           |  0.00B

train/sample_001741/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_001740/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_001742/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_001742/board.png: downloading bytes:           |  0.00B

train/sample_001741/board.png: downloading bytes:           |  0.00B

train/sample_001740/board.png: downloading bytes:           |  0.00B

train/sample_001743/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

train/sample_001743/board.png: downloading bytes:           |  0.00B

train/sample_001744/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_001744/board.png: downloading bytes:           |  0.00B

train/sample_001746/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_001745/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_001746/board.png: downloading bytes:           |  0.00B

train/sample_001745/board.png: downloading bytes:           |  0.00B

train/sample_001747/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_001747/board.png: downloading bytes:           |  0.00B

train/sample_001748/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_001749/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_001748/board.png: downloading bytes:           |  0.00B

train/sample_001749/board.png: downloading bytes:           |  0.00B

train/sample_001750/board.png: reconstructing file:   0%|          |  0.00B / 40.5kB

train/sample_001751/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_001750/board.png: downloading bytes:           |  0.00B

train/sample_001751/board.png: downloading bytes:           |  0.00B

train/sample_001754/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_001752/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_001753/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_001752/board.png: downloading bytes:           |  0.00B

train/sample_001754/board.png: downloading bytes:           |  0.00B

train/sample_001753/board.png: downloading bytes:           |  0.00B

train/sample_001755/board.png: reconstructing file:   0%|          |  0.00B / 16.4kB

train/sample_001755/board.png: downloading bytes:           |  0.00B

train/sample_001757/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_001756/board.png: reconstructing file:   0%|          |  0.00B / 42.9kB

train/sample_001757/board.png: downloading bytes:           |  0.00B

train/sample_001756/board.png: downloading bytes:           |  0.00B

train/sample_001758/board.png: reconstructing file:   0%|          |  0.00B / 20.5kB

train/sample_001758/board.png: downloading bytes:           |  0.00B

train/sample_001759/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_001759/board.png: downloading bytes:           |  0.00B

train/sample_001760/board.png: reconstructing file:   0%|          |  0.00B / 41.1kB

train/sample_001761/board.png: reconstructing file:   0%|          |  0.00B / 42.5kB

train/sample_001761/board.png: downloading bytes:           |  0.00B

train/sample_001760/board.png: downloading bytes:           |  0.00B

train/sample_001762/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_001762/board.png: downloading bytes:           |  0.00B

train/sample_001766/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_001764/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_001763/board.png: reconstructing file:   0%|          |  0.00B / 16.5kB

train/sample_001765/board.png: reconstructing file:   0%|          |  0.00B / 43.7kB

train/sample_001767/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_001764/board.png: downloading bytes:           |  0.00B

train/sample_001766/board.png: downloading bytes:           |  0.00B

train/sample_001765/board.png: downloading bytes:           |  0.00B

train/sample_001763/board.png: downloading bytes:           |  0.00B

train/sample_001767/board.png: downloading bytes:           |  0.00B

train/sample_001768/board.png: reconstructing file:   0%|          |  0.00B / 11.1kB

train/sample_001769/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_001768/board.png: downloading bytes:           |  0.00B

train/sample_001769/board.png: downloading bytes:           |  0.00B

train/sample_001770/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001770/board.png: downloading bytes:           |  0.00B

train/sample_001771/board.png: reconstructing file:   0%|          |  0.00B / 18.8kB

train/sample_001773/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_001772/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

train/sample_001771/board.png: downloading bytes:           |  0.00B

train/sample_001772/board.png: downloading bytes:           |  0.00B

train/sample_001774/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_001773/board.png: downloading bytes:           |  0.00B

train/sample_001775/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

train/sample_001774/board.png: downloading bytes:           |  0.00B

train/sample_001775/board.png: downloading bytes:           |  0.00B

train/sample_001776/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001776/board.png: downloading bytes:           |  0.00B

train/sample_001777/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_001777/board.png: downloading bytes:           |  0.00B

train/sample_001778/board.png: reconstructing file:   0%|          |  0.00B / 24.6kB

train/sample_001778/board.png: downloading bytes:           |  0.00B

train/sample_001779/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

train/sample_001779/board.png: downloading bytes:           |  0.00B

train/sample_001780/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_001780/board.png: downloading bytes:           |  0.00B

train/sample_001781/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_001781/board.png: downloading bytes:           |  0.00B

train/sample_001783/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_001783/board.png: downloading bytes:           |  0.00B

train/sample_001782/board.png: reconstructing file:   0%|          |  0.00B / 21.1kB

train/sample_001782/board.png: downloading bytes:           |  0.00B

train/sample_001784/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001784/board.png: downloading bytes:           |  0.00B

train/sample_001785/board.png: reconstructing file:   0%|          |  0.00B / 44.1kB

train/sample_001785/board.png: downloading bytes:           |  0.00B

train/sample_001786/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_001786/board.png: downloading bytes:           |  0.00B

train/sample_001787/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_001788/board.png: reconstructing file:   0%|          |  0.00B / 41.2kB

train/sample_001787/board.png: downloading bytes:           |  0.00B

train/sample_001788/board.png: downloading bytes:           |  0.00B

train/sample_001789/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_001789/board.png: downloading bytes:           |  0.00B

train/sample_001790/board.png: reconstructing file:   0%|          |  0.00B / 37.2kB

train/sample_001791/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_001790/board.png: downloading bytes:           |  0.00B

train/sample_001791/board.png: downloading bytes:           |  0.00B

train/sample_001792/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_001792/board.png: downloading bytes:           |  0.00B

train/sample_001793/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_001794/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_001794/board.png: downloading bytes:           |  0.00B

train/sample_001793/board.png: downloading bytes:           |  0.00B

train/sample_001795/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_001795/board.png: downloading bytes:           |  0.00B

train/sample_001796/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_001796/board.png: downloading bytes:           |  0.00B

train/sample_001797/board.png: reconstructing file:   0%|          |  0.00B / 15.5kB

train/sample_001797/board.png: downloading bytes:           |  0.00B

train/sample_001798/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_001799/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_001798/board.png: downloading bytes:           |  0.00B

train/sample_001799/board.png: downloading bytes:           |  0.00B

train/sample_001800/board.png: reconstructing file:   0%|          |  0.00B / 22.0kB

train/sample_001800/board.png: downloading bytes:           |  0.00B

train/sample_001802/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_001801/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

train/sample_001802/board.png: downloading bytes:           |  0.00B

train/sample_001801/board.png: downloading bytes:           |  0.00B

train/sample_001803/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_001803/board.png: downloading bytes:           |  0.00B

train/sample_001804/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

train/sample_001804/board.png: downloading bytes:           |  0.00B

train/sample_001805/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

train/sample_001806/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_001807/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_001805/board.png: downloading bytes:           |  0.00B

train/sample_001806/board.png: downloading bytes:           |  0.00B

train/sample_001807/board.png: downloading bytes:           |  0.00B

train/sample_001808/board.png: reconstructing file:   0%|          |  0.00B / 24.6kB

train/sample_001808/board.png: downloading bytes:           |  0.00B

train/sample_001809/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_001810/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_001810/board.png: downloading bytes:           |  0.00B

train/sample_001809/board.png: downloading bytes:           |  0.00B

train/sample_001811/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_001811/board.png: downloading bytes:           |  0.00B

train/sample_001812/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_001812/board.png: downloading bytes:           |  0.00B

train/sample_001813/board.png: reconstructing file:   0%|          |  0.00B / 18.0kB

train/sample_001813/board.png: downloading bytes:           |  0.00B

train/sample_001814/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_001814/board.png: downloading bytes:           |  0.00B

train/sample_001815/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_001815/board.png: downloading bytes:           |  0.00B

train/sample_001816/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_001816/board.png: downloading bytes:           |  0.00B

train/sample_001817/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

train/sample_001817/board.png: downloading bytes:           |  0.00B

train/sample_001818/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

train/sample_001818/board.png: downloading bytes:           |  0.00B

train/sample_001819/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_001819/board.png: downloading bytes:           |  0.00B

train/sample_001820/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_001820/board.png: downloading bytes:           |  0.00B

train/sample_001821/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

train/sample_001821/board.png: downloading bytes:           |  0.00B

train/sample_001822/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_001822/board.png: downloading bytes:           |  0.00B

train/sample_001823/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_001823/board.png: downloading bytes:           |  0.00B

train/sample_001824/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

train/sample_001824/board.png: downloading bytes:           |  0.00B

train/sample_001825/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_001826/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_001825/board.png: downloading bytes:           |  0.00B

train/sample_001826/board.png: downloading bytes:           |  0.00B

train/sample_001827/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_001827/board.png: downloading bytes:           |  0.00B

train/sample_001828/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

train/sample_001828/board.png: downloading bytes:           |  0.00B

train/sample_001829/board.png: reconstructing file:   0%|          |  0.00B / 40.5kB

train/sample_001830/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

train/sample_001829/board.png: downloading bytes:           |  0.00B

train/sample_001830/board.png: downloading bytes:           |  0.00B

train/sample_001831/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_001831/board.png: downloading bytes:           |  0.00B

train/sample_001832/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_001832/board.png: downloading bytes:           |  0.00B

train/sample_001833/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_001833/board.png: downloading bytes:           |  0.00B

train/sample_001834/board.png: reconstructing file:   0%|          |  0.00B / 10.4kB

train/sample_001835/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_001834/board.png: downloading bytes:           |  0.00B

train/sample_001835/board.png: downloading bytes:           |  0.00B

train/sample_001836/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_001836/board.png: downloading bytes:           |  0.00B

train/sample_001837/board.png: reconstructing file:   0%|          |  0.00B / 24.5kB

train/sample_001837/board.png: downloading bytes:           |  0.00B

train/sample_001838/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

train/sample_001839/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

train/sample_001838/board.png: downloading bytes:           |  0.00B

train/sample_001839/board.png: downloading bytes:           |  0.00B

train/sample_001840/board.png: reconstructing file:   0%|          |  0.00B / 16.2kB

train/sample_001840/board.png: downloading bytes:           |  0.00B

train/sample_001841/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

train/sample_001841/board.png: downloading bytes:           |  0.00B

train/sample_001842/board.png: reconstructing file:   0%|          |  0.00B / 41.6kB

train/sample_001843/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_001843/board.png: downloading bytes:           |  0.00B

train/sample_001842/board.png: downloading bytes:           |  0.00B

train/sample_001844/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_001844/board.png: downloading bytes:           |  0.00B

train/sample_001845/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

train/sample_001845/board.png: downloading bytes:           |  0.00B

train/sample_001846/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_001846/board.png: downloading bytes:           |  0.00B

train/sample_001847/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_001847/board.png: downloading bytes:           |  0.00B

train/sample_001848/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_001848/board.png: downloading bytes:           |  0.00B

train/sample_001849/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_001849/board.png: downloading bytes:           |  0.00B

train/sample_001850/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

train/sample_001851/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_001850/board.png: downloading bytes:           |  0.00B

train/sample_001851/board.png: downloading bytes:           |  0.00B

train/sample_001852/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_001852/board.png: downloading bytes:           |  0.00B

train/sample_001853/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_001853/board.png: downloading bytes:           |  0.00B

train/sample_001854/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_001854/board.png: downloading bytes:           |  0.00B

train/sample_001855/board.png: reconstructing file:   0%|          |  0.00B / 15.7kB

train/sample_001855/board.png: downloading bytes:           |  0.00B

train/sample_001856/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_001856/board.png: downloading bytes:           |  0.00B

train/sample_001857/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001857/board.png: downloading bytes:           |  0.00B

train/sample_001858/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

train/sample_001859/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_001858/board.png: downloading bytes:           |  0.00B

train/sample_001859/board.png: downloading bytes:           |  0.00B

train/sample_001860/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

train/sample_001860/board.png: downloading bytes:           |  0.00B

train/sample_001861/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_001861/board.png: downloading bytes:           |  0.00B

train/sample_001862/board.png: reconstructing file:   0%|          |  0.00B / 18.1kB

train/sample_001862/board.png: downloading bytes:           |  0.00B

train/sample_001863/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_001863/board.png: downloading bytes:           |  0.00B

train/sample_001864/board.png: reconstructing file:   0%|          |  0.00B / 38.2kB

train/sample_001864/board.png: downloading bytes:           |  0.00B

train/sample_001865/board.png: reconstructing file:   0%|          |  0.00B / 18.9kB

train/sample_001867/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_001866/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_001865/board.png: downloading bytes:           |  0.00B

train/sample_001866/board.png: downloading bytes:           |  0.00B

train/sample_001867/board.png: downloading bytes:           |  0.00B

train/sample_001868/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_001868/board.png: downloading bytes:           |  0.00B

train/sample_001869/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_001869/board.png: downloading bytes:           |  0.00B

train/sample_001871/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_001870/board.png: reconstructing file:   0%|          |  0.00B / 18.6kB

train/sample_001871/board.png: downloading bytes:           |  0.00B

train/sample_001872/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_001870/board.png: downloading bytes:           |  0.00B

train/sample_001872/board.png: downloading bytes:           |  0.00B

train/sample_001873/board.png: reconstructing file:   0%|          |  0.00B / 41.1kB

train/sample_001873/board.png: downloading bytes:           |  0.00B

train/sample_001874/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_001874/board.png: downloading bytes:           |  0.00B

train/sample_001875/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_001875/board.png: downloading bytes:           |  0.00B

train/sample_001876/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

train/sample_001876/board.png: downloading bytes:           |  0.00B

train/sample_001877/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_001877/board.png: downloading bytes:           |  0.00B

train/sample_001878/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_001878/board.png: downloading bytes:           |  0.00B

train/sample_001879/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_001880/board.png: reconstructing file:   0%|          |  0.00B / 20.2kB

train/sample_001879/board.png: downloading bytes:           |  0.00B

train/sample_001880/board.png: downloading bytes:           |  0.00B

train/sample_001881/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_001881/board.png: downloading bytes:           |  0.00B

train/sample_001882/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_001882/board.png: downloading bytes:           |  0.00B

train/sample_001883/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_001883/board.png: downloading bytes:           |  0.00B

train/sample_001884/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_001884/board.png: downloading bytes:           |  0.00B

train/sample_001885/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_001886/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

train/sample_001885/board.png: downloading bytes:           |  0.00B

train/sample_001886/board.png: downloading bytes:           |  0.00B

train/sample_001887/board.png: reconstructing file:   0%|          |  0.00B / 42.9kB

train/sample_001887/board.png: downloading bytes:           |  0.00B

train/sample_001888/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_001888/board.png: downloading bytes:           |  0.00B

train/sample_001889/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

train/sample_001890/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

train/sample_001889/board.png: downloading bytes:           |  0.00B

train/sample_001890/board.png: downloading bytes:           |  0.00B

train/sample_001891/board.png: reconstructing file:   0%|          |  0.00B / 43.6kB

train/sample_001891/board.png: downloading bytes:           |  0.00B

train/sample_001892/board.png: reconstructing file:   0%|          |  0.00B / 44.4kB

train/sample_001892/board.png: downloading bytes:           |  0.00B

train/sample_001893/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_001893/board.png: downloading bytes:           |  0.00B

train/sample_001894/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_001894/board.png: downloading bytes:           |  0.00B

train/sample_001895/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_001895/board.png: downloading bytes:           |  0.00B

train/sample_001896/board.png: reconstructing file:   0%|          |  0.00B / 38.5kB

train/sample_001897/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

train/sample_001896/board.png: downloading bytes:           |  0.00B

train/sample_001897/board.png: downloading bytes:           |  0.00B

train/sample_001898/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_001898/board.png: downloading bytes:           |  0.00B

train/sample_001899/board.png: reconstructing file:   0%|          |  0.00B / 40.2kB

train/sample_001899/board.png: downloading bytes:           |  0.00B

train/sample_001900/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_001900/board.png: downloading bytes:           |  0.00B

train/sample_001902/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

train/sample_001903/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_001901/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_001902/board.png: downloading bytes:           |  0.00B

train/sample_001901/board.png: downloading bytes:           |  0.00B

train/sample_001903/board.png: downloading bytes:           |  0.00B

train/sample_001904/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_001904/board.png: downloading bytes:           |  0.00B

train/sample_001905/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

train/sample_001905/board.png: downloading bytes:           |  0.00B

train/sample_001906/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_001906/board.png: downloading bytes:           |  0.00B

train/sample_001907/board.png: reconstructing file:   0%|          |  0.00B / 21.6kB

train/sample_001907/board.png: downloading bytes:           |  0.00B

train/sample_001908/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_001908/board.png: downloading bytes:           |  0.00B

train/sample_001909/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_001910/board.png: reconstructing file:   0%|          |  0.00B / 15.4kB

train/sample_001909/board.png: downloading bytes:           |  0.00B

train/sample_001910/board.png: downloading bytes:           |  0.00B

train/sample_001911/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_001911/board.png: downloading bytes:           |  0.00B

train/sample_001912/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_001912/board.png: downloading bytes:           |  0.00B

train/sample_001913/board.png: reconstructing file:   0%|          |  0.00B / 40.7kB

train/sample_001913/board.png: downloading bytes:           |  0.00B

train/sample_001914/board.png: reconstructing file:   0%|          |  0.00B / 17.4kB

train/sample_001914/board.png: downloading bytes:           |  0.00B

train/sample_001915/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_001915/board.png: downloading bytes:           |  0.00B

train/sample_001916/board.png: reconstructing file:   0%|          |  0.00B / 18.0kB

train/sample_001916/board.png: downloading bytes:           |  0.00B

train/sample_001917/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_001917/board.png: downloading bytes:           |  0.00B

train/sample_001918/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_001918/board.png: downloading bytes:           |  0.00B

train/sample_001919/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

train/sample_001919/board.png: downloading bytes:           |  0.00B

train/sample_001920/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_001920/board.png: downloading bytes:           |  0.00B

train/sample_001921/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

train/sample_001921/board.png: downloading bytes:           |  0.00B

train/sample_001922/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_001922/board.png: downloading bytes:           |  0.00B

train/sample_001923/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_001923/board.png: downloading bytes:           |  0.00B

train/sample_001924/board.png: reconstructing file:   0%|          |  0.00B / 19.3kB

train/sample_001924/board.png: downloading bytes:           |  0.00B

train/sample_001925/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

train/sample_001925/board.png: downloading bytes:           |  0.00B

train/sample_001926/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_001927/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_001926/board.png: downloading bytes:           |  0.00B

train/sample_001927/board.png: downloading bytes:           |  0.00B

train/sample_001928/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_001928/board.png: downloading bytes:           |  0.00B

train/sample_001929/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

train/sample_001929/board.png: downloading bytes:           |  0.00B

train/sample_001930/board.png: reconstructing file:   0%|          |  0.00B / 37.0kB

train/sample_001930/board.png: downloading bytes:           |  0.00B

train/sample_001931/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_001931/board.png: downloading bytes:           |  0.00B

train/sample_001932/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_001932/board.png: downloading bytes:           |  0.00B

train/sample_001933/board.png: reconstructing file:   0%|          |  0.00B / 20.7kB

train/sample_001933/board.png: downloading bytes:           |  0.00B

train/sample_001935/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_001934/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_001934/board.png: downloading bytes:           |  0.00B

train/sample_001935/board.png: downloading bytes:           |  0.00B

train/sample_001936/board.png: reconstructing file:   0%|          |  0.00B / 40.0kB

train/sample_001936/board.png: downloading bytes:           |  0.00B

train/sample_001937/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_001937/board.png: downloading bytes:           |  0.00B

train/sample_001938/board.png: reconstructing file:   0%|          |  0.00B / 41.3kB

train/sample_001938/board.png: downloading bytes:           |  0.00B

train/sample_001939/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_001939/board.png: downloading bytes:           |  0.00B

train/sample_001940/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_001941/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_001943/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

train/sample_001940/board.png: downloading bytes:           |  0.00B

train/sample_001942/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_001941/board.png: downloading bytes:           |  0.00B

train/sample_001943/board.png: downloading bytes:           |  0.00B

train/sample_001942/board.png: downloading bytes:           |  0.00B

train/sample_001944/board.png: reconstructing file:   0%|          |  0.00B / 41.5kB

train/sample_001944/board.png: downloading bytes:           |  0.00B

train/sample_001945/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

train/sample_001945/board.png: downloading bytes:           |  0.00B

train/sample_001946/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_001946/board.png: downloading bytes:           |  0.00B

train/sample_001947/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_001947/board.png: downloading bytes:           |  0.00B

train/sample_001949/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_001951/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

train/sample_001950/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_001951/board.png: downloading bytes:           |  0.00B

train/sample_001949/board.png: downloading bytes:           |  0.00B

train/sample_001950/board.png: downloading bytes:           |  0.00B

train/sample_001948/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_001948/board.png: downloading bytes:           |  0.00B

train/sample_001952/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

train/sample_001953/board.png: reconstructing file:   0%|          |  0.00B / 11.9kB

train/sample_001952/board.png: downloading bytes:           |  0.00B

train/sample_001953/board.png: downloading bytes:           |  0.00B

train/sample_001954/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_001954/board.png: downloading bytes:           |  0.00B

train/sample_001956/board.png: reconstructing file:   0%|          |  0.00B / 40.5kB

train/sample_001956/board.png: downloading bytes:           |  0.00B

train/sample_001955/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_001958/board.png: reconstructing file:   0%|          |  0.00B / 14.2kB

train/sample_001957/board.png: reconstructing file:   0%|          |  0.00B / 39.3kB

train/sample_001958/board.png: downloading bytes:           |  0.00B

train/sample_001955/board.png: downloading bytes:           |  0.00B

train/sample_001957/board.png: downloading bytes:           |  0.00B

train/sample_001959/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_001959/board.png: downloading bytes:           |  0.00B

train/sample_001961/board.png: reconstructing file:   0%|          |  0.00B / 44.2kB

train/sample_001960/board.png: reconstructing file:   0%|          |  0.00B / 39.2kB

train/sample_001960/board.png: downloading bytes:           |  0.00B

train/sample_001961/board.png: downloading bytes:           |  0.00B

train/sample_001962/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

train/sample_001962/board.png: downloading bytes:           |  0.00B

train/sample_001963/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_001963/board.png: downloading bytes:           |  0.00B

train/sample_001966/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_001964/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_001965/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_001965/board.png: downloading bytes:           |  0.00B

train/sample_001964/board.png: downloading bytes:           |  0.00B

train/sample_001966/board.png: downloading bytes:           |  0.00B

train/sample_001967/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_001967/board.png: downloading bytes:           |  0.00B

train/sample_001968/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_001968/board.png: downloading bytes:           |  0.00B

train/sample_001969/board.png: reconstructing file:   0%|          |  0.00B / 14.3kB

train/sample_001969/board.png: downloading bytes:           |  0.00B

train/sample_001970/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_001970/board.png: downloading bytes:           |  0.00B

train/sample_001971/board.png: reconstructing file:   0%|          |  0.00B / 43.5kB

train/sample_001971/board.png: downloading bytes:           |  0.00B

train/sample_001972/board.png: reconstructing file:   0%|          |  0.00B / 12.2kB

train/sample_001972/board.png: downloading bytes:           |  0.00B

train/sample_001973/board.png: reconstructing file:   0%|          |  0.00B / 18.8kB

train/sample_001973/board.png: downloading bytes:           |  0.00B

train/sample_001974/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_001974/board.png: downloading bytes:           |  0.00B

train/sample_001975/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_001976/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_001975/board.png: downloading bytes:           |  0.00B

train/sample_001976/board.png: downloading bytes:           |  0.00B

train/sample_001977/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_001977/board.png: downloading bytes:           |  0.00B

train/sample_001978/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

train/sample_001978/board.png: downloading bytes:           |  0.00B

train/sample_001979/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

train/sample_001979/board.png: downloading bytes:           |  0.00B

train/sample_001980/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_001981/board.png: reconstructing file:   0%|          |  0.00B / 20.7kB

train/sample_001980/board.png: downloading bytes:           |  0.00B

train/sample_001983/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_001982/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_001981/board.png: downloading bytes:           |  0.00B

train/sample_001984/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_001982/board.png: downloading bytes:           |  0.00B

train/sample_001983/board.png: downloading bytes:           |  0.00B

train/sample_001984/board.png: downloading bytes:           |  0.00B

train/sample_001985/board.png: reconstructing file:   0%|          |  0.00B / 18.8kB

train/sample_001985/board.png: downloading bytes:           |  0.00B

train/sample_001986/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_001986/board.png: downloading bytes:           |  0.00B

train/sample_001987/board.png: reconstructing file:   0%|          |  0.00B / 15.0kB

train/sample_001987/board.png: downloading bytes:           |  0.00B

train/sample_001988/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_001988/board.png: downloading bytes:           |  0.00B

train/sample_001989/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_001990/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_001991/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_001989/board.png: downloading bytes:           |  0.00B

train/sample_001991/board.png: downloading bytes:           |  0.00B

train/sample_001990/board.png: downloading bytes:           |  0.00B

train/sample_001992/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

train/sample_001992/board.png: downloading bytes:           |  0.00B

train/sample_001993/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_001993/board.png: downloading bytes:           |  0.00B

train/sample_001994/board.png: reconstructing file:   0%|          |  0.00B / 21.6kB

train/sample_001994/board.png: downloading bytes:           |  0.00B

train/sample_001995/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

train/sample_001995/board.png: downloading bytes:           |  0.00B

train/sample_001996/board.png: reconstructing file:   0%|          |  0.00B / 35.9kB

train/sample_001996/board.png: downloading bytes:           |  0.00B

train/sample_001997/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_001997/board.png: downloading bytes:           |  0.00B

train/sample_001998/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_001999/board.png: reconstructing file:   0%|          |  0.00B / 42.5kB

train/sample_002000/board.png: reconstructing file:   0%|          |  0.00B / 37.0kB

train/sample_001998/board.png: downloading bytes:           |  0.00B

train/sample_002000/board.png: downloading bytes:           |  0.00B

train/sample_001999/board.png: downloading bytes:           |  0.00B

train/sample_002001/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002001/board.png: downloading bytes:           |  0.00B

train/sample_002002/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_002003/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_002003/board.png: downloading bytes:           |  0.00B

train/sample_002004/board.png: reconstructing file:   0%|          |  0.00B / 40.2kB

train/sample_002002/board.png: downloading bytes:           |  0.00B

train/sample_002004/board.png: downloading bytes:           |  0.00B

train/sample_002005/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_002005/board.png: downloading bytes:           |  0.00B

train/sample_002007/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

train/sample_002006/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_002006/board.png: downloading bytes:           |  0.00B

train/sample_002007/board.png: downloading bytes:           |  0.00B

train/sample_002009/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_002008/board.png: reconstructing file:   0%|          |  0.00B / 21.0kB

train/sample_002008/board.png: downloading bytes:           |  0.00B

train/sample_002009/board.png: downloading bytes:           |  0.00B

train/sample_002010/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_002010/board.png: downloading bytes:           |  0.00B

train/sample_002011/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_002011/board.png: downloading bytes:           |  0.00B

train/sample_002012/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_002012/board.png: downloading bytes:           |  0.00B

train/sample_002013/board.png: reconstructing file:   0%|          |  0.00B / 41.2kB

train/sample_002013/board.png: downloading bytes:           |  0.00B

train/sample_002014/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_002014/board.png: downloading bytes:           |  0.00B

train/sample_002015/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_002015/board.png: downloading bytes:           |  0.00B

train/sample_002016/board.png: reconstructing file:   0%|          |  0.00B / 12.9kB

train/sample_002017/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_002016/board.png: downloading bytes:           |  0.00B

train/sample_002017/board.png: downloading bytes:           |  0.00B

train/sample_002018/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_002018/board.png: downloading bytes:           |  0.00B

train/sample_002019/board.png: reconstructing file:   0%|          |  0.00B / 15.4kB

train/sample_002019/board.png: downloading bytes:           |  0.00B

train/sample_002020/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_002020/board.png: downloading bytes:           |  0.00B

train/sample_002021/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_002021/board.png: downloading bytes:           |  0.00B

train/sample_002022/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_002024/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

train/sample_002023/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

train/sample_002022/board.png: downloading bytes:           |  0.00B

train/sample_002023/board.png: downloading bytes:           |  0.00B

train/sample_002024/board.png: downloading bytes:           |  0.00B

train/sample_002025/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_002025/board.png: downloading bytes:           |  0.00B

train/sample_002026/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_002026/board.png: downloading bytes:           |  0.00B

train/sample_002027/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_002027/board.png: downloading bytes:           |  0.00B

train/sample_002028/board.png: reconstructing file:   0%|          |  0.00B / 13.9kB

train/sample_002028/board.png: downloading bytes:           |  0.00B

train/sample_002029/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_002029/board.png: downloading bytes:           |  0.00B

train/sample_002030/board.png: reconstructing file:   0%|          |  0.00B / 39.4kB

train/sample_002030/board.png: downloading bytes:           |  0.00B

train/sample_002031/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_002033/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_002032/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_002033/board.png: downloading bytes:           |  0.00B

train/sample_002031/board.png: downloading bytes:           |  0.00B

train/sample_002032/board.png: downloading bytes:           |  0.00B

train/sample_002034/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002036/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

train/sample_002035/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

train/sample_002034/board.png: downloading bytes:           |  0.00B

train/sample_002036/board.png: downloading bytes:           |  0.00B

train/sample_002035/board.png: downloading bytes:           |  0.00B

train/sample_002037/board.png: reconstructing file:   0%|          |  0.00B / 25.6kB

train/sample_002039/board.png: reconstructing file:   0%|          |  0.00B / 39.4kB

train/sample_002037/board.png: downloading bytes:           |  0.00B

train/sample_002038/board.png: reconstructing file:   0%|          |  0.00B / 22.3kB

train/sample_002041/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_002040/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_002039/board.png: downloading bytes:           |  0.00B

train/sample_002038/board.png: downloading bytes:           |  0.00B

train/sample_002041/board.png: downloading bytes:           |  0.00B

train/sample_002040/board.png: downloading bytes:           |  0.00B

train/sample_002042/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_002042/board.png: downloading bytes:           |  0.00B

train/sample_002044/board.png: reconstructing file:   0%|          |  0.00B / 14.3kB

train/sample_002043/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_002044/board.png: downloading bytes:           |  0.00B

train/sample_002043/board.png: downloading bytes:           |  0.00B

train/sample_002045/board.png: reconstructing file:   0%|          |  0.00B / 37.4kB

train/sample_002047/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_002046/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_002048/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_002045/board.png: downloading bytes:           |  0.00B

train/sample_002047/board.png: downloading bytes:           |  0.00B

train/sample_002049/board.png: reconstructing file:   0%|          |  0.00B / 40.3kB

train/sample_002046/board.png: downloading bytes:           |  0.00B

train/sample_002048/board.png: downloading bytes:           |  0.00B

train/sample_002049/board.png: downloading bytes:           |  0.00B

train/sample_002050/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_002050/board.png: downloading bytes:           |  0.00B

train/sample_002051/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_002052/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_002052/board.png: downloading bytes:           |  0.00B

train/sample_002051/board.png: downloading bytes:           |  0.00B

train/sample_002053/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_002053/board.png: downloading bytes:           |  0.00B

train/sample_002054/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_002054/board.png: downloading bytes:           |  0.00B

train/sample_002055/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002056/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_002057/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002055/board.png: downloading bytes:           |  0.00B

train/sample_002057/board.png: downloading bytes:           |  0.00B

train/sample_002056/board.png: downloading bytes:           |  0.00B

train/sample_002058/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

train/sample_002059/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

train/sample_002058/board.png: downloading bytes:           |  0.00B

train/sample_002059/board.png: downloading bytes:           |  0.00B

train/sample_002060/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_002060/board.png: downloading bytes:           |  0.00B

train/sample_002061/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_002061/board.png: downloading bytes:           |  0.00B

train/sample_002062/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_002063/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_002062/board.png: downloading bytes:           |  0.00B

train/sample_002063/board.png: downloading bytes:           |  0.00B

train/sample_002064/board.png: reconstructing file:   0%|          |  0.00B / 23.3kB

train/sample_002064/board.png: downloading bytes:           |  0.00B

train/sample_002065/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_002065/board.png: downloading bytes:           |  0.00B

train/sample_002066/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_002066/board.png: downloading bytes:           |  0.00B

train/sample_002067/board.png: reconstructing file:   0%|          |  0.00B / 24.5kB

train/sample_002069/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

train/sample_002067/board.png: downloading bytes:           |  0.00B

train/sample_002068/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

train/sample_002069/board.png: downloading bytes:           |  0.00B

train/sample_002070/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_002071/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_002068/board.png: downloading bytes:           |  0.00B

train/sample_002070/board.png: downloading bytes:           |  0.00B

train/sample_002071/board.png: downloading bytes:           |  0.00B

train/sample_002072/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

train/sample_002072/board.png: downloading bytes:           |  0.00B

train/sample_002073/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_002073/board.png: downloading bytes:           |  0.00B

train/sample_002074/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_002074/board.png: downloading bytes:           |  0.00B

train/sample_002075/board.png: reconstructing file:   0%|          |  0.00B / 44.1kB

train/sample_002075/board.png: downloading bytes:           |  0.00B

train/sample_002076/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_002076/board.png: downloading bytes:           |  0.00B

train/sample_002077/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_002077/board.png: downloading bytes:           |  0.00B

train/sample_002078/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

train/sample_002078/board.png: downloading bytes:           |  0.00B

train/sample_002079/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_002079/board.png: downloading bytes:           |  0.00B

train/sample_002080/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

train/sample_002080/board.png: downloading bytes:           |  0.00B

train/sample_002081/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_002081/board.png: downloading bytes:           |  0.00B

train/sample_002082/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_002082/board.png: downloading bytes:           |  0.00B

train/sample_002083/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_002083/board.png: downloading bytes:           |  0.00B

train/sample_002084/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_002084/board.png: downloading bytes:           |  0.00B

train/sample_002085/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_002085/board.png: downloading bytes:           |  0.00B

train/sample_002086/board.png: reconstructing file:   0%|          |  0.00B / 41.6kB

train/sample_002086/board.png: downloading bytes:           |  0.00B

train/sample_002087/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_002087/board.png: downloading bytes:           |  0.00B

train/sample_002088/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_002088/board.png: downloading bytes:           |  0.00B

train/sample_002089/board.png: reconstructing file:   0%|          |  0.00B / 22.0kB

train/sample_002089/board.png: downloading bytes:           |  0.00B

train/sample_002090/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_002090/board.png: downloading bytes:           |  0.00B

train/sample_002091/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

train/sample_002091/board.png: downloading bytes:           |  0.00B

train/sample_002092/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_002092/board.png: downloading bytes:           |  0.00B

train/sample_002094/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_002094/board.png: downloading bytes:           |  0.00B

train/sample_002093/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_002093/board.png: downloading bytes:           |  0.00B

train/sample_002095/board.png: reconstructing file:   0%|          |  0.00B / 35.9kB

train/sample_002096/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_002096/board.png: downloading bytes:           |  0.00B

train/sample_002095/board.png: downloading bytes:           |  0.00B

train/sample_002097/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_002097/board.png: downloading bytes:           |  0.00B

train/sample_002098/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_002098/board.png: downloading bytes:           |  0.00B

train/sample_002099/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_002099/board.png: downloading bytes:           |  0.00B

train/sample_002100/board.png: reconstructing file:   0%|          |  0.00B / 16.8kB

train/sample_002101/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_002100/board.png: downloading bytes:           |  0.00B

train/sample_002102/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_002102/board.png: downloading bytes:           |  0.00B

train/sample_002101/board.png: downloading bytes:           |  0.00B

train/sample_002103/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_002103/board.png: downloading bytes:           |  0.00B

train/sample_002104/board.png: reconstructing file:   0%|          |  0.00B / 13.6kB

train/sample_002104/board.png: downloading bytes:           |  0.00B

train/sample_002105/board.png: reconstructing file:   0%|          |  0.00B / 16.3kB

train/sample_002106/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_002105/board.png: downloading bytes:           |  0.00B

train/sample_002106/board.png: downloading bytes:           |  0.00B

train/sample_002107/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_002107/board.png: downloading bytes:           |  0.00B

train/sample_002108/board.png: reconstructing file:   0%|          |  0.00B / 15.9kB

train/sample_002109/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_002108/board.png: downloading bytes:           |  0.00B

train/sample_002110/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_002109/board.png: downloading bytes:           |  0.00B

train/sample_002110/board.png: downloading bytes:           |  0.00B

train/sample_002111/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_002111/board.png: downloading bytes:           |  0.00B

train/sample_002112/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_002113/board.png: reconstructing file:   0%|          |  0.00B / 20.2kB

train/sample_002112/board.png: downloading bytes:           |  0.00B

train/sample_002114/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002113/board.png: downloading bytes:           |  0.00B

train/sample_002114/board.png: downloading bytes:           |  0.00B

train/sample_002115/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_002116/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_002115/board.png: downloading bytes:           |  0.00B

train/sample_002116/board.png: downloading bytes:           |  0.00B

train/sample_002117/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_002117/board.png: downloading bytes:           |  0.00B

train/sample_002118/board.png: reconstructing file:   0%|          |  0.00B / 10.3kB

train/sample_002118/board.png: downloading bytes:           |  0.00B

train/sample_002119/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_002119/board.png: downloading bytes:           |  0.00B

train/sample_002120/board.png: reconstructing file:   0%|          |  0.00B / 24.7kB

train/sample_002121/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_002122/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_002120/board.png: downloading bytes:           |  0.00B

train/sample_002121/board.png: downloading bytes:           |  0.00B

train/sample_002122/board.png: downloading bytes:           |  0.00B

train/sample_002123/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_002123/board.png: downloading bytes:           |  0.00B

train/sample_002124/board.png: reconstructing file:   0%|          |  0.00B / 38.5kB

train/sample_002124/board.png: downloading bytes:           |  0.00B

train/sample_002125/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_002126/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_002126/board.png: downloading bytes:           |  0.00B

train/sample_002125/board.png: downloading bytes:           |  0.00B

train/sample_002127/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_002127/board.png: downloading bytes:           |  0.00B

train/sample_002128/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_002129/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_002128/board.png: downloading bytes:           |  0.00B

train/sample_002130/board.png: reconstructing file:   0%|          |  0.00B / 23.3kB

train/sample_002129/board.png: downloading bytes:           |  0.00B

train/sample_002130/board.png: downloading bytes:           |  0.00B

train/sample_002131/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_002132/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_002131/board.png: downloading bytes:           |  0.00B

train/sample_002132/board.png: downloading bytes:           |  0.00B

train/sample_002133/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_002133/board.png: downloading bytes:           |  0.00B

train/sample_002134/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002134/board.png: downloading bytes:           |  0.00B

train/sample_002135/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

train/sample_002135/board.png: downloading bytes:           |  0.00B

train/sample_002136/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_002136/board.png: downloading bytes:           |  0.00B

train/sample_002137/board.png: reconstructing file:   0%|          |  0.00B / 20.2kB

train/sample_002137/board.png: downloading bytes:           |  0.00B

train/sample_002138/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_002138/board.png: downloading bytes:           |  0.00B

train/sample_002139/board.png: reconstructing file:   0%|          |  0.00B / 17.9kB

train/sample_002139/board.png: downloading bytes:           |  0.00B

train/sample_002140/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_002140/board.png: downloading bytes:           |  0.00B

train/sample_002141/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_002141/board.png: downloading bytes:           |  0.00B

train/sample_002142/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_002142/board.png: downloading bytes:           |  0.00B

train/sample_002143/board.png: reconstructing file:   0%|          |  0.00B / 13.6kB

train/sample_002143/board.png: downloading bytes:           |  0.00B

train/sample_002144/board.png: reconstructing file:   0%|          |  0.00B / 18.9kB

train/sample_002144/board.png: downloading bytes:           |  0.00B

train/sample_002145/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_002146/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_002145/board.png: downloading bytes:           |  0.00B

train/sample_002146/board.png: downloading bytes:           |  0.00B

train/sample_002147/board.png: reconstructing file:   0%|          |  0.00B / 38.9kB

train/sample_002147/board.png: downloading bytes:           |  0.00B

train/sample_002148/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_002149/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

train/sample_002148/board.png: downloading bytes:           |  0.00B

train/sample_002149/board.png: downloading bytes:           |  0.00B

train/sample_002150/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_002150/board.png: downloading bytes:           |  0.00B

train/sample_002151/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_002151/board.png: downloading bytes:           |  0.00B

train/sample_002152/board.png: reconstructing file:   0%|          |  0.00B / 16.8kB

train/sample_002152/board.png: downloading bytes:           |  0.00B

train/sample_002154/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_002153/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_002154/board.png: downloading bytes:           |  0.00B

train/sample_002153/board.png: downloading bytes:           |  0.00B

train/sample_002155/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_002155/board.png: downloading bytes:           |  0.00B

train/sample_002156/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_002156/board.png: downloading bytes:           |  0.00B

train/sample_002157/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_002157/board.png: downloading bytes:           |  0.00B

train/sample_002159/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

train/sample_002158/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_002159/board.png: downloading bytes:           |  0.00B

train/sample_002158/board.png: downloading bytes:           |  0.00B

train/sample_002160/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_002160/board.png: downloading bytes:           |  0.00B

train/sample_002161/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_002161/board.png: downloading bytes:           |  0.00B

train/sample_002162/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_002162/board.png: downloading bytes:           |  0.00B

train/sample_002163/board.png: reconstructing file:   0%|          |  0.00B / 38.0kB

train/sample_002163/board.png: downloading bytes:           |  0.00B

train/sample_002164/board.png: reconstructing file:   0%|          |  0.00B / 41.5kB

train/sample_002164/board.png: downloading bytes:           |  0.00B

train/sample_002165/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_002165/board.png: downloading bytes:           |  0.00B

train/sample_002166/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_002167/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_002166/board.png: downloading bytes:           |  0.00B

train/sample_002167/board.png: downloading bytes:           |  0.00B

train/sample_002168/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_002168/board.png: downloading bytes:           |  0.00B

train/sample_002169/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_002169/board.png: downloading bytes:           |  0.00B

train/sample_002170/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_002170/board.png: downloading bytes:           |  0.00B

train/sample_002171/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_002171/board.png: downloading bytes:           |  0.00B

train/sample_002172/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_002172/board.png: downloading bytes:           |  0.00B

train/sample_002173/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_002174/board.png: reconstructing file:   0%|          |  0.00B / 38.0kB

train/sample_002173/board.png: downloading bytes:           |  0.00B

train/sample_002174/board.png: downloading bytes:           |  0.00B

train/sample_002175/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_002176/board.png: reconstructing file:   0%|          |  0.00B / 44.1kB

train/sample_002175/board.png: downloading bytes:           |  0.00B

train/sample_002176/board.png: downloading bytes:           |  0.00B

train/sample_002177/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_002177/board.png: downloading bytes:           |  0.00B

train/sample_002178/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_002178/board.png: downloading bytes:           |  0.00B

train/sample_002180/board.png: reconstructing file:   0%|          |  0.00B / 13.8kB

train/sample_002179/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_002181/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_002180/board.png: downloading bytes:           |  0.00B

train/sample_002179/board.png: downloading bytes:           |  0.00B

train/sample_002182/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_002181/board.png: downloading bytes:           |  0.00B

train/sample_002182/board.png: downloading bytes:           |  0.00B

train/sample_002183/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_002183/board.png: downloading bytes:           |  0.00B

train/sample_002184/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_002185/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

train/sample_002184/board.png: downloading bytes:           |  0.00B

train/sample_002185/board.png: downloading bytes:           |  0.00B

train/sample_002186/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_002186/board.png: downloading bytes:           |  0.00B

train/sample_002187/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

train/sample_002188/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_002187/board.png: downloading bytes:           |  0.00B

train/sample_002188/board.png: downloading bytes:           |  0.00B

train/sample_002189/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_002189/board.png: downloading bytes:           |  0.00B

train/sample_002190/board.png: reconstructing file:   0%|          |  0.00B / 18.8kB

train/sample_002191/board.png: reconstructing file:   0%|          |  0.00B / 38.0kB

train/sample_002190/board.png: downloading bytes:           |  0.00B

train/sample_002192/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_002191/board.png: downloading bytes:           |  0.00B

train/sample_002193/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

train/sample_002192/board.png: downloading bytes:           |  0.00B

train/sample_002193/board.png: downloading bytes:           |  0.00B

train/sample_002194/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_002194/board.png: downloading bytes:           |  0.00B

train/sample_002195/board.png: reconstructing file:   0%|          |  0.00B / 15.0kB

train/sample_002195/board.png: downloading bytes:           |  0.00B

train/sample_002196/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_002196/board.png: downloading bytes:           |  0.00B

train/sample_002197/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_002197/board.png: downloading bytes:           |  0.00B

train/sample_002199/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_002201/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_002198/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

train/sample_002200/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_002199/board.png: downloading bytes:           |  0.00B

train/sample_002198/board.png: downloading bytes:           |  0.00B

train/sample_002201/board.png: downloading bytes:           |  0.00B

train/sample_002200/board.png: downloading bytes:           |  0.00B

train/sample_002202/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_002202/board.png: downloading bytes:           |  0.00B

train/sample_002203/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_002203/board.png: downloading bytes:           |  0.00B

train/sample_002204/board.png: reconstructing file:   0%|          |  0.00B / 41.4kB

train/sample_002204/board.png: downloading bytes:           |  0.00B

train/sample_002205/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_002206/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_002207/board.png: reconstructing file:   0%|          |  0.00B / 20.5kB

train/sample_002205/board.png: downloading bytes:           |  0.00B

train/sample_002208/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_002209/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_002206/board.png: downloading bytes:           |  0.00B

train/sample_002207/board.png: downloading bytes:           |  0.00B

train/sample_002208/board.png: downloading bytes:           |  0.00B

train/sample_002209/board.png: downloading bytes:           |  0.00B

train/sample_002210/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_002210/board.png: downloading bytes:           |  0.00B

train/sample_002211/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_002211/board.png: downloading bytes:           |  0.00B

train/sample_002212/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002212/board.png: downloading bytes:           |  0.00B

train/sample_002213/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_002213/board.png: downloading bytes:           |  0.00B

train/sample_002214/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_002214/board.png: downloading bytes:           |  0.00B

train/sample_002215/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002215/board.png: downloading bytes:           |  0.00B

train/sample_002216/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_002216/board.png: downloading bytes:           |  0.00B

train/sample_002217/board.png: reconstructing file:   0%|          |  0.00B / 13.7kB

train/sample_002217/board.png: downloading bytes:           |  0.00B

train/sample_002218/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_002219/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_002218/board.png: downloading bytes:           |  0.00B

train/sample_002219/board.png: downloading bytes:           |  0.00B

train/sample_002220/board.png: reconstructing file:   0%|          |  0.00B / 43.2kB

train/sample_002220/board.png: downloading bytes:           |  0.00B

train/sample_002221/board.png: reconstructing file:   0%|          |  0.00B / 12.0kB

train/sample_002221/board.png: downloading bytes:           |  0.00B

train/sample_002223/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

train/sample_002222/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_002224/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_002222/board.png: downloading bytes:           |  0.00B

train/sample_002223/board.png: downloading bytes:           |  0.00B

train/sample_002225/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_002225/board.png: downloading bytes:           |  0.00B

train/sample_002224/board.png: downloading bytes:           |  0.00B

train/sample_002226/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_002227/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

train/sample_002228/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_002228/board.png: downloading bytes:           |  0.00B

train/sample_002226/board.png: downloading bytes:           |  0.00B

train/sample_002227/board.png: downloading bytes:           |  0.00B

train/sample_002229/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_002229/board.png: downloading bytes:           |  0.00B

train/sample_002230/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_002231/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_002230/board.png: downloading bytes:           |  0.00B

train/sample_002232/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_002231/board.png: downloading bytes:           |  0.00B

train/sample_002232/board.png: downloading bytes:           |  0.00B

train/sample_002233/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

train/sample_002233/board.png: downloading bytes:           |  0.00B

train/sample_002234/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

train/sample_002235/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

train/sample_002234/board.png: downloading bytes:           |  0.00B

train/sample_002236/board.png: reconstructing file:   0%|          |  0.00B / 16.2kB

train/sample_002235/board.png: downloading bytes:           |  0.00B

train/sample_002236/board.png: downloading bytes:           |  0.00B

train/sample_002237/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002237/board.png: downloading bytes:           |  0.00B

train/sample_002238/board.png: reconstructing file:   0%|          |  0.00B / 11.9kB

train/sample_002239/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_002240/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_002238/board.png: downloading bytes:           |  0.00B

train/sample_002239/board.png: downloading bytes:           |  0.00B

train/sample_002240/board.png: downloading bytes:           |  0.00B

train/sample_002241/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_002241/board.png: downloading bytes:           |  0.00B

train/sample_002242/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_002242/board.png: downloading bytes:           |  0.00B

train/sample_002244/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_002243/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_002243/board.png: downloading bytes:           |  0.00B

train/sample_002244/board.png: downloading bytes:           |  0.00B

train/sample_002245/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_002245/board.png: downloading bytes:           |  0.00B

train/sample_002247/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_002247/board.png: downloading bytes:           |  0.00B

train/sample_002246/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002246/board.png: downloading bytes:           |  0.00B

train/sample_002248/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_002248/board.png: downloading bytes:           |  0.00B

train/sample_002249/board.png: reconstructing file:   0%|          |  0.00B / 38.7kB

train/sample_002249/board.png: downloading bytes:           |  0.00B

train/sample_002250/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_002250/board.png: downloading bytes:           |  0.00B

train/sample_002251/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_002251/board.png: downloading bytes:           |  0.00B

train/sample_002252/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_002252/board.png: downloading bytes:           |  0.00B

train/sample_002253/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_002253/board.png: downloading bytes:           |  0.00B

train/sample_002254/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

train/sample_002254/board.png: downloading bytes:           |  0.00B

train/sample_002255/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_002256/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_002255/board.png: downloading bytes:           |  0.00B

train/sample_002256/board.png: downloading bytes:           |  0.00B

train/sample_002257/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_002257/board.png: downloading bytes:           |  0.00B

train/sample_002258/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_002258/board.png: downloading bytes:           |  0.00B

train/sample_002259/board.png: reconstructing file:   0%|          |  0.00B / 14.6kB

train/sample_002259/board.png: downloading bytes:           |  0.00B

train/sample_002260/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_002260/board.png: downloading bytes:           |  0.00B

train/sample_002261/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_002261/board.png: downloading bytes:           |  0.00B

train/sample_002262/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_002262/board.png: downloading bytes:           |  0.00B

train/sample_002263/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_002263/board.png: downloading bytes:           |  0.00B

train/sample_002264/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

train/sample_002264/board.png: downloading bytes:           |  0.00B

train/sample_002265/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002265/board.png: downloading bytes:           |  0.00B

train/sample_002266/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_002266/board.png: downloading bytes:           |  0.00B

train/sample_002267/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_002267/board.png: downloading bytes:           |  0.00B

train/sample_002268/board.png: reconstructing file:   0%|          |  0.00B / 40.4kB

train/sample_002268/board.png: downloading bytes:           |  0.00B

train/sample_002269/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_002269/board.png: downloading bytes:           |  0.00B

train/sample_002270/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_002270/board.png: downloading bytes:           |  0.00B

train/sample_002271/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

train/sample_002271/board.png: downloading bytes:           |  0.00B

train/sample_002272/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

train/sample_002272/board.png: downloading bytes:           |  0.00B

train/sample_002273/board.png: reconstructing file:   0%|          |  0.00B / 16.9kB

train/sample_002273/board.png: downloading bytes:           |  0.00B

train/sample_002274/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_002274/board.png: downloading bytes:           |  0.00B

train/sample_002275/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

train/sample_002275/board.png: downloading bytes:           |  0.00B

train/sample_002276/board.png: reconstructing file:   0%|          |  0.00B / 18.1kB

train/sample_002276/board.png: downloading bytes:           |  0.00B

train/sample_002277/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_002277/board.png: downloading bytes:           |  0.00B

train/sample_002279/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_002278/board.png: reconstructing file:   0%|          |  0.00B / 14.1kB

train/sample_002279/board.png: downloading bytes:           |  0.00B

train/sample_002278/board.png: downloading bytes:           |  0.00B

train/sample_002280/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_002280/board.png: downloading bytes:           |  0.00B

train/sample_002281/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_002281/board.png: downloading bytes:           |  0.00B

train/sample_002282/board.png: reconstructing file:   0%|          |  0.00B / 18.8kB

train/sample_002282/board.png: downloading bytes:           |  0.00B

train/sample_002283/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_002284/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_002284/board.png: downloading bytes:           |  0.00B

train/sample_002283/board.png: downloading bytes:           |  0.00B

train/sample_002285/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_002285/board.png: downloading bytes:           |  0.00B

train/sample_002288/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_002286/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_002287/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_002286/board.png: downloading bytes:           |  0.00B

train/sample_002288/board.png: downloading bytes:           |  0.00B

train/sample_002287/board.png: downloading bytes:           |  0.00B

train/sample_002289/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_002289/board.png: downloading bytes:           |  0.00B

train/sample_002290/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_002290/board.png: downloading bytes:           |  0.00B

train/sample_002291/board.png: reconstructing file:   0%|          |  0.00B / 15.6kB

train/sample_002291/board.png: downloading bytes:           |  0.00B

train/sample_002292/board.png: reconstructing file:   0%|          |  0.00B / 18.0kB

train/sample_002292/board.png: downloading bytes:           |  0.00B

train/sample_002293/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_002293/board.png: downloading bytes:           |  0.00B

train/sample_002294/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_002294/board.png: downloading bytes:           |  0.00B

train/sample_002295/board.png: reconstructing file:   0%|          |  0.00B / 43.4kB

train/sample_002296/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_002295/board.png: downloading bytes:           |  0.00B

train/sample_002296/board.png: downloading bytes:           |  0.00B

train/sample_002297/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

train/sample_002297/board.png: downloading bytes:           |  0.00B

train/sample_002298/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_002298/board.png: downloading bytes:           |  0.00B

train/sample_002299/board.png: reconstructing file:   0%|          |  0.00B / 36.3kB

train/sample_002300/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_002299/board.png: downloading bytes:           |  0.00B

train/sample_002300/board.png: downloading bytes:           |  0.00B

train/sample_002301/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_002301/board.png: downloading bytes:           |  0.00B

train/sample_002303/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_002303/board.png: downloading bytes:           |  0.00B

train/sample_002302/board.png: reconstructing file:   0%|          |  0.00B / 14.3kB

train/sample_002304/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_002302/board.png: downloading bytes:           |  0.00B

train/sample_002304/board.png: downloading bytes:           |  0.00B

train/sample_002305/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_002305/board.png: downloading bytes:           |  0.00B

train/sample_002306/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

train/sample_002306/board.png: downloading bytes:           |  0.00B

train/sample_002307/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

train/sample_002307/board.png: downloading bytes:           |  0.00B

train/sample_002308/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

train/sample_002308/board.png: downloading bytes:           |  0.00B

train/sample_002309/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_002309/board.png: downloading bytes:           |  0.00B

train/sample_002311/board.png: reconstructing file:   0%|          |  0.00B / 41.7kB

train/sample_002310/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_002311/board.png: downloading bytes:           |  0.00B

train/sample_002310/board.png: downloading bytes:           |  0.00B

train/sample_002312/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

train/sample_002312/board.png: downloading bytes:           |  0.00B

train/sample_002313/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

train/sample_002313/board.png: downloading bytes:           |  0.00B

train/sample_002314/board.png: reconstructing file:   0%|          |  0.00B / 17.9kB

train/sample_002314/board.png: downloading bytes:           |  0.00B

train/sample_002315/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

train/sample_002316/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_002315/board.png: downloading bytes:           |  0.00B

train/sample_002316/board.png: downloading bytes:           |  0.00B

train/sample_002317/board.png: reconstructing file:   0%|          |  0.00B / 20.8kB

train/sample_002317/board.png: downloading bytes:           |  0.00B

train/sample_002318/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_002318/board.png: downloading bytes:           |  0.00B

train/sample_002319/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_002319/board.png: downloading bytes:           |  0.00B

train/sample_002320/board.png: reconstructing file:   0%|          |  0.00B / 14.8kB

train/sample_002320/board.png: downloading bytes:           |  0.00B

train/sample_002321/board.png: reconstructing file:   0%|          |  0.00B / 41.2kB

train/sample_002321/board.png: downloading bytes:           |  0.00B

train/sample_002322/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_002322/board.png: downloading bytes:           |  0.00B

train/sample_002323/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

train/sample_002323/board.png: downloading bytes:           |  0.00B

train/sample_002324/board.png: reconstructing file:   0%|          |  0.00B / 43.5kB

train/sample_002324/board.png: downloading bytes:           |  0.00B

train/sample_002325/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_002326/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

train/sample_002327/board.png: reconstructing file:   0%|          |  0.00B / 14.3kB

train/sample_002328/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

train/sample_002325/board.png: downloading bytes:           |  0.00B

train/sample_002326/board.png: downloading bytes:           |  0.00B

train/sample_002327/board.png: downloading bytes:           |  0.00B

train/sample_002328/board.png: downloading bytes:           |  0.00B

train/sample_002329/board.png: reconstructing file:   0%|          |  0.00B / 22.6kB

train/sample_002329/board.png: downloading bytes:           |  0.00B

train/sample_002331/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_002330/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_002330/board.png: downloading bytes:           |  0.00B

train/sample_002331/board.png: downloading bytes:           |  0.00B

train/sample_002332/board.png: reconstructing file:   0%|          |  0.00B / 42.3kB

train/sample_002332/board.png: downloading bytes:           |  0.00B

train/sample_002333/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_002333/board.png: downloading bytes:           |  0.00B

train/sample_002334/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

train/sample_002334/board.png: downloading bytes:           |  0.00B

train/sample_002336/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_002335/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_002335/board.png: downloading bytes:           |  0.00B

train/sample_002336/board.png: downloading bytes:           |  0.00B

train/sample_002337/board.png: reconstructing file:   0%|          |  0.00B / 38.0kB

train/sample_002337/board.png: downloading bytes:           |  0.00B

train/sample_002338/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_002338/board.png: downloading bytes:           |  0.00B

train/sample_002339/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_002339/board.png: downloading bytes:           |  0.00B

train/sample_002340/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

train/sample_002342/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_002341/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_002340/board.png: downloading bytes:           |  0.00B

train/sample_002342/board.png: downloading bytes:           |  0.00B

train/sample_002341/board.png: downloading bytes:           |  0.00B

train/sample_002344/board.png: reconstructing file:   0%|          |  0.00B / 42.3kB

train/sample_002344/board.png: downloading bytes:           |  0.00B

train/sample_002343/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

train/sample_002343/board.png: downloading bytes:           |  0.00B

train/sample_002345/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_002345/board.png: downloading bytes:           |  0.00B

train/sample_002346/board.png: reconstructing file:   0%|          |  0.00B / 17.0kB

train/sample_002346/board.png: downloading bytes:           |  0.00B

train/sample_002347/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_002348/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_002351/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_002350/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_002349/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_002347/board.png: downloading bytes:           |  0.00B

train/sample_002351/board.png: downloading bytes:           |  0.00B

train/sample_002348/board.png: downloading bytes:           |  0.00B

train/sample_002349/board.png: downloading bytes:           |  0.00B

train/sample_002350/board.png: downloading bytes:           |  0.00B

train/sample_002352/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_002352/board.png: downloading bytes:           |  0.00B

train/sample_002353/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_002353/board.png: downloading bytes:           |  0.00B

train/sample_002354/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_002354/board.png: downloading bytes:           |  0.00B

train/sample_002356/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002355/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_002356/board.png: downloading bytes:           |  0.00B

train/sample_002357/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_002355/board.png: downloading bytes:           |  0.00B

train/sample_002359/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_002358/board.png: reconstructing file:   0%|          |  0.00B / 22.9kB

train/sample_002357/board.png: downloading bytes:           |  0.00B

train/sample_002359/board.png: downloading bytes:           |  0.00B

train/sample_002358/board.png: downloading bytes:           |  0.00B

train/sample_002360/board.png: reconstructing file:   0%|          |  0.00B / 22.8kB

train/sample_002360/board.png: downloading bytes:           |  0.00B

train/sample_002361/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_002362/board.png: reconstructing file:   0%|          |  0.00B / 24.6kB

train/sample_002361/board.png: downloading bytes:           |  0.00B

train/sample_002362/board.png: downloading bytes:           |  0.00B

train/sample_002363/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_002364/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_002363/board.png: downloading bytes:           |  0.00B

train/sample_002364/board.png: downloading bytes:           |  0.00B

train/sample_002365/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_002366/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_002365/board.png: downloading bytes:           |  0.00B

train/sample_002366/board.png: downloading bytes:           |  0.00B

train/sample_002367/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_002367/board.png: downloading bytes:           |  0.00B

train/sample_002368/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_002368/board.png: downloading bytes:           |  0.00B

train/sample_002369/board.png: reconstructing file:   0%|          |  0.00B / 12.9kB

train/sample_002370/board.png: reconstructing file:   0%|          |  0.00B / 35.5kB

train/sample_002371/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_002372/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_002369/board.png: downloading bytes:           |  0.00B

train/sample_002370/board.png: downloading bytes:           |  0.00B

train/sample_002371/board.png: downloading bytes:           |  0.00B

train/sample_002372/board.png: downloading bytes:           |  0.00B

train/sample_002373/board.png: reconstructing file:   0%|          |  0.00B / 17.1kB

train/sample_002374/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_002374/board.png: downloading bytes:           |  0.00B

train/sample_002373/board.png: downloading bytes:           |  0.00B

train/sample_002375/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_002375/board.png: downloading bytes:           |  0.00B

train/sample_002376/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_002376/board.png: downloading bytes:           |  0.00B

train/sample_002377/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_002377/board.png: downloading bytes:           |  0.00B

train/sample_002378/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

train/sample_002378/board.png: downloading bytes:           |  0.00B

train/sample_002379/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_002379/board.png: downloading bytes:           |  0.00B

train/sample_002380/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_002381/board.png: reconstructing file:   0%|          |  0.00B / 21.6kB

train/sample_002382/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_002380/board.png: downloading bytes:           |  0.00B

train/sample_002381/board.png: downloading bytes:           |  0.00B

train/sample_002382/board.png: downloading bytes:           |  0.00B

train/sample_002383/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_002383/board.png: downloading bytes:           |  0.00B

train/sample_002384/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_002384/board.png: downloading bytes:           |  0.00B

train/sample_002385/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

train/sample_002385/board.png: downloading bytes:           |  0.00B

train/sample_002386/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

train/sample_002386/board.png: downloading bytes:           |  0.00B

train/sample_002388/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

train/sample_002387/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_002387/board.png: downloading bytes:           |  0.00B

train/sample_002388/board.png: downloading bytes:           |  0.00B

train/sample_002389/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_002390/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_002389/board.png: downloading bytes:           |  0.00B

train/sample_002390/board.png: downloading bytes:           |  0.00B

train/sample_002391/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_002391/board.png: downloading bytes:           |  0.00B

train/sample_002392/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002392/board.png: downloading bytes:           |  0.00B

train/sample_002393/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_002393/board.png: downloading bytes:           |  0.00B

train/sample_002394/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_002394/board.png: downloading bytes:           |  0.00B

train/sample_002395/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_002395/board.png: downloading bytes:           |  0.00B

train/sample_002396/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_002396/board.png: downloading bytes:           |  0.00B

train/sample_002397/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_002398/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_002398/board.png: downloading bytes:           |  0.00B

train/sample_002397/board.png: downloading bytes:           |  0.00B

train/sample_002399/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

train/sample_002399/board.png: downloading bytes:           |  0.00B

train/sample_002400/board.png: reconstructing file:   0%|          |  0.00B / 24.7kB

train/sample_002400/board.png: downloading bytes:           |  0.00B

train/sample_002401/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

train/sample_002401/board.png: downloading bytes:           |  0.00B

train/sample_002402/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

train/sample_002402/board.png: downloading bytes:           |  0.00B

train/sample_002405/board.png: reconstructing file:   0%|          |  0.00B / 19.9kB

train/sample_002404/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_002406/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

train/sample_002403/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_002403/board.png: downloading bytes:           |  0.00B

train/sample_002406/board.png: downloading bytes:           |  0.00B

train/sample_002404/board.png: downloading bytes:           |  0.00B

train/sample_002405/board.png: downloading bytes:           |  0.00B

train/sample_002407/board.png: reconstructing file:   0%|          |  0.00B / 14.9kB

train/sample_002408/board.png: reconstructing file:   0%|          |  0.00B / 21.4kB

train/sample_002407/board.png: downloading bytes:           |  0.00B

train/sample_002408/board.png: downloading bytes:           |  0.00B

train/sample_002409/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_002409/board.png: downloading bytes:           |  0.00B

train/sample_002410/board.png: reconstructing file:   0%|          |  0.00B / 18.5kB

train/sample_002410/board.png: downloading bytes:           |  0.00B

train/sample_002411/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_002411/board.png: downloading bytes:           |  0.00B

train/sample_002412/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_002412/board.png: downloading bytes:           |  0.00B

train/sample_002413/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_002413/board.png: downloading bytes:           |  0.00B

train/sample_002414/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_002414/board.png: downloading bytes:           |  0.00B

train/sample_002415/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_002415/board.png: downloading bytes:           |  0.00B

train/sample_002416/board.png: reconstructing file:   0%|          |  0.00B / 18.2kB

train/sample_002416/board.png: downloading bytes:           |  0.00B

train/sample_002417/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_002417/board.png: downloading bytes:           |  0.00B

train/sample_002418/board.png: reconstructing file:   0%|          |  0.00B / 41.4kB

train/sample_002418/board.png: downloading bytes:           |  0.00B

train/sample_002419/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_002419/board.png: downloading bytes:           |  0.00B

train/sample_002421/board.png: reconstructing file:   0%|          |  0.00B / 20.2kB

train/sample_002420/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

train/sample_002422/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_002421/board.png: downloading bytes:           |  0.00B

train/sample_002420/board.png: downloading bytes:           |  0.00B

train/sample_002422/board.png: downloading bytes:           |  0.00B

train/sample_002423/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002423/board.png: downloading bytes:           |  0.00B

train/sample_002424/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_002424/board.png: downloading bytes:           |  0.00B

train/sample_002426/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_002425/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_002425/board.png: downloading bytes:           |  0.00B

train/sample_002426/board.png: downloading bytes:           |  0.00B

train/sample_002427/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_002427/board.png: downloading bytes:           |  0.00B

train/sample_002428/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_002428/board.png: downloading bytes:           |  0.00B

train/sample_002429/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_002429/board.png: downloading bytes:           |  0.00B

train/sample_002430/board.png: reconstructing file:   0%|          |  0.00B / 23.2kB

train/sample_002431/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_002430/board.png: downloading bytes:           |  0.00B

train/sample_002431/board.png: downloading bytes:           |  0.00B

train/sample_002432/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_002432/board.png: downloading bytes:           |  0.00B

train/sample_002433/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_002433/board.png: downloading bytes:           |  0.00B

train/sample_002434/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

train/sample_002435/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_002434/board.png: downloading bytes:           |  0.00B

train/sample_002435/board.png: downloading bytes:           |  0.00B

train/sample_002436/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_002436/board.png: downloading bytes:           |  0.00B

train/sample_002437/board.png: reconstructing file:   0%|          |  0.00B / 24.3kB

train/sample_002437/board.png: downloading bytes:           |  0.00B

train/sample_002438/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_002438/board.png: downloading bytes:           |  0.00B

train/sample_002439/board.png: reconstructing file:   0%|          |  0.00B / 38.2kB

train/sample_002439/board.png: downloading bytes:           |  0.00B

train/sample_002440/board.png: reconstructing file:   0%|          |  0.00B / 14.6kB

train/sample_002440/board.png: downloading bytes:           |  0.00B

train/sample_002441/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_002441/board.png: downloading bytes:           |  0.00B

train/sample_002442/board.png: reconstructing file:   0%|          |  0.00B / 21.4kB

train/sample_002442/board.png: downloading bytes:           |  0.00B

train/sample_002443/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

train/sample_002443/board.png: downloading bytes:           |  0.00B

train/sample_002444/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_002445/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_002444/board.png: downloading bytes:           |  0.00B

train/sample_002446/board.png: reconstructing file:   0%|          |  0.00B / 40.0kB

train/sample_002445/board.png: downloading bytes:           |  0.00B

train/sample_002446/board.png: downloading bytes:           |  0.00B

train/sample_002447/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002447/board.png: downloading bytes:           |  0.00B

train/sample_002448/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002448/board.png: downloading bytes:           |  0.00B

train/sample_002449/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_002449/board.png: downloading bytes:           |  0.00B

train/sample_002450/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_002450/board.png: downloading bytes:           |  0.00B

train/sample_002451/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_002451/board.png: downloading bytes:           |  0.00B

train/sample_002452/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_002452/board.png: downloading bytes:           |  0.00B

train/sample_002453/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_002454/board.png: reconstructing file:   0%|          |  0.00B / 43.2kB

train/sample_002453/board.png: downloading bytes:           |  0.00B

train/sample_002455/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

train/sample_002454/board.png: downloading bytes:           |  0.00B

train/sample_002455/board.png: downloading bytes:           |  0.00B

train/sample_002456/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

train/sample_002456/board.png: downloading bytes:           |  0.00B

train/sample_002457/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_002457/board.png: downloading bytes:           |  0.00B

train/sample_002458/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_002458/board.png: downloading bytes:           |  0.00B

train/sample_002459/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_002459/board.png: downloading bytes:           |  0.00B

train/sample_002461/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

train/sample_002461/board.png: downloading bytes:           |  0.00B

train/sample_002460/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_002460/board.png: downloading bytes:           |  0.00B

train/sample_002462/board.png: reconstructing file:   0%|          |  0.00B / 38.2kB

train/sample_002462/board.png: downloading bytes:           |  0.00B

train/sample_002463/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_002463/board.png: downloading bytes:           |  0.00B

train/sample_002464/board.png: reconstructing file:   0%|          |  0.00B / 10.4kB

train/sample_002464/board.png: downloading bytes:           |  0.00B

train/sample_002465/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_002465/board.png: downloading bytes:           |  0.00B

train/sample_002466/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_002466/board.png: downloading bytes:           |  0.00B

train/sample_002467/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002467/board.png: downloading bytes:           |  0.00B

train/sample_002468/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_002468/board.png: downloading bytes:           |  0.00B

train/sample_002469/board.png: reconstructing file:   0%|          |  0.00B / 37.2kB

train/sample_002469/board.png: downloading bytes:           |  0.00B

train/sample_002470/board.png: reconstructing file:   0%|          |  0.00B / 43.6kB

train/sample_002470/board.png: downloading bytes:           |  0.00B

train/sample_002471/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_002471/board.png: downloading bytes:           |  0.00B

train/sample_002472/board.png: reconstructing file:   0%|          |  0.00B / 21.1kB

train/sample_002472/board.png: downloading bytes:           |  0.00B

train/sample_002473/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_002474/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_002473/board.png: downloading bytes:           |  0.00B

train/sample_002474/board.png: downloading bytes:           |  0.00B

train/sample_002475/board.png: reconstructing file:   0%|          |  0.00B / 38.7kB

train/sample_002475/board.png: downloading bytes:           |  0.00B

train/sample_002476/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_002476/board.png: downloading bytes:           |  0.00B

train/sample_002477/board.png: reconstructing file:   0%|          |  0.00B / 40.3kB

train/sample_002477/board.png: downloading bytes:           |  0.00B

train/sample_002478/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_002478/board.png: downloading bytes:           |  0.00B

train/sample_002479/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_002479/board.png: downloading bytes:           |  0.00B

train/sample_002480/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002480/board.png: downloading bytes:           |  0.00B

train/sample_002481/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_002481/board.png: downloading bytes:           |  0.00B

train/sample_002482/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_002482/board.png: downloading bytes:           |  0.00B

train/sample_002483/board.png: reconstructing file:   0%|          |  0.00B / 19.3kB

train/sample_002484/board.png: reconstructing file:   0%|          |  0.00B / 38.7kB

train/sample_002483/board.png: downloading bytes:           |  0.00B

train/sample_002485/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_002484/board.png: downloading bytes:           |  0.00B

train/sample_002485/board.png: downloading bytes:           |  0.00B

train/sample_002486/board.png: reconstructing file:   0%|          |  0.00B / 15.9kB

train/sample_002486/board.png: downloading bytes:           |  0.00B

train/sample_002487/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_002487/board.png: downloading bytes:           |  0.00B

train/sample_002488/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_002488/board.png: downloading bytes:           |  0.00B

train/sample_002489/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_002489/board.png: downloading bytes:           |  0.00B

train/sample_002490/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

train/sample_002490/board.png: downloading bytes:           |  0.00B

train/sample_002491/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_002492/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_002491/board.png: downloading bytes:           |  0.00B

train/sample_002492/board.png: downloading bytes:           |  0.00B

train/sample_002493/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_002493/board.png: downloading bytes:           |  0.00B

train/sample_002494/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_002494/board.png: downloading bytes:           |  0.00B

train/sample_002495/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_002495/board.png: downloading bytes:           |  0.00B

train/sample_002496/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_002496/board.png: downloading bytes:           |  0.00B

train/sample_002497/board.png: reconstructing file:   0%|          |  0.00B / 40.3kB

train/sample_002497/board.png: downloading bytes:           |  0.00B

train/sample_002498/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_002498/board.png: downloading bytes:           |  0.00B

train/sample_002499/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_002500/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_002499/board.png: downloading bytes:           |  0.00B

train/sample_002500/board.png: downloading bytes:           |  0.00B

train/sample_002501/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_002501/board.png: downloading bytes:           |  0.00B

train/sample_002502/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_002502/board.png: downloading bytes:           |  0.00B

train/sample_002503/board.png: reconstructing file:   0%|          |  0.00B / 18.1kB

train/sample_002503/board.png: downloading bytes:           |  0.00B

train/sample_002504/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_002504/board.png: downloading bytes:           |  0.00B

train/sample_002505/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_002505/board.png: downloading bytes:           |  0.00B

train/sample_002506/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_002506/board.png: downloading bytes:           |  0.00B

train/sample_002507/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

train/sample_002507/board.png: downloading bytes:           |  0.00B

train/sample_002508/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002508/board.png: downloading bytes:           |  0.00B

train/sample_002510/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

train/sample_002509/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

train/sample_002510/board.png: downloading bytes:           |  0.00B

train/sample_002509/board.png: downloading bytes:           |  0.00B

train/sample_002511/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_002511/board.png: downloading bytes:           |  0.00B

train/sample_002512/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_002512/board.png: downloading bytes:           |  0.00B

train/sample_002513/board.png: reconstructing file:   0%|          |  0.00B / 13.2kB

train/sample_002514/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_002515/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_002513/board.png: downloading bytes:           |  0.00B

train/sample_002514/board.png: downloading bytes:           |  0.00B

train/sample_002515/board.png: downloading bytes:           |  0.00B

train/sample_002516/board.png: reconstructing file:   0%|          |  0.00B / 15.8kB

train/sample_002516/board.png: downloading bytes:           |  0.00B

train/sample_002518/board.png: reconstructing file:   0%|          |  0.00B / 23.3kB

train/sample_002517/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

train/sample_002519/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_002518/board.png: downloading bytes:           |  0.00B

train/sample_002519/board.png: downloading bytes:           |  0.00B

train/sample_002517/board.png: downloading bytes:           |  0.00B

train/sample_002520/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_002520/board.png: downloading bytes:           |  0.00B

train/sample_002521/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

train/sample_002522/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

train/sample_002521/board.png: downloading bytes:           |  0.00B

train/sample_002523/board.png: reconstructing file:   0%|          |  0.00B / 16.3kB

train/sample_002522/board.png: downloading bytes:           |  0.00B

train/sample_002523/board.png: downloading bytes:           |  0.00B

train/sample_002524/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

train/sample_002524/board.png: downloading bytes:           |  0.00B

train/sample_002525/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002525/board.png: downloading bytes:           |  0.00B

train/sample_002526/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_002527/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_002527/board.png: downloading bytes:           |  0.00B

train/sample_002526/board.png: downloading bytes:           |  0.00B

train/sample_002528/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_002528/board.png: downloading bytes:           |  0.00B

train/sample_002529/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_002529/board.png: downloading bytes:           |  0.00B

train/sample_002530/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_002530/board.png: downloading bytes:           |  0.00B

train/sample_002531/board.png: reconstructing file:   0%|          |  0.00B / 13.8kB

train/sample_002531/board.png: downloading bytes:           |  0.00B

train/sample_002532/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_002532/board.png: downloading bytes:           |  0.00B

train/sample_002533/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_002534/board.png: reconstructing file:   0%|          |  0.00B / 17.9kB

train/sample_002533/board.png: downloading bytes:           |  0.00B

train/sample_002535/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

train/sample_002534/board.png: downloading bytes:           |  0.00B

train/sample_002535/board.png: downloading bytes:           |  0.00B

train/sample_002536/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_002536/board.png: downloading bytes:           |  0.00B

train/sample_002537/board.png: reconstructing file:   0%|          |  0.00B / 23.2kB

train/sample_002538/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_002537/board.png: downloading bytes:           |  0.00B

train/sample_002538/board.png: downloading bytes:           |  0.00B

train/sample_002539/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_002539/board.png: downloading bytes:           |  0.00B

train/sample_002540/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

train/sample_002540/board.png: downloading bytes:           |  0.00B

train/sample_002541/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_002542/board.png: reconstructing file:   0%|          |  0.00B / 37.4kB

train/sample_002541/board.png: downloading bytes:           |  0.00B

train/sample_002542/board.png: downloading bytes:           |  0.00B

train/sample_002543/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_002543/board.png: downloading bytes:           |  0.00B

train/sample_002544/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_002544/board.png: downloading bytes:           |  0.00B

train/sample_002545/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

train/sample_002545/board.png: downloading bytes:           |  0.00B

train/sample_002546/board.png: reconstructing file:   0%|          |  0.00B / 37.0kB

train/sample_002546/board.png: downloading bytes:           |  0.00B

train/sample_002547/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_002547/board.png: downloading bytes:           |  0.00B

train/sample_002548/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_002548/board.png: downloading bytes:           |  0.00B

train/sample_002549/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

train/sample_002549/board.png: downloading bytes:           |  0.00B

train/sample_002550/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_002550/board.png: downloading bytes:           |  0.00B

train/sample_002551/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_002551/board.png: downloading bytes:           |  0.00B

train/sample_002552/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_002552/board.png: downloading bytes:           |  0.00B

train/sample_002553/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_002553/board.png: downloading bytes:           |  0.00B

train/sample_002554/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_002554/board.png: downloading bytes:           |  0.00B

train/sample_002556/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_002555/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

train/sample_002555/board.png: downloading bytes:           |  0.00B

train/sample_002556/board.png: downloading bytes:           |  0.00B

train/sample_002557/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_002557/board.png: downloading bytes:           |  0.00B

train/sample_002558/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_002558/board.png: downloading bytes:           |  0.00B

train/sample_002559/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_002559/board.png: downloading bytes:           |  0.00B

train/sample_002560/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_002560/board.png: downloading bytes:           |  0.00B

train/sample_002561/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_002562/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_002561/board.png: downloading bytes:           |  0.00B

train/sample_002562/board.png: downloading bytes:           |  0.00B

train/sample_002563/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

train/sample_002563/board.png: downloading bytes:           |  0.00B

train/sample_002564/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_002564/board.png: downloading bytes:           |  0.00B

train/sample_002566/board.png: reconstructing file:   0%|          |  0.00B / 44.4kB

train/sample_002565/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_002567/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_002566/board.png: downloading bytes:           |  0.00B

train/sample_002565/board.png: downloading bytes:           |  0.00B

train/sample_002567/board.png: downloading bytes:           |  0.00B

train/sample_002568/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_002568/board.png: downloading bytes:           |  0.00B

train/sample_002569/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

train/sample_002569/board.png: downloading bytes:           |  0.00B

train/sample_002570/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_002570/board.png: downloading bytes:           |  0.00B

train/sample_002571/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_002571/board.png: downloading bytes:           |  0.00B

train/sample_002572/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_002572/board.png: downloading bytes:           |  0.00B

train/sample_002573/board.png: reconstructing file:   0%|          |  0.00B / 22.6kB

train/sample_002573/board.png: downloading bytes:           |  0.00B

train/sample_002574/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_002575/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_002574/board.png: downloading bytes:           |  0.00B

train/sample_002576/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002575/board.png: downloading bytes:           |  0.00B

train/sample_002576/board.png: downloading bytes:           |  0.00B

train/sample_002578/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_002577/board.png: reconstructing file:   0%|          |  0.00B / 42.0kB

train/sample_002578/board.png: downloading bytes:           |  0.00B

train/sample_002577/board.png: downloading bytes:           |  0.00B

train/sample_002582/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_002581/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

train/sample_002583/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

train/sample_002580/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

train/sample_002579/board.png: reconstructing file:   0%|          |  0.00B / 38.5kB

train/sample_002581/board.png: downloading bytes:           |  0.00B

train/sample_002583/board.png: downloading bytes:           |  0.00B

train/sample_002582/board.png: downloading bytes:           |  0.00B

train/sample_002580/board.png: downloading bytes:           |  0.00B

train/sample_002579/board.png: downloading bytes:           |  0.00B

train/sample_002584/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_002584/board.png: downloading bytes:           |  0.00B

train/sample_002586/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002586/board.png: downloading bytes:           |  0.00B

train/sample_002587/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

train/sample_002587/board.png: downloading bytes:           |  0.00B

train/sample_002585/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_002585/board.png: downloading bytes:           |  0.00B

train/sample_002588/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_002590/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_002589/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_002588/board.png: downloading bytes:           |  0.00B

train/sample_002591/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

train/sample_002590/board.png: downloading bytes:           |  0.00B

train/sample_002589/board.png: downloading bytes:           |  0.00B

train/sample_002591/board.png: downloading bytes:           |  0.00B

train/sample_002592/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_002592/board.png: downloading bytes:           |  0.00B

train/sample_002593/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_002594/board.png: reconstructing file:   0%|          |  0.00B / 21.4kB

train/sample_002593/board.png: downloading bytes:           |  0.00B

train/sample_002594/board.png: downloading bytes:           |  0.00B

train/sample_002595/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_002595/board.png: downloading bytes:           |  0.00B

train/sample_002596/board.png: reconstructing file:   0%|          |  0.00B / 24.7kB

train/sample_002596/board.png: downloading bytes:           |  0.00B

train/sample_002597/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_002597/board.png: downloading bytes:           |  0.00B

train/sample_002598/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_002598/board.png: downloading bytes:           |  0.00B

train/sample_002599/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_002601/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_002600/board.png: reconstructing file:   0%|          |  0.00B / 14.7kB

train/sample_002601/board.png: downloading bytes:           |  0.00B

train/sample_002599/board.png: downloading bytes:           |  0.00B

train/sample_002600/board.png: downloading bytes:           |  0.00B

train/sample_002602/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002602/board.png: downloading bytes:           |  0.00B

train/sample_002603/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002605/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_002604/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

train/sample_002603/board.png: downloading bytes:           |  0.00B

train/sample_002605/board.png: downloading bytes:           |  0.00B

train/sample_002604/board.png: downloading bytes:           |  0.00B

train/sample_002606/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

train/sample_002606/board.png: downloading bytes:           |  0.00B

train/sample_002607/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_002607/board.png: downloading bytes:           |  0.00B

train/sample_002608/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_002608/board.png: downloading bytes:           |  0.00B

train/sample_002609/board.png: reconstructing file:   0%|          |  0.00B / 39.2kB

train/sample_002609/board.png: downloading bytes:           |  0.00B

train/sample_002610/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_002610/board.png: downloading bytes:           |  0.00B

train/sample_002611/board.png: reconstructing file:   0%|          |  0.00B / 11.5kB

train/sample_002611/board.png: downloading bytes:           |  0.00B

train/sample_002612/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_002612/board.png: downloading bytes:           |  0.00B

train/sample_002613/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_002613/board.png: downloading bytes:           |  0.00B

train/sample_002614/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_002614/board.png: downloading bytes:           |  0.00B

train/sample_002615/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_002615/board.png: downloading bytes:           |  0.00B

train/sample_002616/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_002616/board.png: downloading bytes:           |  0.00B

train/sample_002618/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

train/sample_002617/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_002618/board.png: downloading bytes:           |  0.00B

train/sample_002617/board.png: downloading bytes:           |  0.00B

train/sample_002619/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

train/sample_002619/board.png: downloading bytes:           |  0.00B

train/sample_002620/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_002620/board.png: downloading bytes:           |  0.00B

train/sample_002621/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_002621/board.png: downloading bytes:           |  0.00B

train/sample_002622/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

train/sample_002622/board.png: downloading bytes:           |  0.00B

train/sample_002623/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

train/sample_002623/board.png: downloading bytes:           |  0.00B

train/sample_002624/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_002624/board.png: downloading bytes:           |  0.00B

train/sample_002625/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_002625/board.png: downloading bytes:           |  0.00B

train/sample_002626/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_002626/board.png: downloading bytes:           |  0.00B

train/sample_002627/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_002627/board.png: downloading bytes:           |  0.00B

train/sample_002628/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_002628/board.png: downloading bytes:           |  0.00B

train/sample_002629/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

train/sample_002630/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

train/sample_002629/board.png: downloading bytes:           |  0.00B

train/sample_002630/board.png: downloading bytes:           |  0.00B

train/sample_002631/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

train/sample_002631/board.png: downloading bytes:           |  0.00B

train/sample_002632/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

train/sample_002632/board.png: downloading bytes:           |  0.00B

train/sample_002633/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_002633/board.png: downloading bytes:           |  0.00B

train/sample_002634/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_002634/board.png: downloading bytes:           |  0.00B

train/sample_002635/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

train/sample_002635/board.png: downloading bytes:           |  0.00B

train/sample_002636/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_002636/board.png: downloading bytes:           |  0.00B

train/sample_002637/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

train/sample_002637/board.png: downloading bytes:           |  0.00B

train/sample_002638/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_002639/board.png: reconstructing file:   0%|          |  0.00B / 21.0kB

train/sample_002638/board.png: downloading bytes:           |  0.00B

train/sample_002639/board.png: downloading bytes:           |  0.00B

train/sample_002640/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_002640/board.png: downloading bytes:           |  0.00B

train/sample_002641/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_002642/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

train/sample_002641/board.png: downloading bytes:           |  0.00B

train/sample_002642/board.png: downloading bytes:           |  0.00B

train/sample_002643/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_002643/board.png: downloading bytes:           |  0.00B

train/sample_002644/board.png: reconstructing file:   0%|          |  0.00B / 35.9kB

train/sample_002644/board.png: downloading bytes:           |  0.00B

train/sample_002645/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_002645/board.png: downloading bytes:           |  0.00B

train/sample_002647/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

train/sample_002646/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_002646/board.png: downloading bytes:           |  0.00B

train/sample_002648/board.png: reconstructing file:   0%|          |  0.00B / 24.3kB

train/sample_002647/board.png: downloading bytes:           |  0.00B

train/sample_002649/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_002648/board.png: downloading bytes:           |  0.00B

train/sample_002649/board.png: downloading bytes:           |  0.00B

train/sample_002650/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

train/sample_002650/board.png: downloading bytes:           |  0.00B

train/sample_002651/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

train/sample_002651/board.png: downloading bytes:           |  0.00B

train/sample_002652/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_002652/board.png: downloading bytes:           |  0.00B

train/sample_002653/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_002654/board.png: reconstructing file:   0%|          |  0.00B / 21.0kB

train/sample_002653/board.png: downloading bytes:           |  0.00B

train/sample_002654/board.png: downloading bytes:           |  0.00B

train/sample_002655/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_002655/board.png: downloading bytes:           |  0.00B

train/sample_002656/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_002656/board.png: downloading bytes:           |  0.00B

train/sample_002657/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002657/board.png: downloading bytes:           |  0.00B

train/sample_002658/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

train/sample_002658/board.png: downloading bytes:           |  0.00B

train/sample_002659/board.png: reconstructing file:   0%|          |  0.00B / 17.7kB

train/sample_002661/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_002660/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_002659/board.png: downloading bytes:           |  0.00B

train/sample_002660/board.png: downloading bytes:           |  0.00B

train/sample_002661/board.png: downloading bytes:           |  0.00B

train/sample_002662/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_002662/board.png: downloading bytes:           |  0.00B

train/sample_002663/board.png: reconstructing file:   0%|          |  0.00B / 11.3kB

train/sample_002663/board.png: downloading bytes:           |  0.00B

train/sample_002664/board.png: reconstructing file:   0%|          |  0.00B / 35.5kB

train/sample_002664/board.png: downloading bytes:           |  0.00B

train/sample_002665/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_002665/board.png: downloading bytes:           |  0.00B

train/sample_002666/board.png: reconstructing file:   0%|          |  0.00B / 19.3kB

train/sample_002666/board.png: downloading bytes:           |  0.00B

train/sample_002667/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_002668/board.png: reconstructing file:   0%|          |  0.00B / 24.3kB

train/sample_002669/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

train/sample_002667/board.png: downloading bytes:           |  0.00B

train/sample_002668/board.png: downloading bytes:           |  0.00B

train/sample_002669/board.png: downloading bytes:           |  0.00B

train/sample_002670/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

train/sample_002670/board.png: downloading bytes:           |  0.00B

train/sample_002671/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

train/sample_002671/board.png: downloading bytes:           |  0.00B

train/sample_002672/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_002672/board.png: downloading bytes:           |  0.00B

train/sample_002673/board.png: reconstructing file:   0%|          |  0.00B / 23.3kB

train/sample_002673/board.png: downloading bytes:           |  0.00B

train/sample_002674/board.png: reconstructing file:   0%|          |  0.00B / 39.2kB

train/sample_002675/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_002674/board.png: downloading bytes:           |  0.00B

train/sample_002675/board.png: downloading bytes:           |  0.00B

train/sample_002676/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002676/board.png: downloading bytes:           |  0.00B

train/sample_002677/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_002677/board.png: downloading bytes:           |  0.00B

train/sample_002678/board.png: reconstructing file:   0%|          |  0.00B / 44.2kB

train/sample_002679/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_002678/board.png: downloading bytes:           |  0.00B

train/sample_002679/board.png: downloading bytes:           |  0.00B

train/sample_002680/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

train/sample_002680/board.png: downloading bytes:           |  0.00B

train/sample_002681/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_002681/board.png: downloading bytes:           |  0.00B

train/sample_002682/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_002682/board.png: downloading bytes:           |  0.00B

train/sample_002683/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_002683/board.png: downloading bytes:           |  0.00B

train/sample_002686/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_002684/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_002687/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_002685/board.png: reconstructing file:   0%|          |  0.00B / 19.2kB

train/sample_002685/board.png: downloading bytes:           |  0.00B

train/sample_002687/board.png: downloading bytes:           |  0.00B

train/sample_002684/board.png: downloading bytes:           |  0.00B

train/sample_002686/board.png: downloading bytes:           |  0.00B

train/sample_002688/board.png: reconstructing file:   0%|          |  0.00B / 25.2kB

train/sample_002688/board.png: downloading bytes:           |  0.00B

train/sample_002689/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_002689/board.png: downloading bytes:           |  0.00B

train/sample_002690/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_002690/board.png: downloading bytes:           |  0.00B

train/sample_002691/board.png: reconstructing file:   0%|          |  0.00B / 21.7kB

train/sample_002691/board.png: downloading bytes:           |  0.00B

train/sample_002692/board.png: reconstructing file:   0%|          |  0.00B / 22.0kB

train/sample_002693/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_002692/board.png: downloading bytes:           |  0.00B

train/sample_002693/board.png: downloading bytes:           |  0.00B

train/sample_002694/board.png: reconstructing file:   0%|          |  0.00B / 23.2kB

train/sample_002694/board.png: downloading bytes:           |  0.00B

train/sample_002696/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_002695/board.png: reconstructing file:   0%|          |  0.00B / 38.7kB

train/sample_002696/board.png: downloading bytes:           |  0.00B

train/sample_002695/board.png: downloading bytes:           |  0.00B

train/sample_002697/board.png: reconstructing file:   0%|          |  0.00B / 17.4kB

train/sample_002697/board.png: downloading bytes:           |  0.00B

train/sample_002698/board.png: reconstructing file:   0%|          |  0.00B / 35.5kB

train/sample_002698/board.png: downloading bytes:           |  0.00B

train/sample_002699/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_002699/board.png: downloading bytes:           |  0.00B

train/sample_002700/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_002700/board.png: downloading bytes:           |  0.00B

train/sample_002701/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

train/sample_002702/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_002702/board.png: downloading bytes:           |  0.00B

train/sample_002701/board.png: downloading bytes:           |  0.00B

train/sample_002703/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_002703/board.png: downloading bytes:           |  0.00B

train/sample_002704/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_002704/board.png: downloading bytes:           |  0.00B

train/sample_002705/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_002705/board.png: downloading bytes:           |  0.00B

train/sample_002706/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

train/sample_002706/board.png: downloading bytes:           |  0.00B

train/sample_002707/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_002707/board.png: downloading bytes:           |  0.00B

train/sample_002708/board.png: reconstructing file:   0%|          |  0.00B / 18.6kB

train/sample_002708/board.png: downloading bytes:           |  0.00B

train/sample_002709/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_002710/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

train/sample_002709/board.png: downloading bytes:           |  0.00B

train/sample_002711/board.png: reconstructing file:   0%|          |  0.00B / 37.4kB

train/sample_002710/board.png: downloading bytes:           |  0.00B

train/sample_002711/board.png: downloading bytes:           |  0.00B

train/sample_002712/board.png: reconstructing file:   0%|          |  0.00B / 17.1kB

train/sample_002712/board.png: downloading bytes:           |  0.00B

train/sample_002713/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002713/board.png: downloading bytes:           |  0.00B

train/sample_002714/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_002715/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_002714/board.png: downloading bytes:           |  0.00B

train/sample_002715/board.png: downloading bytes:           |  0.00B

train/sample_002716/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

train/sample_002716/board.png: downloading bytes:           |  0.00B

train/sample_002717/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_002717/board.png: downloading bytes:           |  0.00B

train/sample_002718/board.png: reconstructing file:   0%|          |  0.00B / 15.3kB

train/sample_002718/board.png: downloading bytes:           |  0.00B

train/sample_002719/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002719/board.png: downloading bytes:           |  0.00B

train/sample_002720/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_002720/board.png: downloading bytes:           |  0.00B

train/sample_002721/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_002721/board.png: downloading bytes:           |  0.00B

train/sample_002722/board.png: reconstructing file:   0%|          |  0.00B / 21.8kB

train/sample_002722/board.png: downloading bytes:           |  0.00B

train/sample_002723/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_002723/board.png: downloading bytes:           |  0.00B

train/sample_002724/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_002724/board.png: downloading bytes:           |  0.00B

train/sample_002725/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

train/sample_002726/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_002725/board.png: downloading bytes:           |  0.00B

train/sample_002726/board.png: downloading bytes:           |  0.00B

train/sample_002727/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_002727/board.png: downloading bytes:           |  0.00B

train/sample_002729/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_002730/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_002732/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_002728/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_002729/board.png: downloading bytes:           |  0.00B

train/sample_002731/board.png: reconstructing file:   0%|          |  0.00B / 19.5kB

train/sample_002728/board.png: downloading bytes:           |  0.00B

train/sample_002731/board.png: downloading bytes:           |  0.00B

train/sample_002732/board.png: downloading bytes:           |  0.00B

train/sample_002730/board.png: downloading bytes:           |  0.00B

train/sample_002734/board.png: reconstructing file:   0%|          |  0.00B / 19.9kB

train/sample_002734/board.png: downloading bytes:           |  0.00B

train/sample_002733/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_002733/board.png: downloading bytes:           |  0.00B

train/sample_002735/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_002735/board.png: downloading bytes:           |  0.00B

train/sample_002736/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_002736/board.png: downloading bytes:           |  0.00B

train/sample_002737/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

train/sample_002737/board.png: downloading bytes:           |  0.00B

train/sample_002738/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_002739/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_002740/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002741/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002741/board.png: downloading bytes:           |  0.00B

train/sample_002739/board.png: downloading bytes:           |  0.00B

train/sample_002738/board.png: downloading bytes:           |  0.00B

train/sample_002740/board.png: downloading bytes:           |  0.00B

train/sample_002742/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_002742/board.png: downloading bytes:           |  0.00B

train/sample_002743/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_002743/board.png: downloading bytes:           |  0.00B

train/sample_002744/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_002744/board.png: downloading bytes:           |  0.00B

train/sample_002745/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_002745/board.png: downloading bytes:           |  0.00B

train/sample_002746/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

train/sample_002746/board.png: downloading bytes:           |  0.00B

train/sample_002747/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_002747/board.png: downloading bytes:           |  0.00B

train/sample_002748/board.png: reconstructing file:   0%|          |  0.00B / 17.7kB

train/sample_002748/board.png: downloading bytes:           |  0.00B

train/sample_002749/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002749/board.png: downloading bytes:           |  0.00B

train/sample_002750/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

train/sample_002750/board.png: downloading bytes:           |  0.00B

train/sample_002751/board.png: reconstructing file:   0%|          |  0.00B / 13.1kB

train/sample_002751/board.png: downloading bytes:           |  0.00B

train/sample_002752/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_002753/board.png: reconstructing file:   0%|          |  0.00B / 15.6kB

train/sample_002752/board.png: downloading bytes:           |  0.00B

train/sample_002753/board.png: downloading bytes:           |  0.00B

train/sample_002754/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_002754/board.png: downloading bytes:           |  0.00B

train/sample_002755/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

train/sample_002755/board.png: downloading bytes:           |  0.00B

train/sample_002756/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_002756/board.png: downloading bytes:           |  0.00B

train/sample_002757/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_002757/board.png: downloading bytes:           |  0.00B

train/sample_002758/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_002758/board.png: downloading bytes:           |  0.00B

train/sample_002759/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

train/sample_002759/board.png: downloading bytes:           |  0.00B

train/sample_002760/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_002760/board.png: downloading bytes:           |  0.00B

train/sample_002761/board.png: reconstructing file:   0%|          |  0.00B / 22.0kB

train/sample_002761/board.png: downloading bytes:           |  0.00B

train/sample_002762/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_002762/board.png: downloading bytes:           |  0.00B

train/sample_002763/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_002763/board.png: downloading bytes:           |  0.00B

train/sample_002764/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_002765/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_002766/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_002764/board.png: downloading bytes:           |  0.00B

train/sample_002766/board.png: downloading bytes:           |  0.00B

train/sample_002765/board.png: downloading bytes:           |  0.00B

train/sample_002767/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_002767/board.png: downloading bytes:           |  0.00B

train/sample_002768/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_002768/board.png: downloading bytes:           |  0.00B

train/sample_002770/board.png: reconstructing file:   0%|          |  0.00B / 44.1kB

train/sample_002769/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_002770/board.png: downloading bytes:           |  0.00B

train/sample_002769/board.png: downloading bytes:           |  0.00B

train/sample_002771/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_002772/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_002771/board.png: downloading bytes:           |  0.00B

train/sample_002772/board.png: downloading bytes:           |  0.00B

train/sample_002773/board.png: reconstructing file:   0%|          |  0.00B / 40.2kB

train/sample_002773/board.png: downloading bytes:           |  0.00B

train/sample_002774/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002774/board.png: downloading bytes:           |  0.00B

train/sample_002775/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_002775/board.png: downloading bytes:           |  0.00B

train/sample_002776/board.png: reconstructing file:   0%|          |  0.00B / 38.2kB

train/sample_002776/board.png: downloading bytes:           |  0.00B

train/sample_002777/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_002777/board.png: downloading bytes:           |  0.00B

train/sample_002778/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002778/board.png: downloading bytes:           |  0.00B

train/sample_002779/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_002779/board.png: downloading bytes:           |  0.00B

train/sample_002781/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_002780/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_002782/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

train/sample_002782/board.png: downloading bytes:           |  0.00B

train/sample_002781/board.png: downloading bytes:           |  0.00B

train/sample_002780/board.png: downloading bytes:           |  0.00B

train/sample_002783/board.png: reconstructing file:   0%|          |  0.00B / 17.1kB

train/sample_002783/board.png: downloading bytes:           |  0.00B

train/sample_002784/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_002784/board.png: downloading bytes:           |  0.00B

train/sample_002785/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

train/sample_002787/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

train/sample_002785/board.png: downloading bytes:           |  0.00B

train/sample_002787/board.png: downloading bytes:           |  0.00B

train/sample_002786/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_002790/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

train/sample_002788/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_002786/board.png: downloading bytes:           |  0.00B

train/sample_002788/board.png: downloading bytes:           |  0.00B

train/sample_002790/board.png: downloading bytes:           |  0.00B

train/sample_002789/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_002789/board.png: downloading bytes:           |  0.00B

train/sample_002791/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

train/sample_002791/board.png: downloading bytes:           |  0.00B

train/sample_002792/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_002792/board.png: downloading bytes:           |  0.00B

train/sample_002793/board.png: reconstructing file:   0%|          |  0.00B / 12.5kB

train/sample_002794/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_002793/board.png: downloading bytes:           |  0.00B

train/sample_002794/board.png: downloading bytes:           |  0.00B

train/sample_002795/board.png: reconstructing file:   0%|          |  0.00B / 18.5kB

train/sample_002795/board.png: downloading bytes:           |  0.00B

train/sample_002796/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_002797/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_002796/board.png: downloading bytes:           |  0.00B

train/sample_002797/board.png: downloading bytes:           |  0.00B

train/sample_002798/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_002798/board.png: downloading bytes:           |  0.00B

train/sample_002799/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_002799/board.png: downloading bytes:           |  0.00B

train/sample_002800/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_002800/board.png: downloading bytes:           |  0.00B

train/sample_002801/board.png: reconstructing file:   0%|          |  0.00B / 40.9kB

train/sample_002801/board.png: downloading bytes:           |  0.00B

train/sample_002802/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_002802/board.png: downloading bytes:           |  0.00B

train/sample_002803/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_002803/board.png: downloading bytes:           |  0.00B

train/sample_002804/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_002804/board.png: downloading bytes:           |  0.00B

train/sample_002805/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_002805/board.png: downloading bytes:           |  0.00B

train/sample_002806/board.png: reconstructing file:   0%|          |  0.00B / 40.0kB

train/sample_002806/board.png: downloading bytes:           |  0.00B

train/sample_002807/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_002807/board.png: downloading bytes:           |  0.00B

train/sample_002808/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

train/sample_002808/board.png: downloading bytes:           |  0.00B

train/sample_002809/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_002809/board.png: downloading bytes:           |  0.00B

train/sample_002810/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

train/sample_002810/board.png: downloading bytes:           |  0.00B

train/sample_002811/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_002811/board.png: downloading bytes:           |  0.00B

train/sample_002812/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_002812/board.png: downloading bytes:           |  0.00B

train/sample_002813/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002813/board.png: downloading bytes:           |  0.00B

train/sample_002814/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_002814/board.png: downloading bytes:           |  0.00B

train/sample_002815/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_002815/board.png: downloading bytes:           |  0.00B

train/sample_002816/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_002816/board.png: downloading bytes:           |  0.00B

train/sample_002817/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_002817/board.png: downloading bytes:           |  0.00B

train/sample_002818/board.png: reconstructing file:   0%|          |  0.00B / 43.1kB

train/sample_002818/board.png: downloading bytes:           |  0.00B

train/sample_002819/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

train/sample_002820/board.png: reconstructing file:   0%|          |  0.00B / 13.8kB

train/sample_002821/board.png: reconstructing file:   0%|          |  0.00B / 24.6kB

train/sample_002821/board.png: downloading bytes:           |  0.00B

train/sample_002819/board.png: downloading bytes:           |  0.00B

train/sample_002820/board.png: downloading bytes:           |  0.00B

train/sample_002822/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

train/sample_002822/board.png: downloading bytes:           |  0.00B

train/sample_002823/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

train/sample_002823/board.png: downloading bytes:           |  0.00B

train/sample_002824/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_002824/board.png: downloading bytes:           |  0.00B

train/sample_002825/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

train/sample_002825/board.png: downloading bytes:           |  0.00B

train/sample_002826/board.png: reconstructing file:   0%|          |  0.00B / 37.2kB

train/sample_002827/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

train/sample_002828/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_002829/board.png: reconstructing file:   0%|          |  0.00B / 34.1kB

train/sample_002826/board.png: downloading bytes:           |  0.00B

train/sample_002828/board.png: downloading bytes:           |  0.00B

train/sample_002827/board.png: downloading bytes:           |  0.00B

train/sample_002829/board.png: downloading bytes:           |  0.00B

train/sample_002830/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002830/board.png: downloading bytes:           |  0.00B

train/sample_002831/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_002831/board.png: downloading bytes:           |  0.00B

train/sample_002832/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_002832/board.png: downloading bytes:           |  0.00B

train/sample_002833/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_002833/board.png: downloading bytes:           |  0.00B

train/sample_002837/board.png: reconstructing file:   0%|          |  0.00B / 21.4kB

train/sample_002834/board.png: reconstructing file:   0%|          |  0.00B / 19.5kB

train/sample_002835/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_002836/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_002834/board.png: downloading bytes:           |  0.00B

train/sample_002837/board.png: downloading bytes:           |  0.00B

train/sample_002836/board.png: downloading bytes:           |  0.00B

train/sample_002835/board.png: downloading bytes:           |  0.00B

train/sample_002838/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

train/sample_002838/board.png: downloading bytes:           |  0.00B

train/sample_002839/board.png: reconstructing file:   0%|          |  0.00B / 22.8kB

train/sample_002840/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_002839/board.png: downloading bytes:           |  0.00B

train/sample_002840/board.png: downloading bytes:           |  0.00B

train/sample_002841/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_002842/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_002843/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_002841/board.png: downloading bytes:           |  0.00B

train/sample_002844/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_002845/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_002842/board.png: downloading bytes:           |  0.00B

train/sample_002843/board.png: downloading bytes:           |  0.00B

train/sample_002845/board.png: downloading bytes:           |  0.00B

train/sample_002844/board.png: downloading bytes:           |  0.00B

train/sample_002847/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_002846/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_002847/board.png: downloading bytes:           |  0.00B

train/sample_002846/board.png: downloading bytes:           |  0.00B

train/sample_002848/board.png: reconstructing file:   0%|          |  0.00B / 38.0kB

train/sample_002848/board.png: downloading bytes:           |  0.00B

train/sample_002849/board.png: reconstructing file:   0%|          |  0.00B / 21.8kB

train/sample_002849/board.png: downloading bytes:           |  0.00B

train/sample_002850/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

train/sample_002853/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_002850/board.png: downloading bytes:           |  0.00B

train/sample_002851/board.png: reconstructing file:   0%|          |  0.00B / 42.7kB

train/sample_002852/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_002853/board.png: downloading bytes:           |  0.00B

train/sample_002851/board.png: downloading bytes:           |  0.00B

train/sample_002852/board.png: downloading bytes:           |  0.00B

train/sample_002854/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_002854/board.png: downloading bytes:           |  0.00B

train/sample_002855/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_002855/board.png: downloading bytes:           |  0.00B

train/sample_002856/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_002856/board.png: downloading bytes:           |  0.00B

train/sample_002858/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

train/sample_002857/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_002858/board.png: downloading bytes:           |  0.00B

train/sample_002857/board.png: downloading bytes:           |  0.00B

train/sample_002859/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

train/sample_002859/board.png: downloading bytes:           |  0.00B

train/sample_002860/board.png: reconstructing file:   0%|          |  0.00B / 16.8kB

train/sample_002860/board.png: downloading bytes:           |  0.00B

train/sample_002861/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_002862/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

train/sample_002861/board.png: downloading bytes:           |  0.00B

train/sample_002863/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_002862/board.png: downloading bytes:           |  0.00B

train/sample_002864/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_002864/board.png: downloading bytes:           |  0.00B

train/sample_002863/board.png: downloading bytes:           |  0.00B

train/sample_002865/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_002865/board.png: downloading bytes:           |  0.00B

train/sample_002866/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_002866/board.png: downloading bytes:           |  0.00B

train/sample_002867/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_002868/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_002867/board.png: downloading bytes:           |  0.00B

train/sample_002868/board.png: downloading bytes:           |  0.00B

train/sample_002869/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

train/sample_002869/board.png: downloading bytes:           |  0.00B

train/sample_002870/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002870/board.png: downloading bytes:           |  0.00B

train/sample_002871/board.png: reconstructing file:   0%|          |  0.00B / 13.3kB

train/sample_002871/board.png: downloading bytes:           |  0.00B

train/sample_002872/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_002872/board.png: downloading bytes:           |  0.00B

train/sample_002873/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002873/board.png: downloading bytes:           |  0.00B

train/sample_002874/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

train/sample_002875/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

train/sample_002874/board.png: downloading bytes:           |  0.00B

train/sample_002875/board.png: downloading bytes:           |  0.00B

train/sample_002876/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_002876/board.png: downloading bytes:           |  0.00B

train/sample_002878/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

train/sample_002878/board.png: downloading bytes:           |  0.00B

train/sample_002877/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_002877/board.png: downloading bytes:           |  0.00B

train/sample_002879/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_002880/board.png: reconstructing file:   0%|          |  0.00B / 16.3kB

train/sample_002879/board.png: downloading bytes:           |  0.00B

train/sample_002880/board.png: downloading bytes:           |  0.00B

train/sample_002881/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_002882/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_002881/board.png: downloading bytes:           |  0.00B

train/sample_002883/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

train/sample_002882/board.png: downloading bytes:           |  0.00B

train/sample_002883/board.png: downloading bytes:           |  0.00B

train/sample_002884/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_002884/board.png: downloading bytes:           |  0.00B

train/sample_002885/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_002885/board.png: downloading bytes:           |  0.00B

train/sample_002886/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

train/sample_002886/board.png: downloading bytes:           |  0.00B

train/sample_002887/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

train/sample_002888/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_002887/board.png: downloading bytes:           |  0.00B

train/sample_002888/board.png: downloading bytes:           |  0.00B

train/sample_002889/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_002890/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

train/sample_002889/board.png: downloading bytes:           |  0.00B

train/sample_002890/board.png: downloading bytes:           |  0.00B

train/sample_002891/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_002891/board.png: downloading bytes:           |  0.00B

train/sample_002892/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_002892/board.png: downloading bytes:           |  0.00B

train/sample_002893/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_002893/board.png: downloading bytes:           |  0.00B

train/sample_002894/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_002894/board.png: downloading bytes:           |  0.00B

train/sample_002895/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_002895/board.png: downloading bytes:           |  0.00B

train/sample_002896/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_002896/board.png: downloading bytes:           |  0.00B

train/sample_002897/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_002897/board.png: downloading bytes:           |  0.00B

train/sample_002898/board.png: reconstructing file:   0%|          |  0.00B / 14.6kB

train/sample_002898/board.png: downloading bytes:           |  0.00B

train/sample_002899/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

train/sample_002899/board.png: downloading bytes:           |  0.00B

train/sample_002900/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_002900/board.png: downloading bytes:           |  0.00B

train/sample_002901/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_002901/board.png: downloading bytes:           |  0.00B

train/sample_002902/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_002903/board.png: reconstructing file:   0%|          |  0.00B / 39.3kB

train/sample_002904/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

train/sample_002902/board.png: downloading bytes:           |  0.00B

train/sample_002903/board.png: downloading bytes:           |  0.00B

train/sample_002904/board.png: downloading bytes:           |  0.00B

train/sample_002905/board.png: reconstructing file:   0%|          |  0.00B / 12.9kB

train/sample_002905/board.png: downloading bytes:           |  0.00B

train/sample_002906/board.png: reconstructing file:   0%|          |  0.00B / 22.9kB

train/sample_002906/board.png: downloading bytes:           |  0.00B

train/sample_002907/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_002907/board.png: downloading bytes:           |  0.00B

train/sample_002908/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

train/sample_002908/board.png: downloading bytes:           |  0.00B

train/sample_002909/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_002909/board.png: downloading bytes:           |  0.00B

train/sample_002910/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_002910/board.png: downloading bytes:           |  0.00B

train/sample_002911/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_002912/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

train/sample_002911/board.png: downloading bytes:           |  0.00B

train/sample_002912/board.png: downloading bytes:           |  0.00B

train/sample_002913/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

train/sample_002913/board.png: downloading bytes:           |  0.00B

train/sample_002915/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

train/sample_002914/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

train/sample_002915/board.png: downloading bytes:           |  0.00B

train/sample_002914/board.png: downloading bytes:           |  0.00B

train/sample_002916/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

train/sample_002916/board.png: downloading bytes:           |  0.00B

train/sample_002917/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

train/sample_002917/board.png: downloading bytes:           |  0.00B

train/sample_002918/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_002918/board.png: downloading bytes:           |  0.00B

train/sample_002919/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_002919/board.png: downloading bytes:           |  0.00B

train/sample_002920/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_002920/board.png: downloading bytes:           |  0.00B

train/sample_002921/board.png: reconstructing file:   0%|          |  0.00B / 17.0kB

train/sample_002921/board.png: downloading bytes:           |  0.00B

train/sample_002922/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

train/sample_002922/board.png: downloading bytes:           |  0.00B

train/sample_002923/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_002923/board.png: downloading bytes:           |  0.00B

train/sample_002924/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

train/sample_002924/board.png: downloading bytes:           |  0.00B

train/sample_002925/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

train/sample_002925/board.png: downloading bytes:           |  0.00B

train/sample_002926/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

train/sample_002926/board.png: downloading bytes:           |  0.00B

train/sample_002927/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002927/board.png: downloading bytes:           |  0.00B

train/sample_002928/board.png: reconstructing file:   0%|          |  0.00B / 39.8kB

train/sample_002928/board.png: downloading bytes:           |  0.00B

train/sample_002929/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_002929/board.png: downloading bytes:           |  0.00B

train/sample_002930/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_002931/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_002930/board.png: downloading bytes:           |  0.00B

train/sample_002931/board.png: downloading bytes:           |  0.00B

train/sample_002932/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_002932/board.png: downloading bytes:           |  0.00B

train/sample_002933/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

train/sample_002933/board.png: downloading bytes:           |  0.00B

train/sample_002934/board.png: reconstructing file:   0%|          |  0.00B / 37.0kB

train/sample_002934/board.png: downloading bytes:           |  0.00B

train/sample_002935/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_002935/board.png: downloading bytes:           |  0.00B

train/sample_002936/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_002936/board.png: downloading bytes:           |  0.00B

train/sample_002937/board.png: reconstructing file:   0%|          |  0.00B / 18.9kB

train/sample_002937/board.png: downloading bytes:           |  0.00B

train/sample_002938/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_002938/board.png: downloading bytes:           |  0.00B

train/sample_002939/board.png: reconstructing file:   0%|          |  0.00B / 16.5kB

train/sample_002940/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

train/sample_002939/board.png: downloading bytes:           |  0.00B

train/sample_002940/board.png: downloading bytes:           |  0.00B

train/sample_002941/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

train/sample_002941/board.png: downloading bytes:           |  0.00B

train/sample_002942/board.png: reconstructing file:   0%|          |  0.00B / 22.9kB

train/sample_002942/board.png: downloading bytes:           |  0.00B

train/sample_002943/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_002943/board.png: downloading bytes:           |  0.00B

train/sample_002944/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_002944/board.png: downloading bytes:           |  0.00B

train/sample_002947/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_002946/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_002945/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

train/sample_002948/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_002947/board.png: downloading bytes:           |  0.00B

train/sample_002946/board.png: downloading bytes:           |  0.00B

train/sample_002945/board.png: downloading bytes:           |  0.00B

train/sample_002948/board.png: downloading bytes:           |  0.00B

train/sample_002949/board.png: reconstructing file:   0%|          |  0.00B / 38.5kB

train/sample_002949/board.png: downloading bytes:           |  0.00B

train/sample_002950/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_002950/board.png: downloading bytes:           |  0.00B

train/sample_002951/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_002951/board.png: downloading bytes:           |  0.00B

train/sample_002952/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_002952/board.png: downloading bytes:           |  0.00B

train/sample_002953/board.png: reconstructing file:   0%|          |  0.00B / 21.3kB

train/sample_002955/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_002954/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

train/sample_002956/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_002953/board.png: downloading bytes:           |  0.00B

train/sample_002955/board.png: downloading bytes:           |  0.00B

train/sample_002954/board.png: downloading bytes:           |  0.00B

train/sample_002956/board.png: downloading bytes:           |  0.00B

train/sample_002957/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

train/sample_002957/board.png: downloading bytes:           |  0.00B

train/sample_002958/board.png: reconstructing file:   0%|          |  0.00B / 13.0kB

train/sample_002958/board.png: downloading bytes:           |  0.00B

train/sample_002959/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_002959/board.png: downloading bytes:           |  0.00B

train/sample_002960/board.png: reconstructing file:   0%|          |  0.00B / 37.2kB

train/sample_002960/board.png: downloading bytes:           |  0.00B

train/sample_002961/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

train/sample_002961/board.png: downloading bytes:           |  0.00B

train/sample_002962/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

train/sample_002962/board.png: downloading bytes:           |  0.00B

train/sample_002963/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

train/sample_002963/board.png: downloading bytes:           |  0.00B

train/sample_002964/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

train/sample_002964/board.png: downloading bytes:           |  0.00B

train/sample_002965/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

train/sample_002965/board.png: downloading bytes:           |  0.00B

train/sample_002966/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

train/sample_002966/board.png: downloading bytes:           |  0.00B

train/sample_002967/board.png: reconstructing file:   0%|          |  0.00B / 20.7kB

train/sample_002967/board.png: downloading bytes:           |  0.00B

train/sample_002968/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_002968/board.png: downloading bytes:           |  0.00B

train/sample_002969/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

train/sample_002969/board.png: downloading bytes:           |  0.00B

train/sample_002970/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

train/sample_002970/board.png: downloading bytes:           |  0.00B

train/sample_002971/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_002971/board.png: downloading bytes:           |  0.00B

train/sample_002972/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_002972/board.png: downloading bytes:           |  0.00B

train/sample_002973/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_002974/board.png: reconstructing file:   0%|          |  0.00B / 41.6kB

train/sample_002973/board.png: downloading bytes:           |  0.00B

train/sample_002974/board.png: downloading bytes:           |  0.00B

train/sample_002975/board.png: reconstructing file:   0%|          |  0.00B / 41.4kB

train/sample_002975/board.png: downloading bytes:           |  0.00B

train/sample_002976/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_002976/board.png: downloading bytes:           |  0.00B

train/sample_002977/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_002977/board.png: downloading bytes:           |  0.00B

train/sample_002979/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

train/sample_002978/board.png: reconstructing file:   0%|          |  0.00B / 43.5kB

train/sample_002978/board.png: downloading bytes:           |  0.00B

train/sample_002979/board.png: downloading bytes:           |  0.00B

train/sample_002980/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_002980/board.png: downloading bytes:           |  0.00B

train/sample_002981/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_002981/board.png: downloading bytes:           |  0.00B

train/sample_002982/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

train/sample_002982/board.png: downloading bytes:           |  0.00B

HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002983/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002983/board.png
Rate limited. Waiting 105.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 105.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002985/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002985/board.png
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002984/board.png
Rate limited. Waiting 105.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002984/board.png
Rate limited. Waiting 105.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 105.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 105.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002986/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002986/board.png
Rate limited. Waiting 105.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 105.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002987/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002987/board.png
Rate limited. Waiting 105.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 105.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002988/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002988/board.png
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002989/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002989/board.png
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002990/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002990/board.png
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002991/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002991/board.png
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002992/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002992/board.png
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002993/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002993/board.png
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002994/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002994/board.png
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002995/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002995/board.png
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002996/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002996/board.png
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002997/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002997/board.png
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002998/board.png
WARNING:huggingface_hub.utils._http:HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/bdatm-project/dataset_task1/resolve/177153e18b78e9eaefc5962f756e9f4e48603637/train/sample_002998/board.png
Rate limited. Waiting 104.0s before retry [Retry 1/5].
WARNING:huggingface_hub.utils._http:Rate limited. Waiting 104.0s before retry [Retry 1/5].

train/sample_002988/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

train/sample_002988/board.png: downloading bytes:           |  0.00B

train/sample_002989/board.png: reconstructing file:   0%|          |  0.00B / 40.7kB

train/sample_002989/board.png: downloading bytes:           |  0.00B

train/sample_002990/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_002992/board.png: reconstructing file:   0%|          |  0.00B / 14.6kB

train/sample_002990/board.png: downloading bytes:           |  0.00B

train/sample_002992/board.png: downloading bytes:           |  0.00B

train/sample_002991/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_002991/board.png: downloading bytes:           |  0.00B

train/sample_002993/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_002993/board.png: downloading bytes:           |  0.00B

train/sample_002995/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

train/sample_002995/board.png: downloading bytes:           |  0.00B

train/sample_002994/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_002994/board.png: downloading bytes:           |  0.00B

train/sample_002996/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_002996/board.png: downloading bytes:           |  0.00B

train/sample_002997/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

train/sample_002997/board.png: downloading bytes:           |  0.00B

train/sample_002998/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_002998/board.png: downloading bytes:           |  0.00B

train/sample_002999/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

train/sample_002983/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

train/sample_003000/board.png: reconstructing file:   0%|          |  0.00B / 16.7kB

train/sample_002999/board.png: downloading bytes:           |  0.00B

train/sample_003001/board.png: reconstructing file:   0%|          |  0.00B / 15.7kB

train/sample_002985/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_002984/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

train/sample_003000/board.png: downloading bytes:           |  0.00B

train/sample_002983/board.png: downloading bytes:           |  0.00B

train/sample_003001/board.png: downloading bytes:           |  0.00B

train/sample_002984/board.png: downloading bytes:           |  0.00B

train/sample_002985/board.png: downloading bytes:           |  0.00B

train/sample_002986/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_003002/board.png: reconstructing file:   0%|          |  0.00B / 41.0kB

train/sample_002987/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

train/sample_003003/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_002986/board.png: downloading bytes:           |  0.00B

train/sample_003002/board.png: downloading bytes:           |  0.00B

train/sample_003003/board.png: downloading bytes:           |  0.00B

train/sample_002987/board.png: downloading bytes:           |  0.00B

train/sample_003004/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_003004/board.png: downloading bytes:           |  0.00B

train/sample_003006/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_003005/board.png: reconstructing file:   0%|          |  0.00B / 21.4kB

train/sample_003006/board.png: downloading bytes:           |  0.00B

train/sample_003005/board.png: downloading bytes:           |  0.00B

train/sample_003007/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

train/sample_003007/board.png: downloading bytes:           |  0.00B

train/sample_003008/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_003008/board.png: downloading bytes:           |  0.00B

train/sample_003009/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

train/sample_003009/board.png: downloading bytes:           |  0.00B

train/sample_003010/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_003010/board.png: downloading bytes:           |  0.00B

train/sample_003012/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_003011/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_003013/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

train/sample_003014/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_003012/board.png: downloading bytes:           |  0.00B

train/sample_003015/board.png: reconstructing file:   0%|          |  0.00B / 13.6kB

train/sample_003011/board.png: downloading bytes:           |  0.00B

train/sample_003013/board.png: downloading bytes:           |  0.00B

train/sample_003014/board.png: downloading bytes:           |  0.00B

train/sample_003015/board.png: downloading bytes:           |  0.00B

train/sample_003016/board.png: reconstructing file:   0%|          |  0.00B / 38.9kB

train/sample_003016/board.png: downloading bytes:           |  0.00B

train/sample_003017/board.png: reconstructing file:   0%|          |  0.00B / 21.0kB

train/sample_003017/board.png: downloading bytes:           |  0.00B

train/sample_003018/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

train/sample_003019/board.png: reconstructing file:   0%|          |  0.00B / 41.1kB

train/sample_003018/board.png: downloading bytes:           |  0.00B

train/sample_003019/board.png: downloading bytes:           |  0.00B

train/sample_003020/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

train/sample_003020/board.png: downloading bytes:           |  0.00B

train/sample_003021/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

train/sample_003022/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

train/sample_003021/board.png: downloading bytes:           |  0.00B

train/sample_003022/board.png: downloading bytes:           |  0.00B

train/sample_003023/board.png: reconstructing file:   0%|          |  0.00B / 42.5kB

train/sample_003023/board.png: downloading bytes:           |  0.00B

train/sample_003024/board.png: reconstructing file:   0%|          |  0.00B / 43.3kB

train/sample_003024/board.png: downloading bytes:           |  0.00B

train/sample_003025/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

train/sample_003025/board.png: downloading bytes:           |  0.00B

train/sample_003026/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

train/sample_003026/board.png: downloading bytes:           |  0.00B

train/sample_003027/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

train/sample_003027/board.png: downloading bytes:           |  0.00B

train/sample_003028/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

train/sample_003028/board.png: downloading bytes:           |  0.00B

train/sample_003029/board.png: reconstructing file:   0%|          |  0.00B / 38.5kB

train/sample_003029/board.png: downloading bytes:           |  0.00B

train/sample_003030/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

train/sample_003030/board.png: downloading bytes:           |  0.00B

train/sample_003031/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_003031/board.png: downloading bytes:           |  0.00B

train/sample_003032/board.png: reconstructing file:   0%|          |  0.00B / 40.4kB

train/sample_003032/board.png: downloading bytes:           |  0.00B

train/sample_003033/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_003033/board.png: downloading bytes:           |  0.00B

train/sample_003034/board.png: reconstructing file:   0%|          |  0.00B / 21.2kB

train/sample_003034/board.png: downloading bytes:           |  0.00B

train/sample_003035/board.png: reconstructing file:   0%|          |  0.00B / 24.6kB

train/sample_003035/board.png: downloading bytes:           |  0.00B

train/sample_003036/board.png: reconstructing file:   0%|          |  0.00B / 24.5kB

train/sample_003036/board.png: downloading bytes:           |  0.00B

train/sample_003037/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

train/sample_003037/board.png: downloading bytes:           |  0.00B

train/sample_003039/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

train/sample_003038/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

train/sample_003039/board.png: downloading bytes:           |  0.00B

train/sample_003038/board.png: downloading bytes:           |  0.00B

train/sample_003040/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

train/sample_003040/board.png: downloading bytes:           |  0.00B

train/sample_003041/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

train/sample_003041/board.png: downloading bytes:           |  0.00B

train/sample_003042/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

train/sample_003042/board.png: downloading bytes:           |  0.00B

train/sample_003043/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_003043/board.png: downloading bytes:           |  0.00B

train/sample_003044/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

train/sample_003045/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_003044/board.png: downloading bytes:           |  0.00B

train/sample_003045/board.png: downloading bytes:           |  0.00B

train/sample_003047/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_003046/board.png: reconstructing file:   0%|          |  0.00B / 40.9kB

train/sample_003047/board.png: downloading bytes:           |  0.00B

train/sample_003046/board.png: downloading bytes:           |  0.00B

train/sample_003048/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_003048/board.png: downloading bytes:           |  0.00B

train/sample_003049/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

train/sample_003049/board.png: downloading bytes:           |  0.00B

train/sample_003050/board.png: reconstructing file:   0%|          |  0.00B / 41.8kB

train/sample_003050/board.png: downloading bytes:           |  0.00B

train/sample_003051/board.png: reconstructing file:   0%|          |  0.00B / 37.4kB

train/sample_003052/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

train/sample_003051/board.png: downloading bytes:           |  0.00B

train/sample_003052/board.png: downloading bytes:           |  0.00B

train/sample_003053/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

train/sample_003053/board.png: downloading bytes:           |  0.00B

train/sample_003054/board.png: reconstructing file:   0%|          |  0.00B / 41.4kB

train/sample_003054/board.png: downloading bytes:           |  0.00B

train/sample_003055/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_003055/board.png: downloading bytes:           |  0.00B

train/sample_003056/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_003056/board.png: downloading bytes:           |  0.00B

train/sample_003057/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

train/sample_003057/board.png: downloading bytes:           |  0.00B

train/sample_003058/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_003058/board.png: downloading bytes:           |  0.00B

train/sample_003059/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

train/sample_003059/board.png: downloading bytes:           |  0.00B

train/sample_003060/board.png: reconstructing file:   0%|          |  0.00B / 35.3kB

train/sample_003060/board.png: downloading bytes:           |  0.00B

train/sample_003061/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_003061/board.png: downloading bytes:           |  0.00B

train/sample_003062/board.png: reconstructing file:   0%|          |  0.00B / 23.2kB

train/sample_003062/board.png: downloading bytes:           |  0.00B

train/sample_003063/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

train/sample_003063/board.png: downloading bytes:           |  0.00B

train/sample_003064/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

train/sample_003065/board.png: reconstructing file:   0%|          |  0.00B / 19.1kB

train/sample_003064/board.png: downloading bytes:           |  0.00B

train/sample_003065/board.png: downloading bytes:           |  0.00B

train/sample_003066/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

train/sample_003067/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

train/sample_003066/board.png: downloading bytes:           |  0.00B

train/sample_003068/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

train/sample_003067/board.png: downloading bytes:           |  0.00B

train/sample_003068/board.png: downloading bytes:           |  0.00B

train/sample_003069/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

train/sample_003069/board.png: downloading bytes:           |  0.00B

train/sample_003070/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

train/sample_003070/board.png: downloading bytes:           |  0.00B

train/sample_003071/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

train/sample_003071/board.png: downloading bytes:           |  0.00B

train/sample_003072/board.png: reconstructing file:   0%|          |  0.00B / 23.2kB

train/sample_003073/board.png: reconstructing file:   0%|          |  0.00B / 17.1kB

train/sample_003073/board.png: downloading bytes:           |  0.00B

train/sample_003072/board.png: downloading bytes:           |  0.00B

train/sample_003074/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

train/sample_003074/board.png: downloading bytes:           |  0.00B

train/sample_003075/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_003075/board.png: downloading bytes:           |  0.00B

train/sample_003076/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

train/sample_003076/board.png: downloading bytes:           |  0.00B

train/sample_003077/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_003077/board.png: downloading bytes:           |  0.00B

train/sample_003078/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

train/sample_003078/board.png: downloading bytes:           |  0.00B

train/sample_003079/board.png: reconstructing file:   0%|          |  0.00B / 40.3kB

train/sample_003079/board.png: downloading bytes:           |  0.00B

train/sample_003080/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

train/sample_003080/board.png: downloading bytes:           |  0.00B

train/sample_003081/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

train/sample_003081/board.png: downloading bytes:           |  0.00B

train/sample_003082/board.png: reconstructing file:   0%|          |  0.00B / 10.4kB

train/sample_003082/board.png: downloading bytes:           |  0.00B

train/sample_003083/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

train/sample_003083/board.png: downloading bytes:           |  0.00B

train/sample_003084/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

train/sample_003084/board.png: downloading bytes:           |  0.00B

train/sample_003085/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

train/sample_003085/board.png: downloading bytes:           |  0.00B

train/sample_003086/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_003086/board.png: downloading bytes:           |  0.00B

train/sample_003088/board.png: reconstructing file:   0%|          |  0.00B / 17.0kB

train/sample_003087/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

train/sample_003088/board.png: downloading bytes:           |  0.00B

train/sample_003087/board.png: downloading bytes:           |  0.00B

train/sample_003089/board.png: reconstructing file:   0%|          |  0.00B / 39.4kB

train/sample_003089/board.png: downloading bytes:           |  0.00B

train/sample_003090/board.png: reconstructing file:   0%|          |  0.00B / 44.8kB

train/sample_003090/board.png: downloading bytes:           |  0.00B

train/sample_003091/board.png: reconstructing file:   0%|          |  0.00B / 11.9kB

train/sample_003091/board.png: downloading bytes:           |  0.00B

train/sample_003092/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_003093/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

train/sample_003092/board.png: downloading bytes:           |  0.00B

train/sample_003093/board.png: downloading bytes:           |  0.00B

train/sample_003094/board.png: reconstructing file:   0%|          |  0.00B / 35.2kB

train/sample_003094/board.png: downloading bytes:           |  0.00B

train/sample_003095/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

train/sample_003096/board.png: reconstructing file:   0%|          |  0.00B / 21.1kB

train/sample_003095/board.png: downloading bytes:           |  0.00B

train/sample_003096/board.png: downloading bytes:           |  0.00B

train/sample_003097/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_003097/board.png: downloading bytes:           |  0.00B

train/sample_003099/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

train/sample_003099/board.png: downloading bytes:           |  0.00B

train/sample_003098/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

train/sample_003098/board.png: downloading bytes:           |  0.00B

train/sample_003100/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

train/sample_003100/board.png: downloading bytes:           |  0.00B

train/sample_003101/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

train/sample_003101/board.png: downloading bytes:           |  0.00B

train/sample_003102/board.png: reconstructing file:   0%|          |  0.00B / 19.8kB

train/sample_003102/board.png: downloading bytes:           |  0.00B

train/sample_003103/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

train/sample_003103/board.png: downloading bytes:           |  0.00B

train/sample_003104/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_003104/board.png: downloading bytes:           |  0.00B

train/sample_003105/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

train/sample_003105/board.png: downloading bytes:           |  0.00B

train/sample_003106/board.png: reconstructing file:   0%|          |  0.00B / 15.7kB

train/sample_003106/board.png: downloading bytes:           |  0.00B

train/sample_003107/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

train/sample_003107/board.png: downloading bytes:           |  0.00B

train/sample_003108/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_003108/board.png: downloading bytes:           |  0.00B

train/sample_003109/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

train/sample_003109/board.png: downloading bytes:           |  0.00B

train/sample_003110/board.png: reconstructing file:   0%|          |  0.00B / 14.4kB

train/sample_003110/board.png: downloading bytes:           |  0.00B

train/sample_003111/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

train/sample_003111/board.png: downloading bytes:           |  0.00B

train/sample_003112/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

train/sample_003112/board.png: downloading bytes:           |  0.00B

train/sample_003113/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_003113/board.png: downloading bytes:           |  0.00B

train/sample_003114/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

train/sample_003114/board.png: downloading bytes:           |  0.00B

train/sample_003115/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

train/sample_003115/board.png: downloading bytes:           |  0.00B

train/sample_003116/board.png: reconstructing file:   0%|          |  0.00B / 38.9kB

train/sample_003116/board.png: downloading bytes:           |  0.00B

train/sample_003117/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

train/sample_003117/board.png: downloading bytes:           |  0.00B

train/sample_003118/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

train/sample_003118/board.png: downloading bytes:           |  0.00B

train/sample_003119/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

train/sample_003120/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_003121/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_003120/board.png: downloading bytes:           |  0.00B

train/sample_003119/board.png: downloading bytes:           |  0.00B

train/sample_003121/board.png: downloading bytes:           |  0.00B

train/sample_003122/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

train/sample_003122/board.png: downloading bytes:           |  0.00B

train/sample_003123/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

train/sample_003123/board.png: downloading bytes:           |  0.00B

train/sample_003124/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

train/sample_003124/board.png: downloading bytes:           |  0.00B

train/sample_003125/board.png: reconstructing file:   0%|          |  0.00B / 40.4kB

train/sample_003125/board.png: downloading bytes:           |  0.00B

train/sample_003126/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

train/sample_003126/board.png: downloading bytes:           |  0.00B

train/sample_003127/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

train/sample_003127/board.png: downloading bytes:           |  0.00B

train/sample_003129/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

train/sample_003128/board.png: reconstructing file:   0%|          |  0.00B / 14.8kB

train/sample_003129/board.png: downloading bytes:           |  0.00B

train/sample_003128/board.png: downloading bytes:           |  0.00B

train/sample_003130/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

train/sample_003130/board.png: downloading bytes:           |  0.00B

train/sample_003131/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

train/sample_003131/board.png: downloading bytes:           |  0.00B

train/sample_003132/board.png: reconstructing file:   0%|          |  0.00B / 21.1kB

train/sample_003132/board.png: downloading bytes:           |  0.00B

train/sample_003133/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

train/sample_003134/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

train/sample_003135/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

train/sample_003133/board.png: downloading bytes:           |  0.00B

train/sample_003134/board.png: downloading bytes:           |  0.00B

train/sample_003135/board.png: downloading bytes:           |  0.00B

train/sample_003136/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

train/sample_003136/board.png: downloading bytes:           |  0.00B

train/sample_003137/board.png: reconstructing file:   0%|          |  0.00B / 21.7kB

train/sample_003137/board.png: downloading bytes:           |  0.00B

train/sample_003138/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

train/sample_003138/board.png: downloading bytes:           |  0.00B

train/sample_003139/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

train/sample_003139/board.png: downloading bytes:           |  0.00B

train/sample_003140/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

train/sample_003140/board.png: downloading bytes:           |  0.00B

train/sample_003141/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

train/sample_003141/board.png: downloading bytes:           |  0.00B

train/sample_003142/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

train/sample_003143/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

train/sample_003143/board.png: downloading bytes:           |  0.00B

train/sample_003142/board.png: downloading bytes:           |  0.00B

train/sample_003144/board.png: reconstructing file:   0%|          |  0.00B / 18.9kB

train/sample_003144/board.png: downloading bytes:           |  0.00B

train/sample_003145/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

train/sample_003145/board.png: downloading bytes:           |  0.00B

train/sample_003146/board.png: reconstructing file:   0%|          |  0.00B / 40.7kB

train/sample_003146/board.png: downloading bytes:           |  0.00B

train/sample_003147/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

train/sample_003147/board.png: downloading bytes:           |  0.00B

train/sample_003148/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_003148/board.png: downloading bytes:           |  0.00B

train/sample_003149/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

train/sample_003149/board.png: downloading bytes:           |  0.00B

train/sample_003150/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_003150/board.png: downloading bytes:           |  0.00B

train/sample_003151/board.png: reconstructing file:   0%|          |  0.00B / 12.7kB

train/sample_003151/board.png: downloading bytes:           |  0.00B

train/sample_003152/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

train/sample_003152/board.png: downloading bytes:           |  0.00B

train/sample_003153/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

train/sample_003154/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

train/sample_003154/board.png: downloading bytes:           |  0.00B

train/sample_003153/board.png: downloading bytes:           |  0.00B

train/sample_003155/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

train/sample_003155/board.png: downloading bytes:           |  0.00B

train/sample_003156/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

train/sample_003156/board.png: downloading bytes:           |  0.00B

train/sample_003157/board.png: reconstructing file:   0%|          |  0.00B / 11.5kB

train/sample_003157/board.png: downloading bytes:           |  0.00B

train/sample_003158/board.png: reconstructing file:   0%|          |  0.00B / 21.6kB

train/sample_003158/board.png: downloading bytes:           |  0.00B

train/sample_003159/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

train/sample_003159/board.png: downloading bytes:           |  0.00B

train/sample_003160/board.png: reconstructing file:   0%|          |  0.00B / 40.9kB

train/sample_003162/board.png: reconstructing file:   0%|          |  0.00B / 15.4kB

train/sample_003161/board.png: reconstructing file:   0%|          |  0.00B / 13.2kB

train/sample_003160/board.png: downloading bytes:           |  0.00B

train/sample_003161/board.png: downloading bytes:           |  0.00B

train/sample_003162/board.png: downloading bytes:           |  0.00B

train/sample_003163/board.png: reconstructing file:   0%|          |  0.00B / 17.1kB

train/sample_003163/board.png: downloading bytes:           |  0.00B

train/sample_003164/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

train/sample_003164/board.png: downloading bytes:           |  0.00B

train/sample_003165/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

train/sample_003165/board.png: downloading bytes:           |  0.00B

train/sample_003166/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

train/sample_003166/board.png: downloading bytes:           |  0.00B

train/sample_003167/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

train/sample_003167/board.png: downloading bytes:           |  0.00B

train/sample_003168/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

train/sample_003168/board.png: downloading bytes:           |  0.00B

train/sample_003170/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

train/sample_003169/board.png: reconstructing file:   0%|          |  0.00B / 41.5kB

train/sample_003170/board.png: downloading bytes:           |  0.00B

train/sample_003169/board.png: downloading bytes:           |  0.00B

train/sample_003171/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

train/sample_003171/board.png: downloading bytes:           |  0.00B

train/sample_003172/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

train/sample_003173/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_003172/board.png: downloading bytes:           |  0.00B

train/sample_003173/board.png: downloading bytes:           |  0.00B

train/sample_003174/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

train/sample_003174/board.png: downloading bytes:           |  0.00B

train/sample_003176/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_003176/board.png: downloading bytes:           |  0.00B

train/sample_003177/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

train/sample_003175/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

train/sample_003178/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

train/sample_003177/board.png: downloading bytes:           |  0.00B

train/sample_003175/board.png: downloading bytes:           |  0.00B

train/sample_003178/board.png: downloading bytes:           |  0.00B

train/sample_003179/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_003179/board.png: downloading bytes:           |  0.00B

train/sample_003180/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

train/sample_003181/board.png: reconstructing file:   0%|          |  0.00B / 22.9kB

train/sample_003180/board.png: downloading bytes:           |  0.00B

train/sample_003181/board.png: downloading bytes:           |  0.00B

train/sample_003182/board.png: reconstructing file:   0%|          |  0.00B / 36.6kB

train/sample_003182/board.png: downloading bytes:           |  0.00B

train/sample_003183/board.png: reconstructing file:   0%|          |  0.00B / 22.3kB

train/sample_003184/board.png: reconstructing file:   0%|          |  0.00B / 38.6kB

train/sample_003186/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

train/sample_003185/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

train/sample_003183/board.png: downloading bytes:           |  0.00B

train/sample_003184/board.png: downloading bytes:           |  0.00B

train/sample_003186/board.png: downloading bytes:           |  0.00B

train/sample_003185/board.png: downloading bytes:           |  0.00B

train/sample_003187/board.png: reconstructing file:   0%|          |  0.00B / 24.3kB

train/sample_003187/board.png: downloading bytes:           |  0.00B

train/sample_003188/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

train/sample_003189/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

train/sample_003189/board.png: downloading bytes:           |  0.00B

train/sample_003188/board.png: downloading bytes:           |  0.00B

train/sample_003190/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

train/sample_003190/board.png: downloading bytes:           |  0.00B

train/sample_003191/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

train/sample_003191/board.png: downloading bytes:           |  0.00B

train/sample_003192/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

train/sample_003193/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

train/sample_003194/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

train/sample_003193/board.png: downloading bytes:           |  0.00B

train/sample_003194/board.png: downloading bytes:           |  0.00B

train/sample_003192/board.png: downloading bytes:           |  0.00B

train/sample_003195/board.png: reconstructing file:   0%|          |  0.00B / 41.2kB

train/sample_003195/board.png: downloading bytes:           |  0.00B

train/sample_003196/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

train/sample_003196/board.png: downloading bytes:           |  0.00B

train/sample_003197/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

train/sample_003197/board.png: downloading bytes:           |  0.00B

train/sample_003198/board.png: reconstructing file:   0%|          |  0.00B / 19.3kB

train/sample_003198/board.png: downloading bytes:           |  0.00B

train/sample_003199/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

train/sample_003199/board.png: downloading bytes:           |  0.00B

metadata.jsonl:   0%|          | 0.00/1.88M [00:00<?, ?B/s]

validation/sample_000001/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

Downloading data:   0%|          | 0/400 [00:00<?, ?files/s]

validation/sample_000000/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

validation/sample_000011/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

validation/sample_000003/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

validation/sample_000006/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

validation/sample_000012/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

validation/sample_000007/board.png: reconstructing file:   0%|          |  0.00B / 17.4kB

validation/sample_000008/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

validation/sample_000002/board.png: reconstructing file:   0%|          |  0.00B / 17.1kB

validation/sample_000009/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

validation/sample_000013/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

validation/sample_000010/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

validation/sample_000014/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

validation/sample_000005/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

validation/sample_000015/board.png: reconstructing file:   0%|          |  0.00B / 21.0kB

validation/sample_000004/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

validation/sample_000001/board.png: downloading bytes:           |  0.00B

validation/sample_000000/board.png: downloading bytes:           |  0.00B

validation/sample_000011/board.png: downloading bytes:           |  0.00B

validation/sample_000003/board.png: downloading bytes:           |  0.00B

validation/sample_000006/board.png: downloading bytes:           |  0.00B

validation/sample_000008/board.png: downloading bytes:           |  0.00B

validation/sample_000007/board.png: downloading bytes:           |  0.00B

validation/sample_000012/board.png: downloading bytes:           |  0.00B

validation/sample_000002/board.png: downloading bytes:           |  0.00B

validation/sample_000009/board.png: downloading bytes:           |  0.00B

validation/sample_000010/board.png: downloading bytes:           |  0.00B

validation/sample_000013/board.png: downloading bytes:           |  0.00B

validation/sample_000014/board.png: downloading bytes:           |  0.00B

validation/sample_000015/board.png: downloading bytes:           |  0.00B

validation/sample_000005/board.png: downloading bytes:           |  0.00B

validation/sample_000004/board.png: downloading bytes:           |  0.00B

validation/sample_000016/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

validation/sample_000018/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

validation/sample_000017/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

validation/sample_000016/board.png: downloading bytes:           |  0.00B

validation/sample_000019/board.png: reconstructing file:   0%|          |  0.00B / 10.4kB

validation/sample_000020/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

validation/sample_000021/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

validation/sample_000018/board.png: downloading bytes:           |  0.00B

validation/sample_000017/board.png: downloading bytes:           |  0.00B

validation/sample_000022/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

validation/sample_000019/board.png: downloading bytes:           |  0.00B

validation/sample_000020/board.png: downloading bytes:           |  0.00B

validation/sample_000021/board.png: downloading bytes:           |  0.00B

validation/sample_000022/board.png: downloading bytes:           |  0.00B

validation/sample_000023/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

validation/sample_000023/board.png: downloading bytes:           |  0.00B

validation/sample_000024/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

validation/sample_000024/board.png: downloading bytes:           |  0.00B

validation/sample_000025/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

validation/sample_000025/board.png: downloading bytes:           |  0.00B

validation/sample_000026/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

validation/sample_000028/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

validation/sample_000027/board.png: reconstructing file:   0%|          |  0.00B / 13.1kB

validation/sample_000029/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

validation/sample_000026/board.png: downloading bytes:           |  0.00B

validation/sample_000028/board.png: downloading bytes:           |  0.00B

validation/sample_000027/board.png: downloading bytes:           |  0.00B

validation/sample_000029/board.png: downloading bytes:           |  0.00B

validation/sample_000030/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

validation/sample_000030/board.png: downloading bytes:           |  0.00B

validation/sample_000031/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

validation/sample_000031/board.png: downloading bytes:           |  0.00B

validation/sample_000032/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

validation/sample_000032/board.png: downloading bytes:           |  0.00B

validation/sample_000034/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

validation/sample_000033/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

validation/sample_000035/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

validation/sample_000033/board.png: downloading bytes:           |  0.00B

validation/sample_000036/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

validation/sample_000034/board.png: downloading bytes:           |  0.00B

validation/sample_000037/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

validation/sample_000035/board.png: downloading bytes:           |  0.00B

validation/sample_000037/board.png: downloading bytes:           |  0.00B

validation/sample_000036/board.png: downloading bytes:           |  0.00B

validation/sample_000038/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

validation/sample_000038/board.png: downloading bytes:           |  0.00B

validation/sample_000039/board.png: reconstructing file:   0%|          |  0.00B / 13.6kB

validation/sample_000039/board.png: downloading bytes:           |  0.00B

validation/sample_000040/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

validation/sample_000041/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

validation/sample_000040/board.png: downloading bytes:           |  0.00B

validation/sample_000041/board.png: downloading bytes:           |  0.00B

validation/sample_000042/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

validation/sample_000042/board.png: downloading bytes:           |  0.00B

validation/sample_000044/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

validation/sample_000043/board.png: reconstructing file:   0%|          |  0.00B / 24.6kB

validation/sample_000045/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

validation/sample_000046/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

validation/sample_000044/board.png: downloading bytes:           |  0.00B

validation/sample_000043/board.png: downloading bytes:           |  0.00B

validation/sample_000045/board.png: downloading bytes:           |  0.00B

validation/sample_000046/board.png: downloading bytes:           |  0.00B

validation/sample_000047/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

validation/sample_000047/board.png: downloading bytes:           |  0.00B

validation/sample_000048/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

validation/sample_000049/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

validation/sample_000050/board.png: reconstructing file:   0%|          |  0.00B / 40.4kB

validation/sample_000048/board.png: downloading bytes:           |  0.00B

validation/sample_000052/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

validation/sample_000051/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

validation/sample_000049/board.png: downloading bytes:           |  0.00B

validation/sample_000050/board.png: downloading bytes:           |  0.00B

validation/sample_000053/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

validation/sample_000051/board.png: downloading bytes:           |  0.00B

validation/sample_000052/board.png: downloading bytes:           |  0.00B

validation/sample_000054/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

validation/sample_000053/board.png: downloading bytes:           |  0.00B

validation/sample_000054/board.png: downloading bytes:           |  0.00B

validation/sample_000055/board.png: reconstructing file:   0%|          |  0.00B / 23.2kB

validation/sample_000055/board.png: downloading bytes:           |  0.00B

validation/sample_000056/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

validation/sample_000056/board.png: downloading bytes:           |  0.00B

validation/sample_000057/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

validation/sample_000057/board.png: downloading bytes:           |  0.00B

validation/sample_000058/board.png: reconstructing file:   0%|          |  0.00B / 13.5kB

validation/sample_000058/board.png: downloading bytes:           |  0.00B

validation/sample_000059/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

validation/sample_000059/board.png: downloading bytes:           |  0.00B

validation/sample_000060/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

validation/sample_000061/board.png: reconstructing file:   0%|          |  0.00B / 41.1kB

validation/sample_000060/board.png: downloading bytes:           |  0.00B

validation/sample_000061/board.png: downloading bytes:           |  0.00B

validation/sample_000062/board.png: reconstructing file:   0%|          |  0.00B / 34.8kB

validation/sample_000062/board.png: downloading bytes:           |  0.00B

validation/sample_000063/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

validation/sample_000063/board.png: downloading bytes:           |  0.00B

validation/sample_000064/board.png: reconstructing file:   0%|          |  0.00B / 19.3kB

validation/sample_000064/board.png: downloading bytes:           |  0.00B

validation/sample_000065/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

validation/sample_000065/board.png: downloading bytes:           |  0.00B

validation/sample_000066/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

validation/sample_000067/board.png: reconstructing file:   0%|          |  0.00B / 25.5kB

validation/sample_000066/board.png: downloading bytes:           |  0.00B

validation/sample_000067/board.png: downloading bytes:           |  0.00B

validation/sample_000068/board.png: reconstructing file:   0%|          |  0.00B / 21.0kB

validation/sample_000068/board.png: downloading bytes:           |  0.00B

validation/sample_000069/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

validation/sample_000069/board.png: downloading bytes:           |  0.00B

validation/sample_000070/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

validation/sample_000070/board.png: downloading bytes:           |  0.00B

validation/sample_000071/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

validation/sample_000071/board.png: downloading bytes:           |  0.00B

validation/sample_000072/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

validation/sample_000072/board.png: downloading bytes:           |  0.00B

validation/sample_000073/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

validation/sample_000073/board.png: downloading bytes:           |  0.00B

validation/sample_000074/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

validation/sample_000074/board.png: downloading bytes:           |  0.00B

validation/sample_000075/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

validation/sample_000075/board.png: downloading bytes:           |  0.00B

validation/sample_000076/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

validation/sample_000076/board.png: downloading bytes:           |  0.00B

validation/sample_000077/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

validation/sample_000078/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

validation/sample_000077/board.png: downloading bytes:           |  0.00B

validation/sample_000078/board.png: downloading bytes:           |  0.00B

validation/sample_000079/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

validation/sample_000079/board.png: downloading bytes:           |  0.00B

validation/sample_000080/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

validation/sample_000080/board.png: downloading bytes:           |  0.00B

validation/sample_000081/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

validation/sample_000081/board.png: downloading bytes:           |  0.00B

validation/sample_000082/board.png: reconstructing file:   0%|          |  0.00B / 21.0kB

validation/sample_000082/board.png: downloading bytes:           |  0.00B

validation/sample_000083/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

validation/sample_000083/board.png: downloading bytes:           |  0.00B

validation/sample_000084/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

validation/sample_000084/board.png: downloading bytes:           |  0.00B

validation/sample_000086/board.png: reconstructing file:   0%|          |  0.00B / 19.2kB

validation/sample_000085/board.png: reconstructing file:   0%|          |  0.00B / 45.1kB

validation/sample_000085/board.png: downloading bytes:           |  0.00B

validation/sample_000086/board.png: downloading bytes:           |  0.00B

validation/sample_000087/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

validation/sample_000088/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

validation/sample_000087/board.png: downloading bytes:           |  0.00B

validation/sample_000088/board.png: downloading bytes:           |  0.00B

validation/sample_000091/board.png: reconstructing file:   0%|          |  0.00B / 40.0kB

validation/sample_000090/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

validation/sample_000089/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

validation/sample_000091/board.png: downloading bytes:           |  0.00B

validation/sample_000090/board.png: downloading bytes:           |  0.00B

validation/sample_000092/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

validation/sample_000089/board.png: downloading bytes:           |  0.00B

validation/sample_000092/board.png: downloading bytes:           |  0.00B

validation/sample_000093/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

validation/sample_000093/board.png: downloading bytes:           |  0.00B

validation/sample_000094/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

validation/sample_000094/board.png: downloading bytes:           |  0.00B

validation/sample_000095/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

validation/sample_000096/board.png: reconstructing file:   0%|          |  0.00B / 15.8kB

validation/sample_000095/board.png: downloading bytes:           |  0.00B

validation/sample_000096/board.png: downloading bytes:           |  0.00B

validation/sample_000097/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

validation/sample_000097/board.png: downloading bytes:           |  0.00B

validation/sample_000098/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

validation/sample_000099/board.png: reconstructing file:   0%|          |  0.00B / 17.1kB

validation/sample_000098/board.png: downloading bytes:           |  0.00B

validation/sample_000099/board.png: downloading bytes:           |  0.00B

validation/sample_000100/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

validation/sample_000100/board.png: downloading bytes:           |  0.00B

validation/sample_000101/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

validation/sample_000101/board.png: downloading bytes:           |  0.00B

validation/sample_000102/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

validation/sample_000102/board.png: downloading bytes:           |  0.00B

validation/sample_000103/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

validation/sample_000103/board.png: downloading bytes:           |  0.00B

validation/sample_000104/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

validation/sample_000104/board.png: downloading bytes:           |  0.00B

validation/sample_000105/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

validation/sample_000105/board.png: downloading bytes:           |  0.00B

validation/sample_000106/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

validation/sample_000106/board.png: downloading bytes:           |  0.00B

validation/sample_000107/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

validation/sample_000108/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

validation/sample_000107/board.png: downloading bytes:           |  0.00B

validation/sample_000108/board.png: downloading bytes:           |  0.00B

validation/sample_000109/board.png: reconstructing file:   0%|          |  0.00B / 40.5kB

validation/sample_000109/board.png: downloading bytes:           |  0.00B

validation/sample_000110/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

validation/sample_000110/board.png: downloading bytes:           |  0.00B

validation/sample_000111/board.png: reconstructing file:   0%|          |  0.00B / 14.4kB

validation/sample_000111/board.png: downloading bytes:           |  0.00B

validation/sample_000112/board.png: reconstructing file:   0%|          |  0.00B / 15.7kB

validation/sample_000112/board.png: downloading bytes:           |  0.00B

validation/sample_000113/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

validation/sample_000113/board.png: downloading bytes:           |  0.00B

validation/sample_000114/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

validation/sample_000114/board.png: downloading bytes:           |  0.00B

validation/sample_000115/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

validation/sample_000115/board.png: downloading bytes:           |  0.00B

validation/sample_000116/board.png: reconstructing file:   0%|          |  0.00B / 17.0kB

validation/sample_000117/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

validation/sample_000116/board.png: downloading bytes:           |  0.00B

validation/sample_000119/board.png: reconstructing file:   0%|          |  0.00B / 16.3kB

validation/sample_000118/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

validation/sample_000117/board.png: downloading bytes:           |  0.00B

validation/sample_000119/board.png: downloading bytes:           |  0.00B

validation/sample_000118/board.png: downloading bytes:           |  0.00B

validation/sample_000120/board.png: reconstructing file:   0%|          |  0.00B / 35.9kB

validation/sample_000120/board.png: downloading bytes:           |  0.00B

validation/sample_000121/board.png: reconstructing file:   0%|          |  0.00B / 26.2kB

validation/sample_000121/board.png: downloading bytes:           |  0.00B

validation/sample_000123/board.png: reconstructing file:   0%|          |  0.00B / 14.8kB

validation/sample_000122/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

validation/sample_000122/board.png: downloading bytes:           |  0.00B

validation/sample_000123/board.png: downloading bytes:           |  0.00B

validation/sample_000124/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

validation/sample_000124/board.png: downloading bytes:           |  0.00B

validation/sample_000125/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

validation/sample_000125/board.png: downloading bytes:           |  0.00B

validation/sample_000126/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

validation/sample_000126/board.png: downloading bytes:           |  0.00B

validation/sample_000127/board.png: reconstructing file:   0%|          |  0.00B / 13.0kB

validation/sample_000127/board.png: downloading bytes:           |  0.00B

validation/sample_000128/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

validation/sample_000128/board.png: downloading bytes:           |  0.00B

validation/sample_000129/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

validation/sample_000129/board.png: downloading bytes:           |  0.00B

validation/sample_000131/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

validation/sample_000130/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

validation/sample_000131/board.png: downloading bytes:           |  0.00B

validation/sample_000130/board.png: downloading bytes:           |  0.00B

validation/sample_000132/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

validation/sample_000132/board.png: downloading bytes:           |  0.00B

validation/sample_000133/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

validation/sample_000133/board.png: downloading bytes:           |  0.00B

validation/sample_000134/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

validation/sample_000134/board.png: downloading bytes:           |  0.00B

validation/sample_000135/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

validation/sample_000135/board.png: downloading bytes:           |  0.00B

validation/sample_000136/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

validation/sample_000136/board.png: downloading bytes:           |  0.00B

validation/sample_000137/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

validation/sample_000137/board.png: downloading bytes:           |  0.00B

validation/sample_000138/board.png: reconstructing file:   0%|          |  0.00B / 16.4kB

validation/sample_000138/board.png: downloading bytes:           |  0.00B

validation/sample_000139/board.png: reconstructing file:   0%|          |  0.00B / 43.1kB

validation/sample_000139/board.png: downloading bytes:           |  0.00B

validation/sample_000140/board.png: reconstructing file:   0%|          |  0.00B / 16.9kB

validation/sample_000140/board.png: downloading bytes:           |  0.00B

validation/sample_000141/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

validation/sample_000141/board.png: downloading bytes:           |  0.00B

validation/sample_000142/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

validation/sample_000142/board.png: downloading bytes:           |  0.00B

validation/sample_000143/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

validation/sample_000143/board.png: downloading bytes:           |  0.00B

validation/sample_000144/board.png: reconstructing file:   0%|          |  0.00B / 22.8kB

validation/sample_000144/board.png: downloading bytes:           |  0.00B

validation/sample_000145/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

validation/sample_000145/board.png: downloading bytes:           |  0.00B

validation/sample_000146/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

validation/sample_000147/board.png: reconstructing file:   0%|          |  0.00B / 22.6kB

validation/sample_000146/board.png: downloading bytes:           |  0.00B

validation/sample_000147/board.png: downloading bytes:           |  0.00B

validation/sample_000148/board.png: reconstructing file:   0%|          |  0.00B / 24.7kB

validation/sample_000148/board.png: downloading bytes:           |  0.00B

validation/sample_000149/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

validation/sample_000149/board.png: downloading bytes:           |  0.00B

validation/sample_000150/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

validation/sample_000150/board.png: downloading bytes:           |  0.00B

validation/sample_000151/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

validation/sample_000151/board.png: downloading bytes:           |  0.00B

validation/sample_000152/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

validation/sample_000152/board.png: downloading bytes:           |  0.00B

validation/sample_000153/board.png: reconstructing file:   0%|          |  0.00B / 37.4kB

validation/sample_000154/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

validation/sample_000155/board.png: reconstructing file:   0%|          |  0.00B / 13.6kB

validation/sample_000153/board.png: downloading bytes:           |  0.00B

validation/sample_000154/board.png: downloading bytes:           |  0.00B

validation/sample_000155/board.png: downloading bytes:           |  0.00B

validation/sample_000156/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

validation/sample_000156/board.png: downloading bytes:           |  0.00B

validation/sample_000157/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

validation/sample_000157/board.png: downloading bytes:           |  0.00B

validation/sample_000158/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

validation/sample_000158/board.png: downloading bytes:           |  0.00B

validation/sample_000159/board.png: reconstructing file:   0%|          |  0.00B / 19.7kB

validation/sample_000159/board.png: downloading bytes:           |  0.00B

validation/sample_000160/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

validation/sample_000160/board.png: downloading bytes:           |  0.00B

validation/sample_000162/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

validation/sample_000161/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

validation/sample_000163/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

validation/sample_000162/board.png: downloading bytes:           |  0.00B

validation/sample_000161/board.png: downloading bytes:           |  0.00B

validation/sample_000164/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

validation/sample_000163/board.png: downloading bytes:           |  0.00B

validation/sample_000164/board.png: downloading bytes:           |  0.00B

validation/sample_000165/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

validation/sample_000165/board.png: downloading bytes:           |  0.00B

validation/sample_000166/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

validation/sample_000166/board.png: downloading bytes:           |  0.00B

validation/sample_000167/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

validation/sample_000167/board.png: downloading bytes:           |  0.00B

validation/sample_000168/board.png: reconstructing file:   0%|          |  0.00B / 28.7kB

validation/sample_000168/board.png: downloading bytes:           |  0.00B

validation/sample_000169/board.png: reconstructing file:   0%|          |  0.00B / 19.5kB

validation/sample_000169/board.png: downloading bytes:           |  0.00B

validation/sample_000170/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

validation/sample_000170/board.png: downloading bytes:           |  0.00B

validation/sample_000171/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

validation/sample_000171/board.png: downloading bytes:           |  0.00B

validation/sample_000172/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

validation/sample_000172/board.png: downloading bytes:           |  0.00B

validation/sample_000173/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

validation/sample_000173/board.png: downloading bytes:           |  0.00B

validation/sample_000174/board.png: reconstructing file:   0%|          |  0.00B / 17.9kB

validation/sample_000174/board.png: downloading bytes:           |  0.00B

validation/sample_000175/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

validation/sample_000175/board.png: downloading bytes:           |  0.00B

validation/sample_000176/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

validation/sample_000176/board.png: downloading bytes:           |  0.00B

validation/sample_000177/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

validation/sample_000177/board.png: downloading bytes:           |  0.00B

validation/sample_000178/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

validation/sample_000178/board.png: downloading bytes:           |  0.00B

validation/sample_000179/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

validation/sample_000180/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

validation/sample_000179/board.png: downloading bytes:           |  0.00B

validation/sample_000180/board.png: downloading bytes:           |  0.00B

validation/sample_000181/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

validation/sample_000181/board.png: downloading bytes:           |  0.00B

validation/sample_000182/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

validation/sample_000183/board.png: reconstructing file:   0%|          |  0.00B / 21.7kB

validation/sample_000182/board.png: downloading bytes:           |  0.00B

validation/sample_000183/board.png: downloading bytes:           |  0.00B

validation/sample_000184/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

validation/sample_000184/board.png: downloading bytes:           |  0.00B

validation/sample_000185/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

validation/sample_000185/board.png: downloading bytes:           |  0.00B

validation/sample_000186/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

validation/sample_000188/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

validation/sample_000186/board.png: downloading bytes:           |  0.00B

validation/sample_000188/board.png: downloading bytes:           |  0.00B

validation/sample_000187/board.png: reconstructing file:   0%|          |  0.00B / 25.6kB

validation/sample_000187/board.png: downloading bytes:           |  0.00B

validation/sample_000189/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

validation/sample_000189/board.png: downloading bytes:           |  0.00B

validation/sample_000190/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

validation/sample_000190/board.png: downloading bytes:           |  0.00B

validation/sample_000191/board.png: reconstructing file:   0%|          |  0.00B / 22.8kB

validation/sample_000191/board.png: downloading bytes:           |  0.00B

validation/sample_000192/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

validation/sample_000192/board.png: downloading bytes:           |  0.00B

validation/sample_000194/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

validation/sample_000193/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

validation/sample_000195/board.png: reconstructing file:   0%|          |  0.00B / 15.0kB

validation/sample_000196/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

validation/sample_000193/board.png: downloading bytes:           |  0.00B

validation/sample_000195/board.png: downloading bytes:           |  0.00B

validation/sample_000194/board.png: downloading bytes:           |  0.00B

validation/sample_000196/board.png: downloading bytes:           |  0.00B

validation/sample_000197/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

validation/sample_000197/board.png: downloading bytes:           |  0.00B

validation/sample_000198/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

validation/sample_000199/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

validation/sample_000198/board.png: downloading bytes:           |  0.00B

validation/sample_000199/board.png: downloading bytes:           |  0.00B

validation/sample_000201/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

validation/sample_000201/board.png: downloading bytes:           |  0.00B

validation/sample_000202/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

validation/sample_000202/board.png: downloading bytes:           |  0.00B

validation/sample_000203/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

validation/sample_000200/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

validation/sample_000204/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

validation/sample_000203/board.png: downloading bytes:           |  0.00B

validation/sample_000200/board.png: downloading bytes:           |  0.00B

validation/sample_000204/board.png: downloading bytes:           |  0.00B

validation/sample_000205/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

validation/sample_000205/board.png: downloading bytes:           |  0.00B

validation/sample_000206/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

validation/sample_000206/board.png: downloading bytes:           |  0.00B

validation/sample_000207/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

validation/sample_000207/board.png: downloading bytes:           |  0.00B

validation/sample_000208/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

validation/sample_000210/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

validation/sample_000209/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

validation/sample_000208/board.png: downloading bytes:           |  0.00B

validation/sample_000211/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

validation/sample_000210/board.png: downloading bytes:           |  0.00B

validation/sample_000209/board.png: downloading bytes:           |  0.00B

validation/sample_000211/board.png: downloading bytes:           |  0.00B

validation/sample_000212/board.png: reconstructing file:   0%|          |  0.00B / 23.8kB

validation/sample_000212/board.png: downloading bytes:           |  0.00B

validation/sample_000213/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

validation/sample_000214/board.png: reconstructing file:   0%|          |  0.00B / 39.3kB

validation/sample_000213/board.png: downloading bytes:           |  0.00B

validation/sample_000214/board.png: downloading bytes:           |  0.00B

validation/sample_000215/board.png: reconstructing file:   0%|          |  0.00B / 21.8kB

validation/sample_000215/board.png: downloading bytes:           |  0.00B

validation/sample_000216/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

validation/sample_000216/board.png: downloading bytes:           |  0.00B

validation/sample_000217/board.png: reconstructing file:   0%|          |  0.00B / 14.6kB

validation/sample_000217/board.png: downloading bytes:           |  0.00B

validation/sample_000218/board.png: reconstructing file:   0%|          |  0.00B / 18.8kB

validation/sample_000218/board.png: downloading bytes:           |  0.00B

validation/sample_000219/board.png: reconstructing file:   0%|          |  0.00B / 16.9kB

validation/sample_000219/board.png: downloading bytes:           |  0.00B

validation/sample_000220/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

validation/sample_000220/board.png: downloading bytes:           |  0.00B

validation/sample_000221/board.png: reconstructing file:   0%|          |  0.00B / 36.3kB

validation/sample_000221/board.png: downloading bytes:           |  0.00B

validation/sample_000222/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

validation/sample_000222/board.png: downloading bytes:           |  0.00B

validation/sample_000223/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

validation/sample_000223/board.png: downloading bytes:           |  0.00B

validation/sample_000224/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

validation/sample_000224/board.png: downloading bytes:           |  0.00B

validation/sample_000225/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

validation/sample_000225/board.png: downloading bytes:           |  0.00B

validation/sample_000226/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

validation/sample_000226/board.png: downloading bytes:           |  0.00B

validation/sample_000228/board.png: reconstructing file:   0%|          |  0.00B / 17.2kB

validation/sample_000228/board.png: downloading bytes:           |  0.00B

validation/sample_000229/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

validation/sample_000229/board.png: downloading bytes:           |  0.00B

validation/sample_000227/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

validation/sample_000230/board.png: reconstructing file:   0%|          |  0.00B / 42.4kB

validation/sample_000227/board.png: downloading bytes:           |  0.00B

validation/sample_000230/board.png: downloading bytes:           |  0.00B

validation/sample_000231/board.png: reconstructing file:   0%|          |  0.00B / 32.2kB

validation/sample_000231/board.png: downloading bytes:           |  0.00B

validation/sample_000232/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

validation/sample_000233/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

validation/sample_000232/board.png: downloading bytes:           |  0.00B

validation/sample_000234/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

validation/sample_000233/board.png: downloading bytes:           |  0.00B

validation/sample_000234/board.png: downloading bytes:           |  0.00B

validation/sample_000235/board.png: reconstructing file:   0%|          |  0.00B / 43.4kB

validation/sample_000235/board.png: downloading bytes:           |  0.00B

validation/sample_000236/board.png: reconstructing file:   0%|          |  0.00B / 12.8kB

validation/sample_000236/board.png: downloading bytes:           |  0.00B

validation/sample_000237/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

validation/sample_000238/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

validation/sample_000237/board.png: downloading bytes:           |  0.00B

validation/sample_000238/board.png: downloading bytes:           |  0.00B

validation/sample_000239/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

validation/sample_000239/board.png: downloading bytes:           |  0.00B

validation/sample_000240/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

validation/sample_000240/board.png: downloading bytes:           |  0.00B

validation/sample_000241/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

validation/sample_000241/board.png: downloading bytes:           |  0.00B

validation/sample_000242/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

validation/sample_000242/board.png: downloading bytes:           |  0.00B

validation/sample_000244/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

validation/sample_000245/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

validation/sample_000243/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

validation/sample_000246/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

validation/sample_000245/board.png: downloading bytes:           |  0.00B

validation/sample_000244/board.png: downloading bytes:           |  0.00B

validation/sample_000243/board.png: downloading bytes:           |  0.00B

validation/sample_000246/board.png: downloading bytes:           |  0.00B

validation/sample_000247/board.png: reconstructing file:   0%|          |  0.00B / 44.0kB

validation/sample_000247/board.png: downloading bytes:           |  0.00B

validation/sample_000248/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

validation/sample_000248/board.png: downloading bytes:           |  0.00B

validation/sample_000249/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

validation/sample_000249/board.png: downloading bytes:           |  0.00B

validation/sample_000250/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

validation/sample_000250/board.png: downloading bytes:           |  0.00B

validation/sample_000251/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

validation/sample_000251/board.png: downloading bytes:           |  0.00B

validation/sample_000253/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

validation/sample_000252/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

validation/sample_000253/board.png: downloading bytes:           |  0.00B

validation/sample_000252/board.png: downloading bytes:           |  0.00B

validation/sample_000254/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

validation/sample_000254/board.png: downloading bytes:           |  0.00B

validation/sample_000255/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

validation/sample_000255/board.png: downloading bytes:           |  0.00B

validation/sample_000256/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

validation/sample_000256/board.png: downloading bytes:           |  0.00B

validation/sample_000257/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

validation/sample_000257/board.png: downloading bytes:           |  0.00B

validation/sample_000258/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

validation/sample_000258/board.png: downloading bytes:           |  0.00B

validation/sample_000259/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

validation/sample_000259/board.png: downloading bytes:           |  0.00B

validation/sample_000260/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

validation/sample_000261/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

validation/sample_000261/board.png: downloading bytes:           |  0.00B

validation/sample_000260/board.png: downloading bytes:           |  0.00B

validation/sample_000262/board.png: reconstructing file:   0%|          |  0.00B / 42.0kB

validation/sample_000262/board.png: downloading bytes:           |  0.00B

validation/sample_000263/board.png: reconstructing file:   0%|          |  0.00B / 37.3kB

validation/sample_000264/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

validation/sample_000263/board.png: downloading bytes:           |  0.00B

validation/sample_000264/board.png: downloading bytes:           |  0.00B

validation/sample_000266/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

validation/sample_000266/board.png: downloading bytes:           |  0.00B

validation/sample_000265/board.png: reconstructing file:   0%|          |  0.00B / 14.7kB

validation/sample_000265/board.png: downloading bytes:           |  0.00B

validation/sample_000268/board.png: reconstructing file:   0%|          |  0.00B / 38.6kB

validation/sample_000268/board.png: downloading bytes:           |  0.00B

validation/sample_000267/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

validation/sample_000267/board.png: downloading bytes:           |  0.00B

validation/sample_000269/board.png: reconstructing file:   0%|          |  0.00B / 20.0kB

validation/sample_000269/board.png: downloading bytes:           |  0.00B

validation/sample_000270/board.png: reconstructing file:   0%|          |  0.00B / 22.0kB

validation/sample_000270/board.png: downloading bytes:           |  0.00B

validation/sample_000271/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

validation/sample_000271/board.png: downloading bytes:           |  0.00B

validation/sample_000272/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

validation/sample_000272/board.png: downloading bytes:           |  0.00B

validation/sample_000273/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

validation/sample_000273/board.png: downloading bytes:           |  0.00B

validation/sample_000274/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

validation/sample_000275/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

validation/sample_000274/board.png: downloading bytes:           |  0.00B

validation/sample_000275/board.png: downloading bytes:           |  0.00B

validation/sample_000276/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

validation/sample_000276/board.png: downloading bytes:           |  0.00B

validation/sample_000278/board.png: reconstructing file:   0%|          |  0.00B / 42.0kB

validation/sample_000277/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

validation/sample_000278/board.png: downloading bytes:           |  0.00B

validation/sample_000277/board.png: downloading bytes:           |  0.00B

validation/sample_000279/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

validation/sample_000280/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

validation/sample_000279/board.png: downloading bytes:           |  0.00B

validation/sample_000280/board.png: downloading bytes:           |  0.00B

validation/sample_000281/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

validation/sample_000281/board.png: downloading bytes:           |  0.00B

validation/sample_000282/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

validation/sample_000282/board.png: downloading bytes:           |  0.00B

validation/sample_000283/board.png: reconstructing file:   0%|          |  0.00B / 22.6kB

validation/sample_000283/board.png: downloading bytes:           |  0.00B

validation/sample_000285/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

validation/sample_000285/board.png: downloading bytes:           |  0.00B

validation/sample_000284/board.png: reconstructing file:   0%|          |  0.00B / 21.4kB

validation/sample_000284/board.png: downloading bytes:           |  0.00B

validation/sample_000286/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

validation/sample_000286/board.png: downloading bytes:           |  0.00B

validation/sample_000287/board.png: reconstructing file:   0%|          |  0.00B / 21.6kB

validation/sample_000288/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

validation/sample_000287/board.png: downloading bytes:           |  0.00B

validation/sample_000288/board.png: downloading bytes:           |  0.00B

validation/sample_000289/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

validation/sample_000289/board.png: downloading bytes:           |  0.00B

validation/sample_000290/board.png: reconstructing file:   0%|          |  0.00B / 19.9kB

validation/sample_000290/board.png: downloading bytes:           |  0.00B

validation/sample_000291/board.png: reconstructing file:   0%|          |  0.00B / 24.3kB

validation/sample_000291/board.png: downloading bytes:           |  0.00B

validation/sample_000292/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

validation/sample_000292/board.png: downloading bytes:           |  0.00B

validation/sample_000293/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

validation/sample_000293/board.png: downloading bytes:           |  0.00B

validation/sample_000294/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

validation/sample_000294/board.png: downloading bytes:           |  0.00B

validation/sample_000296/board.png: reconstructing file:   0%|          |  0.00B / 42.4kB

validation/sample_000295/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

validation/sample_000296/board.png: downloading bytes:           |  0.00B

validation/sample_000295/board.png: downloading bytes:           |  0.00B

validation/sample_000297/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

validation/sample_000298/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

validation/sample_000297/board.png: downloading bytes:           |  0.00B

validation/sample_000298/board.png: downloading bytes:           |  0.00B

validation/sample_000299/board.png: reconstructing file:   0%|          |  0.00B / 42.3kB

validation/sample_000300/board.png: reconstructing file:   0%|          |  0.00B / 34.9kB

validation/sample_000299/board.png: downloading bytes:           |  0.00B

validation/sample_000301/board.png: reconstructing file:   0%|          |  0.00B / 18.4kB

validation/sample_000300/board.png: downloading bytes:           |  0.00B

validation/sample_000301/board.png: downloading bytes:           |  0.00B

validation/sample_000302/board.png: reconstructing file:   0%|          |  0.00B / 16.2kB

validation/sample_000304/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

validation/sample_000302/board.png: downloading bytes:           |  0.00B

validation/sample_000303/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

validation/sample_000304/board.png: downloading bytes:           |  0.00B

validation/sample_000303/board.png: downloading bytes:           |  0.00B

validation/sample_000305/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

validation/sample_000305/board.png: downloading bytes:           |  0.00B

validation/sample_000306/board.png: reconstructing file:   0%|          |  0.00B / 14.3kB

validation/sample_000306/board.png: downloading bytes:           |  0.00B

validation/sample_000307/board.png: reconstructing file:   0%|          |  0.00B / 12.8kB

validation/sample_000307/board.png: downloading bytes:           |  0.00B

validation/sample_000308/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

validation/sample_000308/board.png: downloading bytes:           |  0.00B

validation/sample_000309/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

validation/sample_000309/board.png: downloading bytes:           |  0.00B

validation/sample_000310/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

validation/sample_000310/board.png: downloading bytes:           |  0.00B

validation/sample_000311/board.png: reconstructing file:   0%|          |  0.00B / 18.1kB

validation/sample_000311/board.png: downloading bytes:           |  0.00B

validation/sample_000312/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

validation/sample_000312/board.png: downloading bytes:           |  0.00B

validation/sample_000313/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

validation/sample_000314/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

validation/sample_000313/board.png: downloading bytes:           |  0.00B

validation/sample_000314/board.png: downloading bytes:           |  0.00B

validation/sample_000315/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

validation/sample_000315/board.png: downloading bytes:           |  0.00B

validation/sample_000316/board.png: reconstructing file:   0%|          |  0.00B / 26.7kB

validation/sample_000316/board.png: downloading bytes:           |  0.00B

validation/sample_000317/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

validation/sample_000318/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

validation/sample_000317/board.png: downloading bytes:           |  0.00B

validation/sample_000319/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

validation/sample_000318/board.png: downloading bytes:           |  0.00B

validation/sample_000319/board.png: downloading bytes:           |  0.00B

validation/sample_000320/board.png: reconstructing file:   0%|          |  0.00B / 34.0kB

validation/sample_000320/board.png: downloading bytes:           |  0.00B

validation/sample_000321/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

validation/sample_000321/board.png: downloading bytes:           |  0.00B

validation/sample_000325/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

validation/sample_000322/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

validation/sample_000326/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

validation/sample_000323/board.png: reconstructing file:   0%|          |  0.00B / 14.0kB

validation/sample_000325/board.png: downloading bytes:           |  0.00B

validation/sample_000322/board.png: downloading bytes:           |  0.00B

validation/sample_000326/board.png: downloading bytes:           |  0.00B

validation/sample_000323/board.png: downloading bytes:           |  0.00B

validation/sample_000324/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

validation/sample_000324/board.png: downloading bytes:           |  0.00B

validation/sample_000327/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

validation/sample_000327/board.png: downloading bytes:           |  0.00B

validation/sample_000330/board.png: reconstructing file:   0%|          |  0.00B / 13.5kB

validation/sample_000330/board.png: downloading bytes:           |  0.00B

validation/sample_000332/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

validation/sample_000332/board.png: downloading bytes:           |  0.00B

validation/sample_000328/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

validation/sample_000328/board.png: downloading bytes:           |  0.00B

validation/sample_000329/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

validation/sample_000329/board.png: downloading bytes:           |  0.00B

validation/sample_000333/board.png: reconstructing file:   0%|          |  0.00B / 39.8kB

validation/sample_000333/board.png: downloading bytes:           |  0.00B

validation/sample_000331/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

validation/sample_000334/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

validation/sample_000335/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

validation/sample_000331/board.png: downloading bytes:           |  0.00B

validation/sample_000336/board.png: reconstructing file:   0%|          |  0.00B / 38.7kB

validation/sample_000334/board.png: downloading bytes:           |  0.00B

validation/sample_000337/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

validation/sample_000335/board.png: downloading bytes:           |  0.00B

validation/sample_000336/board.png: downloading bytes:           |  0.00B

validation/sample_000337/board.png: downloading bytes:           |  0.00B

validation/sample_000338/board.png: reconstructing file:   0%|          |  0.00B / 19.8kB

validation/sample_000339/board.png: reconstructing file:   0%|          |  0.00B / 23.7kB

validation/sample_000338/board.png: downloading bytes:           |  0.00B

validation/sample_000339/board.png: downloading bytes:           |  0.00B

validation/sample_000340/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

validation/sample_000340/board.png: downloading bytes:           |  0.00B

validation/sample_000341/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

validation/sample_000341/board.png: downloading bytes:           |  0.00B

validation/sample_000342/board.png: reconstructing file:   0%|          |  0.00B / 36.3kB

validation/sample_000342/board.png: downloading bytes:           |  0.00B

validation/sample_000343/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

validation/sample_000343/board.png: downloading bytes:           |  0.00B

validation/sample_000344/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

validation/sample_000344/board.png: downloading bytes:           |  0.00B

validation/sample_000345/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

validation/sample_000345/board.png: downloading bytes:           |  0.00B

validation/sample_000347/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

validation/sample_000347/board.png: downloading bytes:           |  0.00B

validation/sample_000348/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

validation/sample_000348/board.png: downloading bytes:           |  0.00B

validation/sample_000346/board.png: reconstructing file:   0%|          |  0.00B / 40.3kB

validation/sample_000346/board.png: downloading bytes:           |  0.00B

validation/sample_000349/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

validation/sample_000349/board.png: downloading bytes:           |  0.00B

validation/sample_000350/board.png: reconstructing file:   0%|          |  0.00B / 39.7kB

validation/sample_000350/board.png: downloading bytes:           |  0.00B

validation/sample_000351/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

validation/sample_000352/board.png: reconstructing file:   0%|          |  0.00B / 23.6kB

validation/sample_000351/board.png: downloading bytes:           |  0.00B

validation/sample_000352/board.png: downloading bytes:           |  0.00B

validation/sample_000353/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

validation/sample_000353/board.png: downloading bytes:           |  0.00B

validation/sample_000354/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

validation/sample_000354/board.png: downloading bytes:           |  0.00B

validation/sample_000355/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

validation/sample_000356/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

validation/sample_000355/board.png: downloading bytes:           |  0.00B

validation/sample_000356/board.png: downloading bytes:           |  0.00B

validation/sample_000357/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

validation/sample_000357/board.png: downloading bytes:           |  0.00B

validation/sample_000358/board.png: reconstructing file:   0%|          |  0.00B / 11.3kB

validation/sample_000360/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

validation/sample_000359/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

validation/sample_000358/board.png: downloading bytes:           |  0.00B

validation/sample_000360/board.png: downloading bytes:           |  0.00B

validation/sample_000359/board.png: downloading bytes:           |  0.00B

validation/sample_000361/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

validation/sample_000361/board.png: downloading bytes:           |  0.00B

validation/sample_000362/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

validation/sample_000362/board.png: downloading bytes:           |  0.00B

validation/sample_000363/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

validation/sample_000363/board.png: downloading bytes:           |  0.00B

validation/sample_000364/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

validation/sample_000364/board.png: downloading bytes:           |  0.00B

validation/sample_000365/board.png: reconstructing file:   0%|          |  0.00B / 35.7kB

validation/sample_000366/board.png: reconstructing file:   0%|          |  0.00B / 15.7kB

validation/sample_000365/board.png: downloading bytes:           |  0.00B

validation/sample_000366/board.png: downloading bytes:           |  0.00B

validation/sample_000367/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

validation/sample_000368/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

validation/sample_000367/board.png: downloading bytes:           |  0.00B

validation/sample_000368/board.png: downloading bytes:           |  0.00B

validation/sample_000369/board.png: reconstructing file:   0%|          |  0.00B / 20.3kB

validation/sample_000369/board.png: downloading bytes:           |  0.00B

validation/sample_000370/board.png: reconstructing file:   0%|          |  0.00B / 42.9kB

validation/sample_000370/board.png: downloading bytes:           |  0.00B

validation/sample_000371/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

validation/sample_000371/board.png: downloading bytes:           |  0.00B

validation/sample_000372/board.png: reconstructing file:   0%|          |  0.00B / 30.3kB

validation/sample_000372/board.png: downloading bytes:           |  0.00B

validation/sample_000373/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

validation/sample_000373/board.png: downloading bytes:           |  0.00B

validation/sample_000374/board.png: reconstructing file:   0%|          |  0.00B / 13.6kB

validation/sample_000374/board.png: downloading bytes:           |  0.00B

validation/sample_000375/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

validation/sample_000375/board.png: downloading bytes:           |  0.00B

validation/sample_000376/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

validation/sample_000376/board.png: downloading bytes:           |  0.00B

validation/sample_000377/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

validation/sample_000377/board.png: downloading bytes:           |  0.00B

validation/sample_000378/board.png: reconstructing file:   0%|          |  0.00B / 11.4kB

validation/sample_000378/board.png: downloading bytes:           |  0.00B

validation/sample_000379/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

validation/sample_000379/board.png: downloading bytes:           |  0.00B

validation/sample_000380/board.png: reconstructing file:   0%|          |  0.00B / 21.8kB

validation/sample_000380/board.png: downloading bytes:           |  0.00B

validation/sample_000381/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

validation/sample_000382/board.png: reconstructing file:   0%|          |  0.00B / 31.7kB

validation/sample_000381/board.png: downloading bytes:           |  0.00B

validation/sample_000382/board.png: downloading bytes:           |  0.00B

validation/sample_000383/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

validation/sample_000383/board.png: downloading bytes:           |  0.00B

validation/sample_000384/board.png: reconstructing file:   0%|          |  0.00B / 41.8kB

validation/sample_000384/board.png: downloading bytes:           |  0.00B

validation/sample_000385/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

validation/sample_000385/board.png: downloading bytes:           |  0.00B

validation/sample_000386/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

validation/sample_000386/board.png: downloading bytes:           |  0.00B

validation/sample_000387/board.png: reconstructing file:   0%|          |  0.00B / 36.2kB

validation/sample_000387/board.png: downloading bytes:           |  0.00B

validation/sample_000388/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

validation/sample_000388/board.png: downloading bytes:           |  0.00B

validation/sample_000389/board.png: reconstructing file:   0%|          |  0.00B / 16.7kB

validation/sample_000389/board.png: downloading bytes:           |  0.00B

validation/sample_000390/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

validation/sample_000391/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

validation/sample_000390/board.png: downloading bytes:           |  0.00B

validation/sample_000391/board.png: downloading bytes:           |  0.00B

validation/sample_000392/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

validation/sample_000393/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

validation/sample_000394/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

validation/sample_000392/board.png: downloading bytes:           |  0.00B

validation/sample_000394/board.png: downloading bytes:           |  0.00B

validation/sample_000393/board.png: downloading bytes:           |  0.00B

validation/sample_000395/board.png: reconstructing file:   0%|          |  0.00B / 41.0kB

validation/sample_000395/board.png: downloading bytes:           |  0.00B

validation/sample_000396/board.png: reconstructing file:   0%|          |  0.00B / 40.1kB

validation/sample_000396/board.png: downloading bytes:           |  0.00B

validation/sample_000397/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

validation/sample_000398/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

validation/sample_000397/board.png: downloading bytes:           |  0.00B

validation/sample_000398/board.png: downloading bytes:           |  0.00B

validation/sample_000399/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

validation/sample_000399/board.png: downloading bytes:           |  0.00B

metadata.jsonl:   0%|          | 0.00/235k [00:00<?, ?B/s]

Downloading data:   0%|          | 0/400 [00:00<?, ?files/s]

test/sample_000000/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

test/sample_000001/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

test/sample_000003/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

test/sample_000004/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

test/sample_000008/board.png: reconstructing file:   0%|          |  0.00B / 15.5kB

test/sample_000006/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

test/sample_000002/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

test/sample_000010/board.png: reconstructing file:   0%|          |  0.00B / 37.2kB

test/sample_000009/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

test/sample_000007/board.png: reconstructing file:   0%|          |  0.00B / 24.7kB

test/sample_000014/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

test/sample_000012/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

test/sample_000011/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

test/sample_000000/board.png: downloading bytes:           |  0.00B

test/sample_000015/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

test/sample_000001/board.png: downloading bytes:           |  0.00B

test/sample_000003/board.png: downloading bytes:           |  0.00B

test/sample_000008/board.png: downloading bytes:           |  0.00B

test/sample_000004/board.png: downloading bytes:           |  0.00B

test/sample_000006/board.png: downloading bytes:           |  0.00B

test/sample_000002/board.png: downloading bytes:           |  0.00B

test/sample_000007/board.png: downloading bytes:           |  0.00B

test/sample_000014/board.png: downloading bytes:           |  0.00B

test/sample_000009/board.png: downloading bytes:           |  0.00B

test/sample_000012/board.png: downloading bytes:           |  0.00B

test/sample_000010/board.png: downloading bytes:           |  0.00B

test/sample_000011/board.png: downloading bytes:           |  0.00B

test/sample_000013/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

test/sample_000015/board.png: downloading bytes:           |  0.00B

test/sample_000013/board.png: downloading bytes:           |  0.00B

test/sample_000005/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

test/sample_000005/board.png: downloading bytes:           |  0.00B

test/sample_000016/board.png: reconstructing file:   0%|          |  0.00B / 14.2kB

test/sample_000016/board.png: downloading bytes:           |  0.00B

test/sample_000017/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

test/sample_000017/board.png: downloading bytes:           |  0.00B

test/sample_000019/board.png: reconstructing file:   0%|          |  0.00B / 30.5kB

test/sample_000018/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

test/sample_000022/board.png: reconstructing file:   0%|          |  0.00B / 41.8kB

test/sample_000020/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

test/sample_000021/board.png: reconstructing file:   0%|          |  0.00B / 32.3kB

test/sample_000020/board.png: downloading bytes:           |  0.00B

test/sample_000019/board.png: downloading bytes:           |  0.00B

test/sample_000018/board.png: downloading bytes:           |  0.00B

test/sample_000022/board.png: downloading bytes:           |  0.00B

test/sample_000021/board.png: downloading bytes:           |  0.00B

test/sample_000023/board.png: reconstructing file:   0%|          |  0.00B / 41.8kB

test/sample_000023/board.png: downloading bytes:           |  0.00B

test/sample_000024/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

test/sample_000024/board.png: downloading bytes:           |  0.00B

test/sample_000025/board.png: reconstructing file:   0%|          |  0.00B / 18.2kB

test/sample_000025/board.png: downloading bytes:           |  0.00B

test/sample_000026/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

test/sample_000026/board.png: downloading bytes:           |  0.00B

test/sample_000027/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

test/sample_000027/board.png: downloading bytes:           |  0.00B

test/sample_000028/board.png: reconstructing file:   0%|          |  0.00B / 21.7kB

test/sample_000028/board.png: downloading bytes:           |  0.00B

test/sample_000029/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

test/sample_000029/board.png: downloading bytes:           |  0.00B

test/sample_000030/board.png: reconstructing file:   0%|          |  0.00B / 35.5kB

test/sample_000030/board.png: downloading bytes:           |  0.00B

test/sample_000031/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

test/sample_000031/board.png: downloading bytes:           |  0.00B

test/sample_000032/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

test/sample_000032/board.png: downloading bytes:           |  0.00B

test/sample_000033/board.png: reconstructing file:   0%|          |  0.00B / 39.5kB

test/sample_000033/board.png: downloading bytes:           |  0.00B

test/sample_000034/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

test/sample_000034/board.png: downloading bytes:           |  0.00B

test/sample_000035/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

test/sample_000036/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

test/sample_000037/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

test/sample_000035/board.png: downloading bytes:           |  0.00B

test/sample_000036/board.png: downloading bytes:           |  0.00B

test/sample_000037/board.png: downloading bytes:           |  0.00B

test/sample_000038/board.png: reconstructing file:   0%|          |  0.00B / 39.3kB

test/sample_000038/board.png: downloading bytes:           |  0.00B

test/sample_000039/board.png: reconstructing file:   0%|          |  0.00B / 36.3kB

test/sample_000039/board.png: downloading bytes:           |  0.00B

test/sample_000040/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

test/sample_000040/board.png: downloading bytes:           |  0.00B

test/sample_000041/board.png: reconstructing file:   0%|          |  0.00B / 19.4kB

test/sample_000041/board.png: downloading bytes:           |  0.00B

test/sample_000042/board.png: reconstructing file:   0%|          |  0.00B / 23.9kB

test/sample_000042/board.png: downloading bytes:           |  0.00B

test/sample_000044/board.png: reconstructing file:   0%|          |  0.00B / 20.8kB

test/sample_000043/board.png: reconstructing file:   0%|          |  0.00B / 16.0kB

test/sample_000044/board.png: downloading bytes:           |  0.00B

test/sample_000043/board.png: downloading bytes:           |  0.00B

test/sample_000045/board.png: reconstructing file:   0%|          |  0.00B / 43.9kB

test/sample_000045/board.png: downloading bytes:           |  0.00B

test/sample_000046/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

test/sample_000047/board.png: reconstructing file:   0%|          |  0.00B / 35.1kB

test/sample_000047/board.png: downloading bytes:           |  0.00B

test/sample_000046/board.png: downloading bytes:           |  0.00B

test/sample_000048/board.png: reconstructing file:   0%|          |  0.00B / 23.1kB

test/sample_000048/board.png: downloading bytes:           |  0.00B

test/sample_000049/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

test/sample_000049/board.png: downloading bytes:           |  0.00B

test/sample_000050/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

test/sample_000050/board.png: downloading bytes:           |  0.00B

test/sample_000051/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

test/sample_000052/board.png: reconstructing file:   0%|          |  0.00B / 38.5kB

test/sample_000052/board.png: downloading bytes:           |  0.00B

test/sample_000051/board.png: downloading bytes:           |  0.00B

test/sample_000053/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

test/sample_000054/board.png: reconstructing file:   0%|          |  0.00B / 25.0kB

test/sample_000053/board.png: downloading bytes:           |  0.00B

test/sample_000054/board.png: downloading bytes:           |  0.00B

test/sample_000055/board.png: reconstructing file:   0%|          |  0.00B / 39.4kB

test/sample_000055/board.png: downloading bytes:           |  0.00B

test/sample_000056/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

test/sample_000056/board.png: downloading bytes:           |  0.00B

test/sample_000057/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

test/sample_000057/board.png: downloading bytes:           |  0.00B

test/sample_000058/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

test/sample_000058/board.png: downloading bytes:           |  0.00B

test/sample_000059/board.png: reconstructing file:   0%|          |  0.00B / 26.9kB

test/sample_000060/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

test/sample_000060/board.png: downloading bytes:           |  0.00B

test/sample_000059/board.png: downloading bytes:           |  0.00B

test/sample_000061/board.png: reconstructing file:   0%|          |  0.00B / 18.9kB

test/sample_000061/board.png: downloading bytes:           |  0.00B

test/sample_000062/board.png: reconstructing file:   0%|          |  0.00B / 29.0kB

test/sample_000063/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

test/sample_000062/board.png: downloading bytes:           |  0.00B

test/sample_000063/board.png: downloading bytes:           |  0.00B

test/sample_000064/board.png: reconstructing file:   0%|          |  0.00B / 15.8kB

test/sample_000064/board.png: downloading bytes:           |  0.00B

test/sample_000065/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

test/sample_000065/board.png: downloading bytes:           |  0.00B

test/sample_000067/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

test/sample_000066/board.png: reconstructing file:   0%|          |  0.00B / 38.3kB

test/sample_000067/board.png: downloading bytes:           |  0.00B

test/sample_000068/board.png: reconstructing file:   0%|          |  0.00B / 25.8kB

test/sample_000066/board.png: downloading bytes:           |  0.00B

test/sample_000068/board.png: downloading bytes:           |  0.00B

test/sample_000069/board.png: reconstructing file:   0%|          |  0.00B / 40.6kB

test/sample_000069/board.png: downloading bytes:           |  0.00B

test/sample_000070/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

test/sample_000071/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

test/sample_000070/board.png: downloading bytes:           |  0.00B

test/sample_000071/board.png: downloading bytes:           |  0.00B

test/sample_000072/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

test/sample_000072/board.png: downloading bytes:           |  0.00B

test/sample_000073/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

test/sample_000073/board.png: downloading bytes:           |  0.00B

test/sample_000074/board.png: reconstructing file:   0%|          |  0.00B / 41.0kB

test/sample_000075/board.png: reconstructing file:   0%|          |  0.00B / 19.8kB

test/sample_000074/board.png: downloading bytes:           |  0.00B

test/sample_000076/board.png: reconstructing file:   0%|          |  0.00B / 25.3kB

test/sample_000075/board.png: downloading bytes:           |  0.00B

test/sample_000077/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

test/sample_000077/board.png: downloading bytes:           |  0.00B

test/sample_000076/board.png: downloading bytes:           |  0.00B

test/sample_000078/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

test/sample_000078/board.png: downloading bytes:           |  0.00B

test/sample_000079/board.png: reconstructing file:   0%|          |  0.00B / 13.6kB

test/sample_000079/board.png: downloading bytes:           |  0.00B

test/sample_000080/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

test/sample_000080/board.png: downloading bytes:           |  0.00B

test/sample_000081/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

test/sample_000082/board.png: reconstructing file:   0%|          |  0.00B / 31.1kB

test/sample_000081/board.png: downloading bytes:           |  0.00B

test/sample_000083/board.png: reconstructing file:   0%|          |  0.00B / 32.5kB

test/sample_000082/board.png: downloading bytes:           |  0.00B

test/sample_000083/board.png: downloading bytes:           |  0.00B

test/sample_000084/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

test/sample_000084/board.png: downloading bytes:           |  0.00B

test/sample_000085/board.png: reconstructing file:   0%|          |  0.00B / 18.0kB

test/sample_000085/board.png: downloading bytes:           |  0.00B

test/sample_000086/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

test/sample_000086/board.png: downloading bytes:           |  0.00B

test/sample_000087/board.png: reconstructing file:   0%|          |  0.00B / 17.4kB

test/sample_000087/board.png: downloading bytes:           |  0.00B

test/sample_000089/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

test/sample_000088/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

test/sample_000088/board.png: downloading bytes:           |  0.00B

test/sample_000089/board.png: downloading bytes:           |  0.00B

test/sample_000090/board.png: reconstructing file:   0%|          |  0.00B / 18.9kB

test/sample_000090/board.png: downloading bytes:           |  0.00B

test/sample_000093/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

test/sample_000092/board.png: reconstructing file:   0%|          |  0.00B / 18.2kB

test/sample_000091/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

test/sample_000094/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

test/sample_000093/board.png: downloading bytes:           |  0.00B

test/sample_000092/board.png: downloading bytes:           |  0.00B

test/sample_000091/board.png: downloading bytes:           |  0.00B

test/sample_000094/board.png: downloading bytes:           |  0.00B

test/sample_000095/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

test/sample_000095/board.png: downloading bytes:           |  0.00B

test/sample_000096/board.png: reconstructing file:   0%|          |  0.00B / 38.6kB

test/sample_000096/board.png: downloading bytes:           |  0.00B

test/sample_000097/board.png: reconstructing file:   0%|          |  0.00B / 35.4kB

test/sample_000098/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

test/sample_000097/board.png: downloading bytes:           |  0.00B

test/sample_000098/board.png: downloading bytes:           |  0.00B

test/sample_000099/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

test/sample_000099/board.png: downloading bytes:           |  0.00B

test/sample_000100/board.png: reconstructing file:   0%|          |  0.00B / 19.9kB

test/sample_000101/board.png: reconstructing file:   0%|          |  0.00B / 22.0kB

test/sample_000100/board.png: downloading bytes:           |  0.00B

test/sample_000101/board.png: downloading bytes:           |  0.00B

test/sample_000102/board.png: reconstructing file:   0%|          |  0.00B / 26.8kB

test/sample_000102/board.png: downloading bytes:           |  0.00B

test/sample_000103/board.png: reconstructing file:   0%|          |  0.00B / 38.8kB

test/sample_000103/board.png: downloading bytes:           |  0.00B

test/sample_000104/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

test/sample_000104/board.png: downloading bytes:           |  0.00B

test/sample_000105/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

test/sample_000105/board.png: downloading bytes:           |  0.00B

test/sample_000106/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

test/sample_000106/board.png: downloading bytes:           |  0.00B

test/sample_000107/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

test/sample_000107/board.png: downloading bytes:           |  0.00B

test/sample_000108/board.png: reconstructing file:   0%|          |  0.00B / 15.6kB

test/sample_000109/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

test/sample_000108/board.png: downloading bytes:           |  0.00B

test/sample_000110/board.png: reconstructing file:   0%|          |  0.00B / 11.4kB

test/sample_000109/board.png: downloading bytes:           |  0.00B

test/sample_000110/board.png: downloading bytes:           |  0.00B

test/sample_000111/board.png: reconstructing file:   0%|          |  0.00B / 15.1kB

test/sample_000111/board.png: downloading bytes:           |  0.00B

test/sample_000112/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

test/sample_000112/board.png: downloading bytes:           |  0.00B

test/sample_000113/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

test/sample_000113/board.png: downloading bytes:           |  0.00B

test/sample_000114/board.png: reconstructing file:   0%|          |  0.00B / 18.8kB

test/sample_000114/board.png: downloading bytes:           |  0.00B

test/sample_000115/board.png: reconstructing file:   0%|          |  0.00B / 31.9kB

test/sample_000115/board.png: downloading bytes:           |  0.00B

test/sample_000116/board.png: reconstructing file:   0%|          |  0.00B / 18.3kB

test/sample_000116/board.png: downloading bytes:           |  0.00B

test/sample_000117/board.png: reconstructing file:   0%|          |  0.00B / 29.9kB

test/sample_000117/board.png: downloading bytes:           |  0.00B

test/sample_000118/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

test/sample_000118/board.png: downloading bytes:           |  0.00B

test/sample_000119/board.png: reconstructing file:   0%|          |  0.00B / 20.1kB

test/sample_000119/board.png: downloading bytes:           |  0.00B

test/sample_000120/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

test/sample_000120/board.png: downloading bytes:           |  0.00B

test/sample_000121/board.png: reconstructing file:   0%|          |  0.00B / 40.2kB

test/sample_000121/board.png: downloading bytes:           |  0.00B

test/sample_000122/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

test/sample_000122/board.png: downloading bytes:           |  0.00B

test/sample_000123/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

test/sample_000123/board.png: downloading bytes:           |  0.00B

test/sample_000124/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

test/sample_000124/board.png: downloading bytes:           |  0.00B

test/sample_000125/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

test/sample_000126/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

test/sample_000125/board.png: downloading bytes:           |  0.00B

test/sample_000126/board.png: downloading bytes:           |  0.00B

test/sample_000127/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

test/sample_000127/board.png: downloading bytes:           |  0.00B

test/sample_000128/board.png: reconstructing file:   0%|          |  0.00B / 23.2kB

test/sample_000128/board.png: downloading bytes:           |  0.00B

test/sample_000130/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

test/sample_000130/board.png: downloading bytes:           |  0.00B

test/sample_000129/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

test/sample_000129/board.png: downloading bytes:           |  0.00B

test/sample_000131/board.png: reconstructing file:   0%|          |  0.00B / 23.5kB

test/sample_000132/board.png: reconstructing file:   0%|          |  0.00B / 39.4kB

test/sample_000132/board.png: downloading bytes:           |  0.00B

test/sample_000131/board.png: downloading bytes:           |  0.00B

test/sample_000133/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

test/sample_000133/board.png: downloading bytes:           |  0.00B

test/sample_000134/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

test/sample_000134/board.png: downloading bytes:           |  0.00B

test/sample_000135/board.png: reconstructing file:   0%|          |  0.00B / 39.2kB

test/sample_000135/board.png: downloading bytes:           |  0.00B

test/sample_000138/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

test/sample_000136/board.png: reconstructing file:   0%|          |  0.00B / 30.8kB

test/sample_000137/board.png: reconstructing file:   0%|          |  0.00B / 40.5kB

test/sample_000138/board.png: downloading bytes:           |  0.00B

test/sample_000137/board.png: downloading bytes:           |  0.00B

test/sample_000136/board.png: downloading bytes:           |  0.00B

test/sample_000139/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

test/sample_000140/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

test/sample_000139/board.png: downloading bytes:           |  0.00B

test/sample_000140/board.png: downloading bytes:           |  0.00B

test/sample_000141/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

test/sample_000141/board.png: downloading bytes:           |  0.00B

test/sample_000142/board.png: reconstructing file:   0%|          |  0.00B / 13.3kB

test/sample_000142/board.png: downloading bytes:           |  0.00B

test/sample_000143/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

test/sample_000143/board.png: downloading bytes:           |  0.00B

test/sample_000144/board.png: reconstructing file:   0%|          |  0.00B / 43.8kB

test/sample_000144/board.png: downloading bytes:           |  0.00B

test/sample_000145/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

test/sample_000145/board.png: downloading bytes:           |  0.00B

test/sample_000146/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

test/sample_000148/board.png: reconstructing file:   0%|          |  0.00B / 40.3kB

test/sample_000147/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

test/sample_000146/board.png: downloading bytes:           |  0.00B

test/sample_000148/board.png: downloading bytes:           |  0.00B

test/sample_000147/board.png: downloading bytes:           |  0.00B

test/sample_000149/board.png: reconstructing file:   0%|          |  0.00B / 32.9kB

test/sample_000149/board.png: downloading bytes:           |  0.00B

test/sample_000150/board.png: reconstructing file:   0%|          |  0.00B / 29.5kB

test/sample_000150/board.png: downloading bytes:           |  0.00B

test/sample_000151/board.png: reconstructing file:   0%|          |  0.00B / 15.9kB

test/sample_000151/board.png: downloading bytes:           |  0.00B

test/sample_000152/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

test/sample_000153/board.png: reconstructing file:   0%|          |  0.00B / 27.0kB

test/sample_000155/board.png: reconstructing file:   0%|          |  0.00B / 20.6kB

test/sample_000156/board.png: reconstructing file:   0%|          |  0.00B / 24.1kB

test/sample_000152/board.png: downloading bytes:           |  0.00B

test/sample_000154/board.png: reconstructing file:   0%|          |  0.00B / 25.6kB

test/sample_000153/board.png: downloading bytes:           |  0.00B

test/sample_000155/board.png: downloading bytes:           |  0.00B

test/sample_000156/board.png: downloading bytes:           |  0.00B

test/sample_000154/board.png: downloading bytes:           |  0.00B

test/sample_000158/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

test/sample_000158/board.png: downloading bytes:           |  0.00B

test/sample_000157/board.png: reconstructing file:   0%|          |  0.00B / 36.9kB

test/sample_000157/board.png: downloading bytes:           |  0.00B

test/sample_000159/board.png: reconstructing file:   0%|          |  0.00B / 36.0kB

test/sample_000159/board.png: downloading bytes:           |  0.00B

test/sample_000160/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

test/sample_000161/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

test/sample_000160/board.png: downloading bytes:           |  0.00B

test/sample_000162/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

test/sample_000163/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

test/sample_000164/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

test/sample_000163/board.png: downloading bytes:           |  0.00B

test/sample_000162/board.png: downloading bytes:           |  0.00B

test/sample_000161/board.png: downloading bytes:           |  0.00B

test/sample_000164/board.png: downloading bytes:           |  0.00B

test/sample_000165/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

test/sample_000165/board.png: downloading bytes:           |  0.00B

test/sample_000166/board.png: reconstructing file:   0%|          |  0.00B / 25.1kB

test/sample_000166/board.png: downloading bytes:           |  0.00B

test/sample_000167/board.png: reconstructing file:   0%|          |  0.00B / 38.1kB

test/sample_000167/board.png: downloading bytes:           |  0.00B

test/sample_000168/board.png: reconstructing file:   0%|          |  0.00B / 29.2kB

test/sample_000168/board.png: downloading bytes:           |  0.00B

test/sample_000169/board.png: reconstructing file:   0%|          |  0.00B / 30.0kB

test/sample_000169/board.png: downloading bytes:           |  0.00B

test/sample_000170/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

test/sample_000171/board.png: reconstructing file:   0%|          |  0.00B / 24.4kB

test/sample_000170/board.png: downloading bytes:           |  0.00B

test/sample_000171/board.png: downloading bytes:           |  0.00B

test/sample_000172/board.png: reconstructing file:   0%|          |  0.00B / 18.6kB

test/sample_000173/board.png: reconstructing file:   0%|          |  0.00B / 20.4kB

test/sample_000173/board.png: downloading bytes:           |  0.00B

test/sample_000172/board.png: downloading bytes:           |  0.00B

test/sample_000174/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

test/sample_000174/board.png: downloading bytes:           |  0.00B

test/sample_000175/board.png: reconstructing file:   0%|          |  0.00B / 18.7kB

test/sample_000175/board.png: downloading bytes:           |  0.00B

test/sample_000176/board.png: reconstructing file:   0%|          |  0.00B / 31.3kB

test/sample_000176/board.png: downloading bytes:           |  0.00B

test/sample_000178/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

test/sample_000177/board.png: reconstructing file:   0%|          |  0.00B / 26.1kB

test/sample_000179/board.png: reconstructing file:   0%|          |  0.00B / 37.5kB

test/sample_000178/board.png: downloading bytes:           |  0.00B

test/sample_000177/board.png: downloading bytes:           |  0.00B

test/sample_000180/board.png: reconstructing file:   0%|          |  0.00B / 38.7kB

test/sample_000179/board.png: downloading bytes:           |  0.00B

test/sample_000180/board.png: downloading bytes:           |  0.00B

test/sample_000181/board.png: reconstructing file:   0%|          |  0.00B / 15.5kB

test/sample_000181/board.png: downloading bytes:           |  0.00B

test/sample_000182/board.png: reconstructing file:   0%|          |  0.00B / 28.1kB

test/sample_000182/board.png: downloading bytes:           |  0.00B

test/sample_000183/board.png: reconstructing file:   0%|          |  0.00B / 30.2kB

test/sample_000183/board.png: downloading bytes:           |  0.00B

test/sample_000184/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

test/sample_000184/board.png: downloading bytes:           |  0.00B

test/sample_000185/board.png: reconstructing file:   0%|          |  0.00B / 17.8kB

test/sample_000186/board.png: reconstructing file:   0%|          |  0.00B / 24.5kB

test/sample_000185/board.png: downloading bytes:           |  0.00B

test/sample_000187/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

test/sample_000186/board.png: downloading bytes:           |  0.00B

test/sample_000188/board.png: reconstructing file:   0%|          |  0.00B / 33.2kB

test/sample_000187/board.png: downloading bytes:           |  0.00B

test/sample_000189/board.png: reconstructing file:   0%|          |  0.00B / 22.1kB

test/sample_000188/board.png: downloading bytes:           |  0.00B

test/sample_000189/board.png: downloading bytes:           |  0.00B

test/sample_000190/board.png: reconstructing file:   0%|          |  0.00B / 17.4kB

test/sample_000190/board.png: downloading bytes:           |  0.00B

test/sample_000191/board.png: reconstructing file:   0%|          |  0.00B / 26.3kB

test/sample_000191/board.png: downloading bytes:           |  0.00B

test/sample_000192/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

test/sample_000192/board.png: downloading bytes:           |  0.00B

test/sample_000193/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

test/sample_000193/board.png: downloading bytes:           |  0.00B

test/sample_000194/board.png: reconstructing file:   0%|          |  0.00B / 15.7kB

test/sample_000195/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

test/sample_000194/board.png: downloading bytes:           |  0.00B

test/sample_000195/board.png: downloading bytes:           |  0.00B

test/sample_000196/board.png: reconstructing file:   0%|          |  0.00B / 32.6kB

test/sample_000197/board.png: reconstructing file:   0%|          |  0.00B / 31.2kB

test/sample_000196/board.png: downloading bytes:           |  0.00B

test/sample_000198/board.png: reconstructing file:   0%|          |  0.00B / 17.6kB

test/sample_000197/board.png: downloading bytes:           |  0.00B

test/sample_000198/board.png: downloading bytes:           |  0.00B

test/sample_000199/board.png: reconstructing file:   0%|          |  0.00B / 18.1kB

test/sample_000199/board.png: downloading bytes:           |  0.00B

test/sample_000200/board.png: reconstructing file:   0%|          |  0.00B / 22.2kB

test/sample_000200/board.png: downloading bytes:           |  0.00B

test/sample_000201/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

test/sample_000201/board.png: downloading bytes:           |  0.00B

test/sample_000202/board.png: reconstructing file:   0%|          |  0.00B / 39.0kB

test/sample_000202/board.png: downloading bytes:           |  0.00B

test/sample_000203/board.png: reconstructing file:   0%|          |  0.00B / 20.2kB

test/sample_000203/board.png: downloading bytes:           |  0.00B

test/sample_000205/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

test/sample_000204/board.png: reconstructing file:   0%|          |  0.00B / 32.7kB

test/sample_000205/board.png: downloading bytes:           |  0.00B

test/sample_000204/board.png: downloading bytes:           |  0.00B

test/sample_000206/board.png: reconstructing file:   0%|          |  0.00B / 42.2kB

test/sample_000206/board.png: downloading bytes:           |  0.00B

test/sample_000207/board.png: reconstructing file:   0%|          |  0.00B / 21.6kB

test/sample_000207/board.png: downloading bytes:           |  0.00B

test/sample_000209/board.png: reconstructing file:   0%|          |  0.00B / 28.0kB

test/sample_000208/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

test/sample_000210/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

test/sample_000209/board.png: downloading bytes:           |  0.00B

test/sample_000208/board.png: downloading bytes:           |  0.00B

test/sample_000210/board.png: downloading bytes:           |  0.00B

test/sample_000211/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

test/sample_000211/board.png: downloading bytes:           |  0.00B

test/sample_000212/board.png: reconstructing file:   0%|          |  0.00B / 34.3kB

test/sample_000212/board.png: downloading bytes:           |  0.00B

test/sample_000213/board.png: reconstructing file:   0%|          |  0.00B / 24.0kB

test/sample_000213/board.png: downloading bytes:           |  0.00B

test/sample_000214/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

test/sample_000214/board.png: downloading bytes:           |  0.00B

test/sample_000215/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

test/sample_000215/board.png: downloading bytes:           |  0.00B

test/sample_000216/board.png: reconstructing file:   0%|          |  0.00B / 22.4kB

test/sample_000217/board.png: reconstructing file:   0%|          |  0.00B / 36.7kB

test/sample_000218/board.png: reconstructing file:   0%|          |  0.00B / 28.3kB

test/sample_000216/board.png: downloading bytes:           |  0.00B

test/sample_000218/board.png: downloading bytes:           |  0.00B

test/sample_000217/board.png: downloading bytes:           |  0.00B

test/sample_000219/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

test/sample_000220/board.png: reconstructing file:   0%|          |  0.00B / 30.7kB

test/sample_000219/board.png: downloading bytes:           |  0.00B

test/sample_000220/board.png: downloading bytes:           |  0.00B

test/sample_000221/board.png: reconstructing file:   0%|          |  0.00B / 20.5kB

test/sample_000221/board.png: downloading bytes:           |  0.00B

test/sample_000222/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

test/sample_000222/board.png: downloading bytes:           |  0.00B

test/sample_000223/board.png: reconstructing file:   0%|          |  0.00B / 36.5kB

test/sample_000224/board.png: reconstructing file:   0%|          |  0.00B / 32.0kB

test/sample_000225/board.png: reconstructing file:   0%|          |  0.00B / 16.7kB

test/sample_000223/board.png: downloading bytes:           |  0.00B

test/sample_000226/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

test/sample_000224/board.png: downloading bytes:           |  0.00B

test/sample_000227/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

test/sample_000225/board.png: downloading bytes:           |  0.00B

test/sample_000226/board.png: downloading bytes:           |  0.00B

test/sample_000227/board.png: downloading bytes:           |  0.00B

test/sample_000228/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

test/sample_000228/board.png: downloading bytes:           |  0.00B

test/sample_000230/board.png: reconstructing file:   0%|          |  0.00B / 17.0kB

test/sample_000229/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

test/sample_000230/board.png: downloading bytes:           |  0.00B

test/sample_000229/board.png: downloading bytes:           |  0.00B

test/sample_000231/board.png: reconstructing file:   0%|          |  0.00B / 28.5kB

test/sample_000231/board.png: downloading bytes:           |  0.00B

test/sample_000232/board.png: reconstructing file:   0%|          |  0.00B / 13.0kB

test/sample_000233/board.png: reconstructing file:   0%|          |  0.00B / 27.9kB

test/sample_000232/board.png: downloading bytes:           |  0.00B

test/sample_000234/board.png: reconstructing file:   0%|          |  0.00B / 39.6kB

test/sample_000233/board.png: downloading bytes:           |  0.00B

test/sample_000235/board.png: reconstructing file:   0%|          |  0.00B / 42.8kB

test/sample_000234/board.png: downloading bytes:           |  0.00B

test/sample_000235/board.png: downloading bytes:           |  0.00B

test/sample_000236/board.png: reconstructing file:   0%|          |  0.00B / 28.4kB

test/sample_000236/board.png: downloading bytes:           |  0.00B

test/sample_000237/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

test/sample_000237/board.png: downloading bytes:           |  0.00B

test/sample_000238/board.png: reconstructing file:   0%|          |  0.00B / 34.7kB

test/sample_000238/board.png: downloading bytes:           |  0.00B

test/sample_000239/board.png: reconstructing file:   0%|          |  0.00B / 29.1kB

test/sample_000239/board.png: downloading bytes:           |  0.00B

test/sample_000240/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

test/sample_000242/board.png: reconstructing file:   0%|          |  0.00B / 16.6kB

test/sample_000241/board.png: reconstructing file:   0%|          |  0.00B / 15.3kB

test/sample_000243/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

test/sample_000240/board.png: downloading bytes:           |  0.00B

test/sample_000241/board.png: downloading bytes:           |  0.00B

test/sample_000242/board.png: downloading bytes:           |  0.00B

test/sample_000243/board.png: downloading bytes:           |  0.00B

test/sample_000244/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

test/sample_000244/board.png: downloading bytes:           |  0.00B

test/sample_000245/board.png: reconstructing file:   0%|          |  0.00B / 37.9kB

test/sample_000246/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

test/sample_000245/board.png: downloading bytes:           |  0.00B

test/sample_000246/board.png: downloading bytes:           |  0.00B

test/sample_000247/board.png: reconstructing file:   0%|          |  0.00B / 39.8kB

test/sample_000247/board.png: downloading bytes:           |  0.00B

test/sample_000248/board.png: reconstructing file:   0%|          |  0.00B / 28.2kB

test/sample_000248/board.png: downloading bytes:           |  0.00B

test/sample_000249/board.png: reconstructing file:   0%|          |  0.00B / 19.5kB

test/sample_000250/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

test/sample_000249/board.png: downloading bytes:           |  0.00B

test/sample_000251/board.png: reconstructing file:   0%|          |  0.00B / 21.6kB

test/sample_000250/board.png: downloading bytes:           |  0.00B

test/sample_000251/board.png: downloading bytes:           |  0.00B

test/sample_000252/board.png: reconstructing file:   0%|          |  0.00B / 43.9kB

test/sample_000252/board.png: downloading bytes:           |  0.00B

test/sample_000253/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

test/sample_000253/board.png: downloading bytes:           |  0.00B

test/sample_000254/board.png: reconstructing file:   0%|          |  0.00B / 38.0kB

test/sample_000254/board.png: downloading bytes:           |  0.00B

test/sample_000256/board.png: reconstructing file:   0%|          |  0.00B / 36.4kB

test/sample_000256/board.png: downloading bytes:           |  0.00B

test/sample_000255/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

test/sample_000255/board.png: downloading bytes:           |  0.00B

test/sample_000257/board.png: reconstructing file:   0%|          |  0.00B / 38.4kB

test/sample_000257/board.png: downloading bytes:           |  0.00B

test/sample_000258/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

test/sample_000259/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

test/sample_000258/board.png: downloading bytes:           |  0.00B

test/sample_000259/board.png: downloading bytes:           |  0.00B

test/sample_000260/board.png: reconstructing file:   0%|          |  0.00B / 24.3kB

test/sample_000260/board.png: downloading bytes:           |  0.00B

test/sample_000261/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

test/sample_000261/board.png: downloading bytes:           |  0.00B

test/sample_000262/board.png: reconstructing file:   0%|          |  0.00B / 27.2kB

test/sample_000263/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

test/sample_000262/board.png: downloading bytes:           |  0.00B

test/sample_000264/board.png: reconstructing file:   0%|          |  0.00B / 31.8kB

test/sample_000263/board.png: downloading bytes:           |  0.00B

test/sample_000264/board.png: downloading bytes:           |  0.00B

test/sample_000265/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

test/sample_000265/board.png: downloading bytes:           |  0.00B

test/sample_000267/board.png: reconstructing file:   0%|          |  0.00B / 15.2kB

test/sample_000266/board.png: reconstructing file:   0%|          |  0.00B / 14.4kB

test/sample_000268/board.png: reconstructing file:   0%|          |  0.00B / 34.4kB

test/sample_000267/board.png: downloading bytes:           |  0.00B

test/sample_000266/board.png: downloading bytes:           |  0.00B

test/sample_000268/board.png: downloading bytes:           |  0.00B

test/sample_000269/board.png: reconstructing file:   0%|          |  0.00B / 27.5kB

test/sample_000269/board.png: downloading bytes:           |  0.00B

test/sample_000270/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

test/sample_000271/board.png: reconstructing file:   0%|          |  0.00B / 25.4kB

test/sample_000270/board.png: downloading bytes:           |  0.00B

test/sample_000271/board.png: downloading bytes:           |  0.00B

test/sample_000272/board.png: reconstructing file:   0%|          |  0.00B / 27.6kB

test/sample_000272/board.png: downloading bytes:           |  0.00B

test/sample_000273/board.png: reconstructing file:   0%|          |  0.00B / 24.5kB

test/sample_000273/board.png: downloading bytes:           |  0.00B

test/sample_000274/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

test/sample_000275/board.png: reconstructing file:   0%|          |  0.00B / 32.1kB

test/sample_000276/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

test/sample_000274/board.png: downloading bytes:           |  0.00B

test/sample_000275/board.png: downloading bytes:           |  0.00B

test/sample_000276/board.png: downloading bytes:           |  0.00B

test/sample_000277/board.png: reconstructing file:   0%|          |  0.00B / 18.2kB

test/sample_000277/board.png: downloading bytes:           |  0.00B

test/sample_000278/board.png: reconstructing file:   0%|          |  0.00B / 40.4kB

test/sample_000278/board.png: downloading bytes:           |  0.00B

test/sample_000279/board.png: reconstructing file:   0%|          |  0.00B / 16.2kB

test/sample_000279/board.png: downloading bytes:           |  0.00B

test/sample_000280/board.png: reconstructing file:   0%|          |  0.00B / 23.0kB

test/sample_000280/board.png: downloading bytes:           |  0.00B

test/sample_000281/board.png: reconstructing file:   0%|          |  0.00B / 32.8kB

test/sample_000281/board.png: downloading bytes:           |  0.00B

test/sample_000282/board.png: reconstructing file:   0%|          |  0.00B / 29.3kB

test/sample_000284/board.png: reconstructing file:   0%|          |  0.00B / 37.8kB

test/sample_000282/board.png: downloading bytes:           |  0.00B

test/sample_000283/board.png: reconstructing file:   0%|          |  0.00B / 29.7kB

test/sample_000283/board.png: downloading bytes:           |  0.00B

test/sample_000284/board.png: downloading bytes:           |  0.00B

test/sample_000285/board.png: reconstructing file:   0%|          |  0.00B / 41.0kB

test/sample_000285/board.png: downloading bytes:           |  0.00B

test/sample_000286/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

test/sample_000286/board.png: downloading bytes:           |  0.00B

test/sample_000287/board.png: reconstructing file:   0%|          |  0.00B / 43.1kB

test/sample_000287/board.png: downloading bytes:           |  0.00B

test/sample_000288/board.png: reconstructing file:   0%|          |  0.00B / 21.8kB

test/sample_000288/board.png: downloading bytes:           |  0.00B

test/sample_000289/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

test/sample_000289/board.png: downloading bytes:           |  0.00B

test/sample_000290/board.png: reconstructing file:   0%|          |  0.00B / 21.8kB

test/sample_000290/board.png: downloading bytes:           |  0.00B

test/sample_000291/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

test/sample_000292/board.png: reconstructing file:   0%|          |  0.00B / 45.1kB

test/sample_000291/board.png: downloading bytes:           |  0.00B

test/sample_000292/board.png: downloading bytes:           |  0.00B

test/sample_000293/board.png: reconstructing file:   0%|          |  0.00B / 28.8kB

test/sample_000293/board.png: downloading bytes:           |  0.00B

test/sample_000294/board.png: reconstructing file:   0%|          |  0.00B / 16.1kB

test/sample_000294/board.png: downloading bytes:           |  0.00B

test/sample_000295/board.png: reconstructing file:   0%|          |  0.00B / 36.8kB

test/sample_000295/board.png: downloading bytes:           |  0.00B

test/sample_000296/board.png: reconstructing file:   0%|          |  0.00B / 38.2kB

test/sample_000296/board.png: downloading bytes:           |  0.00B

test/sample_000297/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

test/sample_000298/board.png: reconstructing file:   0%|          |  0.00B / 39.9kB

test/sample_000297/board.png: downloading bytes:           |  0.00B

test/sample_000298/board.png: downloading bytes:           |  0.00B

test/sample_000299/board.png: reconstructing file:   0%|          |  0.00B / 21.9kB

test/sample_000299/board.png: downloading bytes:           |  0.00B

test/sample_000300/board.png: reconstructing file:   0%|          |  0.00B / 37.7kB

test/sample_000300/board.png: downloading bytes:           |  0.00B

test/sample_000301/board.png: reconstructing file:   0%|          |  0.00B / 21.5kB

test/sample_000302/board.png: reconstructing file:   0%|          |  0.00B / 31.4kB

test/sample_000303/board.png: reconstructing file:   0%|          |  0.00B / 22.0kB

test/sample_000301/board.png: downloading bytes:           |  0.00B

test/sample_000302/board.png: downloading bytes:           |  0.00B

test/sample_000303/board.png: downloading bytes:           |  0.00B

test/sample_000304/board.png: reconstructing file:   0%|          |  0.00B / 14.9kB

test/sample_000304/board.png: downloading bytes:           |  0.00B

test/sample_000305/board.png: reconstructing file:   0%|          |  0.00B / 33.9kB

test/sample_000305/board.png: downloading bytes:           |  0.00B

test/sample_000306/board.png: reconstructing file:   0%|          |  0.00B / 14.0kB

test/sample_000306/board.png: downloading bytes:           |  0.00B

test/sample_000307/board.png: reconstructing file:   0%|          |  0.00B / 42.3kB

test/sample_000307/board.png: downloading bytes:           |  0.00B

test/sample_000308/board.png: reconstructing file:   0%|          |  0.00B / 29.8kB

test/sample_000309/board.png: reconstructing file:   0%|          |  0.00B / 27.4kB

test/sample_000310/board.png: reconstructing file:   0%|          |  0.00B / 17.4kB

test/sample_000308/board.png: downloading bytes:           |  0.00B

test/sample_000309/board.png: downloading bytes:           |  0.00B

test/sample_000310/board.png: downloading bytes:           |  0.00B

test/sample_000311/board.png: reconstructing file:   0%|          |  0.00B / 23.4kB

test/sample_000311/board.png: downloading bytes:           |  0.00B

test/sample_000312/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

test/sample_000312/board.png: downloading bytes:           |  0.00B

test/sample_000313/board.png: reconstructing file:   0%|          |  0.00B / 30.9kB

test/sample_000313/board.png: downloading bytes:           |  0.00B

test/sample_000314/board.png: reconstructing file:   0%|          |  0.00B / 33.6kB

test/sample_000314/board.png: downloading bytes:           |  0.00B

test/sample_000315/board.png: reconstructing file:   0%|          |  0.00B / 24.3kB

test/sample_000315/board.png: downloading bytes:           |  0.00B

test/sample_000316/board.png: reconstructing file:   0%|          |  0.00B / 33.7kB

test/sample_000316/board.png: downloading bytes:           |  0.00B

test/sample_000317/board.png: reconstructing file:   0%|          |  0.00B / 25.7kB

test/sample_000317/board.png: downloading bytes:           |  0.00B

test/sample_000318/board.png: reconstructing file:   0%|          |  0.00B / 20.5kB

test/sample_000318/board.png: downloading bytes:           |  0.00B

test/sample_000319/board.png: reconstructing file:   0%|          |  0.00B / 29.6kB

test/sample_000319/board.png: downloading bytes:           |  0.00B

test/sample_000320/board.png: reconstructing file:   0%|          |  0.00B / 18.1kB

test/sample_000321/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

test/sample_000320/board.png: downloading bytes:           |  0.00B

test/sample_000321/board.png: downloading bytes:           |  0.00B

test/sample_000322/board.png: reconstructing file:   0%|          |  0.00B / 28.9kB

test/sample_000322/board.png: downloading bytes:           |  0.00B

test/sample_000323/board.png: reconstructing file:   0%|          |  0.00B / 24.6kB

test/sample_000323/board.png: downloading bytes:           |  0.00B

test/sample_000324/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

test/sample_000324/board.png: downloading bytes:           |  0.00B

test/sample_000325/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

test/sample_000326/board.png: reconstructing file:   0%|          |  0.00B / 17.5kB

test/sample_000325/board.png: downloading bytes:           |  0.00B

test/sample_000326/board.png: downloading bytes:           |  0.00B

test/sample_000327/board.png: reconstructing file:   0%|          |  0.00B / 31.0kB

test/sample_000327/board.png: downloading bytes:           |  0.00B

test/sample_000328/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

test/sample_000328/board.png: downloading bytes:           |  0.00B

test/sample_000329/board.png: reconstructing file:   0%|          |  0.00B / 37.1kB

test/sample_000329/board.png: downloading bytes:           |  0.00B

test/sample_000330/board.png: reconstructing file:   0%|          |  0.00B / 24.8kB

test/sample_000330/board.png: downloading bytes:           |  0.00B

test/sample_000331/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

test/sample_000331/board.png: downloading bytes:           |  0.00B

test/sample_000332/board.png: reconstructing file:   0%|          |  0.00B / 15.9kB

test/sample_000332/board.png: downloading bytes:           |  0.00B

test/sample_000333/board.png: reconstructing file:   0%|          |  0.00B / 24.5kB

test/sample_000333/board.png: downloading bytes:           |  0.00B

test/sample_000334/board.png: reconstructing file:   0%|          |  0.00B / 14.5kB

test/sample_000334/board.png: downloading bytes:           |  0.00B

test/sample_000335/board.png: reconstructing file:   0%|          |  0.00B / 17.9kB

test/sample_000335/board.png: downloading bytes:           |  0.00B

test/sample_000336/board.png: reconstructing file:   0%|          |  0.00B / 19.0kB

test/sample_000336/board.png: downloading bytes:           |  0.00B

test/sample_000337/board.png: reconstructing file:   0%|          |  0.00B / 33.0kB

test/sample_000337/board.png: downloading bytes:           |  0.00B

test/sample_000338/board.png: reconstructing file:   0%|          |  0.00B / 27.8kB

test/sample_000338/board.png: downloading bytes:           |  0.00B

test/sample_000339/board.png: reconstructing file:   0%|          |  0.00B / 26.6kB

test/sample_000339/board.png: downloading bytes:           |  0.00B

test/sample_000340/board.png: reconstructing file:   0%|          |  0.00B / 15.3kB

test/sample_000340/board.png: downloading bytes:           |  0.00B

test/sample_000342/board.png: reconstructing file:   0%|          |  0.00B / 37.0kB

test/sample_000342/board.png: downloading bytes:           |  0.00B

test/sample_000341/board.png: reconstructing file:   0%|          |  0.00B / 23.3kB

test/sample_000341/board.png: downloading bytes:           |  0.00B

test/sample_000343/board.png: reconstructing file:   0%|          |  0.00B / 26.0kB

test/sample_000343/board.png: downloading bytes:           |  0.00B

test/sample_000344/board.png: reconstructing file:   0%|          |  0.00B / 36.3kB

test/sample_000344/board.png: downloading bytes:           |  0.00B

test/sample_000345/board.png: reconstructing file:   0%|          |  0.00B / 33.5kB

test/sample_000345/board.png: downloading bytes:           |  0.00B

test/sample_000346/board.png: reconstructing file:   0%|          |  0.00B / 33.3kB

test/sample_000346/board.png: downloading bytes:           |  0.00B

test/sample_000347/board.png: reconstructing file:   0%|          |  0.00B / 34.2kB

test/sample_000347/board.png: downloading bytes:           |  0.00B

test/sample_000348/board.png: reconstructing file:   0%|          |  0.00B / 29.4kB

test/sample_000349/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

test/sample_000349/board.png: downloading bytes:           |  0.00B

test/sample_000348/board.png: downloading bytes:           |  0.00B

test/sample_000350/board.png: reconstructing file:   0%|          |  0.00B / 40.4kB

test/sample_000350/board.png: downloading bytes:           |  0.00B

test/sample_000351/board.png: reconstructing file:   0%|          |  0.00B / 19.6kB

test/sample_000351/board.png: downloading bytes:           |  0.00B

test/sample_000352/board.png: reconstructing file:   0%|          |  0.00B / 27.1kB

test/sample_000352/board.png: downloading bytes:           |  0.00B

test/sample_000353/board.png: reconstructing file:   0%|          |  0.00B / 20.9kB

test/sample_000353/board.png: downloading bytes:           |  0.00B

test/sample_000354/board.png: reconstructing file:   0%|          |  0.00B / 31.6kB

test/sample_000354/board.png: downloading bytes:           |  0.00B

test/sample_000355/board.png: reconstructing file:   0%|          |  0.00B / 19.8kB

test/sample_000355/board.png: downloading bytes:           |  0.00B

test/sample_000356/board.png: reconstructing file:   0%|          |  0.00B / 17.4kB

test/sample_000356/board.png: downloading bytes:           |  0.00B

test/sample_000357/board.png: reconstructing file:   0%|          |  0.00B / 38.6kB

test/sample_000357/board.png: downloading bytes:           |  0.00B

test/sample_000358/board.png: reconstructing file:   0%|          |  0.00B / 16.4kB

test/sample_000358/board.png: downloading bytes:           |  0.00B

test/sample_000359/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

test/sample_000360/board.png: reconstructing file:   0%|          |  0.00B / 31.5kB

test/sample_000359/board.png: downloading bytes:           |  0.00B

test/sample_000361/board.png: reconstructing file:   0%|          |  0.00B / 30.4kB

test/sample_000360/board.png: downloading bytes:           |  0.00B

test/sample_000361/board.png: downloading bytes:           |  0.00B

test/sample_000362/board.png: reconstructing file:   0%|          |  0.00B / 24.2kB

test/sample_000362/board.png: downloading bytes:           |  0.00B

test/sample_000363/board.png: reconstructing file:   0%|          |  0.00B / 30.6kB

test/sample_000363/board.png: downloading bytes:           |  0.00B

test/sample_000364/board.png: reconstructing file:   0%|          |  0.00B / 39.1kB

test/sample_000365/board.png: reconstructing file:   0%|          |  0.00B / 30.1kB

test/sample_000364/board.png: downloading bytes:           |  0.00B

test/sample_000365/board.png: downloading bytes:           |  0.00B

test/sample_000366/board.png: reconstructing file:   0%|          |  0.00B / 20.8kB

test/sample_000366/board.png: downloading bytes:           |  0.00B

test/sample_000367/board.png: reconstructing file:   0%|          |  0.00B / 22.5kB

test/sample_000367/board.png: downloading bytes:           |  0.00B

test/sample_000368/board.png: reconstructing file:   0%|          |  0.00B / 33.4kB

test/sample_000368/board.png: downloading bytes:           |  0.00B

test/sample_000369/board.png: reconstructing file:   0%|          |  0.00B / 16.0kB

test/sample_000369/board.png: downloading bytes:           |  0.00B

test/sample_000370/board.png: reconstructing file:   0%|          |  0.00B / 19.8kB

test/sample_000370/board.png: downloading bytes:           |  0.00B

test/sample_000371/board.png: reconstructing file:   0%|          |  0.00B / 35.8kB

test/sample_000372/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

test/sample_000371/board.png: downloading bytes:           |  0.00B

test/sample_000372/board.png: downloading bytes:           |  0.00B

test/sample_000373/board.png: reconstructing file:   0%|          |  0.00B / 15.5kB

test/sample_000373/board.png: downloading bytes:           |  0.00B

test/sample_000374/board.png: reconstructing file:   0%|          |  0.00B / 35.6kB

test/sample_000374/board.png: downloading bytes:           |  0.00B

test/sample_000375/board.png: reconstructing file:   0%|          |  0.00B / 26.4kB

test/sample_000376/board.png: reconstructing file:   0%|          |  0.00B / 17.7kB

test/sample_000375/board.png: downloading bytes:           |  0.00B

test/sample_000376/board.png: downloading bytes:           |  0.00B

test/sample_000377/board.png: reconstructing file:   0%|          |  0.00B / 32.4kB

test/sample_000377/board.png: downloading bytes:           |  0.00B

test/sample_000378/board.png: reconstructing file:   0%|          |  0.00B / 27.7kB

test/sample_000378/board.png: downloading bytes:           |  0.00B

test/sample_000379/board.png: reconstructing file:   0%|          |  0.00B / 25.9kB

test/sample_000379/board.png: downloading bytes:           |  0.00B

test/sample_000380/board.png: reconstructing file:   0%|          |  0.00B / 28.6kB

test/sample_000381/board.png: reconstructing file:   0%|          |  0.00B / 11.0kB

test/sample_000382/board.png: reconstructing file:   0%|          |  0.00B / 20.2kB

test/sample_000381/board.png: downloading bytes:           |  0.00B

test/sample_000380/board.png: downloading bytes:           |  0.00B

test/sample_000382/board.png: downloading bytes:           |  0.00B

test/sample_000384/board.png: reconstructing file:   0%|          |  0.00B / 39.3kB

test/sample_000384/board.png: downloading bytes:           |  0.00B

test/sample_000383/board.png: reconstructing file:   0%|          |  0.00B / 33.1kB

test/sample_000385/board.png: reconstructing file:   0%|          |  0.00B / 35.0kB

test/sample_000383/board.png: downloading bytes:           |  0.00B

test/sample_000385/board.png: downloading bytes:           |  0.00B

test/sample_000386/board.png: reconstructing file:   0%|          |  0.00B / 22.7kB

test/sample_000386/board.png: downloading bytes:           |  0.00B

test/sample_000388/board.png: reconstructing file:   0%|          |  0.00B / 16.3kB

test/sample_000387/board.png: reconstructing file:   0%|          |  0.00B / 36.1kB

test/sample_000388/board.png: downloading bytes:           |  0.00B

test/sample_000387/board.png: downloading bytes:           |  0.00B

test/sample_000389/board.png: reconstructing file:   0%|          |  0.00B / 26.5kB

test/sample_000390/board.png: reconstructing file:   0%|          |  0.00B / 34.6kB

test/sample_000389/board.png: downloading bytes:           |  0.00B

test/sample_000390/board.png: downloading bytes:           |  0.00B

test/sample_000391/board.png: reconstructing file:   0%|          |  0.00B / 24.9kB

test/sample_000391/board.png: downloading bytes:           |  0.00B

test/sample_000392/board.png: reconstructing file:   0%|          |  0.00B / 40.0kB

test/sample_000392/board.png: downloading bytes:           |  0.00B

test/sample_000394/board.png: reconstructing file:   0%|          |  0.00B / 34.5kB

test/sample_000393/board.png: reconstructing file:   0%|          |  0.00B / 44.1kB

test/sample_000394/board.png: downloading bytes:           |  0.00B

test/sample_000393/board.png: downloading bytes:           |  0.00B

test/sample_000395/board.png: reconstructing file:   0%|          |  0.00B / 27.3kB

test/sample_000395/board.png: downloading bytes:           |  0.00B

test/sample_000396/board.png: reconstructing file:   0%|          |  0.00B / 15.4kB

test/sample_000396/board.png: downloading bytes:           |  0.00B

test/sample_000398/board.png: reconstructing file:   0%|          |  0.00B / 37.6kB

test/sample_000397/board.png: reconstructing file:   0%|          |  0.00B / 21.6kB

test/sample_000397/board.png: downloading bytes:           |  0.00B

test/sample_000398/board.png: downloading bytes:           |  0.00B

test/sample_000399/board.png: reconstructing file:   0%|          |  0.00B / 33.8kB

test/sample_000399/board.png: downloading bytes:           |  0.00B

metadata.jsonl:   0%|          | 0.00/235k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3200 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/400 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/400 [00:00<?, ? examples/s]

model.safetensors.index.json:   0%|          | 0.00/50.9k [00:00<?, ?B/s]

model.safetensors-00001-of-00001.safeten(…): reconstructing file:   0%|          |  0.00B / 1.75GB

model.safetensors-00001-of-00001.safeten(…): downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

[transformers] `causal_conv1d_fn` is falling back to its reference PyTorch implementation because `causal_conv1d` is not installed. This is correct but much slower; install `causal_conv1d` for the optimized kernel.

[token reordering] OK: {'image_tokens': 64, 'token_grid': (8, 8), 'max_logit_change': 2.03125}

## 5. Evaluate and compare

For each task: load the dataset and our published results table, then evaluate every selected row
and compare it with our saved predictions. Every row prints a progress bar; Task 1 rows take
about 20-25 minutes each on all 400 samples, Task 2 and Task 3 rows about 2 minutes. The 512px
rows are slower, because each image gives 4 times as many visual tokens.

In the comparison table:

- **ours, same samples**: the score of our saved predictions on the samples evaluated here;
- **reproduced**: the score of the new predictions on the same samples;
- **identical predictions**: how many new predictions are exactly the same string as ours;
- **ours, 400 samples (README)**: the number reported in the README.

### Task 1

In [5]:
comparison_task1 = reproduce_task("task1", LEVEL, processors, NUM_WORKERS, TASK1_SUBSET)
display(pd.DataFrame(comparison_task1))

Resolving data files:   0%|          | 0/3201 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/401 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/401 [00:00<?, ?it/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 10.9kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

learned_order.json:   0%|          | 0.00/574 [00:00<?, ?B/s]

learned_order.json:   0%|          | 0.00/320 [00:00<?, ?B/s]

=== Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256]:   0%|          | 0/100 [00:00<?, ?it/s][transformers] `causal_conv1d_update` is falling back to its reference PyTorch implementation because `causal_conv1d` is not installed. This is correct but much slower; install `causal_conv1d` for the optimized kernel.
Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256]: 100%|██████████| 100/100 [07:59<00:00,  4.79s/it]

Evaluation completed for Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256]! Results saved to task1_vanilla_qwen3.5-0.8b_(zero-shot)_[tok256]_results.csv.

(…).5-0.8b_%28zero-shot%29_%5Btok256%5D.csv:   0%|          | 0.00/197k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256]', 'test samples': 100, 'ours, same samples (%)': 0.0, 'reproduced (%)': 0.0, 'identical predictions': '86/100', 'ours, 400 samples (README, %)': 0.0}

=== Vanilla Qwen3.5-0.8B (3-Shot) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Vanilla Qwen3.5-0.8B (3-Shot) [tok256]: 100%|██████████| 100/100 [03:56<00:00,  2.37s/it]

Evaluation completed for Vanilla Qwen3.5-0.8B (3-Shot) [tok256]! Results saved to task1_vanilla_qwen3.5-0.8b_(3-shot)_[tok256]_results.csv.

(…)en3.5-0.8b_%283-shot%29_%5Btok256%5D.csv:   0%|          | 0.00/96.8k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Vanilla Qwen3.5-0.8B (3-Shot) [tok256]', 'test samples': 100, 'ours, same samples (%)': 0.0, 'reproduced (%)': 0.0, 'identical predictions': '78/100', 'ours, 400 samples (README, %)': 0.0}

=== Qwen + LoRA (Raster - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Raster - SFT) [tok256]: 100%|██████████| 400/400 [22:16<00:00,  3.34s/it]

Evaluation completed for Qwen + LoRA (Raster - SFT) [tok256]! Results saved to task1_qwen_+_lora_(raster_-_sft)_[tok256]_results.csv.

(…)lora_%28raster_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/88.1k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA (Raster - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 97.0, 'reproduced (%)': 97.0, 'identical predictions': '338/400', 'ours, 400 samples (README, %)': 97.0}

=== Qwen + LoRA Raster, read zigzag (TF) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read zigzag (TF) [tok256]: 100%|██████████| 100/100 [05:48<00:00,  3.49s/it]

Evaluation completed for Qwen + LoRA Raster, read zigzag (TF) [tok256]! Results saved to task1_qwen_+_lora_raster,_read_zigzag_(tf)_[tok256]_results.csv.

(…)2C_read_zigzag_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/94.6k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA Raster, read zigzag (TF) [tok256]', 'test samples': 100, 'ours, same samples (%)': 0.0, 'reproduced (%)': 0.0, 'identical predictions': '60/100', 'ours, 400 samples (README, %)': 0.0}

=== Qwen + LoRA Raster, read spiral_center_out (TF) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read spiral_center_out (TF) [tok256]: 100%|██████████| 100/100 [06:36<00:00,  3.97s/it]

Evaluation completed for Qwen + LoRA Raster, read spiral_center_out (TF) [tok256]! Results saved to task1_qwen_+_lora_raster,_read_spiral_center_out_(tf)_[tok256]_results.csv.

(…)ral_center_out_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/98.2k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA Raster, read spiral_center_out (TF) [tok256]', 'test samples': 100, 'ours, same samples (%)': 0.0, 'reproduced (%)': 0.0, 'identical predictions': '57/100', 'ours, 400 samples (README, %)': 0.0}

=== Qwen + LoRA Raster, read file_wise (TF) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read file_wise (TF) [tok256]: 100%|██████████| 100/100 [07:01<00:00,  4.22s/it]

Evaluation completed for Qwen + LoRA Raster, read file_wise (TF) [tok256]! Results saved to task1_qwen_+_lora_raster,_read_file_wise_(tf)_[tok256]_results.csv.

(…)read_file_wise_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/98.1k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA Raster, read file_wise (TF) [tok256]', 'test samples': 100, 'ours, same samples (%)': 0.0, 'reproduced (%)': 0.0, 'identical predictions': '49/100', 'ours, 400 samples (README, %)': 0.0}

=== Qwen + LoRA Raster, read hilbert (TF) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

[reorder] Fetching https://github.com/d3tk/REOrder@ddb2904 into /content/BigDataAndTextMiningProject/external/REOrder ...

Evaluating Qwen + LoRA Raster, read hilbert (TF) [tok256]: 100%|██████████| 100/100 [06:19<00:00,  3.80s/it]

Evaluation completed for Qwen + LoRA Raster, read hilbert (TF) [tok256]! Results saved to task1_qwen_+_lora_raster,_read_hilbert_(tf)_[tok256]_results.csv.

(…)C_read_hilbert_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/96.4k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA Raster, read hilbert (TF) [tok256]', 'test samples': 100, 'ours, same samples (%)': 0.0, 'reproduced (%)': 0.0, 'identical predictions': '57/100', 'ours, 400 samples (README, %)': 0.0}

=== Qwen + LoRA (Zigzag - SFT) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Zigzag - SFT) [tok256]: 100%|██████████| 100/100 [05:35<00:00,  3.35s/it]

Evaluation completed for Qwen + LoRA (Zigzag - SFT) [tok256]! Results saved to task1_qwen_+_lora_(zigzag_-_sft)_[tok256]_results.csv.

(…)lora_%28zigzag_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/88.0k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA (Zigzag - SFT) [tok256]', 'test samples': 100, 'ours, same samples (%)': 97.0, 'reproduced (%)': 97.0, 'identical predictions': '94/100', 'ours, 400 samples (README, %)': 97.5}

=== Qwen + LoRA (Spiral_center_out - SFT) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Spiral_center_out - SFT) [tok256]: 100%|██████████| 100/100 [05:32<00:00,  3.33s/it]

Evaluation completed for Qwen + LoRA (Spiral_center_out - SFT) [tok256]! Results saved to task1_qwen_+_lora_(spiral_center_out_-_sft)_[tok256]_results.csv.

(…)ral_center_out_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/88.0k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA (Spiral_center_out - SFT) [tok256]', 'test samples': 100, 'ours, same samples (%)': 99.0, 'reproduced (%)': 99.0, 'identical predictions': '83/100', 'ours, 400 samples (README, %)': 98.5}

=== Qwen + LoRA (File_wise - SFT) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (File_wise - SFT) [tok256]: 100%|██████████| 100/100 [05:32<00:00,  3.33s/it]

Evaluation completed for Qwen + LoRA (File_wise - SFT) [tok256]! Results saved to task1_qwen_+_lora_(file_wise_-_sft)_[tok256]_results.csv.

(…)a_%28file_wise_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/88.1k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA (File_wise - SFT) [tok256]', 'test samples': 100, 'ours, same samples (%)': 95.0, 'reproduced (%)': 95.0, 'identical predictions': '82/100', 'ours, 400 samples (README, %)': 96.75}

=== Qwen + LoRA (Hilbert - SFT) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Hilbert - SFT) [tok256]: 100%|██████████| 100/100 [05:14<00:00,  3.15s/it]

Evaluation completed for Qwen + LoRA (Hilbert - SFT) [tok256]! Results saved to task1_qwen_+_lora_(hilbert_-_sft)_[tok256]_results.csv.

(…)ora_%28hilbert_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/88.1k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA (Hilbert - SFT) [tok256]', 'test samples': 100, 'ours, same samples (%)': 96.0, 'reproduced (%)': 96.0, 'identical predictions': '77/100', 'ours, 400 samples (README, %)': 95.25}

=== Qwen + LoRA (Learned Reordering) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Learned Reordering) [tok256]: 100%|██████████| 100/100 [05:15<00:00,  3.16s/it]

Evaluation completed for Qwen + LoRA (Learned Reordering) [tok256]! Results saved to task1_qwen_+_lora_(learned_reordering)_[tok256]_results.csv.

(…)28learned_reordering%29_%5Btok256%5D.csv:   0%|          | 0.00/88.2k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA (Learned Reordering) [tok256]', 'test samples': 100, 'ours, same samples (%)': 96.0, 'reproduced (%)': 96.0, 'identical predictions': '80/100', 'ours, 400 samples (README, %)': 95.75}

=== Qwen + LoRA (Learned Reordering, frozen policy) [tok256] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Learned Reordering, frozen policy) [tok256]: 100%|██████████| 100/100 [05:15<00:00,  3.15s/it]

Evaluation completed for Qwen + LoRA (Learned Reordering, frozen policy) [tok256]! Results saved to task1_qwen_+_lora_(learned_reordering,_frozen_policy)_[tok256]_results.csv.

(…)ing%2C_frozen_policy%29_%5Btok256%5D.csv:   0%|          | 0.00/88.0k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA (Learned Reordering, frozen policy) [tok256]', 'test samples': 100, 'ours, same samples (%)': 94.0, 'reproduced (%)': 94.0, 'identical predictions': '89/100', 'ours, 400 samples (README, %)': 96.75}

=== Qwen + LoRA (Raster - SFT) [512px] (100 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA Fine-Tuning (from HF): 100%|██████████| 100/100 [05:16<00:00,  3.16s/it]

Evaluation completed for Qwen + LoRA Fine-Tuning (from HF)! Results saved to task1_qwen_+_lora_fine-tuning_(from_hf)_results.csv.

(…)n_%2B_lora_fine-tuning_%28from_hf%29.csv:   0%|          | 0.00/87.9k [00:00<?, ?B/s]

{'task': 'task1', 'model': 'Qwen + LoRA (Raster - SFT) [512px]', 'test samples': 100, 'ours, same samples (%)': 100.0, 'reproduced (%)': 99.0, 'identical predictions': '82/100', 'ours, 400 samples (README, %)': 99.0}

,task,model,test samples,"ours, same samples (%)",reproduced (%),identical predictions,"ours, 400 samples (README, %)"
0,task1,Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256],100,0.0,0.0,86/100,0.00
1,task1,Vanilla Qwen3.5-0.8B (3-Shot) [tok256],100,0.0,0.0,78/100,0.00
2,task1,Qwen + LoRA (Raster - SFT) [tok256],400,97.0,97.0,338/400,97.00
3,task1,"Qwen + LoRA Raster, read zigzag (TF) [tok256]",100,0.0,0.0,60/100,0.00
4,task1,"Qwen + LoRA Raster, read spiral_center_out (TF...",100,0.0,0.0,57/100,0.00
5,task1,"Qwen + LoRA Raster, read file_wise (TF) [tok256]",100,0.0,0.0,49/100,0.00
6,task1,"Qwen + LoRA Raster, read hilbert (TF) [tok256]",100,0.0,0.0,57/100,0.00
7,task1,Qwen + LoRA (Zigzag - SFT) [tok256],100,97.0,97.0,94/100,97.50
8,task1,Qwen + LoRA (Spiral_center_out - SFT) [tok256],100,99.0,99.0,83/100,98.50
9,task1,Qwen + LoRA (File_wise - SFT) [tok256],100,95.0,95.0,82/100,96.75
10,task1,Qwen + LoRA (Hilbert - SFT) [tok256],100,96.0,96.0,77/100,95.25
11,task1,Qwen + LoRA (Learned Reordering) [tok256],100,96.0,96.0,80/100,95.75
12,task1,"Qwen + LoRA (Learned Reordering, frozen policy...",100,94.0,94.0,89/100,96.75
13,task1,Qwen + LoRA (Raster - SFT) [512px],100,100.0,99.0,82/100,99.00

### Task 2

In [7]:
comparison_task2 = reproduce_task("task2", LEVEL, processors, NUM_WORKERS, TASK1_SUBSET)
display(pd.DataFrame(comparison_task2))

Resolving data files:   0%|          | 0/3201 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/401 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/401 [00:00<?, ?it/s]

metadata.jsonl:   0%|          | 0.00/213k [00:00<?, ?B/s]

Setting num_proc from 8 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 8 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Generating train split:   0%|          | 0/3200 [00:00<?, ? examples/s]

Setting num_proc from 8 back to 1 for the validation split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 8 back to 1 for the validation split to disable multiprocessing as it only contains one shard.

Generating validation split:   0%|          | 0/400 [00:00<?, ? examples/s]

Setting num_proc from 8 back to 1 for the test split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 8 back to 1 for the test split to disable multiprocessing as it only contains one shard.

Generating test split:   0%|          | 0/400 [00:00<?, ? examples/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 9.62kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

learned_order.json:   0%|          | 0.00/574 [00:00<?, ?B/s]

learned_order.json:   0%|          | 0.00/320 [00:00<?, ?B/s]

=== Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] (Task 2): 100%|██████████| 400/400 [03:08<00:00,  2.12it/s]

Evaluation completed for Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256]! Results saved to task2_vanilla_qwen3.5-0.8b_(zero-shot)_[tok256]_results.csv.

(…).5-0.8b_%28zero-shot%29_%5Btok256%5D.csv:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256]', 'test samples': 400, 'ours, same samples (%)': 0.0, 'reproduced (%)': 0.25, 'identical predictions': '252/400', 'ours, 400 samples (README, %)': 0.0}

=== Vanilla Qwen3.5-0.8B (3-Shot) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Vanilla Qwen3.5-0.8B (3-Shot) [tok256] (Task 2): 100%|██████████| 400/400 [01:32<00:00,  4.31it/s]

Evaluation completed for Vanilla Qwen3.5-0.8B (3-Shot) [tok256]! Results saved to task2_vanilla_qwen3.5-0.8b_(3-shot)_[tok256]_results.csv.

(…)en3.5-0.8b_%283-shot%29_%5Btok256%5D.csv:   0%|          | 0.00/19.6k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Vanilla Qwen3.5-0.8B (3-Shot) [tok256]', 'test samples': 400, 'ours, same samples (%)': 0.75, 'reproduced (%)': 0.75, 'identical predictions': '317/400', 'ours, 400 samples (README, %)': 0.75}

=== Qwen + LoRA (Raster - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Raster - SFT) [tok256] (Task 2): 100%|██████████| 400/400 [02:00<00:00,  3.31it/s]

Evaluation completed for Qwen + LoRA (Raster - SFT) [tok256]! Results saved to task2_qwen_+_lora_(raster_-_sft)_[tok256]_results.csv.

(…)lora_%28raster_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/19.7k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA (Raster - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 60.25, 'reproduced (%)': 60.0, 'identical predictions': '399/400', 'ours, 400 samples (README, %)': 60.25}

=== Qwen + LoRA Raster, read zigzag (TF) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read zigzag (TF) [tok256] (Task 2): 100%|██████████| 400/400 [02:01<00:00,  3.30it/s]

Evaluation completed for Qwen + LoRA Raster, read zigzag (TF) [tok256]! Results saved to task2_qwen_+_lora_raster,_read_zigzag_(tf)_[tok256]_results.csv.

(…)2C_read_zigzag_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/19.7k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA Raster, read zigzag (TF) [tok256]', 'test samples': 400, 'ours, same samples (%)': 52.75, 'reproduced (%)': 52.25, 'identical predictions': '393/400', 'ours, 400 samples (README, %)': 52.75}

=== Qwen + LoRA Raster, read spiral_center_out (TF) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read spiral_center_out (TF) [tok256] (Task 2): 100%|██████████| 400/400 [02:00<00:00,  3.32it/s]

Evaluation completed for Qwen + LoRA Raster, read spiral_center_out (TF) [tok256]! Results saved to task2_qwen_+_lora_raster,_read_spiral_center_out_(tf)_[tok256]_results.csv.

(…)ral_center_out_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/19.8k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA Raster, read spiral_center_out (TF) [tok256]', 'test samples': 400, 'ours, same samples (%)': 14.5, 'reproduced (%)': 14.0, 'identical predictions': '391/400', 'ours, 400 samples (README, %)': 14.5}

=== Qwen + LoRA Raster, read file_wise (TF) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read file_wise (TF) [tok256] (Task 2): 100%|██████████| 400/400 [02:00<00:00,  3.31it/s]

Evaluation completed for Qwen + LoRA Raster, read file_wise (TF) [tok256]! Results saved to task2_qwen_+_lora_raster,_read_file_wise_(tf)_[tok256]_results.csv.

(…)read_file_wise_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/19.7k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA Raster, read file_wise (TF) [tok256]', 'test samples': 400, 'ours, same samples (%)': 9.75, 'reproduced (%)': 9.5, 'identical predictions': '391/400', 'ours, 400 samples (README, %)': 9.75}

=== Qwen + LoRA Raster, read hilbert (TF) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read hilbert (TF) [tok256] (Task 2): 100%|██████████| 400/400 [02:00<00:00,  3.31it/s]

Evaluation completed for Qwen + LoRA Raster, read hilbert (TF) [tok256]! Results saved to task2_qwen_+_lora_raster,_read_hilbert_(tf)_[tok256]_results.csv.

(…)C_read_hilbert_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/19.8k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA Raster, read hilbert (TF) [tok256]', 'test samples': 400, 'ours, same samples (%)': 29.0, 'reproduced (%)': 29.5, 'identical predictions': '388/400', 'ours, 400 samples (README, %)': 29.0}

=== Qwen + LoRA (Zigzag - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Zigzag - SFT) [tok256] (Task 2): 100%|██████████| 400/400 [02:01<00:00,  3.30it/s]

Evaluation completed for Qwen + LoRA (Zigzag - SFT) [tok256]! Results saved to task2_qwen_+_lora_(zigzag_-_sft)_[tok256]_results.csv.

(…)lora_%28zigzag_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/19.6k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA (Zigzag - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 53.5, 'reproduced (%)': 53.5, 'identical predictions': '400/400', 'ours, 400 samples (README, %)': 53.5}

=== Qwen + LoRA (Spiral_center_out - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Spiral_center_out - SFT) [tok256] (Task 2): 100%|██████████| 400/400 [02:01<00:00,  3.28it/s]

Evaluation completed for Qwen + LoRA (Spiral_center_out - SFT) [tok256]! Results saved to task2_qwen_+_lora_(spiral_center_out_-_sft)_[tok256]_results.csv.

(…)ral_center_out_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/19.6k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA (Spiral_center_out - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 54.0, 'reproduced (%)': 54.0, 'identical predictions': '400/400', 'ours, 400 samples (README, %)': 54.0}

=== Qwen + LoRA (File_wise - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (File_wise - SFT) [tok256] (Task 2): 100%|██████████| 400/400 [02:00<00:00,  3.31it/s]

Evaluation completed for Qwen + LoRA (File_wise - SFT) [tok256]! Results saved to task2_qwen_+_lora_(file_wise_-_sft)_[tok256]_results.csv.

(…)a_%28file_wise_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/19.7k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA (File_wise - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 54.75, 'reproduced (%)': 54.75, 'identical predictions': '400/400', 'ours, 400 samples (README, %)': 54.75}

=== Qwen + LoRA (Hilbert - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Hilbert - SFT) [tok256] (Task 2): 100%|██████████| 400/400 [02:01<00:00,  3.29it/s]

Evaluation completed for Qwen + LoRA (Hilbert - SFT) [tok256]! Results saved to task2_qwen_+_lora_(hilbert_-_sft)_[tok256]_results.csv.

(…)ora_%28hilbert_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/19.6k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA (Hilbert - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 52.5, 'reproduced (%)': 52.5, 'identical predictions': '400/400', 'ours, 400 samples (README, %)': 52.5}

=== Qwen + LoRA (Learned Reordering) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Learned Reordering) [tok256] (Task 2): 100%|██████████| 400/400 [02:00<00:00,  3.31it/s]

Evaluation completed for Qwen + LoRA (Learned Reordering) [tok256]! Results saved to task2_qwen_+_lora_(learned_reordering)_[tok256]_results.csv.

(…)28learned_reordering%29_%5Btok256%5D.csv:   0%|          | 0.00/19.7k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA (Learned Reordering) [tok256]', 'test samples': 400, 'ours, same samples (%)': 57.75, 'reproduced (%)': 57.75, 'identical predictions': '400/400', 'ours, 400 samples (README, %)': 57.75}

=== Qwen + LoRA (Learned Reordering, frozen policy) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Learned Reordering, frozen policy) [tok256] (Task 2): 100%|██████████| 400/400 [02:01<00:00,  3.29it/s]

Evaluation completed for Qwen + LoRA (Learned Reordering, frozen policy) [tok256]! Results saved to task2_qwen_+_lora_(learned_reordering,_frozen_policy)_[tok256]_results.csv.

(…)ing%2C_frozen_policy%29_%5Btok256%5D.csv:   0%|          | 0.00/19.6k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA (Learned Reordering, frozen policy) [tok256]', 'test samples': 400, 'ours, same samples (%)': 59.5, 'reproduced (%)': 59.5, 'identical predictions': '400/400', 'ours, 400 samples (README, %)': 59.5}

=== Qwen + LoRA (Raster - SFT) [512px] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA Fine-Tuning (from HF) (Task 2): 100%|██████████| 400/400 [02:03<00:00,  3.25it/s]

Evaluation completed for Qwen + LoRA Fine-Tuning (from HF)! Results saved to task2_qwen_+_lora_fine-tuning_(from_hf)_results.csv.

(…)n_%2B_lora_fine-tuning_%28from_hf%29.csv:   0%|          | 0.00/18.7k [00:00<?, ?B/s]

{'task': 'task2', 'model': 'Qwen + LoRA (Raster - SFT) [512px]', 'test samples': 400, 'ours, same samples (%)': 62.0, 'reproduced (%)': 62.5, 'identical predictions': '396/400', 'ours, 400 samples (README, %)': 62.0}

,task,model,test samples,"ours, same samples (%)",reproduced (%),identical predictions,"ours, 400 samples (README, %)"
0,task2,Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256],400,0.00,0.25,252/400,0.00
1,task2,Vanilla Qwen3.5-0.8B (3-Shot) [tok256],400,0.75,0.75,317/400,0.75
2,task2,Qwen + LoRA (Raster - SFT) [tok256],400,60.25,60.00,399/400,60.25
3,task2,"Qwen + LoRA Raster, read zigzag (TF) [tok256]",400,52.75,52.25,393/400,52.75
4,task2,"Qwen + LoRA Raster, read spiral_center_out (TF...",400,14.50,14.00,391/400,14.50
5,task2,"Qwen + LoRA Raster, read file_wise (TF) [tok256]",400,9.75,9.50,391/400,9.75
6,task2,"Qwen + LoRA Raster, read hilbert (TF) [tok256]",400,29.00,29.50,388/400,29.00
7,task2,Qwen + LoRA (Zigzag - SFT) [tok256],400,53.50,53.50,400/400,53.50
8,task2,Qwen + LoRA (Spiral_center_out - SFT) [tok256],400,54.00,54.00,400/400,54.00
9,task2,Qwen + LoRA (File_wise - SFT) [tok256],400,54.75,54.75,400/400,54.75
10,task2,Qwen + LoRA (Hilbert - SFT) [tok256],400,52.50,52.50,400/400,52.50
11,task2,Qwen + LoRA (Learned Reordering) [tok256],400,57.75,57.75,400/400,57.75
12,task2,"Qwen + LoRA (Learned Reordering, frozen policy...",400,59.50,59.50,400/400,59.50
13,task2,Qwen + LoRA (Raster - SFT) [512px],400,62.00,62.50,396/400,62.00

### Task 3

In [8]:
comparison_task3 = reproduce_task("task3", LEVEL, processors, NUM_WORKERS, TASK1_SUBSET)
display(pd.DataFrame(comparison_task3))

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 8004 files:   0%|          | 0/8004 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/6401 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/801 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/801 [00:00<?, ?it/s]

Setting num_proc from 8 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 8 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Generating train split: 0 examples [00:00, ? examples/s]

Setting num_proc from 8 back to 1 for the validation split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 8 back to 1 for the validation split to disable multiprocessing as it only contains one shard.

Generating validation split: 0 examples [00:00, ? examples/s]

Setting num_proc from 8 back to 1 for the test split to disable multiprocessing as it only contains one shard.
WARNING:datasets.builder:Setting num_proc from 8 back to 1 for the test split to disable multiprocessing as it only contains one shard.

Generating test split: 0 examples [00:00, ? examples/s]

Map (num_proc=8):   0%|          | 0/3200 [00:00<?, ? examples/s]

Map (num_proc=8):   0%|          | 0/400 [00:00<?, ? examples/s]

Map (num_proc=8):   0%|          | 0/400 [00:00<?, ? examples/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 9.62kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

learned_order.json:   0%|          | 0.00/574 [00:00<?, ?B/s]

learned_order.json:   0%|          | 0.00/320 [00:00<?, ?B/s]

=== Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   0%|          | 0/400 [00:00<?, ?it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   0%|          | 1/400 [00:00<02:37,  2.54it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   0%|          | 2/400 [00:00<02:34,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   1%|          | 3/400 [00:00<01:59,  3.31it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   1%|          | 4/400 [00:01<02:12,  3.00it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   1%|▏         | 5/400 [00:01<02:18,  2.85it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   2%|▏         | 6/400 [00:02<02:22,  2.77it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   2%|▏         | 7/400 [00:02<02:24,  2.72it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   2%|▏         | 8/400 [00:02<02:25,  2.69it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   2%|▏         | 9/400 [00:03<02:04,  3.15it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   2%|▎         | 10/400 [00:03<01:44,  3.75it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   3%|▎         | 11/400 [00:03<01:57,  3.31it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   3%|▎         | 12/400 [00:04<02:07,  3.05it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   3%|▎         | 13/400 [00:04<02:13,  2.89it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   4%|▎         | 14/400 [00:04<02:20,  2.75it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   4%|▍         | 15/400 [00:05<02:22,  2.71it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   4%|▍         | 16/400 [00:05<02:23,  2.68it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   4%|▍         | 17/400 [00:05<02:23,  2.67it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   4%|▍         | 18/400 [00:06<03:16,  1.95it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   5%|▍         | 19/400 [00:07<03:01,  2.10it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   5%|▌         | 20/400 [00:07<02:50,  2.22it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   5%|▌         | 21/400 [00:08<03:29,  1.81it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   6%|▌         | 22/400 [00:08<03:11,  1.97it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   6%|▌         | 23/400 [00:09<03:03,  2.06it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   6%|▌         | 24/400 [00:09<02:51,  2.19it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   6%|▋         | 25/400 [00:09<02:22,  2.64it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   6%|▋         | 26/400 [00:10<02:24,  2.59it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   7%|▋         | 27/400 [00:10<02:23,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   7%|▋         | 28/400 [00:10<02:24,  2.57it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   7%|▋         | 29/400 [00:11<02:23,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   8%|▊         | 30/400 [00:11<02:22,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   8%|▊         | 31/400 [00:12<02:21,  2.61it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   8%|▊         | 32/400 [00:12<02:22,  2.59it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   8%|▊         | 33/400 [00:12<02:21,  2.59it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   8%|▊         | 34/400 [00:13<02:20,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   9%|▉         | 35/400 [00:13<02:20,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   9%|▉         | 36/400 [00:14<02:19,  2.61it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:   9%|▉         | 37/400 [00:14<02:20,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  10%|▉         | 38/400 [00:14<02:21,  2.55it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  10%|▉         | 39/400 [00:15<02:19,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  10%|█         | 40/400 [00:15<02:19,  2.57it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  10%|█         | 41/400 [00:15<02:19,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  10%|█         | 42/400 [00:16<02:18,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  11%|█         | 43/400 [00:16<02:32,  2.34it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  11%|█         | 44/400 [00:17<02:27,  2.41it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  11%|█▏        | 45/400 [00:17<02:26,  2.42it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  12%|█▏        | 46/400 [00:18<02:22,  2.48it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  12%|█▏        | 47/400 [00:18<03:04,  1.91it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  12%|█▏        | 48/400 [00:19<03:33,  1.65it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  12%|█▏        | 49/400 [00:20<03:09,  1.85it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  12%|█▎        | 50/400 [00:20<02:52,  2.03it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  13%|█▎        | 51/400 [00:20<02:41,  2.17it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  13%|█▎        | 52/400 [00:21<02:32,  2.28it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  13%|█▎        | 53/400 [00:21<02:26,  2.37it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  14%|█▎        | 54/400 [00:21<02:21,  2.44it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  14%|█▍        | 55/400 [00:22<02:18,  2.49it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  14%|█▍        | 56/400 [00:22<02:16,  2.51it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  14%|█▍        | 57/400 [00:23<02:14,  2.54it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  14%|█▍        | 58/400 [00:23<02:13,  2.57it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  15%|█▍        | 59/400 [00:23<02:12,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  15%|█▌        | 60/400 [00:24<02:11,  2.59it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  15%|█▌        | 61/400 [00:24<02:10,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  16%|█▌        | 62/400 [00:25<02:09,  2.61it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  16%|█▌        | 63/400 [00:25<02:08,  2.62it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  16%|█▌        | 64/400 [00:25<01:49,  3.06it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  16%|█▋        | 65/400 [00:25<01:54,  2.92it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  16%|█▋        | 66/400 [00:26<02:39,  2.10it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  17%|█▋        | 67/400 [00:27<02:29,  2.23it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  17%|█▋        | 68/400 [00:27<02:22,  2.34it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  17%|█▋        | 69/400 [00:27<02:16,  2.42it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  18%|█▊        | 70/400 [00:28<02:13,  2.47it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  18%|█▊        | 71/400 [00:28<02:10,  2.52it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  18%|█▊        | 72/400 [00:29<02:09,  2.54it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  18%|█▊        | 73/400 [00:29<02:07,  2.57it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  18%|█▊        | 74/400 [00:29<02:06,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  19%|█▉        | 75/400 [00:30<02:05,  2.59it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  19%|█▉        | 76/400 [00:30<02:04,  2.61it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  19%|█▉        | 77/400 [00:31<02:43,  1.97it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  20%|█▉        | 78/400 [00:31<02:31,  2.12it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  20%|█▉        | 79/400 [00:32<02:23,  2.24it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  20%|██        | 80/400 [00:32<02:16,  2.34it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  20%|██        | 81/400 [00:32<02:12,  2.42it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  20%|██        | 82/400 [00:33<01:46,  2.98it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  21%|██        | 83/400 [00:33<02:29,  2.12it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  21%|██        | 84/400 [00:34<02:20,  2.25it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  21%|██▏       | 85/400 [00:34<02:14,  2.34it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  22%|██▏       | 86/400 [00:35<02:10,  2.42it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  22%|██▏       | 87/400 [00:35<02:08,  2.44it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  22%|██▏       | 88/400 [00:35<02:05,  2.49it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  22%|██▏       | 89/400 [00:36<02:03,  2.52it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  22%|██▎       | 90/400 [00:36<02:03,  2.52it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  23%|██▎       | 91/400 [00:36<02:01,  2.55it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  23%|██▎       | 92/400 [00:37<02:00,  2.55it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  23%|██▎       | 93/400 [00:37<01:59,  2.57it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  24%|██▎       | 94/400 [00:38<01:58,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  24%|██▍       | 95/400 [00:38<02:35,  1.96it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  24%|██▍       | 96/400 [00:39<02:24,  2.11it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  24%|██▍       | 97/400 [00:39<02:15,  2.24it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  24%|██▍       | 98/400 [00:40<02:08,  2.34it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  25%|██▍       | 99/400 [00:40<02:04,  2.42it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  25%|██▌       | 100/400 [00:40<02:00,  2.48it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  25%|██▌       | 101/400 [00:41<02:37,  1.90it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  26%|██▌       | 102/400 [00:42<03:01,  1.65it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  26%|██▌       | 103/400 [00:42<02:41,  1.84it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  26%|██▌       | 104/400 [00:43<02:26,  2.02it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  26%|██▋       | 105/400 [00:43<02:15,  2.17it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  26%|██▋       | 106/400 [00:43<02:08,  2.28it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  27%|██▋       | 107/400 [00:44<02:03,  2.36it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  27%|██▋       | 108/400 [00:44<02:00,  2.43it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  27%|██▋       | 109/400 [00:45<01:57,  2.48it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  28%|██▊       | 110/400 [00:45<01:55,  2.52it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  28%|██▊       | 111/400 [00:45<01:53,  2.55it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  28%|██▊       | 112/400 [00:46<01:52,  2.57it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  28%|██▊       | 113/400 [00:46<01:51,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  28%|██▊       | 114/400 [00:47<01:50,  2.59it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  29%|██▉       | 115/400 [00:47<01:49,  2.59it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  29%|██▉       | 116/400 [00:47<01:49,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  29%|██▉       | 117/400 [00:48<01:48,  2.61it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  30%|██▉       | 118/400 [00:48<01:47,  2.61it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  30%|██▉       | 119/400 [00:48<01:47,  2.61it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  30%|███       | 120/400 [00:49<01:47,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  30%|███       | 121/400 [00:49<01:47,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  30%|███       | 122/400 [00:50<01:49,  2.54it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  31%|███       | 123/400 [00:50<01:48,  2.56it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  31%|███       | 124/400 [00:50<01:47,  2.57it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  31%|███▏      | 125/400 [00:51<01:46,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  32%|███▏      | 126/400 [00:51<01:45,  2.59it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  32%|███▏      | 127/400 [00:52<01:45,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  32%|███▏      | 128/400 [00:52<01:44,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  32%|███▏      | 129/400 [00:52<01:44,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  32%|███▎      | 130/400 [00:53<01:43,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  33%|███▎      | 131/400 [00:54<02:16,  1.97it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  33%|███▎      | 132/400 [00:54<02:06,  2.12it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  33%|███▎      | 133/400 [00:54<01:59,  2.23it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  34%|███▎      | 134/400 [00:55<02:26,  1.81it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  34%|███▍      | 135/400 [00:55<02:12,  2.00it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  34%|███▍      | 136/400 [00:56<02:03,  2.14it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  34%|███▍      | 137/400 [00:57<02:28,  1.77it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  34%|███▍      | 138/400 [00:57<02:46,  1.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  35%|███▍      | 139/400 [00:58<02:25,  1.79it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  35%|███▌      | 140/400 [00:58<02:11,  1.98it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  35%|███▌      | 141/400 [00:59<02:01,  2.13it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  36%|███▌      | 142/400 [00:59<02:27,  1.75it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  36%|███▌      | 143/400 [01:00<01:54,  2.25it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  36%|███▌      | 144/400 [01:00<01:49,  2.34it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  36%|███▋      | 145/400 [01:00<01:45,  2.41it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  36%|███▋      | 146/400 [01:01<01:43,  2.47it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  37%|███▋      | 147/400 [01:01<01:42,  2.47it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  37%|███▋      | 148/400 [01:02<02:12,  1.91it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  37%|███▋      | 149/400 [01:02<02:01,  2.07it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  38%|███▊      | 150/400 [01:02<01:36,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  38%|███▊      | 151/400 [01:03<01:35,  2.61it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  38%|███▊      | 152/400 [01:03<01:34,  2.62it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  38%|███▊      | 153/400 [01:04<01:34,  2.61it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  38%|███▊      | 154/400 [01:04<01:20,  3.04it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  39%|███▉      | 155/400 [01:04<01:24,  2.88it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  39%|███▉      | 156/400 [01:05<01:56,  2.09it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  39%|███▉      | 157/400 [01:05<01:48,  2.23it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  40%|███▉      | 158/400 [01:06<01:43,  2.34it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  40%|███▉      | 159/400 [01:07<02:08,  1.88it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  40%|████      | 160/400 [01:07<02:25,  1.65it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  40%|████      | 161/400 [01:08<01:55,  2.07it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  40%|████      | 162/400 [01:08<01:47,  2.21it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  41%|████      | 163/400 [01:08<01:43,  2.30it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  41%|████      | 164/400 [01:09<01:39,  2.38it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  41%|████▏     | 165/400 [01:09<01:36,  2.44it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  42%|████▏     | 166/400 [01:09<01:33,  2.49it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  42%|████▏     | 167/400 [01:10<01:32,  2.53it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  42%|████▏     | 168/400 [01:10<01:30,  2.56it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  42%|████▏     | 169/400 [01:11<01:29,  2.58it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  42%|████▎     | 170/400 [01:11<01:28,  2.59it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  43%|████▎     | 171/400 [01:11<01:28,  2.60it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  43%|████▎     | 172/400 [01:12<01:27,  2.61it/s]

Evaluating Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3:  43%|████▎     | 173/400 [01:12<01:26,  2.62it/s]


Evaluation completed for Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256] on Task 3! Results saved to task3_vanilla_qwen3.5-0.8b_(zero-shot)_[tok256]_results.csv.

(…).5-0.8b_%28zero-shot%29_%5Btok256%5D.csv:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256]', 'test samples': 400, 'ours, same samples (%)': 0.25, 'reproduced (%)': 0.0, 'identical predictions': '322/400', 'ours, 400 samples (README, %)': 0.25}

=== Vanilla Qwen3.5-0.8B (3-Shot) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Vanilla Qwen3.5-0.8B (3-Shot) [tok256] on Task 3: 100%|██████████| 400/400 [01:49<00:00,  3.67it/s]

Evaluation completed for Vanilla Qwen3.5-0.8B (3-Shot) [tok256] on Task 3! Results saved to task3_vanilla_qwen3.5-0.8b_(3-shot)_[tok256]_results.csv.

(…)en3.5-0.8b_%283-shot%29_%5Btok256%5D.csv:   0%|          | 0.00/19.5k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Vanilla Qwen3.5-0.8B (3-Shot) [tok256]', 'test samples': 400, 'ours, same samples (%)': 0.0, 'reproduced (%)': 0.0, 'identical predictions': '399/400', 'ours, 400 samples (README, %)': 0.0}

=== Qwen + LoRA (Raster - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Raster - SFT) [tok256] on Task 3: 100%|██████████| 400/400 [02:04<00:00,  3.20it/s]

Evaluation completed for Qwen + LoRA (Raster - SFT) [tok256] on Task 3! Results saved to task3_qwen_+_lora_(raster_-_sft)_[tok256]_results.csv.

(…)lora_%28raster_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/19.8k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA (Raster - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 79.75, 'reproduced (%)': 80.25, 'identical predictions': '398/400', 'ours, 400 samples (README, %)': 79.75}

=== Qwen + LoRA Raster, read zigzag (TF) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read zigzag (TF) [tok256] on Task 3: 100%|██████████| 400/400 [02:06<00:00,  3.16it/s]

Evaluation completed for Qwen + LoRA Raster, read zigzag (TF) [tok256] on Task 3! Results saved to task3_qwen_+_lora_raster,_read_zigzag_(tf)_[tok256]_results.csv.

(…)2C_read_zigzag_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/19.8k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA Raster, read zigzag (TF) [tok256]', 'test samples': 400, 'ours, same samples (%)': 42.25, 'reproduced (%)': 42.0, 'identical predictions': '396/400', 'ours, 400 samples (README, %)': 42.25}

=== Qwen + LoRA Raster, read spiral_center_out (TF) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read spiral_center_out (TF) [tok256] on Task 3: 100%|██████████| 400/400 [02:06<00:00,  3.17it/s]

Evaluation completed for Qwen + LoRA Raster, read spiral_center_out (TF) [tok256] on Task 3! Results saved to task3_qwen_+_lora_raster,_read_spiral_center_out_(tf)_[tok256]_results.csv.

(…)ral_center_out_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/19.7k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA Raster, read spiral_center_out (TF) [tok256]', 'test samples': 400, 'ours, same samples (%)': 5.75, 'reproduced (%)': 6.25, 'identical predictions': '392/400', 'ours, 400 samples (README, %)': 5.75}

=== Qwen + LoRA Raster, read file_wise (TF) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read file_wise (TF) [tok256] on Task 3: 100%|██████████| 400/400 [02:07<00:00,  3.14it/s]

Evaluation completed for Qwen + LoRA Raster, read file_wise (TF) [tok256] on Task 3! Results saved to task3_qwen_+_lora_raster,_read_file_wise_(tf)_[tok256]_results.csv.

(…)read_file_wise_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/19.8k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA Raster, read file_wise (TF) [tok256]', 'test samples': 400, 'ours, same samples (%)': 4.0, 'reproduced (%)': 4.25, 'identical predictions': '387/400', 'ours, 400 samples (README, %)': 4.0}

=== Qwen + LoRA Raster, read hilbert (TF) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

Evaluating Qwen + LoRA Raster, read hilbert (TF) [tok256] on Task 3: 100%|██████████| 400/400 [02:08<00:00,  3.12it/s]

Evaluation completed for Qwen + LoRA Raster, read hilbert (TF) [tok256] on Task 3! Results saved to task3_qwen_+_lora_raster,_read_hilbert_(tf)_[tok256]_results.csv.

(…)C_read_hilbert_%28tf%29_%5Btok256%5D.csv:   0%|          | 0.00/19.9k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA Raster, read hilbert (TF) [tok256]', 'test samples': 400, 'ours, same samples (%)': 12.75, 'reproduced (%)': 12.75, 'identical predictions': '393/400', 'ours, 400 samples (README, %)': 12.75}

=== Qwen + LoRA (Zigzag - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Zigzag - SFT) [tok256] on Task 3: 100%|██████████| 400/400 [02:04<00:00,  3.21it/s]

Evaluation completed for Qwen + LoRA (Zigzag - SFT) [tok256] on Task 3! Results saved to task3_qwen_+_lora_(zigzag_-_sft)_[tok256]_results.csv.

(…)lora_%28zigzag_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/19.8k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA (Zigzag - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 77.5, 'reproduced (%)': 77.5, 'identical predictions': '396/400', 'ours, 400 samples (README, %)': 77.5}

=== Qwen + LoRA (Spiral_center_out - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Spiral_center_out - SFT) [tok256] on Task 3: 100%|██████████| 400/400 [02:04<00:00,  3.21it/s]

Evaluation completed for Qwen + LoRA (Spiral_center_out - SFT) [tok256] on Task 3! Results saved to task3_qwen_+_lora_(spiral_center_out_-_sft)_[tok256]_results.csv.

(…)ral_center_out_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/19.7k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA (Spiral_center_out - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 70.75, 'reproduced (%)': 71.0, 'identical predictions': '395/400', 'ours, 400 samples (README, %)': 70.75}

=== Qwen + LoRA (File_wise - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (File_wise - SFT) [tok256] on Task 3: 100%|██████████| 400/400 [02:04<00:00,  3.21it/s]

Evaluation completed for Qwen + LoRA (File_wise - SFT) [tok256] on Task 3! Results saved to task3_qwen_+_lora_(file_wise_-_sft)_[tok256]_results.csv.

(…)a_%28file_wise_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/19.8k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA (File_wise - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 80.5, 'reproduced (%)': 80.5, 'identical predictions': '400/400', 'ours, 400 samples (README, %)': 80.5}

=== Qwen + LoRA (Hilbert - SFT) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Hilbert - SFT) [tok256] on Task 3: 100%|██████████| 400/400 [02:04<00:00,  3.21it/s]

Evaluation completed for Qwen + LoRA (Hilbert - SFT) [tok256] on Task 3! Results saved to task3_qwen_+_lora_(hilbert_-_sft)_[tok256]_results.csv.

(…)ora_%28hilbert_-_sft%29_%5Btok256%5D.csv:   0%|          | 0.00/19.7k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA (Hilbert - SFT) [tok256]', 'test samples': 400, 'ours, same samples (%)': 67.75, 'reproduced (%)': 68.0, 'identical predictions': '395/400', 'ours, 400 samples (README, %)': 67.75}

=== Qwen + LoRA (Learned Reordering) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Learned Reordering) [tok256] on Task 3: 100%|██████████| 400/400 [02:04<00:00,  3.22it/s]

Evaluation completed for Qwen + LoRA (Learned Reordering) [tok256] on Task 3! Results saved to task3_qwen_+_lora_(learned_reordering)_[tok256]_results.csv.

(…)28learned_reordering%29_%5Btok256%5D.csv:   0%|          | 0.00/19.6k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA (Learned Reordering) [tok256]', 'test samples': 400, 'ours, same samples (%)': 57.25, 'reproduced (%)': 57.0, 'identical predictions': '391/400', 'ours, 400 samples (README, %)': 57.25}

=== Qwen + LoRA (Learned Reordering, frozen policy) [tok256] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA (Learned Reordering, frozen policy) [tok256] on Task 3: 100%|██████████| 400/400 [02:03<00:00,  3.23it/s]

Evaluation completed for Qwen + LoRA (Learned Reordering, frozen policy) [tok256] on Task 3! Results saved to task3_qwen_+_lora_(learned_reordering,_frozen_policy)_[tok256]_results.csv.

(…)ing%2C_frozen_policy%29_%5Btok256%5D.csv:   0%|          | 0.00/19.7k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA (Learned Reordering, frozen policy) [tok256]', 'test samples': 400, 'ours, same samples (%)': 75.0, 'reproduced (%)': 74.75, 'identical predictions': '398/400', 'ours, 400 samples (README, %)': 75.0}

=== Qwen + LoRA (Raster - SFT) [512px] (400 test samples) ===

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

adapter_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 25.6MB

adapter_model.safetensors: downloading bytes:           |  0.00B

Evaluating Qwen + LoRA Fine-Tuning (from HF) on Task 3: 100%|██████████| 400/400 [02:07<00:00,  3.14it/s]

Evaluation completed for Qwen + LoRA Fine-Tuning (from HF) on Task 3! Results saved to task3_qwen_+_lora_fine-tuning_(from_hf)_results.csv.

(…)n_%2B_lora_fine-tuning_%28from_hf%29.csv:   0%|          | 0.00/19.8k [00:00<?, ?B/s]

{'task': 'task3', 'model': 'Qwen + LoRA (Raster - SFT) [512px]', 'test samples': 400, 'ours, same samples (%)': 87.5, 'reproduced (%)': 87.5, 'identical predictions': '400/400', 'ours, 400 samples (README, %)': 87.5}

,task,model,test samples,"ours, same samples (%)",reproduced (%),identical predictions,"ours, 400 samples (README, %)"
0,task3,Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256],400,0.25,0.00,322/400,0.25
1,task3,Vanilla Qwen3.5-0.8B (3-Shot) [tok256],400,0.00,0.00,399/400,0.00
2,task3,Qwen + LoRA (Raster - SFT) [tok256],400,79.75,80.25,398/400,79.75
3,task3,"Qwen + LoRA Raster, read zigzag (TF) [tok256]",400,42.25,42.00,396/400,42.25
4,task3,"Qwen + LoRA Raster, read spiral_center_out (TF...",400,5.75,6.25,392/400,5.75
5,task3,"Qwen + LoRA Raster, read file_wise (TF) [tok256]",400,4.00,4.25,387/400,4.00
6,task3,"Qwen + LoRA Raster, read hilbert (TF) [tok256]",400,12.75,12.75,393/400,12.75
7,task3,Qwen + LoRA (Zigzag - SFT) [tok256],400,77.50,77.50,396/400,77.50
8,task3,Qwen + LoRA (Spiral_center_out - SFT) [tok256],400,70.75,71.00,395/400,70.75
9,task3,Qwen + LoRA (File_wise - SFT) [tok256],400,80.50,80.50,400/400,80.50
10,task3,Qwen + LoRA (Hilbert - SFT) [tok256],400,67.75,68.00,395/400,67.75
11,task3,Qwen + LoRA (Learned Reordering) [tok256],400,57.25,57.00,391/400,57.25
12,task3,"Qwen + LoRA (Learned Reordering, frozen policy...",400,75.00,74.75,398/400,75.00
13,task3,Qwen + LoRA (Raster - SFT) [512px],400,87.50,87.50,400/400,87.50

## 6. Summary

All the reproduced rows together. The scores should match ours or differ by one or two samples.
Some predictions can differ because of the numerical noise of the GPU, mostly where the model is
unsure (see the top of the notebook).

In [9]:
summary = pd.DataFrame(comparison_task1 + comparison_task2 + comparison_task3)
summary["difference (points)"] = (summary["reproduced (%)"] - summary["ours, same samples (%)"]).round(2)
print(f"LEVEL = {LEVEL!r}, GPU: {torch.cuda.get_device_name(0)}")
display(summary)

LEVEL = 'tables', GPU: NVIDIA L4

,task,model,test samples,"ours, same samples (%)",reproduced (%),identical predictions,"ours, 400 samples (README, %)",difference (points)
0,task1,Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256],100,0.00,0.00,86/100,0.00,0.00
1,task1,Vanilla Qwen3.5-0.8B (3-Shot) [tok256],100,0.00,0.00,78/100,0.00,0.00
2,task1,Qwen + LoRA (Raster - SFT) [tok256],400,97.00,97.00,338/400,97.00,0.00
3,task1,"Qwen + LoRA Raster, read zigzag (TF) [tok256]",100,0.00,0.00,60/100,0.00,0.00
4,task1,"Qwen + LoRA Raster, read spiral_center_out (TF...",100,0.00,0.00,57/100,0.00,0.00
5,task1,"Qwen + LoRA Raster, read file_wise (TF) [tok256]",100,0.00,0.00,49/100,0.00,0.00
6,task1,"Qwen + LoRA Raster, read hilbert (TF) [tok256]",100,0.00,0.00,57/100,0.00,0.00
7,task1,Qwen + LoRA (Zigzag - SFT) [tok256],100,97.00,97.00,94/100,97.50,0.00
8,task1,Qwen + LoRA (Spiral_center_out - SFT) [tok256],100,99.00,99.00,83/100,98.50,0.00
9,task1,Qwen + LoRA (File_wise - SFT) [tok256],100,95.00,95.00,82/100,96.75,0.00
10,task1,Qwen + LoRA (Hilbert - SFT) [tok256],100,96.00,96.00,77/100,95.25,0.00
11,task1,Qwen + LoRA (Learned Reordering) [tok256],100,96.00,96.00,80/100,95.75,0.00
12,task1,"Qwen + LoRA (Learned Reordering, frozen policy...",100,94.00,94.00,89/100,96.75,0.00
13,task1,Qwen + LoRA (Raster - SFT) [512px],100,100.00,99.00,82/100,99.00,-1.00
14,task2,Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256],400,0.00,0.25,252/400,0.00,0.25
15,task2,Vanilla Qwen3.5-0.8B (3-Shot) [tok256],400,0.75,0.75,317/400,0.75,0.00
16,task2,Qwen + LoRA (Raster - SFT) [tok256],400,60.25,60.00,399/400,60.25,-0.25
17,task2,"Qwen + LoRA Raster, read zigzag (TF) [tok256]",400,52.75,52.25,393/400,52.75,-0.50
18,task2,"Qwen + LoRA Raster, read spiral_center_out (TF...",400,14.50,14.00,391/400,14.50,-0.50
19,task2,"Qwen + LoRA Raster, read file_wise (TF) [tok256]",400,9.75,9.50,391/400,9.75,-0.25
20,task2,"Qwen + LoRA Raster, read hilbert (TF) [tok256]",400,29.00,29.50,388/400,29.00,0.50
21,task2,Qwen + LoRA (Zigzag - SFT) [tok256],400,53.50,53.50,400/400,53.50,0.00
22,task2,Qwen + LoRA (Spiral_center_out - SFT) [tok256],400,54.00,54.00,400/400,54.00,0.00
23,task2,Qwen + LoRA (File_wise - SFT) [tok256],400,54.75,54.75,400/400,54.75,0.00
24,task2,Qwen + LoRA (Hilbert - SFT) [tok256],400,52.50,52.50,400/400,52.50,0.00
25,task2,Qwen + LoRA (Learned Reordering) [tok256],400,57.75,57.75,400/400,57.75,0.00
26,task2,"Qwen + LoRA (Learned Reordering, frozen policy...",400,59.50,59.50,400/400,59.50,0.00
27,task2,Qwen + LoRA (Raster - SFT) [512px],400,62.00,62.50,396/400,62.00,0.50
28,task3,Vanilla Qwen3.5-0.8B (Zero-Shot) [tok256],400,0.25,0.00,322/400,0.25,-0.25
29,task3,Vanilla Qwen3.5-0.8B (3-Shot) [tok256],400,0.00,0.00,399/400,0.00,0.00
30,task3,Qwen + LoRA (Raster - SFT) [tok256],400,79.75,80.25,398/400,79.75,0.50
31,task3,"Qwen + LoRA Raster, read zigzag (TF) [tok256]",400,42.25,42.00,396/400,42.25,-0.25
32,task3,"Qwen + LoRA Raster, read spiral_center_out (TF...",400,5.75,6.25,392/400,5.75,0.50
33,task3,"Qwen + LoRA Raster, read file_wise (TF) [tok256]",400,4.00,4.25,387/400,4.00,0.25
34,task3,"Qwen + LoRA Raster, read hilbert (TF) [tok256]",400,12.75,12.75,393/400,12.75,0.00
35,task3,Qwen + LoRA (Zigzag - SFT) [tok256],400,77.50,77.50,396/400,77.50,0.00
36,task3,Qwen + LoRA (Spiral_center_out - SFT) [tok256],400,70.75,71.00,395/400,70.75,0.25
37,task3,Qwen + LoRA (File_wise - SFT) [tok256],400,80.50,80.50,400/400,80.50,0.00
38,task3,Qwen + LoRA (Hilbert - SFT) [tok256],400,67.75,68.00,395/400,67.75,0.25
39,task3,Qwen + LoRA (Learned Reordering) [tok256],400,57.25,57.00,391/400,57.25,-0.25
40,task3,"Qwen + LoRA (Learned Reordering, frozen policy...",400,75.00,74.75,398/400,75.00,-0.25
41,task3,Qwen + LoRA (Raster - SFT) [512px],400,87.50,87.50,400/400,87.50,0.00